### PR TITLE
Improve parse_test.go

### PR DESCRIPTION
**Pull request by chriscool**
This improves go tests in parse_test.go so that it is easier to write more tests and tests are checking more things.

This will help if we want to fix issue #1141 (ipfs cat "multihash too short" error when using stdin).

### CODE REVIEW

**Comment by chriscool** [comment]
One of the test failure is:

```
expecting success: 
	export IPFS_PATH="$IPTB_ROOT/2" &&
	NODE1_ID=`iptb get id 1` &&
	ipfs name publish /ipns/$NODE1_ID
Error: routing: not found
not ok 4 - add an entry on another node pointing to that one
```

The other one is:

```
No output has been received in the last ... minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by jbenet** [comment]
@whyrusleeping whatever the reason, iptb keeps failing :( -- should we disable it until we have fixed it? (the only other test that fails this (or more) frequently atm is the daemon teardown bug which i haven't disabled because... that would disable most of sharness)

**Comment by jbenet** [comment]
@chriscool sorry, those errors are unrelated. :(

does anybody know why travis fails _so often_  with 
> No output has been received in the last ... minutes, this potentially indicates a stalled build or something wrong with the build itself. The build has been terminated
?

**Comment by jbenet** [comment]
this LGTM. anyone looking at the cli want to comment?

**Comment by whyrusleeping** [comment]
@jbenet i'm pretty sure the iptb test failures are caused by the daemon teardown bug (or at least, they have the same cause)

**Comment by whyrusleeping** [comment]
this LGTM too!

**Pull request merged**
