### PR TITLE
Ipfs shell API

### PR DESCRIPTION
**Pull request by whyrusleeping**
This PR implements the beginnings of the ipfs remote 'shell' API. It can be used to interface with a running daemon using go code. More methods will be added as needed/requested

Example usage:
```go
sh := shell.NewShell("localhost:5001")

fi, err := sh.Cat("QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN")
if err != nil {
    panic(err)
}

io.Copy(os.Stdout, fi)
```

### CODE REVIEW

**Comment by jbenet** [comment]
Looking good. 


Shall we define: 

```go
package ipfs
type Node interface { // could also be named Shell
   // some methods
}

// functions (like in core) that do the various things
```

I wonder what's better, adding methods to interfaces, or adding functions (like in the `core*` packages) that can be implemented in multiple packages, like `shell/remote/unix` or `shell/direct/unix` or even `shell/multinode/unix` or something. Not sure what's better on the user. Maybe its a time for experimentation with various API styles.

**Comment by whyrusleeping** [comment]
I'm not sure how much i want an interface here...

**Comment by jbenet** [comment]
not sure if interface or what, but i'd like to be able to have shells backed by different things (i.e. over HTTP, or in same process, etc. not sure yet what a good interface is

**Comment by whyrusleeping** [comment]
I think we should find people who want to build things using this, and let use-cases drive the development

**Comment by jbenet** [comment]
will be a different package

**Pull request closed without merging**
