### PR TITLE
bump version to 0.4.11-rc1, update changelog

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by magik6k** [comment]
Looks like much of the things in feature list is from 4.10 (shutdown, pin update, key rm, ...)

**Comment by whyrusleeping** [comment]
Hrm... did i mess up the script?

**Comment by kpcyrd** [comment]
Could you include a heads up towards the deprecation notice in the docker entrypoint?
https://github.com/ipfs/go-ipfs/blob/e2a3cd3b66992b0e043b51a0c3dda3fa5cacd2c9/bin/container_daemon#L25-L41
This was added about half a year ago and I'd like to change the behaviour to the new syntax in 0.4.12 :)
Basically, if somebody sees the deprecation notice in their logs, they're overwriting the arguments and have to set the first argument of the container to `daemon`. If there's no deprecation warning, they're compatible with the patch I want to apply. :)

**Comment by whyrusleeping** [comment]
@magik6k looks like this is the problem:
```
LAST_TAG=$(git tag | grep -v -- '-rc' | grep 'v'| tail -n1)
```

0.4.10 comes before 0.4.9 when sorted.

**Pull request merged**
