### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
Got them cross-platform tests for go-ipfs here. Pipeline is here (will move to IPFS org) https://github.com/VictorBjelkholm/jenkins-libs/blob/master/vars/golang.groovy

Still have some refactoring to do with the pipeline and figure out if to skip fuse tests or install fuse on all workers. Thoughts?

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
> go-ipfs should get a custom pipeline

Well, if it absolutely have to, sure. But we should try to make testing across all repositories as similar as possible. This makes it easier to write a generic pipeline that we can reuse, and it'll also help people to get started to develop when they are new, since once you learned how one repo works, it'll be similar.

> The problem here is that sharness is not included

I can see activating sharness tests could be a config option in the `golang()` call from the Jenkinsfile, so we can activate it where sharness tests exists.

> it doens't run on windows

With this new Jenkinsfile, it does test on macOS, Linux and Windows.

**Comment by Kubuxu** [comment]
@VictorBjelkholm go-ipfs is quite a special flower here. Tests, Makefiles and coverage collection are at least an order of magnitude more complex than rest of our projects. In future we might need similar complexity for other repos but I think it might be more worthwhile right now to just make it work with custom pipeline (including the different distros).

Any way we can for time being have both builds, the old pipeline and the new one?

**Comment by VictorBjelkholm** [comment]
Missing to finish:

- Run sharness tests
- Solve macOS test failures for go test
- Solve windows test failures for go test

macOS failures:

```
--- FAIL: TestManageInvalidNFds (0.00s)
	ulimit_test.go:23: Testing file descriptor invalidity
	ulimit_test.go:43: ManageFdLimit should return an error
Successfully raised file descriptor limit to 9223372036854765568.
FAIL
FAIL	github.com/ipfs/go-ipfs/cmd/ipfs/util	0.010s
```

windows failures:

```
--- FAIL: TestConfig (0.00s)
	serialize_test.go:31: config file should not be executable or accessible to world: -rw-rw-rw-
FAIL
FAIL	github.com/ipfs/go-ipfs/repo/fsrepo/serialize	1.628s
--- FAIL: TestValidAfter (0.01s)
	centralized_test.go:168: providers []
FAIL
FAIL	github.com/ipfs/go-ipfs/routing/mock	2.892s
--- FAIL: TestIsPinnedLookup (0.00s)
	pin_test.go:45: A1 should be unpinned
--- FAIL: TestPinUpdate (0.00s)
	pin_test.go:34: c2 should be pinned now
FAIL
FAIL	github.com/ipfs/go-ipfs/pin	30.562s
--- FAIL: TestRepublisher (0.30s)
	repub_test.go:57: shouldnt have received publish yet!
FAIL
FAIL	github.com/ipfs/go-ipfs/mfs	7.318s
--- FAIL: TestReprovide (0.02s)
	reprovide_test.go:51: Should have gotten a provider
FAIL
FAIL	github.com/ipfs/go-ipfs/exchange/reprovide	0.292s
# gx/ipfs/QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9/fuse
..\..\..\gx\ipfs\QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9\fuse\error_std.go:27:20: undefined: errNoXattr
..\..\..\gx\ipfs\QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9\fuse\fuse.go:1345:26: undefined: attr
..\..\..\gx\ipfs\QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9\fuse\fuse_kernel.go:166:28: undefined: syscall.O_DIRECTORY
..\..\..\gx\ipfs\QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9\fuse\fuse_kernel.go:175:38: undefined: syscall.O_ACCMODE
..\..\..\gx\ipfs\QmaFNtBAXX4nVMQWbUqNysXyhevUj1k4B1y5uS45LC7Vw9\fuse\fuse_kernel.go:404:17: undefined: attr
ok  	github.com/ipfs/go-ipfs/cmd/ipfs	0.406s
FAIL	github.com/ipfs/go-ipfs/cmd/ipfs/util [build failed]
# github.com/ipfs/go-ipfs/cmd/ipfs/util
cmd\ipfs\util\ulimit_test.go:29:12: undefined: syscall.Rlimit
cmd\ipfs\util\ulimit_test.go:30:11: undefined: syscall.Getrlimit
cmd\ipfs\util\ulimit_test.go:30:29: undefined: syscall.RLIMIT_NOFILE
cmd\ipfs\util\ulimit_test.go:65:12: undefined: syscall.Rlimit
cmd\ipfs\util\ulimit_test.go:66:11: undefined: syscall.Getrlimit
cmd\ipfs\util\ulimit_test.go:66:29: undefined: syscall.RLIMIT_NOFILE
```

Full build: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/PR-4430/21/pipeline/8

**Comment by magik6k** [comment]
Pushed some fixes for windows tests in https://github.com/ipfs/go-ipfs/pull/4632.

To fix the fuse errors you need to add `nofuse` tag to `go test` on Windows (or just use make):

```
go test ./... -tags="nofuse"
```

**Comment by Kubuxu** [comment]
@magik6k as I understand the blocker here is on propagating go-libp2p-peer, right?

**Comment by magik6k** [comment]
Yep, that's the only thing blocking this for now

**Comment by VictorBjelkholm** [comment]
Closing in favor of https://github.com/ipfs/go-ipfs/pull/4530

**Pull request closed without merging**
