### PR TITLE
Doc: golint-ify path package.

### PR DESCRIPTION
**Pull request by hsanjuan**
This removes all go-lint warnings in the path package.

### CODE REVIEW

**Comment by hsanjuan** [comment]
By the way, I will be extracting this too

**Comment by lgierth** [comment]
> By the way, I will be extracting this too

Have you synced with @Stebalien? It's part of the IPLD extraction/disentanglement

**Comment by Stebalien** [comment]
@lgierth this package actually covers IPFS path resolution as well (the resolver is pluggable, technically).

**Comment by whyrusleeping** [comment]
👏 👏

**Pull request merged**
