### PR TITLE
test: 100% coverage on blocks/set

### PR DESCRIPTION
**Pull request by Kubuxu**
License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
whats with all the bithacking logic? It seems you could make this a tad more readable

**Comment by Kubuxu** [comment]
It makes the slice with elements that have some transformations applied deterministically in this case:

half is added, different half is removed and different half is re-added again.

This way we  cover following cases: just add, add and removed, add removed and add, remove on element not in the set.

I think I can make it a bit more readable

**Comment by whyrusleeping** [comment]
alright, still a bit hacky looking, but LGTM

**Comment by whyrusleeping** [comment]
@Kubuxu want to make sure to check off the boxes in https://github.com/ipfs/go-ipfs/issues/3053

**Pull request merged**
