### PR TITLE
Stdin parsing optional arg

### PR DESCRIPTION
**Pull request by chriscool**
This should fix issue #1260 (Ipfs crashes when run as a node subprocess).

This is based on top of @lgierth 's PR #1255 (parse: fix handling of unwanted stdin) as it modifies the same line of code.

### CODE REVIEW

**Comment by krl** [comment]
This works for me, thx @lgierth and @chriscool for unblocking me!

**Comment by jbenet** [comment]
LGTM. will merge after tests

**Comment by jbenet** [comment]
(any year now)

**Comment by chriscool** [comment]
There are some sharness test errors in the Travis PR build but the are not related:

```
expecting success:
iptb -n=4 -p=9000 init &&
iptb -wait start
Started daemon 0, pid = 10725
Started daemon 1, pid = 10739
Started daemon 2, pid = 10747
Started daemon 3, pid = 10756
ipfs start err: node at 127.0.0.1:10000 failed to bootstrap in given time period
not ok 1 - set up an iptb cluster
#
# iptb -n=4 -p=9000 init &&
# iptb -wait start
# 
```

```
expecting success:
test_kill_repeat_10_sec $IPFS_PID
not ok 39 - 'ipfs daemon' can be killed
#
# test_kill_repeat_10_sec $IPFS_PID
# 
```

```
expecting success:
echo "Error: open $IPFS_PATH/repo.lock: permission denied" > init_fail_exp &&
test_cmp init_fail_out init_fail_exp
> diff -u init_fail_out init_fail_exp
--- init_fail_out 2015-05-21 04:12:57.000000000 +0000
+++ init_fail_exp 2015-05-21 04:12:57.000000000 +0000
@@ -1,2 +1 @@
-Error: ipfs daemon is running. please stop it to run this command
-Use 'ipfs init --help' for information about this command
+Error: open /Users/travis/gopath/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0020-init.sh/.badipfs/repo.lock: permission denied
not ok 3 - ipfs init output looks good
#
# echo "Error: open $IPFS_PATH/repo.lock: permission denied" > init_fail_exp &&
# test_cmp init_fail_out init_fail_exp
#
```

**Comment by jbenet** [comment]
thanks @chriscool and @lgierth !

**Pull request merged**
