### PR TITLE
Wired up the trickle dag flag for the add command

### LINKED ISSUE #1368: trickledag broken?
```
> ipfs cat /ipfs/QmQv4YQNmRPuTTHs4AgBhKEFDdN7eQYeTbSmr8JVWVfury/sintel.mp4 >sintel.mp4
> ipfs add -t sintel.mp4
added QmcPZGXSyaQSnDVEtJrgtp2EyxhENiBdpGa8pfs5rMBCWr sintel.mp4
> graphmd QmcPZGXSyaQSnDVEtJrgtp2EyxhENiBdpGa8pfs5rMBCWr | dot -Tsvg | ipfs add
```

Resulting SVG: http://gateway.ipfs.io/ipfs/QmfJ3Ck69UQBa3GL3KuCK5snXiSxvFWz68KN8f6QJ3ci9S/trickle.svg

### PR DESCRIPTION
**Pull request by dylanPowers**
Fixes #1368

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: dffeceebf0a30cc5ebfd3b8b20f6bcce654e7199
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by dylanPowers** [comment]
Added the signed-off-by lines

**Comment by whyrusleeping** [comment]
this LGTM

**Comment by jbenet** [comment]
This needs a test case. We had this in there for _weeks_ without knowing it didn't work... @whyrusleeping please don't merge things without tests

**Comment by dylanPowers** [comment]
I'm writing the test right now

**Pull request merged**
