### PR TITLE
Bubble ErrNotFound improvements

### LINKED ISSUE #7074: Tracking: Improving ErrNotFound
@Stebalien this is meant to hold a small async discussion about continuing ErrNotFound approach, for lack of a better place (would affect multiple repos).

We have done: https://github.com/ipfs/go-ipld-format/pull/55

And now, roughly:

go-datastore has an ErrNotFound.

go-ipfs-blockstore sees those and turns them into it's own ErrNotFounds

go-blockservice sees those and turns them into it's own ErrNotFounds

go-merkledag sees those and turns them into the ipld.ErrNotFound that we fixed.

Two possible approaches:

* A: Remove package-specific ErrNotFound for blockstore, blockservice and merkledag and use and bubble ipld.ErrNotFound{CID} from the blockstore. This reduces lines of code. At the top level (go-ipfs), check with errors.Is(error, ipld.ErrNotFound{}), where needed.

* B: 
  * Modify all ErrNotFound types in blockstore, blockservice, merkledag (and potentially datastore), to be able to include CID information and NotFound() method
  * Bubble errors directly without re-converting them on every module.
  * At the top-level, where it matters to verify something is a NotFound, check with `errors.As()` to see if what we got implements the NotFound() interface.
  * This is more righteous at the expense of some more, duplicated code.

For practical reasons, I lean towards A, given that Blockstore, blockservice, merkledag, ipld-format are almost like internal modules in the go-ipfs codebase, and then it would not be too crazy to consolidate on a single error type for this.

(of  course I can bypass all this and just make go-merkledag work with the new ipld.ErrNotFound, but I thought I'd ask as this would all be quick to fix in one go, either way).

Thoughts?

### PR DESCRIPTION
**Pull request by hsanjuan**
Closes #7074

### CODE REVIEW

**Comment by hsanjuan** [comment]
There's an example test failing out and I wonder if it's because the CID it tries to fetch is no longer easily available. I have pinned it on web3.storage. Perhaps that improves things.

**Comment by hsanjuan** [comment]
@aschmahmann can I have green light to tag all the dependencies now?

**Comment by aschmahmann** [comment]
@hsanjuan this looks good to me. Before merging and tagging in all the dependencies can you make sure those PRs have been reviewed too. They're probably an easy 👍, but sometimes things can slip there too.

If you dump a list of the child PRs in the description it'll be easy to track which are still in need of review.

**Comment by hsanjuan** [comment]
@aschmahmann the list is here: https://github.com/ipfs/go-ipfs/issues/7074#issuecomment-610654770

**Comment by BigLep** [comment]
@aschmahmann : @Jorropo volunteered to look at / merge these PRs.  Are you ok to delegate to him?

**Review by Jorropo — APPROVED** [review]
LGTM

**Pull request merged**
