### PR TITLE
Move go-ipfs-config back into go-ipfs

### PR DESCRIPTION
**Pull request by laurentsenta**
This PR moves the `go-ipfs-config` repo into `go-ipfs/config`.

Fixes [go-ipfs-config#151](https://github.com/ipfs/go-ipfs-config/issues/151).

Extra care was taken into preserving the history, steps to replicate are shared below:

## Notes

This branch looks daunting, but it's actually one merge commit plus 3 commits to update packages.
maybe running a `git diff go-ipfs/config go-ipfs-config` (to confirm the code is actually the same),
and reviewing the last commits only would make reviewers life easier.

```diff
› diff -r go-ipfs/config go-ipfs-config
Only in go-ipfs-config-vanilla: .git
Only in go-ipfs-config-vanilla: .github
Only in go-ipfs-config-vanilla: .gitignore
Only in go-ipfs-config-vanilla: .gx
Only in go-ipfs-config-vanilla: LICENSE
Only in go-ipfs-config-vanilla: README.md
Only in go-ipfs-config-vanilla: go.mod
Only in go-ipfs-config-vanilla: go.sum
diff -r go-ipfs-laurent/config/serialize/serialize.go go-ipfs-config-vanilla/serialize/serialize.go
11c11
<       "github.com/ipfs/go-ipfs/config"
---
>       "github.com/ipfs/go-ipfs-config"
diff -r go-ipfs-laurent/config/serialize/serialize_test.go go-ipfs-config-vanilla/serialize/serialize_test.go
8c8
<       config "github.com/ipfs/go-ipfs/config"
---
>       config "github.com/ipfs/go-ipfs-config"
Only in go-ipfs-config-vanilla: version.json
```

## How to replicate

(1) Rewrite the commit history with a go-ipfs-config prefix:

```bash
git filter-repo --commit-callback '
msg = commit.message.decode("utf-8")
newmsg = "go-ipfs-config: " + msg
commit.message = newmsg.encode("utf-8")
' --force
```

(2) Move the go-ipfs-config to a subfolder

```bash
cd go-ipfs-config
git filter-repo --to-subdirectory-filter config
```

(3) Remove non-go changes

```
git log --name-only ./config | grep '^config/' | grep -v 'go$' | sort | uniq > /tmp/remove
```

edited remove file:
```
config/.circleci/
config/.github/
config/.gitignore
config/.gx/
config/.travis.yml
config/LICENSE
config/README.md
config/go.mod
config/go.sum
config/package.json
config/version.json
```

Remove these files from the history

```
cat /tmp/remove | xargs -I{} git filter-repo --path "{}" --invert-path
```
(⚠️ I had to use `--force`, do it from a fresh repo, because as far as I know it filters the WHOLE repo)

Also remove the version file from history:

```
git filter-repo --path config/version.go --invert-path 
```

(4)   then merge it into go-ipfs

```bash
cd ..
cd go-ipfs
git remote add config ../go-ipfs-config
git fetch config
git merge --allow-unrelated-histories config/master
git remote remove config
```

(now the `go-ipfs/config` folder contains the code AND its git history)

(5) Update go-ipfs code to use the new config package

- Rewrite the imports with a simple search and replace
- Run `git mod tidy` to clean up the module.
- Tweak the `go-ipfs-as-a-library` test (we have to rewrite the module path during the tests)
- removed the `package-list.json` line about `go-ipfs-config`
  - run `npx package-table --data=package-list.json`

## Tasks

- [x] Pass CI
  - [x] Temporary update to Circleci's test of `go-ipfs-as-a-library`
- [x] ~Clean up the `test/dependencies/go.sum`~
  - We need a `go-ipfs-config` dependency here because `github.com/ipfs/iptb-plugins` depends on it.
- [x] Raise the question of other dependencies (in the issue)
   - We have at list 11 other dependencies in the `/ipfs` org that are NOT `go-ipfs`
   - https://pkg.go.dev/github.com/ipfs/go-ipfs-config?tab=importedby
- [x] Update documentation
- [x] filter out all non-go files. That will drop all the release, gx, etc. commits.

## Follow-up tasks

- When this becomes the new mainstream IPFS, remove the package rewrite in `.circleci/main.yml`

### CODE REVIEW

**Comment by Stebalien** [comment]
I think we should be filtering out all non-go files. That will drop all the release, gx, etc. commits.

Otherwise, LGTM! `filter-repo` makes this so much easier...

**Comment by BigLep** [comment]
2022-03-03 conversation: we'll merge when:
1. @hsanjuan had a chance to raise anything in https://github.com/ipfs/go-ipfs-config/issues/151
2. Feedback from @Stebalien gets incorporated

Any of the go-ipfs Stewards will then merge.

**Comment by laurentsenta** [comment]
Thanks for the feedback and the quick review @Stebalien!
I removed the non-go code, AND the `version.go` file (see step 3 in the description),

(might be useful when we're ready to merge: `git rebase --rebase-merges origin/master` to rebase without dealing with the merge's internal conflicts).

**Review by lidel — APPROVED** [review]
Thank you for doing this, :ship:ing, so we can benefit from this asap :heart:

**Pull request merged**
