### PR TITLE
add link to init system examples

### LINKED ISSUE #1430: systemd support
`systemctl <command> ipfs` doesn't work, which makes this a pain to manage as a daemon

### PR DESCRIPTION
**Pull request by slang800**
closes #1430

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: dd8299f0872a4713efebdba5ffef52fdce0b2fc4
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by jbenet** [comment]
@slang800 could you sign your work? check out the https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages thanks!

**Comment by slang800** [comment]
I changed it so gitcop doesn't complain. However, since this is a really small contribution, I don't have any opinion on the license of this particular commit.

**Comment by jbenet** [comment]
thanks @slang800

**Pull request merged**
