### PR TITLE
move core mock into its own package

### PR DESCRIPTION
**Pull request by whyrusleeping**
related #637

### CODE REVIEW

**Comment by whyrusleeping** [comment]
dont merge yet, theres more to come:

```
Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/test/ttest.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/blockservice/worker/bench/main.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/blockservice/mock.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/util/testutil/gen.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/util/testutil/identity.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/merkledag/test/utils.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/p2p/test/util/key.go:	"testing"
Godeps/_workspace/src/github.com/ipfs/go-ipfs/p2p/test/util/util.go:	"testing"
```

**Comment by wking** [comment]
Can the package name for core/mock/… be ‘mock’?  Or maybe ‘coremock’?
I'm not comfortable yet with Go's package layouts, but I'd like to
avoid confusion with the non-mock core API.

In general, I'm still not sure where test utilities should live (see
also #1158).  It's nice to have tests near the code that tests them
(so core/mock/… and core/…_test.go), but that's only going to work for
external tests (we can't have the following import chain: foo_test.go
→ core/mock/… → core/ if foo_test is *in* the core package).  But
maybe core/mock/… is only going to be useful to packages outside of
core that are building on the core/ layer?

**Comment by whyrusleeping** [comment]
> only going to be useful to packages outside of
core that are building on the core/ layer?

I think thats what its used for yeah.

renaming the package to coremock makes sense too

**Comment by jbenet** [comment]
lmk when ready

**Comment by whyrusleeping** [comment]
@jbenet i think this is good for now. can do more later as needed

**Comment by jbenet** [comment]
@whyrusleeping 
- [ ] this doesn't build: https://travis-ci.org/ipfs/go-ipfs/builds/63693658
- [ ] squash (dont need two commits on this i think)
- [ ] rebase

**Comment by jbenet** [comment]
@whyrusleeping build error
- [ ] https://travis-ci.org/ipfs/go-ipfs/jobs/64839185#L129

**Pull request merged**
