### PR TITLE
remove the rest of the supernode code

### PR DESCRIPTION
**Pull request by Stebalien**
missed in the initial cleanup

### CODE REVIEW

**Comment by whyrusleeping** [comment]
still got some in cmd/ipfs/daemon.go, see: `hipster-fast-search-utility supernode`

**Comment by Stebalien** [comment]
@whyrusleeping I left that in to tell users that the option isn't supported. Would you like me to remove it?

**Comment by whyrusleeping** [comment]
Ah, I guess that makes sense to leave in then.

**Comment by Kubuxu** [comment]
@Stebalien I missed this in the initial PR, could you add a sharness test for error message if supernode is selected?

**Comment by Stebalien** [comment]
@Kubuxu picky picky... 😜. Done.

(and thanks for being a stickler for things like this)

**Pull request merged**
