### PR TITLE
Maint/godeps2master

### LINKED ISSUE #14: Why are you using Datastore library for local storage?
I browsed the source code and all the local storage stubs refer to the `datastore` library `github.com/jbenet/datastore.go`. The README and the references describe it as an abstraction layer that would allow to bind it to any database format there is.

And then there is a link to `level_db` as one of the 'datastore' types in `config/config.go:db`.

I am really not sure if that abstraction layer is needed at this stage. Specific implementation of the local storage is not that important for minimum viable version. More than that, `git`, that other very successful DAG-on-top-of-data blobs design, implements and stores objects in a very opinionated way and seems to be successful in spite of it.

Is using that datastore library an intentional design decision? Can we just use something like `github.com/syndtr/goleveldb` at this stage?  

Loving the project and the design, keep up the amazing work!

### PR DESCRIPTION
**Pull request by cryptix**
Please merge #1300  and #1301 first. Will rebase this one after them.

Shortlog:

```
* github.com/Sirupsen/logrus (old rev 26709e2714106fb8ad40b773b711ebce25b78914) (new rev 6ba91e24c498b49d0363c723e9e2ab2b5b8fd012)
Alexander F Rødseth (1):
      Terminals on Windows may not have colors

Antoine Grondin (1):
      default logs to stderr

Dotan J. Nahum (1):
      logrus_syslog / syslog - example should now be valid

Madhav Puri (2):
      Fix Fatalf() and Fatalln() to exit irrespective of log level
      Fix Fatal*() function of logger to match the behavior of Fatal*() functions of entry

Matthew Baird (1):
      proper use of TextFormatter in documentation

Philip Allen (4):
      Added Raygun hook.
      Moving raygun hook to its own repositiroy at github.com/squirkle/logrus-raygun-hook
      Merge branch 'master' of https://github.com/Sirupsen/logrus
      removing raygun hook from hooks dir, adding reference in hooks table of main README.md

Simon Eskildsen (12):
      Merge pull request #170 from aybabtme/log-to-stderr
      Merge pull request #177 from xyproto/master
      Merge pull request #178 from mattbaird/patch-1
      Merge pull request #168 from squirkle/master
      Merge pull request #183 from evalphobia/feature/sentry-http-request
      formatter/json: fix possible race
      version: bump to 0.8
      Merge pull request #187 from mapuri/master
      version: bump to 0.8.1
      Merge pull request #188 from mapuri/master
      version: 0.8.2
      Merge pull request #189 from jondot/patch-1

evalphobia (1):
      Added special field for *http.Request to Sentry hook

* github.com/cenkalti/backoff (old rev 9831e1e25c874e0a0601b6dc43641071414eec7a) (new rev 6c45d6bc1e78d94431dff8fc28a99f20bafa355a)
Cenk Alti (1):
      fix #14

* github.com/cheggaaa/pb (old rev e8c7cc515bfde3e267957a3b110080ceed51354e) (new rev d7729fd7ec1372c15b83db39834bf842bf2d69fb)
Andrew Sutherland (4):
      just return ourselves on chainable methods
      use channel to trigger isFinished
      make units type safe
      dont panic on multiple Finish calls

Andrey Smirnov (1):
      Fix the data race on pb.isFinish member.

Frederick F. Kautz IV (1):
      Running gofmt, no semantic changes.

Fábio Gomes (1):
      Adds Set64 func to set the current value as int64

Sergey Cherepanov (8):
      netbsd support
      Merge pull request #34 from smira/master
      Merge pull request #35 from nixxquality/patch-1
      Merge pull request #36 from fkautz/pr_out_running_gofmt_no_semantic_changes
      Merge pull request #37 from drewis/forupstream
      Merge pull request #38 from monde-sistemas/master
      correct speed when start value not 0
      return object for a chain calling

nixxquality (1):
      Fix typo

* github.com/crowdmob/goamz (old rev 82345796204222aa56be89cf930c316b1297f906) (new rev 3a06871fe9fc0281ca90f3a7d97258d042ed64c0)
Adrien Bustany (2):
      s3: Retry on url.Error too
      s3test: Implement MultiDel support

Ali Moeeny (4):
      Merge pull request #324 from abustany/s3-retry-url-error
      Merge pull request #329 from richarddbarnett/master
      Merge pull request #330 from abustany/s3test-multidel
      Merge pull request #331 from AndreyKostov/master

Andrey Kostov (1):
      Fix signed urls for s3 with v4 auth and IAM roles

Matthew Moore (1):
      Update README.md

Richard Barnett (1):
      Add Kinesis endpoint for us-west-1

* github.com/fd/go-nat (old rev 50e7633d5f27d81490026a13e5b92d2e42d8c6bb) (new rev dcaf50131e4810440bed2cbb6f7f32c4f4cc95dd)
Simon Menke (1):
      Using github.com/jackpal/gateway to discover NAT-PMP/PCP gateways

* github.com/fzzy/radix/redis (old rev 27a863cdffdb0998d13e1e11992b18489aeeaa25) (new rev 031cc11e9800a2626ee2ae629655a922b630a07d)
Brian Picciano (19):
      make cluster package thread-safe
      CHANGELOG
      update READMEs to have references to cluster
      throttle Reset calls in cluster
      change how options are passed around in cluster, and fix throttle
      CHANGELOG
      add a Pattern field to SubReply
      make DialTimeout actually use DialTimeout (requested by #53)
      fix bugs in cluster which prevented proper failover handling
      make cluster.getConn attempt to make the pool in question to better handle failover cases, also simplify moved logic a bit
      fix cluster test to handle the Reset throttle properly
      CHANGELOG
      refactor resp writing to not create an intermediate buffer and just write directly to the io.Writer
      small formatting fixes
      optimize flattening in resp to not create as many intermediate data structures
      refactor resp writing even further by making conn have a writeBuffer pre-allocated which resp simply appends to
      update cluster tests for newest testify code
      CHANGELOG
      CHANGELOG

Victor (1):
      add Reply.Float64() method

* github.com/gogo/protobuf (old rev 0ac967c269268f1af7d9bcc7927ccc9a589b2b36) (new rev b9e369e8ffb6773efc654ea13594566404314ee1)
Anton Povarov (1):
      simpler and more computationally efficient solution

Dwayne Schultz (4):
      Add checks in marshal/unmarshal for presence of required fields
      Improve compatibility
      Revert "Improve compatibility"
      Use import helper

Georg Apitz (2):
      Apply @anton-povarov's patch for bitmasks for missing required fields
      Add test for nested NinOptNative

John Tuley (11):
      Update artifacts from `make all`
      Test using `Marshal` instead of `MarshalTo`
      Use `proto.Marshal`/`proto.Unmarshal`
      Move NewRequiredNotSetError to encode_gogo.go
      Restore permissions on protoc-gen-gogo/main.go
      Remove empty lines
      Remove empty lines
      Check marshal error in requiredexamplepb_test.go
      Merge remote-tracking branch 'gogo/master'
      Add test for unmarshalling populated optional fields as required
      Add tests for required fields

Tamir Duberstein (1):
      Generate errcheck-passing code

Walter Schulze (4):
      regenerated code
      Merge pull request #51 from tamird/errcheck
      fixed errcheck for old protoc versions
      Merge pull request #48 from jmtuley/master

* github.com/hashicorp/golang-lru (old rev 253b2dc1ca8bae42c3b5b6e53dd2eab1a7551116) (new rev 995efda3e073b6946b175ed93901d729ad47466a)
Alexander Gugel (1):
      Add Contains, Peek

Armon Dadgar (6):
      Merge pull request #3 from blopker/master
      Merge pull request #4 from mreid-moz/add_onevict
      Merge pull request #6 from client9/master
      Merge pull request #8 from sciolizer/keys-order
      Merge pull request #10 from alexanderGugel/has-peek
      Merge pull request #12 from dkumor/master

Bo Lopker (1):
      Add RWMutex for read-only functions

Daniel Kumor (2):
      Fixed onEvict bug for Purge
      Added test for onEvicted interface value

Joshua Ball (1):
      Keys() preserves order

Kyle Kelley (1):
      fmt.Sprintf inside panic call

Mark Reid (6):
      Add an 'onEvict' function called when an element is removed.
      Export the "OnEvicted" function.
      Stop exposing the internals for eviction.
      Take a single lock to purge the cache.
      Purge in the correct LRU order.
      Call the evict function, then reset the cache.

Nick Galbreath (2):
      change Add method to return bool on eviction
      gofmt cleanup

Ryan Uber (1):
      Merge pull request #2 from rgbkrk/patch-1

* github.com/hashicorp/yamux (old rev 9feabe6854fadca1abec9cd3bd2a613fe9a34000) (new rev b2e55852ddaf823a85c67f798080eb7d08acd71d)
Armon Dadgar (5):
      Prevent Read on a closed stream
      Adding NumStreams to query open stream count
      Prevent deadlock with closeStream race
      Session close waits for receive loop to terminate
      Adding backpressure to Open to avoid RST

* github.com/howeyc/fsnotify (old rev 6b1ef893dc11e0447abda6da20a5203481878dda) (new rev 4894fe7efedeeef21891033e1cce3b23b9af7ad2)
Chris Howey (1):
      Merge pull request #109 from missdeer/master

Fan Yang (2):
      Update fsnotify_bsd.go
      Update fsnotify_open_bsd.go

* github.com/huin/goupnp (old rev 223008361153d7d434c1f0ac990cd3fcae6931f5) (new rev c57ae84388ab59076fd547f1abeab71c2edb0a21)
Felix Lange (1):
      soap: quote action names in header

Huin (1):
      Fix CharsetReader creation.

Jianfei Wang (1):
      support xml encoding other than utf-8

John Beisley (2):
      Merge branch 'fjl-soap-quote'
      Merge branch 'thinxer-master'

* github.com/jackpal/go-nat-pmp (old rev a45aa3d54aef73b504e15eb71bea0e5565b5e6e1) (new rev 46523a463303c6ede3ddfe45bde1c7ed52ebaacd)
Jack Palevich (1):
      Add NewClientForDefaultGateway, test of same.

* github.com/jbenet/go-peerstream (old rev 8d52ed2801410a2af995b4e87660272d11c8a9a4) (new rev 675a5da7e3500d73c2edc84565d6c46b540ad1b4)
Brian Tiger Chow (1):
      Update listener.go

Juan Batiz-Benet (1):
      Merge pull request #7 from briantigerchow/patch-1

* github.com/kardianos/osext (old rev 8fef92e41e22a70e700a96b29f066cda30ea24ef) (new rev 6e7f843663477789fac7c02def0d0909e969b4e5)
Daniel Theophanes (2):
      osext: do not return trailing slash in folder path.
      osext: state in readme that args[0] doesn't always work.

* github.com/miekg/dns (old rev 82ffc45b1f84ff71bd1cebed8b210118ce3d181e) (new rev bb1103f648f811d2018d4bedcb2d4b2bce34a0f1)
Alex Sergeyev (6):
      Issue with TLSA parsing identified
      Fixed SSHFP parsing when multiple lines used for text representation.
      Updated NSAP support according to RFC1706
      Fixed reversed logic.
      Support for almost all possible ways to format HINFO record
      Added comment to commented-out testcase

Mart Roosmaa (1):
      Use algorithm number to determine private key type.

Michael Haro (3):
      Check that the query ID matches the answer ID.
      Keep Exchange as it was, but still check ID.
      Cleanup Client.exchange

Miek Gieben (10):
      Merge pull request #207 from roosmaa/keyparse
      Merge pull request #208 from michaelharo/checkid
      Merge pull request #209 from michaelharo/client
      Merge commit '627287e675fb79f57928f77fbfae24abe15ed58b' into tlsa
      Playing with TLSA records
      Fix off-by-one on the maxTok and maxCom check
      Add TLSA parsing tests
      Check the l.err token errors
      Merge pull request #211 from miekg/tlsa
      Merge pull request #212 from asergeyev/master

* github.com/syndtr/goleveldb/leveldb (old rev 4875955338b0a434238a31165cb87255ab6e9e4a) (new rev 315fcfb05d4d46d4354b313d146ef688dda272a9)
Suryandaru Triandana (6):
      Merge pull request #106 from restlessbandit/getprop-errors
      leveldb: allows disabling buffer pool
      manualtest/dbstress: disable block cache and buffer pool by default
      memdb: use named constant instead of integer literal and Reset now holds lock
      leveldb: cleanup DB.recoverJournal(), memdb, session record and split session.go
      leveldb: allows open or puts DB into read-only mode (closes #107)

Travis J Parker (1):
      uses a public API error that can be compared against for invalid property names

* github.com/whyrusleeping/iptb (old rev 3970c95a864f1a40037f796ff596607ce8ae43be) (new rev fa9bbc437fae1c3a9410e7f1bc3dd02f0449279a)
Jeromy (1):
      bootstrap addrs cant be 0.0.0.0

* golang.org/x/crypto (old rev c84e1f8e3a7e322d497cd16c0e8a13c7e127baf3) (new rev ce6bda69189e9f4ff278a5e181691cd695f753ae)
Dmitry Savintsev (1):
      crypto/ssh: fix encoding of ssh certs with critical options

Han-Wen Nienhuys (1):
      x/crypto/ssh: bail early if a server has no auth methods configured.

Joel Sing (1):
      poly1305: fix compilation on arm with go tip

Jungho Ahn (1):
      x/crypto/poly1305: add ARM assembly

KB Sriram (1):
      x/crypto/openpgp: Limit packet recursion depth.

Shenghou Ma (1):
      ocsp: fix test on TZ=UTC systems

datianshi (1):
      ssh: add hmac-sha2-256.

* golang.org/x/net (old rev ff8eb9a34a5cbb9941ffc6f84a19a8014c2646ad) (new rev 589db58a47224e5786650dac2677b9c302bab6c2)
Dave Cheney (1):
      x/net/websocket: always close underlying connection on ws.Close

Ian Lance Taylor (1):
      html/charset/testdata: update licensing info in README

Mikio Hara (4):
      ipv4: fix build on linux/arm64
      ipv6: fix build on linux/arm64
      icmp: more coverage to ping test
      icmp: add missing attribute length check

Nigel Tao (7):
      webdav: skip XML-related tests on Go 1.4.
      webdav: make properties belong to the File(System), not a PropSystem.
      webdav: special-case the propfind_invalid2 litmus test.
      webdav: delete the PropSystem and MemPS types.
      webdav: add StripPrefix.
      webdav: have copyFiles copy dead properties.
      webdav: let DeadPropsHolder.DeadProps return an error.

Robert Stepanek (3):
      webdav: Add PROPPATCH support to in-memory property system.
      webdav: Return HTTP 404 for PROPFIND/PROPPATCH requests on an inexistent     webdav.Dir resource.
      webdav: Simplify handling of Etag and Content-Type headers for GET, HEAD,     POST and PUT requests.

* gopkg.in/natefinch/lumberjack.v2 (old rev d28785c2f27cd682d872df46ccd8232843629f54) (new rev 588a21fb0fa0ebdfde42670fa214576b6f0f22df)
Matt Silverlock (1):
      Fixed import in example test to use gopkg.in.

Nate Finch (2):
      Merge pull request #11 from elithrar/v2.0
      Fix bug #12
```

### CODE REVIEW

**Comment by cryptix** [comment]
Shortlog script:

```
#!/bin/sh

gopath=/tmp/ipfsGodeps

getShortLog() {
	echo "* $1 (old rev $2) (new rev $3)"
	git -C $gopath/src/$1 shortlog ${2}..${3}
}

cat << EOF | while read change; do getShortLog $change; done
github.com/Sirupsen/logrus 26709e2714106fb8ad40b773b711ebce25b78914 6ba91e24c498b49d0363c723e9e2ab2b5b8fd012
github.com/cenkalti/backoff 9831e1e25c874e0a0601b6dc43641071414eec7a 6c45d6bc1e78d94431dff8fc28a99f20bafa355a
github.com/cheggaaa/pb e8c7cc515bfde3e267957a3b110080ceed51354e d7729fd7ec1372c15b83db39834bf842bf2d69fb
github.com/crowdmob/goamz 82345796204222aa56be89cf930c316b1297f906 3a06871fe9fc0281ca90f3a7d97258d042ed64c0
github.com/fd/go-nat 50e7633d5f27d81490026a13e5b92d2e42d8c6bb dcaf50131e4810440bed2cbb6f7f32c4f4cc95dd
github.com/fzzy/radix/redis 27a863cdffdb0998d13e1e11992b18489aeeaa25 031cc11e9800a2626ee2ae629655a922b630a07d
github.com/gogo/protobuf 0ac967c269268f1af7d9bcc7927ccc9a589b2b36 b9e369e8ffb6773efc654ea13594566404314ee1
github.com/hashicorp/golang-lru 253b2dc1ca8bae42c3b5b6e53dd2eab1a7551116 995efda3e073b6946b175ed93901d729ad47466a
github.com/hashicorp/yamux 9feabe6854fadca1abec9cd3bd2a613fe9a34000 b2e55852ddaf823a85c67f798080eb7d08acd71d
github.com/howeyc/fsnotify 6b1ef893dc11e0447abda6da20a5203481878dda 4894fe7efedeeef21891033e1cce3b23b9af7ad2
github.com/huin/goupnp 223008361153d7d434c1f0ac990cd3fcae6931f5 c57ae84388ab59076fd547f1abeab71c2edb0a21
github.com/jackpal/go-nat-pmp a45aa3d54aef73b504e15eb71bea0e5565b5e6e1 46523a463303c6ede3ddfe45bde1c7ed52ebaacd
github.com/jbenet/go-peerstream 8d52ed2801410a2af995b4e87660272d11c8a9a4 675a5da7e3500d73c2edc84565d6c46b540ad1b4
github.com/kardianos/osext 8fef92e41e22a70e700a96b29f066cda30ea24ef 6e7f843663477789fac7c02def0d0909e969b4e5
github.com/miekg/dns 82ffc45b1f84ff71bd1cebed8b210118ce3d181e bb1103f648f811d2018d4bedcb2d4b2bce34a0f1
github.com/syndtr/goleveldb/leveldb 4875955338b0a434238a31165cb87255ab6e9e4a 315fcfb05d4d46d4354b313d146ef688dda272a9
github.com/whyrusleeping/iptb 3970c95a864f1a40037f796ff596607ce8ae43be fa9bbc437fae1c3a9410e7f1bc3dd02f0449279a
golang.org/x/crypto c84e1f8e3a7e322d497cd16c0e8a13c7e127baf3 ce6bda69189e9f4ff278a5e181691cd695f753ae
golang.org/x/net ff8eb9a34a5cbb9941ffc6f84a19a8014c2646ad 589db58a47224e5786650dac2677b9c302bab6c2
gopkg.in/natefinch/lumberjack.v2 d28785c2f27cd682d872df46ccd8232843629f54 588a21fb0fa0ebdfde42670fa214576b6f0f22df
EOF
```

**Comment by whyrusleeping** [comment]
i'm ever so slightly worried about the potential issues caused by such a widescale update of our dependencies. Lets make sure to get a few good fully green test runs in before merging.

**Comment by cryptix** [comment]
Totally agreed. Problem is, they get harder to review the longer you stall.

Doing this regularly gives you at least a chance of getting in touch with upstream when (breaking) changes are introduced.

**Comment by jbenet** [comment]
merged #1300 and #1301 
- [ ] rebase

**Comment by jbenet** [comment]
> i'm ever so slightly worried about the potential issues caused by such a widescale update of our dependencies. Lets make sure to get a few good fully green test runs in before merging.

i'm pretty worried. +1 to testing lots.

**Comment by cryptix** [comment]
rebased for fun and test results

**Pull request merged**
