### PR TITLE
fix(unixfs): issue #5217 (Avoid use of `pb.Data`)

### PR DESCRIPTION
**Pull request by overbool**
License: MIT
Signed-off-by: Overbool <overbool.xu@gmail.com>

Fixes: https://github.com/ipfs/go-ipfs/issues/5217

### CODE REVIEW

**Comment by kevina** [comment]
@overbool what about removing the `FromBytes` function as described in the original function.

**Comment by overbool** [comment]
@kevina 
> @overbool what about removing the `FromBytes` function as described in the original function.

I had added description in original function.

**Comment by kevina** [comment]
I'm sorry, I misspoken.  Is it possible to just delete the `FromBytes` function now as described in the original _issue_ (#5217)?

The added commented are not really necessary and in my opinion are just adding noise.  Others may disagree with me though.

**Comment by overbool** [comment]
@kevina @schomatis I had done a similar replacement for  here https://github.com/ipfs/go-unixfs/pull/18 and https://github.com/ipfs/go-mfs/pull/7

**Pull request merged**
