### PR TITLE
Add module files for go-ipfs-as-a-library example

### PR DESCRIPTION
**Pull request by lthibault**
Fixes https://github.com/ipfs/go-ipfs/issues/6811.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Should we just document how to setup the example on a separate location?

My main issue with this is that we might forget to keep this go.mod up to date, therefore the example might break when people want to use it with newer go-ipfs versions.

**Comment by Stebalien** [comment]
Eh, I'd add it. It's a good starting point.

However, we should probably wait till the release so we can make it depend on v0.5.0 instead of a specific git commit.

**Comment by hsanjuan** [comment]
I put it in the milestone so that we don't forget...

**Comment by Stebalien** [comment]
@lthibault could you rebase this and update go-ipfs to 0.5.0?

**Comment by lthibault** [comment]
@Stebalien Done.

**Pull request merged**
