### PR TITLE
chore: webui v2.11.1

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Bumps to new Webui: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.1

cc https://github.com/ipfs/go-ipfs/issues/7560

### CODE REVIEW

**Comment by aschmahmann** [comment]
@rafaelramalho19 could you rebase on master, it looks like you have a conflict.

**Comment by rafaelramalho19** [comment]
> @rafaelramalho19 could you rebase on master, it looks like you have a conflict.

Thanks, we'll have to do a new webui release soon, so please don't merge this yet

**Comment by lidel** [comment]
Update: turned out that fix in https://github.com/ipfs-shipyard/ipfs-webui/pull/1628 was specific to ipfs-desktop and does not impact use in regular browsers, so there is no need to block go-ipfs on this. 

@aschmahmann feel free to squash & merge as-is (`v2.11.0`), no need to wait for `v2.11.1`

**Comment by aschmahmann** [comment]
@lidel @rafaelramalho19 Have we done some tests with this version of go-ipfs + webui just to make sure everything looks right before merging?

Was hoping to do the full release tomorrow or Wednesday (pending an issue I'm investigating) so if the new WebUI is up by then or you need a bit more time lmk.

**Comment by lidel** [comment]
Cool,  I believe we should have new webui by tomorrow :) 
If we don't update this PR by then, feel free to merge as-is.

As for tests, so far all good:

- End-to-end regression tests are green with  0.7.0-rc2
  (we run them  CI against the custom binary, config is in [.circleci/config.yml#L257-L287](https://github.com/ipfs/go-ipfs/blob/v0.7.0-rc2/.circleci/config.yml#L257-L287))
- I've been using webui v2.11 with 0.7.0-rc2 for about a week without any regressions
  - On top of UI fixes/improvements, the key benefit of this release is that one can import big files without buffering the entire thing in browser's memory. Import of a 2GB video takes a moment, but is no longer crashing my browser.

**Comment by rafaelramalho19** [comment]
I've bumped webui version to the latest now

**Review by aschmahmann — APPROVED** [review]

**Pull request merged**
