### PR TITLE
GitHub: Updates to the issue templates including the new "GitHub Issue Forms"

### PR DESCRIPTION
**Pull request by RubenKelevra**
- Add a CLI reference to the selection with a link
- Add a security issue to the selection with a link
- Create a form instead of a simple text field for bugs

### Important:

Before merging make sure this repo is part of the beta - [application form](https://docs.google.com/forms/d/e/1FAIpQLSea1QJ_9Os2gWpGCtpESjeV6VvghKn0iELvbYo8iQFi9GyFsA/viewform).

### CODE REVIEW

**Comment by Stebalien** [comment]
Currently waiting to join the beta.

**Comment by RubenKelevra** [comment]
Had no way to test this, though. So make sure to give it a thorough look. :)

**Comment by BigLep** [comment]
Next steps are for a maintainer to test this out now that we're in the beta.  
This hasn't been a major paint point for us though which is why it's labeled P3.

**Comment by Stebalien** [comment]
I've taken your form, trimmed it down a bit, and added forms for the rest of the other templates in https://github.com/ipfs/go-ipfs/pull/8279. Let's continue discussion there.

**Pull request closed without merging**
