### PR TITLE
Add ResolveMany

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by jbenet** [comment]
Not sure about this
-  the `core*` functions are the API, we want to restrict what we add there as all other systems will want to match the interface. 
- This change may then open door to lots of other commands too (like `ls`, `get`, `object stat`, `object links`, etc...). the cli and other interfaces could add support for this without the changing the core.
- so far i'm :-1: on this API addition.

(also, the `objectsForPaths` func probably wants to run those in parallel, as resolve may be slow)

**Comment by rht** [comment]
Ok nvm then, though at least it is cheaper to preallocate the slice like in `objectsForPaths` than `append`?

**Comment by jbenet** [comment]
@rht maybe just make it an isolated helper? like `core.helpers` or something. i want to be able to point somewhere to a relatively _small_ number of function calls that someone may have to implement. ok to have helpers elsewhere that dont increase that number.

**Comment by rht** [comment]
Add `core.helpers` only if it reaches a critical mass of such functions.

On the other hand, if the 1. `ResolveMany` pattern is used in several places, 2. each call is slow, it is worthwhile to make it async & use channel?

**Pull request closed without merging**
