### PR TITLE
ds-help: add helper functions to convert from Cid to DsKey and the reverse

### PR DESCRIPTION
**Pull request by kevina**
In the filestore (#2634) i needed to convert from Cid to DsKey and the reverse in several places so I created two helper functions to that effect.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Maybe these should be in the dshelper package?

**Comment by kevina** [comment]
I take it you mean `thirdparty/ds-help`.  I thought about that, but it will add a dependency to that small package and also these methods are used in the same places the blockstore is used so I thought the blockstore package was a better place to avoid having yet another import.  I can move it though, just give the word.

**Comment by whyrusleeping** [comment]
@kevina the thing is that your helper methods would be useful in nearly every place that that package is used.

**Comment by kevina** [comment]
No problem, I'll move it.

**Comment by kevina** [comment]
@whyrusleeping, moved

**Comment by kevina** [comment]
@whyrusleeping tests passed.  Marking a RFM.

**Pull request merged**
