### PR TITLE
Godeps: remove go-random*

### PR DESCRIPTION
**Pull request by zramsay**
- works toward #2722
- of the two packages published to `gx`, one *may* need to be re-published (I don't fully understand the gx/gx-go pipeline yet). To what extent is https://github.com/jbenet/go-random-files/pull/2 required?
- keeping it small for now though definitely keen to get Godeps out of this repo & will make bigger PRs if this one is :+1:

### CODE REVIEW

**Comment by zramsay** [comment]
the repos put from gx remained available on the public gateway, though I've pinned them now and the CI should be able to get them. Does opening and closing a PR re-trigger the CI or do I have to push new commits?

**Comment by magik6k** [comment]
You can just do `git commit --amend`+`git push -f` to re-trigger

**Comment by whyrusleeping** [comment]
@zramsay it seems the go-random package that is gx vendored here is missing some dependencies or something. @Kubuxu can you take a look here?

**Comment by Kubuxu** [comment]
You have published the package of go-random in weird state (with references to itself rewritten with some other version).

Make sure that imports in it are not rewritten (`gx-go uw`), and then publish it.

**Comment by Kubuxu** [comment]
Also see https://github.com/jbenet/go-random/pull/8/files and https://github.com/jbenet/go-random-files/pull/2/files for correct `package.json` definitions.

**Pull request closed without merging**
