### PR TITLE
fix emitting errors on `ipfs rm`

### PR DESCRIPTION
**Pull request by petar**

### CODE REVIEW

**Comment by petar** [comment]
Do we also want the errors to include the relevant file in a separate field?

**Review by Mitumaru — APPROVED** [review]

**Comment by guseggert** [comment]
@petar, what's the motivation for this change?

**Comment by petar** [comment]
> @petar, what's the motivation for this change?

This change makes errors be emitted as proper json objects (as opposed to free form text), so they can be parsed.
I don't recall the motivation for doing it.

**Comment by guseggert** [comment]
@petar are you okay with closing this then?

**Pull request closed without merging**
