### PR TITLE
sharness: add /ws multinode test

### PR DESCRIPTION
**Pull request by lgierth**
That iptb branch is whyrusleeping/iptb#31 -- I guess don't merge before that one lands :)

### CODE REVIEW

**Comment by lgierth** [comment]
Merge on next iptb release?

**Comment by whyrusleeping** [comment]
@lgierth if your commit is a published hash then i'll merge this now

**Comment by whyrusleeping** [comment]
@lgierth can you rebase this? i think the test failures have been fixed recently

**Comment by lgierth** [comment]
Hrm I suppose these build timeouts hint at /ws issues :(

**Comment by whyrusleeping** [comment]
Hrm... Want me to investigate this? 

In either case, pushing back to 0.4.8

**Comment by lgierth** [comment]
> Hrm... Want me to investigate this?

That'd be great :+1: I'm not sure I'll get to it anytime soon :(

**Comment by whyrusleeping** [comment]
@lgierth wanna rebase this? it might show more failures with the new ws lib

**Comment by Stebalien** [comment]
Rebased.

**Comment by Stebalien** [comment]
Rebased on-top of #4205 (to see if they actually fix everything).

**Comment by Stebalien** [comment]
Failures:

```
expecting success: 
		iptb stop ||
			test_fsh tail -n +1 .iptb/*/daemon.std*
	
ipfs kill err:  error killing daemon /go/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0130-multinode.sh/.iptb/4: os: process already finished
> tail -n +1 .iptb/0/daemon.stderr .iptb/0/daemon.stdout .iptb/1/daemon.stderr .iptb/1/daemon.stdout .iptb/2/daemon.stderr .iptb/2/daemon.stdout .iptb/3/daemon.stderr .iptb/3/daemon.stdout .iptb/4/daemon.stderr .iptb/4/daemon.stdout
==> .iptb/0/daemon.stderr <==

==> .iptb/0/daemon.stdout <==
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/40837/ws
Swarm listening on /ip4/172.17.0.3/tcp/40837/ws
Swarm listening on /p2p-circuit/ipfs/QmUoVGZN6fiBSAxybrV58EiRU3hp6ditWcTNn3kqS5xCyS
Swarm announcing /ip4/127.0.0.1/tcp/40837/ws
Swarm announcing /ip4/172.17.0.3/tcp/40837/ws
API server listening on /ip4/127.0.0.1/tcp/35731
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

==> .iptb/1/daemon.stderr <==

==> .iptb/1/daemon.stdout <==
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/34433/ws
Swarm listening on /ip4/172.17.0.3/tcp/34433/ws
Swarm listening on /p2p-circuit/ipfs/QmcBnfGMQuBWSCAZzsnenjP3Jjw6kA9ApVPR6GzfL6urV7
Swarm announcing /ip4/127.0.0.1/tcp/34433/ws
Swarm announcing /ip4/172.17.0.3/tcp/34433/ws
API server listening on /ip4/127.0.0.1/tcp/45557
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

==> .iptb/2/daemon.stderr <==

==> .iptb/2/daemon.stdout <==
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/40097/ws
Swarm listening on /ip4/172.17.0.3/tcp/40097/ws
Swarm listening on /p2p-circuit/ipfs/QmX359Wr4vzmGSyC2mt5dpAHrzUnY5seLYXZPtiEb9CXdz
Swarm announcing /ip4/127.0.0.1/tcp/40097/ws
Swarm announcing /ip4/172.17.0.3/tcp/40097/ws
API server listening on /ip4/127.0.0.1/tcp/34591
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

==> .iptb/3/daemon.stderr <==

==> .iptb/3/daemon.stdout <==
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/46453/ws
Swarm listening on /ip4/172.17.0.3/tcp/46453/ws
Swarm listening on /p2p-circuit/ipfs/QmPqzxRp6xUJXsrBCWjiDRPoZCBsTKLZQ9dfemtJ39wXbh
Swarm announcing /ip4/127.0.0.1/tcp/46453/ws
Swarm announcing /ip4/172.17.0.3/tcp/46453/ws
API server listening on /ip4/127.0.0.1/tcp/39541
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

==> .iptb/4/daemon.stderr <==
panic: concurrent write to websocket connection

goroutine 73381 [running]:
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*messageWriter).flushFrame(0xc4223a7bf0, 0xc420029b01, 0x0, 0x0, 0x0, 0xc42073a200, 0x30)
	/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:585 +0x57b
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*messageWriter).Close(0xc4223a7bf0, 0x90f7fb, 0xc420029b20)
	/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:699 +0x60
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).prepWrite(0xc421e45040, 0x8, 0xc4210cfc08, 0x3)
	/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:468 +0x10c
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).NextWriter(0xc421e45040, 0x8, 0x8f607f, 0xc4210cfc58, 0xc4204a2000, 0x93a780)
	/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:488 +0x39
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).WriteMessage(0xc421e45040, 0x8, 0x0, 0x0, 0x0, 0xc4226f9098, 0xc4210cfd28)
	/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:745 +0x74
gx/ipfs/QmSN8R5YxkLgkjeptMpAwV77m11DrHnC7LtxEvb4zFKDtt/go-ws-transport.(*Conn).Close(0xc42057c660, 0x0, 0xc4204a2000)
	/go/src/gx/ipfs/QmSN8R5YxkLgkjeptMpAwV77m11DrHnC7LtxEvb4zFKDtt/go-ws-transport/conn.go:81 +0x5f
gx/ipfs/QmX3U3YXCQ6UYBxq2LVWF8dARS1hPUTEYLrSx654Qyxyw6/go-multiaddr-net.(*maConn).Close(0xc42057c7b0, 0xc4226f9098, 0x13f2ae8)
	<autogenerated>:1 +0x49
gx/ipfs/QmSN8R5YxkLgkjeptMpAwV77m11DrHnC7LtxEvb4zFKDtt/go-ws-transport.(*wsConn).Close(0xc4201aff80, 0xc4210cfd80, 0xc4226f9080)
	<autogenerated>:75 +0x49
gx/ipfs/QmVjRAPfRtResCMCE4eBqr4Beoa6A89P1YweG9wUS6RqUL/go-libp2p-metrics/conn.(*MeteredConn).Close(0xc4201affe0, 0x13f2ae8, 0xc421608700)
	<autogenerated>:1 +0x4a
gx/ipfs/QmeBgocDF6Ru2Aik9ZbahqfbNu8qkDARqJ4D8K3U5RTPVc/go-libp2p-conn.(*singleConn).Close(0xc421608700, 0x0, 0x0)
	/go/src/gx/ipfs/QmeBgocDF6Ru2Aik9ZbahqfbNu8qkDARqJ4D8K3U5RTPVc/go-libp2p-conn/conn.go:61 +0x70
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*etmWriter).Close(0xc421164580, 0x7fe6b0331100, 0xc421164580)
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/rw.go:79 +0x6b
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).Close(0xc4209e13a0, 0x13f3808, 0xc4200951d8)
	/go/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:252 +0x277
gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio.(*secureSession).Close(0xc420094fc0, 0x0, 0x0)
	/go/src/gx/ipfs/QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M/go-libp2p-secio/interface.go:92 +0x98
gx/ipfs/QmeBgocDF6Ru2Aik9ZbahqfbNu8qkDARqJ4D8K3U5RTPVc/go-libp2p-conn.(*secureConn).Close(0xc4209e04a0, 0x13f3808, 0xc421fc0208)
	/go/src/gx/ipfs/QmeBgocDF6Ru2Aik9ZbahqfbNu8qkDARqJ4D8K3U5RTPVc/go-libp2p-conn/secure_conn.go:51 +0x34
gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Session).Close(0xc421fc0160, 0x0, 0x0)
	/go/src/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux/session.go:226 +0xf2
gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Session).exitErr(0xc421fc0160, 0x1a59780, 0xc420012170)
	/go/src/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux/session.go:245 +0x6a
gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.(*Session).recv(0xc421fc0160)
	/go/src/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux/session.go:407 +0x5c
created by gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux.newSession
	/go/src/gx/ipfs/QmQvbWzZPGpoppaAvBtj6QmyBZPw4ivFD7ryyHesxuYYDa/yamux/session.go:108 +0x460

==> .iptb/4/daemon.stdout <==
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/40269/ws
Swarm listening on /ip4/172.17.0.3/tcp/40269/ws
Swarm listening on /p2p-circuit/ipfs/QmRe4VrzFBnBhbLYSz8thZTzD994VQ2LQmK2pyWZ6UuJh7
Swarm announcing /ip4/127.0.0.1/tcp/40269/ws
Swarm announcing /ip4/172.17.0.3/tcp/40269/ws
API server listening on /ip4/127.0.0.1/tcp/37659
Daemon is ready

not ok 106 - shut down nodes
#	
#			iptb stop ||
#				test_fsh tail -n +1 .iptb/*/daemon.std*
#		
```

**Comment by Stebalien** [comment]
So, the websocket library isn't threadsafe.

**Comment by dignifiedquire** [comment]
@Stebalien from the godocs:

> Concurrency
> Connections support one concurrent reader and one concurrent writer.

> Applications are responsible for ensuring that no more than one goroutine calls the write methods (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON, EnableWriteCompression, SetCompressionLevel) concurrently and that no more than one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage, ReadJSON, SetPongHandler, SetPingHandler) concurrently.

>The Close and WriteControl methods can be called concurrently with all other methods.

https://godoc.org/github.com/gorilla/websocket

**Comment by Stebalien** [comment]
Got it. I'll fix the transport lib.

**Comment by Stebalien** [comment]
The bug is fixed *but* yeah we're going to try to fix https://github.com/ipfs/go-ipfs/issues/4202 before moving forward on this.

**Comment by whyrusleeping** [comment]
@Stebalien I merged the /ws fix PR. This one seems good to go, agree? (or does it need another rebase?)

**Comment by Stebalien** [comment]
@whyrusleeping Did the rebase, should be good to go.

**Pull request merged**
