### PR TITLE
switch to go 1.11

### PR DESCRIPTION
**Pull request by Stebalien**
Go 1.11 changes the output of `go fmt` slightly so we either need to
all *downgrade* or *upgrade*. Let's upgrade.

### CODE REVIEW

**Comment by Stebalien** [comment]
Blocked on CI updates (and possibly a gx release)

**Comment by magik6k** [comment]
(https://github.com/ipfs/testing/issues/139)

**Comment by VictorBjelkholm** [comment]
Ok, https://github.com/ipfs/jenkins/pull/126 was deployed, so I rebuilt this branch, but it's failing.

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/PR-5483/3/pipeline/14

```
==> Download complete!

==> using 'tar' to extract binary from archive

rm -f bin/gx-go

ln -s gx-go-v1.7.0 bin/gx-go

gx install --global

ERROR: Error: package 'go-ipfs' requires at least go version 1.11.

however, your gx-go binary was compiled with go1.10.2.

Please update gx-go (or recompile with your current go compiler)

ERROR: req-check hook failed: exit status 1 

mk/gx.mk:4: recipe for target 'gx-deps' failed

make: *** [gx-deps] Error 1

script returned exit code 2
```

**Comment by Stebalien** [comment]
We need to cut a new gx-go release. I'm going to try to merge some fixes first.

**Comment by Kubuxu** [comment]
Any progress on this?

**Comment by Stebalien** [comment]
So, I released a new GX but this is still failing saying that go 1.11 is not available. Does anything else need to be done to get it working?

**Comment by magik6k** [comment]
You need to add a build to dists built with go1.11:
```
==> Using wget to download "https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.14.0/gx_v0.14.0_linux-amd64.tar.gz" to "bin/tmp/gx.tar.gz"

--2018-10-09 09:32:14--  https://ipfs.io/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv/gx/v0.14.0/gx_v0.14.0_linux-amd64.tar.gz
Resolving ipfs.io (ipfs.io)... 209.94.78.81, 209.94.78.78, 209.94.78.79, ...
Connecting to ipfs.io (ipfs.io)|209.94.78.81|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-09 09:32:14 ERROR 404: Not Found.

```

Then set the hash in https://github.com/ipfs/go-ipfs/pull/5483/files#diff-31a09fc8a6f12712273987524eccb1faR3

**Comment by Stebalien** [comment]
Ah, thanks!

**Pull request merged**
