### PR TITLE
Add strings option

### PR DESCRIPTION
**Pull request by crackcomm**
Command strings array option.

It works like that:

```console
$ ipfs -i node_modules -i .git -i yarn.lock -r .
```

It's required to get #3643 done for above to work – ignoring paths.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This feature sounds good to me, makes sense to have and i can definitely see it being useful. I'd like to see some tests around this.

Also, we will have to coordinate adding this feature with @keks refactor work. Shouldnt be a big deal, but definitely need to account for it.

**Comment by kevina** [comment]
@crackcomm the tests failure in ci/circleci look related to your changes

**Comment by crackcomm** [comment]
@kevina passed now

**Comment by whyrusleeping** [comment]
@crackcomm could you add a test or two to commands/cli/parse_test.go for this new flag type?

**Comment by keks** [comment]
The feature and the code LGTM. Since at this point there are zero tests, wouldn't it be better to make this change on top of https://github.com/ipfs/go-ipfs/pull/3856? If we keep changing commands that one will never get merged.

**Comment by crackcomm** [comment]
@keks feel free to do so.

**Comment by crackcomm** [comment]
btw. there are some tests in #4013

**Comment by keks** [comment]
Sure, I'll do that

**Comment by hsanjuan** [comment]
This should be resolved in go-ipfs-cmds if anywhere. So closing this one.

**Comment by Stebalien** [comment]
Fixed a few days ago, actually...

**Pull request closed without merging**
