### PR TITLE
add hidden file by default when add file recursively

### PR DESCRIPTION
**Pull request by kjzz**
fix bug #5126 

License: MIT
Signed-off-by: Kejie Zhang <601172892@qq.com>

### CODE REVIEW

**Comment by kjzz** [comment]
hey @Stebalien , it has already paased required ci,please help me review it .Thx a lot.

**Comment by kjzz** [comment]
hey @Stebalien  , it has already paased required ci,please help me review it .Thx a lot.

**Comment by Stebalien** [comment]
We should get some discussion on this. I'd *prefer* to have done it this way from the very beginning *however*, this is a breaking change.

@ipfs/go-team thoughts? Objections?

**Comment by magik6k** [comment]
Most unix commands such as `cp -r dirA dirB` or `tar -cvf` will include hidden files (shell expansion with `*` won't). It makes sense for me.
(we should ping js team too at some point)

**Comment by bigs** [comment]
yeah i’m in favor of adding dotfiles by default

**Comment by schomatis** [comment]
> Most unix commands such as `cp -r dirA dirB` or `tar -cvf` will include hidden files

:+1:

**Comment by Stebalien** [comment]
@alanshaw ping.

**Comment by kjzz** [comment]
And when we use command `git add`,it also will include hidden file.

**Comment by hsanjuan** [comment]
This is a silently breaking change (the user won't we warned that something has changed). Things like the [go-ipfs-api](https://godoc.org/github.com/ipfs/go-ipfs-api#Shell.AddDir) will start behaving differently because they don't add the `hidden` parameter to the request and the hidden-file-filter happens server-side. People might have been adding files and using hidden folders as a way to exclude files that they don't want to add, or simply forgot about hidden files, potentially leading to security compromises. I'd hope this doesn't affect anyone but if it does, it's not very nice.

**Comment by kjzz** [comment]
> People might have been adding files and using hidden folders as a way to exclude files that they don't want to add, or simply forgot about hidden files, potentially leading to security compromises.
Agree!So Can we add a file like `.gitignore` ,in ipfs it maybe names `.ipfsignore`? It will help user solve this solution.

**Comment by djdv** [comment]
On OS X and Windows, they have specific file-attributes ("invisible" and "hidden") outside of just a dot in the filename. It's a bit more explicit and standard, but I don't know if there's something like that for other systems.
I think dotfiles should be added by default, but files with "hidden" attributes should not.
However, doing that without having those attributes on all platforms, would lock out the ability to skip files for users. So I don't know how best to handle determining what is and is not "hidden". This seems like the bigger problem to me. But likely out of scope.

No opinion on the decision otherwise.

**Comment by kjzz** [comment]
Hey @Stebalien ,I know that `.ipfsignore` won't actually resolve @hsanjuan 's objection.
However,IMO,we could consider to add `.ipfsigonre` feature to help user hidde some file when we use command `-r`or we add directory.This may be a good user experience.WDYT?
And if you agree,i am willing to do it.

**Comment by Stebalien** [comment]
This work was started in https://github.com/ipfs/go-ipfs/issues/3643 but I'm not entirely sure where it left off.

**Comment by djdv** [comment]
After reading the conventions people have posted. I find it hard to believe that someone would have files they don't intend to share, in a target directory. Other tools don't seem to exclude them either, in the same case.
It seems that "hidden" rarely implies "excluded", they're only excluded in listings, like with `ls`.

That being said, this seems like just a configuration change, and I think that's a reasonable thing to do later, during a redesign, so long as we have some kind of clear statement of why something was changed, and how it might impact a user (security/privacy implications, etc.).

**Comment by Kubuxu** [comment]
This will also breat gx as far as I understand as it will start adding `.git`.

**Comment by alanshaw** [comment]
I’m +1 on adding hidden by default. I’m also pretty sure js-ipfs already does this :P

**Comment by keks** [comment]
I just asked David and he says js-ipfs does what go-ipfs does. So probably not doing that by default.

**Comment by vyzo** [comment]
I think that the breakage of applications from this change has to be seriously considered.
We can't quite merge it yet.

**Comment by Stebalien** [comment]
Yeah, this looks like an API 2.0 thing.

**Comment by alanshaw** [comment]
@keks yep, I re-checked and @diasdavid is correct - sorry for any confusion

**Pull request closed without merging**
