### PR TITLE
remove tour command from ipfs

### PR DESCRIPTION
**Pull request by sherodtaylor**
I thought I'd take a stab at my first contribution to ipfs :) #4117

### CODE REVIEW

**Comment by Kubuxu** [comment]
I think you will also have to remove connected sharness tests.

**Comment by sherodtaylor** [comment]
@Kubuxu what sharness test? I can't find a reference to the tour command?

**Comment by Kubuxu** [comment]
```
 …/ipfs/go-ipfs  master  cd test/sharness             
 …/test/sharness  master  ag tour
t0110-gateway.sh
143:for cmd in "add" "block/put" "bootstrap" "config" "dht" "diag" "dns" "get" "id" "mount" "name/publish" "object/put" "object/new" "object/patch" "pin" "ping" "refs/local" "repo" "resolve" "stats" "swarm" "tour" "file" "update" "version" "bitswap"; do
```

**Comment by Kubuxu** [comment]
You can also go here: https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/PR-4123/8/pipeline?start=0#step-80-log-0

and search for `not ok` that isn't marked as `TODO known breakage`

**Comment by sherodtaylor** [comment]
@Kubuxu fixed the sharness test but one build is failing due to issue #4055 and code climate failed because bindata.go is generated. Should I ignore because i don't want to edit the generated file.

**Comment by Kubuxu** [comment]
Ignore the codeclimate on bindata.

**Comment by sherodtaylor** [comment]
is this good to go then?

**Comment by sherodtaylor** [comment]
any update on this @lgierth

**Comment by Kubuxu** [comment]
SGTM but I would like to someone to re-review the bindata.

**Comment by whyrusleeping** [comment]
?This LGTM, could @Kubuxu or @lgierth regen the go-bindata stuff on their own? Would be great to verify all that binary looking nonsense

**Comment by sherodtaylor** [comment]
Is this good to go or are we waiting on another review?

**Comment by whyrusleeping** [comment]
@sherodtaylor Its nearly good to go, I was hoping someone else could verify the bindata generated here. I'll just go ahead and do it now.

**Comment by whyrusleeping** [comment]
Alright, verified this locally. The bindata is correct. Thanks @sherodtaylor !

**Comment by sherodtaylor** [comment]
@whyrusleeping np! Is there anything else I can jump on?

**Comment by whyrusleeping** [comment]
@sherodtaylor theres always something to be done :) I did a quick scan through, and this issue might be something you could tackle: https://github.com/ipfs/go-ipfs/issues/4052. If that looks intimidating then really anything in the issue tracker is fair game, reviewing other peoples code is also one of the most helpful things anyone can do 

Hop into #ipfs-dev on freenode IRC if you have questions

**Pull request merged**
