### PR TITLE
fix log tail command

### PR DESCRIPTION
**Pull request by whyrusleeping**
ipfs log tail works again, turns out its much easier with the new code.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
hrm... apparently the context doesnt behave like i expected it to. I had thought killing the client side would cancel the context. Gotta rewrite something

**Comment by jbenet** [comment]
so with this PR it's exposed in both http routes, correct? (this looks fine to me)

**Comment by whyrusleeping** [comment]
@jbenet yeap! its exposed in both places. I could remove the one at `/logs` if you like.

**Comment by jbenet** [comment]
@whyrusleeping fine keeping it in both places by me.

**Pull request merged**
