### PR TITLE
Make closenotify work [wip]

### PR DESCRIPTION
**Pull request by rht**
@whyrusleeping this appears to reveal the closenotify problem, that now I can receive the "closenotify".

Looks like closenotify channel is consumed during the version check.
This PR still doesn't fix the client cancel yet, since the cancel is for version check request, not the command itself.

### CODE REVIEW

**Comment by rht** [comment]
https://github.com/golang/go/issues/13165

**Comment by whyrusleeping** [comment]
@rht interesting, so if that bug is what we're seeing, then we could solve the problem by adding some buffering to the read side of the request body.

**Comment by rht** [comment]
How to buffer the `ResponseWriter`'s channel without rewriting how `ServeHTTP` is called?

Or put the version check and the command into 1 request packet, fixing #1990 along the way.

**Comment by whyrusleeping** [comment]
hrm, i think this should be able to be solved without doing anything hacky. We just have to figure out what we're doing thats breaking it. Think you could try and get a minimal repro carved out?

**Comment by whyrusleeping** [comment]
@rht close notify is high priority now, i'm noticing it causing lots of issues. Do you think you can figure something out by this weekend? if not, i'll prioritize taking it on myself.

**Comment by rht** [comment]
How about If I figure a sketch of how to solve it I will update you right away?

**Comment by rht** [comment]
(I think this has been solved in etcd before; while golang solution will have to wail until go1.6)

**Comment by whyrusleeping** [comment]
@rht any idea why ours doesnt work, but a simple http server using close notify succeeds?

**Comment by whyrusleeping** [comment]
> How about If I figure a sketch of how to solve it I will update you right away?

Sounds good to me, keep me posted

**Comment by rht** [comment]
@whyrusleeping I tried catching the `<-ctx.Done()` in commands/http/client.client.Send, explicitly, I added
```go

go func(){
    <-req.Context().Done()
    log.Error("client ctx is really canceled")
}()
```

It doesn't print any log message when I C-c the client.

**Comment by rht** [comment]
((Saw the 'closenotify' firing when the client's transport's `DisableKeepAlive` was set to `false` (and other tweaks). When I tried to isolate this change, no longer saw the `closenotify` ever again))

**Comment by whyrusleeping** [comment]
will be fixed in #2032

**Pull request closed without merging**
