### PR TITLE
Remove old DNS TXT schema

### LINKED ISSUE #760: IPNS dns record incorrect
AFAICT the IPNS record lookup is currently incorrect:

```go
	txt, err := net.LookupTXT(name)
	if err != nil {
		return "", err
	}

	for _, t := range txt {
		chk := b58.Decode(t)
```

It should be:

```go
	for _, t := range txt {
		if !strings.HasPrefix(t, "ipns=") {
			continue
		}
		chk := b58.Decode(t[5:])
```

I'll be changing it, which may break people's IPNS names.

### PR DESCRIPTION
**Pull request by Kubuxu**
As for now only dnslink is valid.
Fixes #760

License: MIT
Signed-off-by: Jakub (Kubuxu) Sztandera <kubuxu@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
Should I recreate this PR for dev0.4.0?

**Comment by lgierth** [comment]
> Should I recreate this PR for dev0.4.0?

Looks like it's already based off dev0.4.0 right?

**Comment by Kubuxu** [comment]
I wrote under wrong PR. Sorry for that.

(I should have been sleeping instead of codding and looking through github).

**Comment by Kubuxu** [comment]
It is set to merge to dev0.4.0. Instead of merging it via GH, you have to manually pull this branch into master.

**Comment by jbenet** [comment]
@Kubuxu will be easier if you push a new PR i think. we want CI to run on top of master.

**Comment by Kubuxu** [comment]
See #2193.

**Pull request closed without merging**
