### PR TITLE
update appveyor go version

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
oh. so appveyor has go version 1.5.1 hardcoded. The config value doesnt actually do anything... awesome.

**Comment by whyrusleeping** [comment]
@FeodorFitsner could appveyor install a version of go as specified by the appveyor.yml file? It would be really useful for our testing

**Comment by FeodorFitsner** [comment]
You can install any Go version as part of the build: https://gist.github.com/FeodorFitsner/1cd330d50e91b731b424

**Comment by whyrusleeping** [comment]
oh, nice. Thanks!

**Pull request closed without merging**
