### PR TITLE
fix default-net profile not reverting bootstrap config

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/ipfs/go-ipfs/issues/4842

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@magik6k mind adding a small sharness test for this?

**Comment by magik6k** [comment]
Done

**Comment by whyrusleeping** [comment]
@magik6k I merged your other PR first, need to resolve the conflicts

**Comment by magik6k** [comment]
Rebased

**Pull request merged**
