### PR TITLE
Remove GC timeout, fix GC tests

### LINKED ISSUE #3436: Automatic GC times out
#### Description:

The automatic GC times out. StorageMax is 54G, the repo is 60G big, so the timeout for GC should be something like 6 minutes.

From jupiter:
```
23:41:29.807 WARNI   corerepo: pre-GC: Maximum storage limit exceeded. Maybe unpin some files? gc.go:187
23:41:29.807  INFO   corerepo: Watermark exceeded. Starting repo GC... gc.go:191
23:42:58.626 ERROR   corerepo: context deadline exceeded gc.go:165
```

Note how the context times out after after less than 1.5m already.

### PR DESCRIPTION
**Pull request by lgierth**
Closes #3436 #2129

commit a9b8c8bbd5e243f12d44f67fdb46b80f7f096c5e
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 17:26:53 2016 +0100

    gc: remove wonky timeout
    
    This timeout was:
    - unneccessary
    - based on a metric that doesn't make sense
    
    License: MIT
    Signed-off-by: Lars Gierth <larsg@systemli.org>

commit 8f0c7ee3b02ad0a56358d46f32abd7729e05a791
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 17:28:31 2016 +0100

    gc: remove unneccessary full repo scan
    
    GetStorageUsage() is super expensive as it involves a full repo scan,
    and it's already bad enough that we have do it once.
    
    The call that's being removed here is purely for cosmetical purposes:
    printing the number of bytes freed by the GC run. Let's drop it.
    
    License: MIT
    Signed-off-by: Lars Gierth <larsg@systemli.org>

commit 49802ebac9526740fb0d3dad2c39fe0b132589ba
Author: Lars Gierth <larsg@systemli.org>
Date:   Fri Dec 9 18:04:55 2016 +0100

    gc: fix and re-enable sharness tests
    
    I'm bumping up the waiting time significantly.
    I prefer a slightly slower test to no test at all.
    
    License: MIT
    Signed-off-by: Lars Gierth <larsg@systemli.org>

### CODE REVIEW

**Comment by lgierth** [comment]
Oh my, it timed out on me right away again. Is there any way to avoid the sleep? sync(1)?

**Comment by Kubuxu** [comment]
Sync won't matter as it does kernel cache to disk and problem here is go-ipfs process to kernel. I would just suggest bigger files and error margins.

**Comment by whyrusleeping** [comment]
Yeah... i remember this test being really troublesome. Let me know if you need any help @lgierth

**Comment by lgierth** [comment]
If we're trying to wait for IPFS flusing its writes, why not expose the state of that in the `diag` command?

**Comment by Kubuxu** [comment]
I don't think it will be easy.

**Comment by whyrusleeping** [comment]
@lgierth ipfs flushes its writes... what is the problem?

**Comment by Kubuxu** [comment]
The delay it will take to flush the write is unspecified AFAIK.

**Comment by whyrusleeping** [comment]
The commands shouldnt return before things get flushed...  (unless you have no-flush set)

**Comment by whyrusleeping** [comment]
@lgierth progress here?

**Comment by lgierth** [comment]
This is good to go, I've split the stuff about tests out into the feat/corerepo-gc branch, since it turned into a full-blown rewrite of this GC stuff. :)

This one here now only removes the timeout context around gc.GC(), and the second repo scan after the GC run.

**Comment by lgierth** [comment]
OSX failure is #3496

**Pull request merged**
