### PR TITLE
Feat: ipfs repo size command

### PR DESCRIPTION
**Pull request by hsanjuan**
ipfs repo size just display the repository size without needing to
count the blocks, which takes a significant amount of the repo stat
time.

ipfs-cluster queries the repository size to allocate pins to those
peers with most free space using repo/stat. When done too often on a busy
node, this has resulted in downgraded performance. Counting
blocks is an information that cluster does not use.

License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

### CODE REVIEW

**Comment by hsanjuan** [comment]
This is still relatively slow so I'm not 100% sure it fixes the problem, responses do show a ~40% improvement.

Any of you guys can think of a better way to keeping track of the repo size? Would it be doable to calculate it once and then update the value on every write/gc ?

**Comment by whyrusleeping** [comment]
Maybe we should just add this as a flag to repo stat?

**Comment by Stebalien** [comment]
> Any of you guys can think of a better way to keeping track of the repo size? Would it be doable to calculate it once and then update the value on every write/gc?

I think we should leave it up to the datastore. That is, ask the datastore its size and let it do whatever it needs. For flatfs, we should keep a running count. If you think the performance sucks now, it's going to absolutely *tank* when we upgrade to a kernel with meltdown protections enabled (syscall performance will tank, we're currently doing a `du` (effectively)). For badger, we can just *ask* badger (it provides a `Size` function).

**Comment by lgierth** [comment]
Would it be an option at all to keep track of repo size separately? i.e. start at zero, then increment for every added block, decrement for every deleted block? That'd make repo size an accounting function and not an IO operation anymore.

I don't know how Badger or LevelDB keep track of size, they're probably smarter than flatfs. In that case accounting would still be an option for flatfs?

**Comment by hsanjuan** [comment]
> I think we should leave it up to the datastore. That is, ask the datastore its size and let it do whatever it needs. For flatfs, we should keep a running count.

This sounds like a good way to do. I can try do this. Do you have any pointers? (There's an interface and datastores are implemented in different repos right ?) What datastores are available now?

> Maybe we should just add this as a flag to repo stat?

Sure, it's cosmetic so I can do it at the end (along with tests)

**Comment by kevina** [comment]
Although this might brake backwards compatibility I would lean towards having the stat command only return what is is already computed (much like how the stat system call works on unix) and have *this* command do the actual computation.

**Comment by hsanjuan** [comment]
See #5010

**Pull request closed without merging**
