### PR TITLE
feat: use package-table

### PR DESCRIPTION
**Pull request by hacdias**
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by diasdavid** [comment]
@Stebalien can I merge this?

**Comment by Stebalien** [comment]
@diasdavid not yet.

**Comment by diasdavid** [comment]
@hacdias can you solve the merge conflicts and get your commit signed so that gitcop is happy?

**Comment by hacdias** [comment]
@diasdavid gitcop is now happy!

**Comment by diasdavid** [comment]
@Stebalien can we have this merged?

**Comment by hacdias** [comment]
@Stebalien just updated the table with that info 😄

**Comment by Stebalien** [comment]
(fell into the recesses of my inbox)

**Pull request merged**
