### PR TITLE
Config: allow to set maps on null value

### LINKED ISSUE #1561: Setting "deep" config options doesn't work
I consulted the new CORS documentation in `ipfs daemon --help` and found this

```
You can setup CORS headers the same way:

ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

However, when I tried it I got an error at first.

Using `ipfs config show` I saw that `API.HTTPHeaders` is set to `null`, so I set it to an empty object like this:

```
ipfs config --json API.HTTPHeaders '{}'
```

Afterwards I was also able set properties within the `API.HTTPHeaders` object.

I would have expected the `ipfs config --json` command to automatically create objects along a valid property path.

### PR DESCRIPTION
**Pull request by rht**
Also, now, if ipfs config foo.bar has value of anything that is not map (0, "0", 0.1),
then ipfs config foo.bar.baz now returns an error instead of a panic

Fixes #1561

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c6d1413594b3aa73cc45fb28751f6ac41882195d
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 183a5240d61297863096936ae4ea7648cea16f27
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
Does this mean we can set config values that dont actually exist in the config struct? like `foo.bar.baz`?

**Comment by rht** [comment]
This was already possible before. The PR makes it that if one of the key is null, it can be overwritten with a map (bar with value null -> bar.baz).

**Comment by whyrusleeping** [comment]
@rht okay, seems fine to me then

**Comment by jbenet** [comment]
I just realized that afbdedb was before  c0a0cde, which means one commit fails tests -- let's order things such that no commit fails tests. otherwise hard to rebase.

(this (and github's lack of "issuing a test is why https://github.com/jbenet/git-push-each exists))

**Comment by rht** [comment]
Sorry, I did remember switching the order with rebase but didn't check.

**Pull request merged**
