### PR TITLE
Fix "PNetFingerpint" field typo of core.IpfsNode

### PR DESCRIPTION
**Pull request by ridewindx**

### CODE REVIEW

**Comment by Kubuxu** [comment]
@whyrusleeping I think we can let this pass without Sign-off, what do you think?

**Comment by whyrusleeping** [comment]
He added the signoff. gitcop is just annoying and has bad regexes

**Comment by whyrusleeping** [comment]
formatting is off. @Kubuxu could you run a gofmt on this and push it up?

**Comment by Kubuxu** [comment]
@ridewindx mind rebasing the PR and fixing the conflict, we will try to merge it first thing after 0.4.14 is out.

**Comment by Kubuxu** [comment]
Uhh, sorry. This is already merged, just not in this PR see: https://github.com/ipfs/go-ipfs/pull/4752/

**Pull request closed without merging**
