### PR TITLE
Clear progress bar on `ipfs cat` exit

### LINKED ISSUE #1345: clear progress bar on exit
progress bar sometimes lingers after exit:

```
> ipfs cat QmWmupGwtrGwbu8WL3prFkw4ChAeiYQqHfwRTvBnGhuh6S >/dev/null
75.28 MB / 90.41 MB [=========================================================>-----------] 83.27 % 1s
>
```
would be ideal to (a) stop the progress bar, (b) clear the line before (c) exiting.

### PR DESCRIPTION
**Pull request by rht**
Close #1345 

like `ipfs add`, but not wget/curl.

### CODE REVIEW

**Comment by jbenet** [comment]
This LGTM. I'll try it on OSX. (wish we could test this sort of thing)

thoughts @whyrusleeping ?

**Comment by whyrusleeping** [comment]
this is a pattern i've been seeing more and more frequently, needing to capture the EOF 'event' of a reader and do something to it, whether its close the httpResponse and check for a trailer error, or clear a line of output... I wonder if theres a nice composition for that to happen 'generically'.

Anyways, these changes look good to me, although i wish it was testable

**Comment by rht** [comment]
Ok I will put an asciinema as an evidence. But this only proves that it works on my terminal (urxvt, which emulates vt102).

The chance is high on os x (iterm2 or terminal.app): https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by rht** [comment]
https://asciinema.org/a/4spni8ebrynbu4gy9p2k417jp

**Comment by jbenet** [comment]
@rht that looks really nice :) :+1:

**Pull request merged**
