### PR TITLE
Add newline to end of `ipfs object put` text output.

### PR DESCRIPTION
**Pull request by nham**
License: MIT
Signed-off-by: Nick Hamann <nick@wabbo.org>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
you'll also need to update the relevant sharness tests, `t0051-object.sh` i think

**Comment by rht** [comment]
- [ ] (optional) this class of bug can be wiped out entirely from `core/commands`. If you grep for `strings.NewReader`, there are several more still (e.g. `ipfs id`).

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8a61b536daa413c444bebb8d9173f1caa80c1644
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by nham** [comment]
Per @rht's suggestion I've added newlines to the output for a few more commands: `ipfs resolve`, `ipfs name resolve`, and `ipfs tar add`. I believe I've fixed all the tests. Not sure what the test failure is about, seems unrelated to my changes.

**Comment by rht** [comment]
@nham there are still `ipfs dns`, `ipfs id` left yet to be fixed.

**Comment by jbenet** [comment]
LGTM thanks @nham -- we can do dns and id as separate PR.

**Pull request merged**
