### PR TITLE
Update WebUI version

### PR DESCRIPTION
**Pull request by hacdias**
That ^ /cc @diasdavid

### CODE REVIEW

**Comment by hacdias** [comment]
@Stebalien, despite the Connections page, where are you having issues? 😄

**Comment by Stebalien** [comment]
I think it was just lag introduced by the connections page. That is, I'd open the connections page and then try to switch to the Home page and it wouldn't show anything (although, on further testing, it's just really slow).

I also couldn't get it to create a directory in the Files page on my first try but I can't reproduce that.

**Comment by hacdias** [comment]
@Stebalien yeah, the Conns page is very laggy and buggy. I really want to change that as you know.

**Comment by whyrusleeping** [comment]
@hacdias hrm... either it doesnt work in firefox, or it doesnt work with the ipfs-companion extension. I get the following error message: 
screen shot 2017-12-03 at 9 10 11 am

**Comment by Stebalien** [comment]
Do you not get that second error with the current WebUI? IIRC, the companion redirects any URL starting with `/ipfs/QmId...` to the local gateway (which would cause the webui to be served from the local gateway instead of the local API, causing cors issues).

However, I can confirm that the connections page is broken on Firefox. Here's a stacktrace (FWIW, the JS is compressed).

```
TypeError: e is null
Stack trace:
get@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2502288
n@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2502166
tt@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2529702
t.default/<@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2432989
t.default@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2432111
value@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2428299
value@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:2427636
commitLifeCycles@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:864589
t@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:851042
E@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:856513
_@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:856214
h@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:855346
p@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:854739
updateContainer@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:867378
Jt/<@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:879185
unbatchedUpdates@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:865873
Jt@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:879154
render@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:909256
@http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/ipfs-webui.0.3.0.js:1:771231
 ipfs-webui.0.3.0.js:1:854273
```

**Comment by hacdias** [comment]
@Stebalien strange... every page is working on my computer on Firefox. (I'm using `npm run start` directly from the repo).

**Comment by diasdavid** [comment]
@Stebalien double check to see if you were using the latest released go-ipfs

**Comment by whyrusleeping** [comment]
@hacdias ah, it was the ipfs-companion redirect. @lidel can you take a look at this?

**Comment by lidel** [comment]
Yup, its is the same issues as described in https://github.com/ipfs/ipfs-companion/issues/291
I'll bump the priority and fix it shortly.

Workaround for now: replace `localhost:5001` with `127.0.0.1:5001` (API URL in  browser extension Preferences)

**Comment by whyrusleeping** [comment]
Thanks @lidel!

**Comment by whyrusleeping** [comment]
Also, thank you  @hacdias for all the fixes :)

**Comment by hacdias** [comment]
It was a pleasure!

**Comment by diasdavid** [comment]
Woooooot! :D

**Comment by Stebalien** [comment]
> double check to see if you were using the latest released go-ipfs

It's because I've disabled webgl in Firefox (it's a large attack surface). Nevermind.

**Comment by hacdias** [comment]
😄

**Pull request merged**
