### PR TITLE
S3 0.4.0

### PR DESCRIPTION
**Pull request by whyrusleeping**
PR'ing @tv42's s3 branch against dev0.4.0

### CODE REVIEW

**Comment by tv42** [comment]
Uhh https://github.com/ipfs/go-ipfs/pull/1261 much?

**Comment by tv42** [comment]
Oh I see that pull request is against master; it's that old.

**Comment by whyrusleeping** [comment]
@tv42 yeah, no worries! we've been putting off merging this for way too long.

**Comment by jbenet** [comment]
@whyrusleeping not sure why the tests failed. also looks like it needs to be rebased?

otherwise LGTM

**Comment by whyrusleeping** [comment]
@jbenet can we merge this?

**Comment by jbenet** [comment]
this is failing go tests on mac pretty reliably. 0/6 (3x2) successes

**Pull request merged**
