### PR TITLE
add in some events to bitswap to emit worker information

### PR DESCRIPTION
**Pull request by whyrusleeping**
I'm working on making a bitswap dashboard tool. This PR adds in some events that can be parsed out of the eventlog firehose to generate an informative dashboard to help us better understand what the hell bitswap is up to.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
LGTM. i'll wait for tests

**Comment by whyrusleeping** [comment]
https://github.com/whyrusleeping/bsdash <- if you want to try it out

**Comment by jbenet** [comment]
for you @whyrusleeping -- https://github.com/jbenet/node-bsdash  with gif:

**Comment by whyrusleeping** [comment]
:clap: :+1: now a pretty web gui? :D

**Comment by jbenet** [comment]
> :clap: :+1: now a pretty web gui? :D

@krl, what's the nascent ipfs-app interface? maybe i can make one out of this

**Pull request merged**
