### PR TITLE
Dependancy updates to Go.mod packages

### PR DESCRIPTION
**Pull request by bhaskarvilles**
I have checked the latest versions from package repositories and changed to best upgrades availabe.

Signed-off-by: Bhaskar <hey@bhaskar.email>

### CODE REVIEW

**Comment by Jorropo** [comment]
@bhaskarvilles the tests are failing you need to `go mod tidy` too after updating.

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles the tests are failing you need to `go mod tidy` too after updating.

I got no errors in local branch, but the upgrades was clear and no conflicts with base branch, why it happens with CI ?

**Comment by Jorropo** [comment]
Because your local tests dont check for go mod tidy.

**Comment by BigLep** [comment]
@bhaskarvilles: thanks for the PR.  We usually do this as part of our release process.  We will get that formulated in https://github.com/ipfs/go-ipfs/issues/8576 .  I'm closing this as a result.

**Pull request closed without merging**
