### PR TITLE
daemon: add options to set the API and GW addresses

### PR DESCRIPTION
**Pull request by BenoitKnecht**
The ipfs daemon command lets you initialize the configuration with
default parameters, but in certain situations (like starting ipfs daemon
in a docker container), it would be convenient to be able to set the
API and gateway addresses to something more meaningful.

This patch introduces two new options for the ipfs daemon command:
-address-api and -address-gateway. When used together with -init, they
set the respective addresses in the generated configuration file:

  $ ipfs daemon -init -address-api=/ip4/0.0.0.0/tcp/5001 \
  -address-gateway=/ip4/0.0.0.0/tcp/8080

When used without -init, they simply override value for that run of the
daemon, without overwriting it in the configuration file:

  $ ipfs daemon -address-api=/ip4/0.0.0.0/tcp/5001 \
  -address-gateway=/ip4/0.0.0.0/tcp/8080

### CODE REVIEW

**Comment by Luzifer** [comment]
Intention <3

**Comment by whyrusleeping** [comment]
Would be neat to generalize this into something like:
```
$ ipfs daemon -conf="Addresses.API=/ip4/0.0.0.0/tcp/5002"
```
Although that might be difficult/confusing

**Comment by BenoitKnecht** [comment]
Sorry about the breakage, it should work now.

@whyrusleeping I agree it would be nice to have something more generic, but as you say, it would be more complicated to implement.

**Comment by whyrusleeping** [comment]
Yeah, this LGTM. It solves the problem at hand.

**Comment by jbenet** [comment]
I'd prefer if we generalized sooner than later. when we change, it will break people's scripts.

- How about `--config="<key>=<val>"` as @whyrusleeping suggests?
- And/or, allow passing a partial config via stdin to `ipfs daemon --init`? (some values are json arrays)
- And/or, allow overriding with env vars.

see also: #387 #251 github.com/spf13/viper

**Comment by BenoitKnecht** [comment]
@jbenet Okay, but then it should also be unified between `daemon`, `init` and `config`, as they all offer different ways to alter the configuration file. I'll try and take a look at it over the week-end, and see if I can come up with something.

If anyone has suggestions, or wants to help me on this, don't hesitate.

**Comment by chriscool** [comment]
git has a '-c' option that can be used to change some config parameters when launching a command. No config file is changed. Config options passed like this only have effects on the current command. This option can be used with any command but must me put between 'git' and the command name on the command line.

For example `git -c "color.ui=false" log` will show the output of the log command without color, but will not change any default.

**Comment by jbenet** [comment]
thanks @chriscool -- i like it. agreed that it should only be for that run-- no change to the config on disk. 

Perhaps we should repurpose our own `-c` to do this too, and switch its current use of `-c` (changing the `IPFS_PATH`) to `--ipfs-path`.

**Comment by jbenet** [comment]
@BenoitKnecht thoughts on this?

**Comment by whyrusleeping** [comment]
closing due to inactivity, please reopen as necessary

note: all pull requests older than three weeks may be closed in an effort to keep our open pull requests more focused.

**Comment by Arlodotexe** [comment]
I would like to see this feature added. I'm building dotnet tooling to bootstrap the Kubo process, and would like to provide the option to change this _before_ first startup. This would greatly simplify the setup.

**Pull request closed without merging**
