### PR TITLE
WIP: Add FullName option to adder.

### PR DESCRIPTION
**Pull request by kevina**
Connects to #2634.

### CODE REVIEW

**Comment by kevina** [comment]
Please ignore this one for now.  The failing tests may resolve themselfs when other pull requests related to #2634 get merged.  Marking as blocked.

**Comment by whyrusleeping** [comment]
@kevina Are you going to use this PR? or can we go ahead and close it?

**Comment by kevina** [comment]
@whyrusleeping Unlikely.  However, I would like to keep it open until #3342 is resolved.  If nothing else as a reminder that I need to revert these changes in my branch.

Once #3342 is resolved I will close all obsolete PR.

**Comment by eingenito** [comment]
I'm working my way through PRs oldest first. It sounds like this and #3300 and #3258 are (were) blocked on some complex discussion about desired behavior. I'd like to make a new roll up issue that references the existing issues and these PRs and close all others. @kevina are you okay with that?

**Comment by kevina** [comment]
@eingenito this p.r. doesn't serve a purpose anymore so we can close it.

**Pull request closed without merging**
