### PR TITLE
update go-libp2p with negotiate lazy fixes

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu I pulled your multiplex tests over here because they were able to reproduce the issue this PR is fixing

**Comment by whyrusleeping** [comment]
CHANGELOG:
fix multistream negoitate bug on readonly streams.

**Comment by whyrusleeping** [comment]
CHANGELOG:
Add sharness tests for go-multiplex stream muxer.

**Comment by Kubuxu** [comment]
You didn't pull last commit from that branch 8499ba4

**Pull request merged**
