### PR TITLE
dht: degrade 'no addresses' from error to warning

### LINKED ISSUE #2495: Getting "no addresses on peer being sent!" error
Just installed the go binary 0.3.11 on my Mac OS X, running daemon like explained in the "getting started" guide, and I see errors in the console:

```
19:38:33.376 ERROR        dht: no addresses on peer being sent!
					[local:<peer.ID XKKFFa>]
					[sending:<peer.ID >]
					[remote:<peer.ID SoLnSG>] handlers.go:73
```

Not sure what is this. Is it because I ran `ipfs diag net`?

It seems I am connected well:

```
ipfs swarm peers | wc -l
100
```

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves #2495

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu leave off the makefile changes. And only drop it to a warning. Until we resolve the issue i don't want to have it slip away into oblivion

**Comment by Kubuxu** [comment]
Sorry about the makefile changes, based off a wrong branch.

**Comment by Kubuxu** [comment]
It might be better to lower it to Info so it doesn't how on normal user's console.

**Comment by whyrusleeping** [comment]
@Kubuxu warnings dont show up by default, I think warning is fine for now

**Comment by whyrusleeping** [comment]
@Kubuxu actually....... could you move this change to the https://github.com/libp2p/go-libp2p-kad-dht repo?

**Comment by Kubuxu** [comment]
Moved to https://github.com/libp2p/go-libp2p-kad-dht/pull/15

**Pull request closed without merging**
