### PR TITLE
t0042: fix test indentation

### PR DESCRIPTION
**Pull request by chriscool**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 72bff4348f452aa0505ef0676804c3a97f795a8e
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by chriscool** [comment]
I sent a commit with no trailers on purpose to test the new GitCop message, but it didn't work. I think I didn't log in to GitCop with the right account ...

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f3ff83a2aff426c050a4d23f9aa7b95d17d0471e
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by chriscool** [comment]
Ok, the new GitCop message appears now!

**Comment by chriscool** [comment]
There is this unrelated test failure:

```
go test -tags nofuse ./...
?   	github.com/ipfs/go-ipfs	[no test files]
ok  	github.com/ipfs/go-ipfs/assets	0.098s
ok  	github.com/ipfs/go-ipfs/blocks	0.006s
--- FAIL: TestAllKeysRespectsContext-2 (0.00s)
	blockstore_test.go:184: sync is wrong
FAIL
FAIL	github.com/ipfs/go-ipfs/blocks/blockstore	0.015s
```

**Pull request merged**
