### PR TITLE
refactor: remove dir-index-html submodule  

### LINKED ISSUE #8532: Remove ./assets/dir-index-html submodule
I believe we should merge [dir-index-html](https://github.com/ipfs/dir-index-html) back to go-ipfs. 

No reason for it to be outside. It is a key part of gateway functionality, and having a separate repo + git submodule makes it ridiculously hard to contribute changes.

### PR DESCRIPTION
**Pull request by longfeiWan9**
This PR will close #8532.

- [x] Moved `dir-index-html` submodule back to `go-ipfs`
- [x] Kept the commit history of `dir-index-html`
- [x] update docs to reflect the change
- [x] ensure `binddata` still works as expected with command `go generate .`
- [x] update `go generate .` to build `./assets/dir-index-html/dir-index.html` from `./assets/dir-index-html/src/`
- [x] remove `./assets/dir-index-html/.github|gx`
- [x] decide if we squash or do merge commit 
  > @lidel: discussed during triage, due to the license change and related contributor signoffs (or their lack) we  want to preserve original history and will merge this with merge commit

### CODE REVIEW

**Comment by longfeiWan9** [comment]
Hi, @lidel  I have successfully done the step of removing submodule into go-ipfs, and also keeping the commit history of `dir-index-html`.  But I have a little issue to make sure `go generate .` works properly. I have tried running `go generate .` before and after removing submodule without seccess. Could you please help to review and see if I am doing everything fine ?

**Review by lidel — CHANGES_REQUESTED** [review]
Thank you for cleaning up this @longfeiWan9! :heart:  

Looks good to me, but before we merge this we need to clean up some things that are no longer needed. See comments inline.

**Comment by longfeiWan9** [comment]
@lidel Thanks for all the comments. I have updated the code accordingly, could you please take a look at it to see I understand you and fix it correctly?

**Review by lidel — APPROVED** [review]
Looks good, thank you for cleaning this up @longfeiWan9 

@aschmahmann this is ready for merging. Given the license change and related contributor signoffs (or their lack) we may want to preserve original history, but perhaps it is enough to have it on this PR, and only land squashed commit on `master`?  I'm fine either way.

**Comment by lidel** [comment]
Discussed during triage: due to commits reaching way back beyond the license changes, and related contributor signoffs (or their lack) we  want to preserve original history and will merge this with merge commit

**Pull request merged**
