### PR TITLE
make json, cbor, and git codecs error on empty input

### LINKED ISSUE #8378: Bugs related to codecs that return EOF on encode/decode (EOF error are ignored by CLI so we would need to either fix that or wrap the errors)

### PR DESCRIPTION
**Pull request by mvdan**
(once finished, see the commit message)

Fixes #8378

### CODE REVIEW

**Comment by mvdan** [comment]
This fixes all problems:

```
$ printf '' | ./cmd/ipfs/ipfs dag put --input-enc=dag-json --format=dag-json
Error: unexpected EOF
$ printf 'test' | ./cmd/ipfs/ipfs dag put --input-enc=git-raw
Error: unexpected EOF
```

I imagine we want to tag releases for both ipld-prime and go-ipld-git before we can merge this for a go-ipfs tag.

**Comment by rvagg** [comment]
test/sharness/t0053-dag.sh would be an easy place to test these

**Comment by aschmahmann** [comment]
TODO: Use released version numbers here and then merge

**Comment by mvdan** [comment]
I can help tag go-ipld-git if needed, but go-ipld-prime is @warpfork's realm. Otherwise I don't think you need me for anything else here :)

**Comment by aschmahmann** [comment]
Nope, and AFAICT everything's been released already just needed to do a bump. Thanks for the help here 🙏

**Review by aschmahmann — APPROVED** [review]

**Pull request merged**
