### PR TITLE
Test sort cmp

### PR DESCRIPTION
**Pull request by chriscool**
This implements a test_sort_cmp() shell function that just sorts the files passed as arguments before  calling test_cmp() on the sorted files. This simplifies test scripts.

### CODE REVIEW

**Comment by chriscool** [comment]
One test fails in t0090-get.sh but it is not related.

**Comment by whyrusleeping** [comment]
I really dont know why those tarchive tests have been failing recently... its kinda weird

**Comment by chriscool** [comment]
When I build ipfs with -race and try the following (which is part of t0090-get.sh):

```
echo "Hello Worlds!" >data &&
HASH=`ipfs add -q data` &&
ipfs get "$HASH" >actual
```

you a lot of debug output and `Found 8 data race(s)`.

**Comment by chriscool** [comment]
I opened issue #1012 (ipfs get race conditions).

**Comment by jbenet** [comment]
> I get a lot of debug output and Found 8 data race(s).

wow. great finds! 

---

this PR LGTM. merging

**Pull request merged**
