### PR TITLE
Fix Resolver Cache TTL Check (Issue: 6556)

### PR DESCRIPTION
**Pull request by postables**
Fixes https://github.com/ipfs/go-ipfs/issues/6656

### CODE REVIEW

**Comment by kpp** [comment]
One reason the test failed in CI could be https://github.com/ipfs/go-ipfs/issues/6663

**Comment by postables** [comment]
Why is it a 1min cache? If the record is valid for longer than 1 minute it should be in the cache for the duration of it's validity.

Only storing it for 1 minute leads to a ton of excess work being done searching for a record

**Comment by kpp** [comment]
Still `DefaultResolverCacheTTL` should be `MaxResolverCacheTTL`

**Comment by Stebalien** [comment]
@postables for anyone else visiting this PR, the discussion continues in https://github.com/ipfs/go-ipfs/issues/6656.

@kpp. It's the default, not the max. https://github.com/ipfs/go-ipfs/issues/6656#issuecomment-534252128 is definitely a bug.

**Pull request closed without merging**
