### PR TITLE
refactor object patch command to work more betterer

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
should fix #2070, needs a test for that though

**Comment by Dignifiedquire** [comment]
:100: for great language

**Comment by jbenet** [comment]
diff hard to read-- what changed here?

**Comment by whyrusleeping** [comment]
data for object patch set-data and append-data was being encoded into the url, I moved it into the body as a multipart file (like all our other 'data' commands). The difficult part was breaking up object patch (which was a single command object) into multiple commands to allow us to specify that the data argument needed to be a file (and thus streamed)

**Pull request merged**
