### PR TITLE
chore: Disable testground for now

### PR DESCRIPTION
**Pull request by ajnavarro**
It is having some timeout errors on PRs.

Related: https://github.com/ipfs/go-ipfs/pull/8990

### CODE REVIEW

**Review by galargh — CHANGES_REQUESTED** [review]
https://github.com/ipfs/go-ipfs/actions/workflows/testground-on-push.yml suggests that the workflow is doing just fine in general. 

There might have been some intermittent issues with testground-as-a-service or the dependency upgrade from the PR you linked is actually making go-ipfs slower.

To check the first one, rerun the failing workflows. 

To go around the second one, you could increase the timeout we set on the testground workflow. If you do that, I think this should be done in the PR where you upgrade the dependencies so that it's clear why the timeout had to be upped. Might be worth investigating why the runtime is longer first though.

Either way, I think disabling tests altogether is not what we want here.

**Comment by galargh** [comment]
Also it looks like the change is not a valid workflow yaml - https://github.com/ipfs/go-ipfs/actions/runs/2383097142/workflow

BTW, if we wanted to actually temporarily disable the workflow, we can do that through the `Actions` tab on the repo. Again, I don't think we should do that now.

**Comment by ajnavarro** [comment]
Now they appear to be failing on the master branch. @galargh WDYT about @guseggert comment?

**Comment by galargh** [comment]
> We had a discussion about this yesterday and decided to disable TG tests until the TG setup in general is ironed out, which folks are actively working on.

Could you elaborate on this? At a glance, it seems that over the past 2 weeks it hasn't been behaving too badly.

> I just reran some tests that succeeded a few days ago and they are now failing, some immediately and some with timeouts, presumably the TG cluster is unhealthy or something.

Yeap, that's unfortunate timing. It just went down completely. The timeout issue reported originally was not caused by this.

> But for now I think we should disable this until the dust settles.

I did disable it now but I'd want to reenable it once it comes back online. If for nothing more, just so that we have historical data and can track improvements. But

**Pull request closed without merging**
