### PR TITLE
[CORS] Bubble go-ipfs-cmds 2.0.10 - Updates CORS library

### PR DESCRIPTION
**Pull request by hsanjuan**
Merge only after https://github.com/ipfs/go-ipfs-cmds/pull/139

Small behaviour change but should not affect things.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Fixes one item in #5745

**Comment by Stebalien** [comment]
Looks like some error checks in the API sharness tests need to be updated for https://github.com/ipfs/go-ipfs-cmds/pull/138.

**Comment by hsanjuan** [comment]
Ỳeah I noticed. Will go through that later.

**Comment by hsanjuan** [comment]
@Stebalien I have fixed the sharness. I don't think the rest of failing tests are my fault.

**Pull request merged**
