### PR TITLE
t0040: test ipfs add with stdin

### PR DESCRIPTION
**Pull request by chriscool**
Let's test 'ipfs add' with stdin input too.

License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

### CODE REVIEW

**Comment by chriscool** [comment]
The errors are:

```
race: limit on 8192 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap	4.227s
```

```
expecting success: 
	test_must_fail ipfs init 2> init_fail_out

initializing ipfs node at /workspace/ipfs_test_all_commits_on_branch/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0020-init.sh/.badipfs
generating 2048-bit RSA keypair...done
peer identity: QmNUG47KsEkMVDcxVLceRmjTYYjn8WVBZRkmaxogHvG2TY
to get started, enter:

	ipfs cat /ipfs/Qmcqtw8FfrVSBaRmbWwHxt3AuySBhJLcvmFYi3Lbc4xnwj/readme

not ok 2 - ipfs init fails
#	
#		test_must_fail ipfs init 2> init_fail_out
#	
```

```
expecting success: 
	export IPFS_PATH="$IPTB_ROOT/3" &&
	NODE2_ID=`iptb get id 2` &&
	ipfs cat /ipns/$NODE2_ID > output
Error: context deadline exceeded
not ok 5 - cat that entry on a third node
#	
#		export IPFS_PATH="$IPTB_ROOT/3" &&
#		NODE2_ID=`iptb get id 2` &&
#		ipfs cat /ipns/$NODE2_ID > output
#	
```

```
expecting success: 
	export IPFS_PATH="$IPTB_ROOT/2" &&
	ipfs cat $FILEA_HASH >fileb
Error: context deadline exceeded
not ok 3 - cat that file on node2
#	
#		export IPFS_PATH="$IPTB_ROOT/2" &&
#		ipfs cat $FILEA_HASH >fileb
#	
```

**Comment by whyrusleeping** [comment]
digging into the iptb failures, i'm beginning to think its a DHT issue. the keyspace randomly gets into a position where there are no nodes closer to a given key other than yourself, so you end up failing to do a get/put

**Comment by chriscool** [comment]
@whyrusleeping anyway it is not related to the PR so please merge it.

**Comment by jbenet** [comment]
@chriscool LGTM, thanks

**Pull request merged**
