### PR TITLE
Add ip6 interface to default config

### PR DESCRIPTION
**Pull request by spikebike**
Seems like a good idea for the default config file to listen IP6 equivalent of /ip4/0.0.0.0/.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ad937576cc0166e029c8f83a0e70da479f615d0d
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

Guidelines are available at: https://github.com/ipfs/community/blob/master/docs/commit-message.md Your feedback on GitCop is welcome on the following issue: https://github.com/ipfs/infrastructure/issues/23

---
This message was auto-generated by https://gitcop.com

**Comment by spikebike** [comment]
License: MIT Signed-off-by: Bill Broadley <bill@broadley.org>

**Comment by jbenet** [comment]
@spikebike thanks, this is great. need to add the signoff to the git commit itself

**Comment by jbenet** [comment]
@spikebike can just fix it and force-push to the same branch

**Pull request closed without merging**
