### PR TITLE
Dev0.4.0 vendor exp

### PR DESCRIPTION
**Pull request by whyrusleeping**
This PR begins the process of using gx and the go vendor experiment to break code out from the main go-ipfs codebase. Getting this in will make pulling out (and vendoring) libp2p much easier.

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping which are the relevant extracted out repos?

One important thing that made npm very successful is that it tries hard to get a repo associated with the packages. that way users can find where to contribute + file bugs, etc. would be good to have properties like 
```
"issues": "https://github.com/whyrusleeping/go-keyspace/issues"
```

---

also, can we put all of them in the ipfs org? that way we'll be sure they stay there and dont change names long term etc.

**Comment by whyrusleeping** [comment]
re: the issues key, thats a good idea. 

> also, can we put all of them in the ipfs org?

We can, i'm just leery about cluttering up the ipfs org with all of these packages. maybe a `go-ipfs` org?

**Comment by jbenet** [comment]
> cluttering up the ipfs org

why is a large number of repos a problem? they're not hurting anyone-- there's a search bar and already way too many to browse. the directory is what people should look at for descriptions anyway

**Comment by jbenet** [comment]
there's a bunch of problems with managing multiple orgs, acl's on github are annoying.

**Pull request closed without merging**
