### PR TITLE
ci: Collect test times for sharness

### PR DESCRIPTION
**Pull request by magik6k**

### CODE REVIEW

**Comment by magik6k** [comment]
Should be ready, you can now view and sort by test times in the old ui - https://ci.ipfs.team/job/IPFS/job/go-ipfs/job/PR-4959/7/testReport/sharnessLinux/

**Comment by magik6k** [comment]
Needed to install a custom version of JUnit plugin with one fix applied, related issue - https://github.com/ipfs/jenkins/issues/110

**Comment by Kubuxu** [comment]
Should we also collect it for OSX?

**Comment by Kubuxu** [comment]
But let's do it in separate PR.

**Comment by Kubuxu** [comment]
Ahh, osx is temporaryly disabled becuase it fails too frequently.

**Pull request merged**
