### PR TITLE
feat: Update to the latest version of the webui

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Ref #2162

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: da7b22f894d3a987aa122eefcf4c6dfb5f775319
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by RichardLitt** [comment]
That's weird, that sign off looks fine to me.

**Comment by Dignifiedquire** [comment]
@RichardLitt force push ;)

**Comment by whyrusleeping** [comment]
LGTM

**Comment by jbenet** [comment]
@whyrusleeping did you test it manually before merging?
>
>

**Comment by whyrusleeping** [comment]
Yeap! on two machines

**Comment by whyrusleeping** [comment]
(and on firefox)

**Comment by whyrusleeping** [comment]
and we ran through all the tests for js-ipfs-api

**Comment by jbenet** [comment]
:+1:
>
>

**Pull request merged**
