### PR TITLE
mfs: remove `sort` from `ListNames()`

### PR DESCRIPTION
**Pull request by schomatis**
Fixes https://github.com/ipfs/go-ipfs/issues/5181.

### CODE REVIEW

**Comment by schomatis** [comment]
Checking if this upsets any test...

**Comment by schomatis** [comment]
It doesn't, the sort can be added at the `ipfs` command level.

**Comment by schomatis** [comment]
Add test.

**Comment by Stebalien** [comment]
@schomatis I assume this is ready (and no longer "do not merge").

**Comment by schomatis** [comment]
Yes, sorry, forgot to change that, thanks!

(I use too many anti-merge precautionary measures :))

**Pull request merged**
