### PR TITLE
add fetch flag to pin add and Pin() functions

### PR DESCRIPTION
**Pull request by Voker57**
this allows pinning without fetching data in case it's not needed

### CODE REVIEW

**Comment by Kubuxu** [comment]
The fetch is needed for the GC to function correctly, if whole data isn't present from a pin tree GC will throw an error to prevent loss of data (one missing block could cause removal of TBs of data).

The fetch will check local repo first so it won't be doing unnecessary fetches.

Is that what you were going for?

**Comment by Voker57** [comment]
No, I'm going for speeding up pinning of already local data. I'm doing repeat pins on updated directory and checking for data in local repo is taking vast majority of time (34m for each iteration currently)

**Comment by Kubuxu** [comment]
That is necessary operation for guarantee we want to provide, it also just means that we should improve performance of this process instead.

How big is the data your are pinning and the repo itself?

**Comment by whyrusleeping** [comment]
I think this is probably okay to add, *BUT* we need to add a warning that using this when you don't actually have all blocks local will cause repo corruption.

**Comment by Kubuxu** [comment]
I can +1 on that with very clear warnings and option with name similar to `--i-know-what-I-am-doing-just-let-me-do-it`.

It is potentially more damaging than block rm command.

**Comment by Voker57** [comment]
Added warning. Is scary name really necessary?

**Comment by whyrusleeping** [comment]
I'm still moderately uncomfortable having this named fetch. I do think it should be named something a little scarier. Any thoughts @Kubuxu ?

In reality, the need for this can be alleviated by making `FetchGraph` faster

**Comment by kevina** [comment]
> It is potentially more damaging than block rm command.

Yes.  And in that case @whyrusleeping insistent I check for pins even though it can be very slow.  I has an option to avoid the pin check but I removed it die to @whyrusleeping which I somewhat agree with.

**Comment by whyrusleeping** [comment]
@kevina Yeah... I think i'm really leaning towards closing this PR.

@Voker57 With the recent improvements to the enumerate code, is the perf in an acceptable range for you?

**Comment by Voker57** [comment]
@whyrusleeping absolutely unacceptable, only link caching might help.

**Comment by whyrusleeping** [comment]
@Voker57 Would an `ipfs pin update` command help with your usecase? It would short circuit fetching things that are already pinned by a given pin. the usecase here is for updating pins on large datasets as they change over time

**Comment by Voker57** [comment]
@whyrusleeping yes, it would mostly solve the problem.

**Comment by whyrusleeping** [comment]
@Voker57 Great! We will get that done in the next release

**Comment by Voker57** [comment]
Not much point in this now, especially if #3642 gets merged.

**Pull request closed without merging**
