### PR TITLE
gx: update go-libp2p-peer

### PR DESCRIPTION
**Pull request by Stebalien**
Reverts the changes that allowed small keys (ed25519 keys) to be inlined.

### CODE REVIEW

**Comment by Stebalien** [comment]
@hoffmabc this should unblock the rebase (once merged).

**Comment by Stebalien** [comment]
This is a large GX update. Will this cause any rebase headaches?

**Comment by magik6k** [comment]
This will have some conflicts with https://github.com/ipfs/go-ipfs/pull/5661 and some of it's deps, but feel free to merge this if you feel that files2.0 need more work

**Comment by Stebalien** [comment]
@magik6k I'll handle that rebase.

**Pull request merged**
