### PR TITLE
use floodsub version 0.8.1

### PR DESCRIPTION
**Pull request by keks**
New floodsub! Now with cancellation and stuff.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This LGTM.

**Comment by keks** [comment]
@haadcode what do you think?

**Comment by keks** [comment]
firing `Ctrl+C` in `ipfs pubsub sub foo` behaves different than in master now...I don't get what happens yet.

**Comment by keks** [comment]
I now treat a `context.Canceled` error returned by `sub.Next(ctx)` the same as an `io.EOF`.

**Comment by haadcode** [comment]
LGTM too. With this PR the issues on JS side are fixed, so 🎉 

Thank you @keks!

**Comment by whyrusleeping** [comment]
@keks mind rebasing? I'll merge as soon as thats done

**Comment by keks** [comment]
@whyrusleeping Okay I rebased. Idk what's with CircleCI, I can't even view the page. Its all blank for me

**Pull request merged**
