### PR TITLE
adds more info about chunker option

### PR DESCRIPTION
**Pull request by thisconnect**
see https://github.com/ipfs/go-ipfs/issues/4276

License: MIT
Signed-off-by: Enrique Erne <enrique.erne@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Yeah, definitely worth having this + examples in the `LongDescription` section.

**Comment by whyrusleeping** [comment]
Thanks for the PR @thisconnect, documentation additions are the best :)

**Comment by thisconnect** [comment]
Sorry my internet a bit wonky I am traveling. Explaining the option in LongDescription does make sense, but the short one also needs something more descriptive than `Chunking algorithm to use.` + Default

What do you all think about the latest commit? Still too long?

**Comment by whyrusleeping** [comment]
@thisconnect That looks good to me! Mind also adding something to the long description while we're at it? Maybe a few examples?

**Pull request merged**
