### PR TITLE
Humanize bytes in dir index listing

### PR DESCRIPTION
**Pull request by rht**
Fixes https://github.com/ipfs/dir-index-html/issues/3

### CODE REVIEW

**Comment by jbenet** [comment]
LGTm

**Comment by jbenet** [comment]
(guessing vendor first, then merge)

**Comment by lgierth** [comment]
looking forward to meeting the first humanoid bytes

**Comment by rht** [comment]
Here is the chronology

* `dir-index-html (master): git commit -a -m "Remove 'bytes'"`
* `dir-index-html (master): git push upstream master`
* `dir-index-html (master): gx publish`
* `dir-index-html (master): new_hash=`get_the_hash_from_prev_output_with_mouse``
* `dir-index-html (master): cd $go_ipfs_repo`
* `go-ipfs (dir-index-humanize): old_hash=`get_the_hash_from_vendor_src_with_mouse``
* `go-ipfs (dir-index-humanize): ipfs daemon &`
* `go-ipfs (dir-index-humanize): gx update $old_hash $new_hash`
* `go-ipfs (dir-index-humanize): cd assets`
* `go-ipfs (dir-index-humanize): ln -sf ../vendor/src/QmeMZwyPnHMkvgdUNtdNcTX425gTCi5DCMeHLwTXbKoUB8/dir-index-html/gw-assets gw-assets`
se`d -i s/$old_hash/$new_hash/ core/corehttp/gateway_indexPage.go # because sed: couldn't edit assets: not a regular file`
* `go-ipfs (dir-index-humanize): go-bindata -pkg=assets init-doc gw-assets ../vendor/src/$new_hash/dir-index-html/dir-index.html ../vendor/src/$new_hash/dir-index-html/knownIcons.txt && cd -`
* `go-ipfs (dir-index-humanize): git rm -r vendor/src/$old_hash`
* `go-ipfs (dir-index-humanize): git add vendor/src/$new_hash`
* `go-ipfs (dir-index-humanize): git commit --amend --no-edit -a`
* `go-ipfs (dir-index-humanize): git push --force`

**Comment by jbenet** [comment]
wonder how we want to be using gx. cc @whyrusleeping for feedback.

**Comment by jbenet** [comment]
@rht could we turn this into a quick script or something?
 
```
make update
```
in that directory or something.

**Comment by rht** [comment]
The only `make update` parts are
```shell
update() {
hash="$1"
cd assets
ln -sf ../vendor/src/$hash/dir-index-html/gw-assets gw-assets
go-bindata -pkg=assets init-doc gw-assets ../vendor/src/$hash/dir-index-html/dir-index.html ../vendor/src/$new_hash/dir-index-html/knownIcons.txt
cd -
}
```

The rest should be a git hook like `git gx-update $oldhash $newhash`.

**Comment by jbenet** [comment]
@rht sure, can you add that to a script there?

**Comment by rht** [comment]
@jbenet the make will be simpler (no need to pass the hash to the `make update`) after @lgierth's update on dir-index-html.

**Comment by jbenet** [comment]
Ok

**Pull request merged**
