### PR TITLE
More robust version checking

### PR DESCRIPTION
**Pull request by rht**
@jedahan's PR #2100 ~~with the signoff fixed~~.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c0382befcc2952d5da45d621cf5cfc46a589b90b
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by rht** [comment]
Attribution fixed.

**Comment by rht** [comment]
cc @germonprez to shed some light here.

**Comment by whyrusleeping** [comment]
I don't think we can do this. We can rewrite the fix ourselves, but this is applying a different license to code than the author intended (whether on purpose or not).

**Comment by rht** [comment]
It might be possible to do this, ref: https://github.com/ipfs/go-ipfs/pull/2100#issuecomment-174533869.

**Comment by rht** [comment]
I'm signing this off under rht, not jedahan. The remaining issue is attribution.

**Comment by whyrusleeping** [comment]
mmm, okay. that sounds feasible... i guess we should ping a lawyer or something (which it looks like you might have already done)

**Comment by whyrusleeping** [comment]
would also be good to set a pre-receive hook on the server to flat out reject any commits that don't have a proper signoff (not sure if we can do that)

**Pull request closed without merging**
