### PR TITLE
Fix docker $ipfs_data mount path in README

### PR DESCRIPTION
**Pull request by ehd**
Hey, just a small doc fix. I noticed that no data was placed in my host system's folder. wking on IRC pointed out that the folder moved in 0.3.0 and the documentation hasn't been updated.

### CODE REVIEW

**Comment by jbenet** [comment]
@ehd ah yes! thanks.

**Comment by Luzifer** [comment]
The new `Dockerfile` put the ipfs dir into `/data/ipfs`

**Comment by jbenet** [comment]
Arg, that's right >.<

**Comment by ehd** [comment]
Whoops, thought I checked the Dockerfile for `VOLUME` instructions, but probably looked before that change was made! Made #1167

**Pull request merged**
