### PR TITLE
try to raise ulimit if its too low

### PR DESCRIPTION
**Pull request by whyrusleeping**
ref #2431

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by diasdavid** [comment]
registry-mirror requires more than 1024 files open at the same time (or at least makes IPFS do it), it would be nice if IPFS would increase the limit preemptively before crashing.

**Comment by whyrusleeping** [comment]
@diasdavid but did it work for you?

**Comment by diasdavid** [comment]
@whyrusleeping failed with 1024, worked with 4096

**Comment by chriscool** [comment]
Why is there this last commit merging master into the branch for this PR?
Also maybe there could be some tests to make sure this works or, if not possible, fails gracefully.

**Comment by whyrusleeping** [comment]
@chriscool thats github being weird... I'm also not sure how to test this. Any ideas?

**Pull request merged**
