### PR TITLE
[WIP] gx: update `go-merkledag` to match version used in `go-unixfs`

### PR DESCRIPTION
**Pull request by schomatis**
Do not merge.

See https://github.com/ipfs/go-unixfs/issues/4.

### CODE REVIEW

**Comment by schomatis** [comment]
Closed due to forced push.

**Comment by whyrusleeping** [comment]
You'll also need to update go-blockservice I think. Run `gx deps dupes` to see if anything looks wrong.

**Comment by schomatis** [comment]
`gx deps dupes` reported (among many duplicates) the old hash of `go-merkledag` being used, I grep'ed for it in the `gx` dir (is there an easier way for this? a `gx` flag to know which package is importing the old hash?) and it seems that the `go-path` version used in `go-ipfs` is using it, although this doesn't affect the build (probably because those two don't interact), should I update the `go-path` version in this same PR?

**Comment by schomatis** [comment]
So, this is breaking the build because I updated `go-merkledag` to the version used by the `master` branch  of `go-unixfs` (for `gx-go link` to work) but `go-ipfs` is using a gx-version of `go-unixfs` which is actually using the old `go-merkledag` version (`QmRy4Q...s59`) that I'm updating here, so I guess I need to first update `go-unixfs` here to the master version gx-release (that uses the new `go-merkledag` version `QmfGzd...9TS`) and then update `go-merkledag`, or maybe that needs to happen in the same PR otherwise I think there might be a version mismatch in the converse relation of the what's happening here now that's breaking the build (my head is aching at this point so I'm going to take a pause here and rethink this, let's not merge anything until then).

**Comment by schomatis** [comment]
Closing in favor of #5336, thanks @hsanjuan!

**Pull request closed without merging**
