### PR TITLE
Tune resource limits on BSDs

### PR DESCRIPTION
**Pull request by polezaivsani**
License: MIT
Signed-off-by: Vasily Kolobkov <polezaivsani@openmailbox.org>

### CODE REVIEW

**Comment by lgierth** [comment]
Cool thanks! Did you test this automatically raise the ulimit if it's too low?

**Comment by polezaivsani** [comment]
Ya, does it's job fine on OpenBSD. Funny thing, my daemon log was
rampant with 'too many files open' messages and i though the bound
on open files is yet to be implemented when accidentally having
stumbled upon this little thingy :)

**Comment by lgierth** [comment]
Hah good to hear! LGTM :+1:

**Comment by whyrusleeping** [comment]
Huh, cool. Didnt know if this code would just work on those systems or not. Thanks!

**Pull request merged**
