### PR TITLE
RFC(Kuba): updated urlstore

### PR DESCRIPTION
**Pull request by Stebalien**
This is a rebase of feat/ai-mirror on top of the latest master. Before
force-pushing this to feat/ai-mirror, I figured @Kubuxu should look it over.

DO NOT MERGE THIS PR INTO MASTER.

REVIEW ONLY!

### CODE REVIEW

**Comment by Kubuxu** [comment]
@Stebalien I pushed a commit into that branch.

```
diff --git a/filestore/fsrefstore.go b/filestore/fsrefstore.go
index f476ba6fd..9b1be80d2 100644
--- a/filestore/fsrefstore.go
+++ b/filestore/fsrefstore.go
@@ -121,7 +121,7 @@ func (f *FileManager) Get(c *cid.Cid) (blocks.Block, error) {
 }
 
 func (f *FileManager) readDataObj(c *cid.Cid, d *pb.DataObj) ([]byte, error) {
-	if !*d.URL {
+	if d.GetURL() {
 		return f.readFileDataObj(c, d)
 	} else {
 		return f.readURLDataObj(c, d)
```

**Comment by Stebalien** [comment]
(I reset feat/ai-mirror to this branch and pushed the same commit (well, with `!d.GetURL()`).

**Comment by Kubuxu** [comment]
yeah, right, sorry for that

**Comment by Stebalien** [comment]
Nope, my bad. I should have read your comment and gotten this working before resetting `feat/ai-mirror` (I saw the :heavy_check_mark: and jumped the gun).

**Pull request closed without merging**
