### PR TITLE
add some tips for making dep installs go smoothly

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@RichardLitt take a look at this for me?

**Comment by noffle** [comment]
Aw yeah, that's an unfortunate gotch-ya. Can `gx` check the daemon version and fallback to public gateway if it's < 0.4.0?

**Comment by whyrusleeping** [comment]
@noffle yeah, we could do that... but it feels kinda weird. what if people start using gx on 0.3.* ? (maybe we just don't support that?)

**Comment by noffle** [comment]
Right: the check should be in the makefile here, not in `gx`.

**Comment by Kubuxu** [comment]
`gx` could have flag to force it using global gateway and then run `gx` in the Makefile with this flag if detected IPFS version is <0.4.

**Comment by RichardLitt** [comment]
@whyrusleeping LGTM. Added a commit.

**Pull request merged**
