### PR TITLE
Close errnotifier chan on err

### PR DESCRIPTION
**Pull request by rht**
updated #2102

### CODE REVIEW

**Comment by whyrusleeping** [comment]
cool, remove the spaces and squash those commits then LGTM

**Comment by rht** [comment]
While this PR does explicitly close the chans, it still hasn't fixed the add stall (e.g. the latest travis-ci err in commit 7)

**Comment by rht** [comment]
At least the err location has been constrained to be within `writeErrNotifier`.

**Comment by whyrusleeping** [comment]
closing in favor of #2554

**Pull request closed without merging**
