### PR TITLE
feat(daemon): print version

### PR DESCRIPTION
**Pull request by overbool**
License: MIT
Signed-off-by: Overbool <overbool.xu@gmail.com>

Fixes: https://github.com/ipfs/go-ipfs/issues/5498

### CODE REVIEW

**Comment by overbool** [comment]
@Stebalien @kevina 

`make install` will call `go install -ldflags="-X "github.com/ipfs/go-ipfs/repo".CurrentCommit=7a98bcb52" ./cmd/ipfs`, is it right?

`CurrentCommit` is under the package `ipfs/go-ipfs`, therefore, I think it should be modify to 

`make install` will call `go install -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=7a98bcb52" ./cmd/ipfs`

**Comment by kevina** [comment]
@magik6k `git blame` shows you last modifying the relevant line in `cmd/ipfs/Rules.mk`
```
b65cf84a (Łukasz Magiera  2018-07-23 19:11:39 +0200 16) $(d)_flags =-ldflags="-X "github.com/ipfs/go-ipfs/repo".CurrentCommit=$(git-hash)"
```
Commit b65cf84a

**Comment by magik6k** [comment]
No, this isn't right, pushed a fix in https://github.com/ipfs/go-ipfs/pull/5507

**Comment by Stebalien** [comment]
(:+1: to what @kevina said)

**Comment by overbool** [comment]
@Stebalien @kevina Which package should we use to put some common functions(like `printVersion`, maybe will be used by `cmd/ipfs/daemon.go` and `core/commands`)

**Pull request merged**
