### PR TITLE
fix swaped argument in rabin.go

### PR DESCRIPTION
**Pull request by MichaelMure**
License: MIT
Signed-off-by: Michael Muré <batolettre@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
whoops.

**Comment by whyrusleeping** [comment]
that *would* explain why sizes were kinda finicky

**Comment by rht** [comment]
LGTM

**Comment by jbenet** [comment]
:/ we should have tests for this.

**Comment by jbenet** [comment]
thanks @MichaelMure

**Comment by jbenet** [comment]
@whyrusleeping want to write some tests? you're most familiar with all that jazz.

**Pull request merged**
