### PR TITLE
Switch to Go 1.12

### PR DESCRIPTION
**Pull request by Kubuxu**
Got some errors in version deps PR from updating to Go 1.12
Creating this PR to track it

### CODE REVIEW

**Comment by Kubuxu** [comment]
Sharness is failing on some `ipfs add`, not sure why.

**Comment by Stebalien** [comment]
(rebuilding as there was no useful information in the test logs)

**Comment by Stebalien** [comment]
Ok, I think we have a memory corruption bug somewhere. Fun times.

**Comment by Kubuxu** [comment]
It is still failing so I wouldn't pass it.
I also don't really have time to investigate it deeply.

**Comment by Stebalien** [comment]
That's disturbing...

**Comment by Stebalien** [comment]
I still have no idea what's going on here. I can't reproduce on my machine at all.

**Comment by Kubuxu** [comment]
Same, I couldn't reproduce.

**Comment by Kubuxu** [comment]
Aaah, it is a problem in sharness coverage wrapper: 
```
goroutine 19 [running]:
os.(*Process).signal(0x0, 0x4f8600, 0xc0000d2188, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:131
main.main.func1(0xc0000ec000, 0xc0000de1e0)
	/home/circleci/ipfs/go-ipfs/coverage/main/main.go:49 +0x71
created by main.main
	/home/circleci/ipfs/go-ipfs/coverage/main/main.go:47 +0x428
```

**Comment by Kubuxu** [comment]
@Stebalien should be fixed.

**Comment by Kubuxu** [comment]
On circle: disabled `-j10`, disabled continue on failure, enabled SSH, waited for failure, connected SSH (this took 5 tires because I was leaving it for too long and Circle was closing SSH). Then I've checked the trash directory in `test/sharness`.

**Comment by Stebalien** [comment]
TIL, circle has ssh access... That's going to make my life much easier.

**Comment by Kubuxu** [comment]
Yeah, it is semi-hidden under a menu arrow of `Rebuild`

**Pull request merged**
