### PR TITLE
Fix "ipfs ls" to once again work on arbitrary dag objects.

### LINKED ISSUE #4075: `ipfs ls $blobhash` gives: Error: merkledag node was not a directory or shard
Version: 0.4.10

Issue at hand is that it is no longer possible to use `ipfs ls` with blob hashes (hashes of straight up files). It was broken somewhere along integration of sharding or cleanup of some error messages.

~ Kubuxu - this was edited by me as it is top message of the issue

### PR DESCRIPTION
**Pull request by kevina**
Closes #4075

License: MIT
Signed-off-by: Kevin Atkinson <k@kevina.org>

### CODE REVIEW

**Comment by Stebalien** [comment]
Should this really be listing the links at the merkledag level? `ls file.txt` in POSIX systems will just list the file.

**Comment by kevina** [comment]
This simply restores the old behavior (before c4c665395a8ef92360f4251bbb3df712538035f6) instead of returning the error.

**Comment by Stebalien** [comment]
you're right... we can fix that later (#4186)

**Comment by whyrusleeping** [comment]
@Kubuxu @VictorBjelkholm why does the jenkins link take me to a broken ngrok?

**Comment by Kubuxu** [comment]
@VictorBjelkholm was updating the jenkins. Something broke?

**Comment by VictorBjelkholm** [comment]
@whyrusleeping 

> @Kubuxu @VictorBjelkholm why does the jenkins link take me to a broken ngrok?

I was running tests from local jenkins instance to verify that new changes were not breaking stuff. I rerun the job on the production instance now, and the link have changed to https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/PR-4184/ now Sorry for that!

**Pull request merged**
