### PR TITLE
sharness: fix the error message in the mount-publish test case

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
Travis didn't catch this as it doesn't test FUSE.

**Comment by whyrusleeping** [comment]
LGTM, good catch @Stebalien :)

As a side note, do the fuse bindings (and tests) work for you?

**Comment by Stebalien** [comment]
I don't think I've been able to run them all the way through (mostly because some of the longer ones take *hours*).

**Comment by Kubuxu** [comment]
The fuse tests like to hang for no reason. It got better when we updated the FUSE lib but it still might be the case.

**Comment by Stebalien** [comment]
Many of them *do* finish, they just take a while (some of them seem to be hashing *lots* of data).

**Pull request merged**
