### PR TITLE
[wip] ci: Run ipfs/js-ipfs-http-client & ipfs/interop tests

### PR DESCRIPTION
**Pull request by magik6k**
This PR:
* Runs tests from https://github.com/ipfs/interop
* And from https://github.com/ipfs/js-ipfs-api
* And pushes more statuses to github so we don't have to wait for everything to finish

TODO:
- [ ] Make sure the tests actually use provided go-ipfs
- [ ] Try to skip parts that don't touch go-ipfs
- [ ] Make sure tests are stable
- [ ] Deduplicate code with jenkins-libs
- [ ] Collect test results

### CODE REVIEW

**Comment by magik6k** [comment]
I updated js-ipfs-api/interop to latest versions, but there was only 1.5/20 successful passes. the tests also took a ton of time (avg 26min for interop, and ~101min (!) for js-api)

@diasdavid @alanshaw Can you have a look at the failures in https://ci.ipfs.team/job/IPFS/job/go-ipfs/job/PR-5053/? Is that caused by the way the tests are invoked here or could something be broken in go-ipfs master?

**Comment by alanshaw** [comment]
hey @magik6k, awesome to see this PR! 💖 

js-ipfs-api tests take around 40 minutes right now (they run against go-ipfs): https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/activity. I'm hoping to decrease that time this quarter.

For the js-ipfs 0.31 release I ran the interop tests locally and they all passed. I believe they were also passing on CI...

I was under the impression these were working on CI also, https://github.com/ipfs/interop/pull/28 ...can't lookup the history as the jobs have been purged already but it looks like it was also failing here.

It would be cool if we could work together to fix this up - I think it's both our responsibilities to create and maintain interop!

**Comment by magik6k** [comment]
So I've rebased this and updated js-ipfs-api/interop commits, and it looks like we've broke some things between now and 0.4.17: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/PR-5053/13/tests

**Comment by Stebalien** [comment]
Rebased again on #5708.

**Comment by Stebalien** [comment]
Rebased for an RC.

**Comment by magik6k** [comment]
We don't have Jenkins anymore.

**Comment by magik6k** [comment]
(Don't delete this branch for now though)

**Comment by Kubuxu** [comment]
If it goes missing and you need it, check `go-ipfs-archive`.

**Pull request closed without merging**
