### PR TITLE
Dev0.4.0

### PR DESCRIPTION
**Pull request by whyrusleeping**
This is the development branch for ipfs version 0.4.0

It will contain many changes that are incompatible with previous versions, including repo modifications and protocol changes.

Any change wishing to make it into the 0.4.0 release should PR against this branch.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 762e8791873c6b4132e7ab5cc73598969e65bda7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 153c85c55fc18eef3800976350aec81df367aac7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 46e51ebb3e932966d6bfec2dd0e2c07e447c95b1
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 2499c0254b6065f06fb6dbb5ab48288c7b9c2efe
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 166015cfc1bd7bcd51890103ba75f084d6838174
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: def89ec32d0dc7ba27fdea22a0cecab66baf5cbc
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 47ac37139ec03525b200cb4a3a81493170bf0941
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 32575a1c74c36d118feb44af0bf8271c0397e26e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 927e9852fa7a040d76c13cc3e133ec7cc1db6a32
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 186bfc3153edfa5f82c2ac30a871ff234d984beb
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 553cb6222215fd32d1911c781d08b42bb6e17984
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 43efab5a4cad00619a1e74787af363d3998c745f
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: f9ec03f75db1895533d951d835c421bd32f16d56
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 4bedcf117f344577a2e00656f547f165fea88ebd
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 1923cc044550101ca20c1dc241ba74c37c7da3e4
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: ddd717965751c7f9226e69d102822636515b6206
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 9146894186da819b593a291279fee615d08bb8c9
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 67f2ceeb6ef55ad4c58cf8eb7f743dd54e2332be
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: d672791f1a0097b8a8c800c04cf1594190346819
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by jbenet** [comment]
And to think i doubted you ~~triceracop~~ gitcop :')

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41e570172d8e77213739bc4e8dbb55ce6fc43011
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: eb42e2f0bd9a4fc22ec23d4b4a43863fa0251317
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 12a44574180edf412f65528a72eced0b14bd3cad
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 27dc7c515b598c9b42cf3fc73977d30b116b6588
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 4aee752d963c8f664593a489b5e5df3f42591f45
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 7f6e78acc4cfa28f31fb97dce6bc2ab474fefb43
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 474d041604e603040d6d0594b75504ec5e0ae9a7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 19658648c857ea7fdd72c471a2d66997279ee9db
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: d1f484042240692bc1e6000af0663c8c4aabde9e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 053a7ee3279f37081a25ec35dbe5e53654e388e4
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3e08d5e9076be876afeecf1b3595c90f22176f6e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: aa2b9fe127731f8828075183606810ca722f5043
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3bdf75df82bc3b05427d64286f9af57899d4785b
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: d7ce4c429c6c83e1133a8e98cf3b2e5cf3aad5f0
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 81bdbc45406ec4f2b5f4a3965563ec78dccb506d
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 2b973622849ba91c6bf97e60c3d3f5fe08fd2cba
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 30dbde8a66804a2dfd6e9988f1623e97dcac1bf5
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 03acffb50c3ab0ff798d587ab88ed6ac7846e5b7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 0e5faecb18b190197037ed2a359d9f41a5328691
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41e570172d8e77213739bc4e8dbb55ce6fc43011
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: eb42e2f0bd9a4fc22ec23d4b4a43863fa0251317
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 12a44574180edf412f65528a72eced0b14bd3cad
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 27dc7c515b598c9b42cf3fc73977d30b116b6588
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 4aee752d963c8f664593a489b5e5df3f42591f45
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 7f6e78acc4cfa28f31fb97dce6bc2ab474fefb43
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 474d041604e603040d6d0594b75504ec5e0ae9a7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 19658648c857ea7fdd72c471a2d66997279ee9db
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: d1f484042240692bc1e6000af0663c8c4aabde9e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 053a7ee3279f37081a25ec35dbe5e53654e388e4
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3e08d5e9076be876afeecf1b3595c90f22176f6e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: aa2b9fe127731f8828075183606810ca722f5043
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3bdf75df82bc3b05427d64286f9af57899d4785b
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 42b9e53b5fe5c44b32bba327df791b8355b7fcf9
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 86776db140d214b1edf2d89bf5f54a4679850f1e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 1493ca0ec45252b35ef67d3f19730284e469b0eb
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: e72dbf333fc6d0677168dd766be6afedaaee52ed
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 617714a759960d7bd07de71722efb84793e722df
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41e570172d8e77213739bc4e8dbb55ce6fc43011
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: eb42e2f0bd9a4fc22ec23d4b4a43863fa0251317
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 12a44574180edf412f65528a72eced0b14bd3cad
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 27dc7c515b598c9b42cf3fc73977d30b116b6588
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 4aee752d963c8f664593a489b5e5df3f42591f45
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 7f6e78acc4cfa28f31fb97dce6bc2ab474fefb43
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 474d041604e603040d6d0594b75504ec5e0ae9a7
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 19658648c857ea7fdd72c471a2d66997279ee9db
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: d1f484042240692bc1e6000af0663c8c4aabde9e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 053a7ee3279f37081a25ec35dbe5e53654e388e4
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3e08d5e9076be876afeecf1b3595c90f22176f6e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: aa2b9fe127731f8828075183606810ca722f5043
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 3bdf75df82bc3b05427d64286f9af57899d4785b
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 42b9e53b5fe5c44b32bba327df791b8355b7fcf9
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 86776db140d214b1edf2d89bf5f54a4679850f1e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 1493ca0ec45252b35ef67d3f19730284e469b0eb
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: e72dbf333fc6d0677168dd766be6afedaaee52ed
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 617714a759960d7bd07de71722efb84793e722df
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: c42b501f7e0a2e2289353a3611d49acf3f8a2834
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 956e398768b2e28f2dbd565efe3dbb56d4f1fa15
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef347684bdb626f2234323336d51111e8858333a
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
I have some nodes on the net running dev0.4.0, if anyone wants to try out the new branch, you can use them as bootstrap nodes:
```
/ip4/192.241.194.199/tcp/4001/ipfs/QmY1uAk28LushvGhTc9dvWhzAgeULwPbBjH2dAJgpkSkVA
/ip4/45.55.196.28/tcp/4001/ipfs/QmVStL8ADgdk8H46mfgAgp6uMrzEBzXf7UC4SpbpEHo8cx
```

I'm beginning a 'soak' test. So feel free to jump onto dev0.4.0, but be aware that things will be changing fast and may break.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef347684bdb626f2234323336d51111e8858333a
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef347684bdb626f2234323336d51111e8858333a
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
kinda funny that the github generated merge commits fail GitCops check

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef347684bdb626f2234323336d51111e8858333a
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 82afdb112c85fb03b607a5570dfaf1de8b1e7f09
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 82afdb112c85fb03b607a5570dfaf1de8b1e7f09
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 82afdb112c85fb03b607a5570dfaf1de8b1e7f09
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
@jbenet I think that we should pick a point in the very near future to make all new work be on top of dev040. That last rebase wasnt fun

**Comment by jbenet** [comment]
@whyrusleeping agreed. i want 0.4.0 in as well.

**Comment by whyrusleeping** [comment]
@jbenet how about, after CCC camp, all dev work moves to be on top of dev0.4.0?

**Comment by whyrusleeping** [comment]
current ref 6948d30

**Comment by jbenet** [comment]
@whyrusleeping: merge button says there's conflicts.

**Comment by whyrusleeping** [comment]
yeah, you merged something after i started the rebase.

**Comment by whyrusleeping** [comment]
alright, my remaining requirements for 0.4.0:

- utp
- importer arguments in file root block
- directory sharding
- ensure handshake can be added to without breaking protocol (may already be)

**Comment by jbenet** [comment]
directory sharding would be awesome but may be hard. we should:
- spec it out asap (this week?)
- drop it if it doesnt merge in time

**Comment by jbenet** [comment]
we need to plan out the upgrade path a bit better-- people have been worried about the "handshake breaks problem". in particular:
- need the plan for infrastructure (how long to run the old version) cc @lgierth 
- how to talk to people and have them ready to switch over (flag days / periods suck in general)
- people have asked for a way to connect to the old protocols meanwhile, at least for some time. we could do this, by making dev0.4.0 speak both (but maybe display a warning). 
- (the -Wall thing will be useful)

**Comment by lgierth** [comment]
> need the plan for infrastructure (how long to run the old version) cc @lgierth 

We could do something like this maybe?

1. add generic messaging to ipfs daemon, "you should update regularly, you're running v0.3.10 from 2015-12-09"
  - should be there right as the first line (not as a debug message)
  - we might have to rely on ldflags for the date part, which won't work with go get (but with a makefile build)
2. update half the gateway/bootstrap nodes with the 0.4.0 release
3. update one more gateway/bootstrap node every week or so
  - we can change this interval at any point

Letting both 0.4.0 and 0.3.x serve ipfs.io would be very hairy (https://github.com/ipfs/infrastructure/pull/115#issuecomment-161837892), so it's likely not worth that.
We can have a 0.3.x-backed http://v03x.ipfs.io or so though.

> people have asked for a way to connect to the old protocols meanwhile, at least for some time. we could do this, by making dev0.4.0 speak both (but maybe display a warning). 

I think there should be a very good case for adding this kind of backwards compatibility.
It might seem straightforward but the hidden cost is getting rid of it again.
There'll be plenty of future occasions for introducing this kind of technical debt ;)

We'd also have to deal with 0.4.0 nodes talking to all kinds of 0.3.x nodes,
which might be a source of distracting issues.

Instead, we should make the migration to 0.4.0 as simple as possible.
I'd guess the people asking for backward compatiblity are concerned about downtime during the migration?
A readonly mode would help there (#2051).

> (the -Wall thing will be useful)

this sounds gcc-ish to me, or do you just mean the motd-like wall we talked about?

**Comment by jbenet** [comment]
@lgierth yes, all of what you say makes perfect sense and i agree with it. same views here.

the concerns brought up to me were that if they have a `0.3.x` node out there, suddenly the gateway wont serve their content anymore and now it wont work for them, which sort of breaks the service. this is hard if they have deployed `0.3.x` as part of another application, and it is embedded there, where they have no control over the end-user's updating it. it's certainly tricky. alphaness means we're ok with this, but worth thinking through to see if there's a reasonable way out of this for the future.

**Comment by lgierth** [comment]
> suddenly the gateway wont serve their content anymore and now it wont work for them

Is it about the gateway or about the swarm? When you said handshake backwards compat I assumed swarm.

**Comment by jbenet** [comment]
> Is it about the gateway or about the swarm? When you said handshake backwards compat I assumed swarm.

it is about the swarm, but that transitively means the _global_ https://ipfs.io gateway wont work for them either.

**Comment by whyrusleeping** [comment]
perhaps we should first have a `v040.ipfs.io` to be the dev0.4.0 gateway, and keep that for a while, we can also add a `v03x.ipfs.io` as an alias to the current `ipfs.io`, and urge people to use that if they don't intend to upgrade.

**Comment by whyrusleeping** [comment]
we could also do something like "make requests to both 0.4.0 and 0.3.10 and return whichever returns non error first"

**Comment by jbenet** [comment]
yeah we could try both. it will be annoying to do so forever, so we should sunset that eventually, or continue to use the old handshake as a valid transport protocol in our gateways. (having the handshake itself in the multiaddr would help distinguish this, though we can also detect from the first few bytes received)

**Comment by diasdavid** [comment]
@whyrusleeping found one of the issues why registry-mirror keeps creating so much metadata, it is because each time mfs.Mkdir is called, a flush happens and therefore all the writes in the world occur. Good news, Jeromy knows how to fix it already :) 

(Keeping this documented so we don't loose it :) )

**Comment by diasdavid** [comment]
@whyrusleeping 0.4.0 doesn't know about 0.3.10 ndjson stuff, right?

**Comment by Dignifiedquire** [comment]
:tada:

**Comment by whyrusleeping** [comment]
wooooooo!

**Pull request merged**
