### PR TITLE
docs-randomports: edit docs config add 'randomports' flag.

### PR DESCRIPTION
**Pull request by tarekbadrshalaan**
Issue: https://github.com/ipfs/go-ipfs/issues/5176

- the code is not done yet, but to make sure we will not missing the document.
- I need to ask, what is the process to change the import link is the main implementation, because i found different link for "go-ipfs-config".
https://github.com/ipfs/go-ipfs/blob/d3bba25f05aa5f3ac5c9b3d966654eba488caaf2/cmd/ipfs/init.go#L19-L22

### CODE REVIEW

**Comment by djdv** [comment]
@tarekbadrshalaan
Waiting on a response to https://github.com/ipfs/go-ipfs-config/pull/17#issuecomment-435402490
Can I request a status update?
Is there something still unclear I can help with?

**Comment by djdv** [comment]
@tarekbadrshalaan 
No worries, just making sure. 👋

**Comment by djdv** [comment]
@tarekbadrshalaan 
>I need to ask, what is the process to change the import link is the main implementation, because i found different link for "go-ipfs-config".

I believe you are looking for `gx update go-ipfs-config $HASH`
This will update the version in `package.json`, for the project.
See: https://github.com/whyrusleeping/gx#updating

**Comment by Stebalien** [comment]
Merged locally because I couldn't push a rebase.

**Pull request closed without merging**
