### PR TITLE
Enumerate log level subsystem commands

### PR DESCRIPTION
**Pull request by RichardLitt**
See #2305

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
There are more subsystems and even more sub-subsystems.

**Comment by RichardLitt** [comment]
Cool. What are they? Can you log subsubsystems?

**Comment by Kubuxu** [comment]
I always have to search the code when looking for logger that is handling given system. I have no idea if there is some general solution.

**Comment by RichardLitt** [comment]
So, that's less than ideal, because someone may not know they can search for them. How do you know if something is a subsystem? How does the system know?

**Comment by Kubuxu** [comment]
Here are all logger modules: https://gist.github.com/Kubuxu/ff5c472713a3f058049f

**Comment by RichardLitt** [comment]
Hmm. That is a lot. Maybe we can mention that in the mans? Not all of them, but a way to find them all? Maybe even just that grep command. cc @whyrusleeping

**Comment by whyrusleeping** [comment]
we could have a log subcommand that lists all registered logger subsystems

**Comment by RichardLitt** [comment]
I would like that.

**Comment by dignifiedquire** [comment]
@whyrusleeping I just found this interesting log event: `github.com/ipfs/go-libp2p/p2p/net/swarm/addr` which is probably not meant like this

**Comment by whyrusleeping** [comment]
@RichardLitt what do we want to do here? There are too many subsystems to enumerate in the argument description.

**Comment by RichardLitt** [comment]
@whyrusleeping: "we could have a log subcommand that lists all registered logger subsystems"

We should do this. It should be called `ipfs log ls`. Basically, just build a go-process to create the list Kubuxu pasted above.

**Comment by whyrusleeping** [comment]
@RichardLitt cool, i'll file an issue describing that command, and then close this PR

**Pull request closed without merging**
