### PR TITLE
add NetBSD support

### PR DESCRIPTION
**Pull request by erde74**
with this patch i was able to build ipfs on NetBSD 7 with "gmake nofuse"
License: MIT
Signed-off-by: Stefan Hertenberger <github@hertenberger.bayern>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Hrm, for me on linux, setting `GOOS` to `netbsd` it still fails with:
```
# gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll
../../../gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll/poll_bsd.go:29: cannot use nil as type int64 in field value
```

Does this build for you?

**Comment by erde74** [comment]
you are right, i changed it

`

        func New(fd int) (p *Poller, err error) {
        p = &Poller{}

        p.kqfd, err = syscall.Kqueue()
        if p.kqfd == -1 || err != nil {
                return nil, err
        }

        p.event = syscall.Kevent_t{
                Ident:  uint64(fd),
                Filter: syscall.EVFILT_WRITE,
                Flags:  syscall.EV_ADD | syscall.EV_ENABLE | syscall.EV_ONESHOT,
                Fflags: 0,
                Data:   0,
                Udata:  0,
        }
        return p, nil
}
`

**Comment by whyrusleeping** [comment]
@erde74 mind submitting a PR for that over at https://github.com/jbenet/go-reuseport ?

**Comment by erde74** [comment]
done

**Comment by whyrusleeping** [comment]
sweet. I'll go ahead and merge this for now. We will get the reuseport code pushed up soon after.

**Pull request merged**
