### PR TITLE
All commands: Align to under 78-ruler width

### PR DESCRIPTION
**Pull request by RichardLitt**
This is just for the description, for now.

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
why 78?

**Comment by RichardLitt** [comment]
I expect this to break some tests. Will fix.

**Comment by whyrusleeping** [comment]
@RichardLitt they look happy so far, strangely enough

**Comment by RichardLitt** [comment]
Weird!

**Comment by whyrusleeping** [comment]
:+1: go richard go!

**Pull request merged**
