### PR TITLE
Add testcase for issue reported in #1925

### PR DESCRIPTION
**Pull request by eminence**
Test is currently failing (is not marked as expecting failure)

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@eminence could you rebase this on latest master and verify if its still an issue?

**Comment by eminence** [comment]
@whyrusleeping I believe you fixed this issue (and so this test should now be passing).  We should still add this test, so I will rebase onto the latest master.

**Comment by whyrusleeping** [comment]
:+1:

**Comment by whyrusleeping** [comment]
merged in #2555

**Pull request closed without merging**
