### PR TITLE
take gc-lock when updating pins

### PR DESCRIPTION
**Pull request by Stebalien**
Otherwise, we can GC half-way through.

### CODE REVIEW

**Comment by Stebalien** [comment]
(now that we know that holding the pin lock doesn't actually help...)

**Comment by Stebalien** [comment]
@magik6k should `PinAPI.Update` take this lock internally?

**Comment by michaelavila** [comment]
Related: I think lines like https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/add.go#L194 also need to block GC, right?

**Comment by Stebalien** [comment]
> Related

We actually need to take the lock at a higher layer there. That is, we need to hold the lock between adding the file and pinning.

Apparently, this has already been fixed... https://github.com/ipfs/go-ipfs/pull/5506

**Comment by magik6k** [comment]
> @magik6k should `PinAPI.Update` take this lock internally?

Yup, it should map 1-1 to the command with what it does

**Comment by Stebalien** [comment]
Replaced by #5550.

**Pull request closed without merging**
