### PR TITLE
Make `ipfs add -r` follow symlinks

### PR DESCRIPTION
**Pull request by mildred**
Fix issue described in #616, symlinks are now followed by default.

### CODE REVIEW

**Comment by mappum** [comment]
If we're following symlinks, we might need cycle detection (what if you linked to the parent directory?). Also, might be better to only follow symlinks when a CLI flag is used (`ipfs add -r -l`).

**Comment by whyrusleeping** [comment]
Yeah, agreed with @mappum.

**Comment by mildred** [comment]
Ok, so if we want to default to not follow symlinks, we'll have first to implement symlinks in unixfs.

As for cycle detection, I'm sure this could be a good idea, but I don't think any other program out there does it. You shouldn't have cycles on your filesystem, period. Following symlinks is a natural behaviour, and you generally have to be explicit if you suspect there is a symlink and you don't want to follow it. Go is a kind of exception here with its `os.Readdir` function that does a `lstat()` instead of the more conventional `stat()` function.

So I think adding cycle detection would slow things down a lot and add too much complexity to the code to be worth implementing.

**Comment by whyrusleeping** [comment]
@mildred most unix programs do actually do a sort of 'cycle detection' in counting how many symlinks theyve seen in the current resolution and failing if that number goes over a certain threshold. It costs pretty much nothing as its done in-line during the resolve.

Implementing symlinks in unixfs is feasible, and should just be as simple as storing a path in the dag node.

**Comment by jbenet** [comment]
@mildred thanks for the PR! 

agree on both:
- follow symlinks with a flag (default operation should just add the symlink, like git does) 
- cycle detection (either the symlink count, or could be done with a map of absolute paths)

**Comment by jbenet** [comment]
ping @whyrusleeping

**Comment by whyrusleeping** [comment]
If we can add a sharness test or two around this, that would be awesome. Otherwise, LGTM

**Comment by whyrusleeping** [comment]
closing due to inactivity, please reopen as necessary

note: all pull requests older than three weeks may be closed in an effort to keep our open pull requests more focused.

**Pull request closed without merging**
