### PR TITLE
Fix flatfs on Windows

### PR DESCRIPTION
**Pull request by tv42**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@tv42 not really related to this PR, but have you looked into the performance of doing the directory syncs less frequently?

**Comment by tv42** [comment]
@whyrusleeping Plenty of optimization opportunities all around. I slapped in profiling temporarily and that didn't seem to be the bottleneck for `ipfs add`.

**Comment by whyrusleeping** [comment]
Well thats good news, as long as its not the bottleneck im not worried about optimizing it yet :+1:

**Comment by jbenet** [comment]
LGTM. Thanks @tv42

**Pull request merged**
