### PR TITLE
refactor(gw/dir-index-html): remove gobindata

### PR DESCRIPTION
**Pull request by lidel**
This is code by @ frankywahl   from https://github.com/ipfs/go-ipfs/pull/8834 pushed as upstream branch just to fix Circle CI.

### CODE REVIEW

**Comment by lidel** [comment]
@Jorropo will you have time to fix errors detected on CI?

**Review by Jorropo — APPROVED** [review]
LGTM (altho `go.mod` needs a fix first)

**Comment by Jorropo** [comment]
@lidel I can tomorrow

**Comment by frankywahl** [comment]
> LGTM (altho `go.mod` needs a fix first)

Right - xxxhash is now a dependency - I missed that. Ran `go mod tidy` [here](https://github.com/OpenSourceProjects/go-ipfs/commit/0fb439b0928b02779647bef0fe079b5b6928adae) - I think that is probably the missing dependency.

**Comment by Jorropo** [comment]
@lidel we actually use `github.com/cespare/xxhash` not `github.com/OneOfOne/xxhash` so I've changed it to compile a single implementation and don't make the binary bigger:
```console
$ ipfs version deps | grep xxhash
github.com/cespare/xxhash@v1.1.0
github.com/cespare/xxhash/v2@v2.1.1
```

**Comment by Jorropo** [comment]
I've also took the liberty to meaning fully squash thoses commits as of the atomic principles.

**Pull request merged**
