### PR TITLE
readme: mention building from source on windows

### PR DESCRIPTION
**Pull request by lgierth**
Thanks @drwasho

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b8c579981423e2305c32ce0727c1f463e758a485
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
I'm not sure how i feel linking to a mutable gist...

**Comment by djdv** [comment]
What about this?
https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md

**Comment by chriscool** [comment]
@djdv thanks for pointing to the existing doc!

@drwasho your documentation should suggest to build using:

```
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=XXXXXXX"
```

or:

```
go build -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=XXXXXXX"
```

Thanks!

**Comment by lgierth** [comment]
Thanks @djdv

**Pull request closed without merging**
