### PR TITLE
add test to enforce helptext on commands

### PR DESCRIPTION
**Pull request by whyrusleeping**
This is WIP. Not to be merged for a while.

@RichardLitt here you go :)

License: MIT
Signed-off-by: Jeromy why@ipfs.io

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thank you!

**Comment by noffle** [comment]
pretty excited about this

**Comment by Kubuxu** [comment]
I rebased and updated this PR with change required by #2694

**Comment by Kubuxu** [comment]
Before this is merged those commits should be squashed as the latter will be fixing some tests.

**Comment by chriscool** [comment]
There is a test here: https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0010-basic-commands.sh#L44
I wonder if it is relevant and if it could be improved.

**Comment by RichardLitt** [comment]
@Kubuxu Might be cool if we could automatically generate the Synopsis.

**Comment by Kubuxu** [comment]
If you point me to exact style we are aiming for with all possible options I will look into it.

**Comment by RichardLitt** [comment]
@Kubuxu Something like this? https://github.com/ipfs/go-ipfs/blob/master/core/commands/stat.go#L35

**Comment by Kubuxu** [comment]
Problem is that alg wouldn't know where to take `peerId`, `protocol` and `timeInterval` from. I could either use the name of the option (not so good) or for example give option of some mapping.

**Comment by RichardLitt** [comment]
@Kubuxu If it is super hard, I can just do them all manually -- what do you think?

**Comment by Kubuxu** [comment]
I could introduce something like: `SynopsisMapings` which would be map optionName->optionValueInSynopsis. How does it sound?

**Comment by RichardLitt** [comment]
Can you show me a test? This should be automatic for all of them, or we'll constantly be scrambling around updating it.

**Comment by Kubuxu** [comment]
Like in this case of `ipfs stats bw`:
```go
SynopsisOptionsValues: map[string]string{
  "peer": "peerId",
  "proto": "protocol",
  "interval": "timeInterval",
}
```
And it would be per command basis.
This allows for something like: `ipfs get [(--output | -o) <FILE>]` to be generated automagically.

**Comment by RichardLitt** [comment]
I love it. Would that be hard to implement?

**Comment by Kubuxu** [comment]
I think not at all.

**Comment by Kubuxu** [comment]
@RichardLitt see https://github.com/ipfs/go-ipfs/pull/2785

**Comment by RichardLitt** [comment]
@Kubuxu Would it be possible to output a list of all commands that don't have synopses and general helptexts? Something like project-repos?

**Comment by Kubuxu** [comment]
It is part of the output of the test.
You can see it here: http://ci.ipfs.team:8111/viewLog.html?buildId=6533&buildTypeId=GoIpfs_CiTests&tab=buildLog#_state=656&focus=932

**Comment by Kubuxu** [comment]
Or run locally: `go test ./core/commands -run TestHelptexts`

**Comment by RichardLitt** [comment]
@Kubuxu Any reason why I would only get a one line output from that command? 

```
$ go test ./core/commands -run TestHelptexts
ok  	github.com/ipfs/go-ipfs/core/commands	0.013s
```

**Comment by Kubuxu** [comment]
Are you running in on this branch or the mater?

**Comment by RichardLitt** [comment]
Sweet. Ok, here is the result. I think that all of these should be dealt with before this should be closed. Sound right to you, @Kubuxu? 

- [ ]  ipfs has no long description!
- [ ]  ipfs has no short description!
- [ ]  ipfs block has no synopsis!
- [ ]  ipfs block put has no synopsis!
- [ ]  ipfs block rm has no synopsis!
- [ ]  ipfs block stat has no synopsis!
- [ ]  ipfs block get has no synopsis!
- [ ]  ipfs bootstrap has no synopsis!
- [ ]  ipfs bootstrap rm has no synopsis!
- [ ]  ipfs bootstrap rm all has no synopsis!
- [ ]  ipfs bootstrap list has no synopsis!
- [ ]  ipfs bootstrap add has no synopsis!
- [ ]  ipfs bootstrap add default has no synopsis!
- [ ]  ipfs get has no synopsis!
- [ ]  ipfs ls has no synopsis!
- [ ]  ipfs version has no synopsis!
- [ ]  ipfs resolve has no synopsis!
- [ ]  ipfs log has no synopsis!
- [ ]  ipfs log tail has no synopsis!
- [ ]  ipfs log level has no synopsis!
- [ ]  ipfs log ls has no synopsis!
- [ ]  ipfs pin has no long description!
- [ ]  ipfs pin has no short description!
- [ ]  ipfs pin has no synopsis!
- [ ]  ipfs pin add has no synopsis!
- [ ]  ipfs pin rm has no synopsis!
- [ ]  ipfs pin ls has no synopsis!
- [ ]  ipfs ping has no synopsis!
- [ ]  ipfs refs has no synopsis!
- [ ]  ipfs refs local has no synopsis!
- [ ]  ipfs config has no synopsis!
- [ ]  ipfs config show has no synopsis!
- [ ]  ipfs config edit has no synopsis!
- [ ]  ipfs config replace has no synopsis!
- [ ]  ipfs files has no synopsis!
- [ ]  ipfs files flush has no synopsis!
- [ ]  ipfs files read has no synopsis!
- [ ]  ipfs files mv has no synopsis!
- [ ]  ipfs files cp has no long description!
- [ ]  ipfs files cp has no short description!
- [ ]  ipfs files cp has no synopsis!
- [ ]  ipfs files mkdir has no synopsis!
- [ ]  ipfs files stat has no long description!
- [ ]  ipfs files stat has no short description!
- [ ]  ipfs files stat has no synopsis!
- [ ]  ipfs files write has no synopsis!
- [ ]  ipfs files ls has no synopsis!
- [ ]  ipfs files rm has no synopsis!
- [ ]  ipfs update has no tagline!
- [ ]  ipfs update has no long description!
- [ ]  ipfs update has no short description!
- [ ]  ipfs update has no synopsis!
- [ ]  ipfs diag has no long description!
- [ ]  ipfs diag has no short description!
- [ ]  ipfs diag has no synopsis!
- [ ]  ipfs diag net has no synopsis!
- [ ]  ipfs diag sys has no synopsis!
- [ ]  ipfs diag cmds has no synopsis!
- [ ]  ipfs diag cmds clear has no long description!
- [ ]  ipfs diag cmds clear has no short description!
- [ ]  ipfs diag cmds clear has no synopsis!
- [ ]  ipfs diag cmds set-time has no long description!
- [ ]  ipfs diag cmds set-time has no short description!
- [ ]  ipfs diag cmds set-time has no synopsis!
- [ ]  ipfs mount has no synopsis!
- [ ]  ipfs name has no synopsis!
- [ ]  ipfs name publish has no synopsis!
- [ ]  ipfs name resolve has no synopsis!
- [ ]  ipfs stats has no synopsis!
- [ ]  ipfs stats repo has no synopsis!
- [ ]  ipfs stats bitswap has no long description!
- [ ]  ipfs stats bitswap has no short description!
- [ ]  ipfs stats bitswap has no synopsis!
- [ ]  ipfs stats bw has no synopsis!
- [ ]  ipfs tar has no long description!
- [ ]  ipfs tar has no short description!
- [ ]  ipfs tar has no synopsis!
- [ ]  ipfs tar cat has no synopsis!
- [ ]  ipfs tar add has no synopsis!
- [ ]  ipfs tour has no synopsis!
- [ ]  ipfs tour list has no long description!
- [ ]  ipfs tour list has no short description!
- [ ]  ipfs tour list has no synopsis!
- [ ]  ipfs tour next has no long description!
- [ ]  ipfs tour next has no short description!
- [ ]  ipfs tour next has no synopsis!
- [ ]  ipfs tour restart has no long description!
- [ ]  ipfs tour restart has no short description!
- [ ]  ipfs tour restart has no synopsis!
- [ ]  ipfs dht has no long description!
- [ ]  ipfs dht has no short description!
- [ ]  ipfs dht has no synopsis!
- [ ]  ipfs dht query has no synopsis!
- [ ]  ipfs dht findprovs has no synopsis!
- [ ]  ipfs dht findpeer has no synopsis!
- [ ]  ipfs dht get has no synopsis!
- [ ]  ipfs dht put has no synopsis!
- [ ]  ipfs dht provide has no long description!
- [ ]  ipfs dht provide has no short description!
- [ ]  ipfs dht provide has no synopsis!
- [ ]  ipfs repo has no synopsis!
- [ ]  ipfs repo fsck has no synopsis!
- [ ]  ipfs repo version has no synopsis!
- [ ]  ipfs repo verify has no long description!
- [ ]  ipfs repo verify has no short description!
- [ ]  ipfs repo verify has no synopsis!
- [ ]  ipfs repo gc has no synopsis!
- [ ]  ipfs repo stat has no synopsis!
- [ ]  ipfs swarm has no synopsis!
- [ ]  ipfs swarm addrs has no synopsis!
- [ ]  ipfs swarm addrs local has no synopsis!
- [ ]  ipfs swarm connect has no synopsis!
- [ ]  ipfs swarm disconnect has no synopsis!
- [ ]  ipfs swarm filters has no synopsis!
- [ ]  ipfs swarm filters add has no synopsis!
- [ ]  ipfs swarm filters rm has no synopsis!
- [ ]  ipfs swarm peers has no synopsis!
- [ ]  ipfs cat has no synopsis!
- [ ]  ipfs id has no synopsis!
- [ ]  ipfs bitswap has no long description!
- [ ]  ipfs bitswap has no short description!
- [ ]  ipfs bitswap has no synopsis!
- [ ]  ipfs bitswap wantlist has no synopsis!
- [ ]  ipfs bitswap stat has no long description!
- [ ]  ipfs bitswap stat has no short description!
- [ ]  ipfs bitswap stat has no synopsis!
- [ ]  ipfs bitswap unwant has no long description!
- [ ]  ipfs bitswap unwant has no short description!
- [ ]  ipfs bitswap unwant has no synopsis!
- [ ]  ipfs bitswap ledger has no synopsis!
- [ ]  ipfs add has no synopsis!
- [ ]  ipfs commands has no synopsis!
- [ ]  ipfs dns has no synopsis!
- [ ]  ipfs object has no synopsis!
- [ ]  ipfs object stat has no synopsis!
- [ ]  ipfs object data has no synopsis!
- [ ]  ipfs object diff has no synopsis!
- [ ]  ipfs object get has no synopsis!
- [ ]  ipfs object links has no synopsis!
- [ ]  ipfs object new has no synopsis!
- [ ]  ipfs object patch has no synopsis!
- [ ]  ipfs object patch append-data has no synopsis!
- [ ]  ipfs object patch add-link has no synopsis!
- [ ]  ipfs object patch rm-link has no synopsis!
- [ ]  ipfs object patch set-data has no synopsis!
- [ ]  ipfs object put has no synopsis!
- [ ]  ipfs file has no synopsis!
- [ ]  ipfs file ls has no synopsis!

**Comment by Kubuxu** [comment]
Yes it has to be dealt with before me merge this as tests have to pass.

**Comment by RichardLitt** [comment]
Here I go, then. :)

**Comment by whyrusleeping** [comment]
Although the synopsis part is a bit off, IMO. We autogenerate synopses when they arent set.

**Comment by whyrusleeping** [comment]
@Kubuxu thoughts on rebasing this one, and then marking the test as  'skipped' ? That way we can run it manually as needed, and it doesnt linger in unmerged PR hell forever

**Comment by Kubuxu** [comment]
@whyrusleeping done

**Pull request merged**
