### PR TITLE
Bump version of dir-index-html

### PR DESCRIPTION
**Pull request by rht**
Based on https://github.com/ipfs/go-ipfs/pull/1615

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@rht not that it affects this PR, but I updated gx so that it puts packages directly in `/vendor` instead of `/vendor/src`. It will also symlink packages you `import` to their packagename-version in the vendor directory, so you dont have to hardcode hashes anywhere.

**Comment by rht** [comment]
Now the build process becomes
```shell
ipfs daemon&
gx update $oldhash $newhash
cd assets && go generate && cd -
git rm -r vendor/$oldhash
git add vendor/$newhash
```

**Comment by rht** [comment]
`gx update $oldhash $newhash && git rm -r vendor/$oldhash && git add vendor/$newhash` -> `gx update --git-stage $oldhash $newhash`?

**Comment by whyrusleeping** [comment]
@rht I need better docs for gx, for the update, you can just do: `gx update packagename $newhash`

**Comment by whyrusleeping** [comment]
(also, thanks a ton for trying things out and giving me all this feedback, its great)

**Comment by jbenet** [comment]
LGTM

**Pull request merged**
