### PR TITLE
Switch coverage to codecov from coveralls

### PR DESCRIPTION
**Pull request by Kubuxu**
It works, coveralls stopped suddenly. It has also much nicer UI and more config options.

Still WIP, I will comment when it is ready.

### CODE REVIEW

**Comment by Kubuxu** [comment]
After this build passes on CircleCI it should be ready.

Comments will be disabled once we merge it to master (config file).

**Comment by lgierth** [comment]
> Comments will be disabled once we merge it to master (config file).

Will it use the github PR status then? I think it's important to show a big red flag if coverage decreases with a PR.

**Comment by Kubuxu** [comment]
Yes, once CircleCI goes through the build status for coverage will be shown.

Disabling comments was required by @whyrusleeping

**Comment by Kubuxu** [comment]
The last few patches also might have to be in master. If not, I will work a bit more to get it to work.

@whyrusleeping should be good to merge.

**Pull request merged**
