### PR TITLE
upgrade to go 1.14.2

### PR DESCRIPTION
**Pull request by RubenKelevra**

### CODE REVIEW

**Comment by Stebalien** [comment]
Thanks! We'll do this after the release as I'm not sure I trust it yet :).

**Comment by RubenKelevra** [comment]
I can confirm, all issues I had with crashes or busy loops are gone in my setup. :)

**Comment by RubenKelevra** [comment]
Also, note that the AUR package for ArchLinux does build exclusively with 1.14.2 and there was no complaint over the last 9 days. :)

https://aur.archlinux.org/packages/go-ipfs-git/

**Comment by Stebalien** [comment]
@RubenKelevra could you rebase this?

**Comment by RubenKelevra** [comment]
Sure, will do that tomorrow.

**Comment by RubenKelevra** [comment]
@Stebalien ready for merge

**Pull request merged**
