### PR TITLE
Add multiple performance metrics

### LINKED ISSUE #3607: Testing Metrics
@jbenet and I brainstormed a list of metrics we want integrated into go-ipfs and exported to prometheus for testing.

- [x] Duplicate Blocks Received
- [ ] BW usage
  - [x] up
  - [x] down
- [x] api io throughput - not per end point
- [x] datastore metrics (measure-ds output)
- [ ] dht traffic
- [ ] bitswap traffic
- [ ] total blocks added/received/stored
  - [x] if datastore metrics is enough
-  [ ] pinset sizes (by type)
- [ ] dht bucked fill ratio

@lgierth Since you know the most about these, could you lead getting these put in?

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves #3607

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu build failure

**Comment by Kubuxu** [comment]
@whyrusleeping fixed

**Comment by flyingzumwalt** [comment]
Related to today's standup discussion, this PR doesn't add any tests or documentation. 
* It doesn't make it clear _how_ you would get these metrics out of go-ipfs when you run it
* It doesn't test that the metrics are actually being recorded when you run the code

**Comment by whyrusleeping** [comment]
@flyingzumwalt Thanks, mind filing an issue about needing to add tests for metrics?

Since we don't currently have the setup to test metrics in a meaningful way, adding them here is out of scope for this PR as implementing it would be a non-significant endeavor and would take a good hunk of time from our already tight timeline.

**Comment by Kubuxu** [comment]
Good after it passes.

**Comment by whyrusleeping** [comment]
@Kubuxu OSX sharness failures don't appear to be a fluke.

**Comment by Kubuxu** [comment]
It is same as: https://github.com/ipfs/go-ipfs/issues/3677#issuecomment-279249187

**Comment by whyrusleeping** [comment]
@Kubuxu I'm sorry, can you rebase?

**Comment by Kubuxu** [comment]
Rebased

**Comment by Kubuxu** [comment]
❤️

**Pull request merged**
