### PR TITLE
fixup DHT sharness tests

### PR DESCRIPTION
**Pull request by Stebalien**
(in preparation for libp2p/go-libp2p-kad-dht#165)

### CODE REVIEW

**Comment by magik6k** [comment]
Looks like something is making macs in jenkins really slow, https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/fix%2Ffix-dht-tests/2/pipeline/98/ didn't even fetch gx dependencies before timing out in 10 min. cc @VictorBjelkholm

**Comment by VictorBjelkholm** [comment]
@magik6k yeah, screensavers was somehow enabled again. Seems the last update installed itself and re-activated the screensavers. Deactivated again and now it's running OK.

**Comment by whyrusleeping** [comment]
@Stebalien update here?

**Comment by Stebalien** [comment]
Jenkins keeps throwing a hissy fit.

**Comment by Stebalien** [comment]
@whyrusleeping jenkins is now happy. This could use a review but doesn't really need one.

**Pull request merged**
