### PR TITLE
chore: update welcome bot template

### PR DESCRIPTION
**Pull request by moul**
previous markdown rendering wasn't pleasant to read:

    Your contribution itself is clear (code comments, self-review for the
    rest) and in its best form. Follow the code contribution
    guidelines
    if they apply.

Example: https://github.com/ipfs/go-ipfs/pull/7662#issuecomment-689562417

### CODE REVIEW

**Comment by aschmahmann** [comment]
@hsanjuan is there a way to do this more uniformly across repos?

**Comment by moul** [comment]
if needed, I can make a bash loop :)

**Comment by hsanjuan** [comment]
No nice way other than scripts PR-ing everywhere. But should update the template repo at least.

**Comment by BigLep** [comment]
Closing - welcome bot templates are in process of getting re-written.

**Pull request closed without merging**
