### PR TITLE
ipfs add: added size to response of `ipfs add` command

### PR DESCRIPTION
**Pull request by te0d**
The `ipfs add` command was modified to include the added
node's size as a string. The size is included in the
dagnode info sent over the output channel.

License: MIT
Signed-off-by: Tom O'Donnell todonnel91@gmail.com

### CODE REVIEW

**Comment by te0d** [comment]
Fixes: #4008

**Comment by whyrusleeping** [comment]
@te0d thanks! This looks great. I'd like to have a test for this. @Kubuxu can you think of a simple way to test this? `ipfs add --enc=json` doesnt give the output we want here (note: this seems kinda broken).

**Comment by Kubuxu** [comment]
`curl -F file=@filename  "http://localhost:5001/api/v0/add"` should work and returns JSON

**Comment by te0d** [comment]
Would <https://gist.github.com/te0d/fcdfc0d1578fc3bcb7d1fed36c2a260b> meet testing needs? Is the test in the appropriate location (../test/sharness/t0410-api-add.sh)?

**Comment by whyrusleeping** [comment]
@te0d I'd at least like to make sure we verify the value thats returned is correct, but yeah, thats pretty much what i'm hoping for

**Comment by diasdavid** [comment]
wooooot! 🚀

**Pull request merged**
