### PR TITLE
chore(gw):  extract logical functions to improve readability

### PR DESCRIPTION
**Pull request by justincjohnson**
@lidel if you approve, this is an initial PR with some cleanup before implementing any [redirects support](https://github.com/ipfs/go-ipfs/pull/8816).

### CODE REVIEW

**Review by Mitumaru — APPROVED** [review]

**Comment by lidel** [comment]
@justincjohnson permissions at `fission-suite` org make it very difficult to review your PRs:
- CircleCI does not run because  of your org permissions
- I am not able to push small cleanups 

To work around this, I am closign this PR and re-opening as upstream branch in https://github.com/ipfs/go-ipfs/pull/8883 – lets continue there.

To sure how to avoid these problems In the future.
Would it be possible for you to open PRs from your personal account?
It should fix both CI and review papercuts.

**Comment by justincjohnson** [comment]
No problem @lidel.  Sorry for the bumps that have made this review process more painful.

**Comment by justincjohnson** [comment]
@lidel Fission prefers that we work on branches in our org.  By any chance are the CircleCI permission issues documented somewhere and something we could just fix on our end, or are there other problems caused by us working in our own org?  Thanks.

**Comment by lidel** [comment]
@justincjohnson not aware of any docs, this seems to be uncharted teritory. You could see if https://app.circleci.com/ allows you to enable CircleCI on your go-ipfs fork repo. Perhaps that will solve the problem?

**Pull request closed without merging**
