### PR TITLE
update message.proto

### PR DESCRIPTION
**Pull request by diasdavid**
Add some comments so that I don't forget about these

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@diasdavid fix your commit msg pls

**Comment by diasdavid** [comment]
@whyrusleeping there:
image

**Comment by Kubuxu** [comment]
gitcop doesn't like you as it want's email in triangular brackets.

**Comment by diasdavid** [comment]
thank you @Kubuxu, I was missing that

**Pull request merged**
