### PR TITLE
Support for listing only cached links in refs command

### PR DESCRIPTION
**Pull request by sivachandran**
Added "--cached" option to "refs" command that lists only cached links. Also added "<linksize>" token in format to print the size of the link.

By listing only cached refs and their sizes we can easily find the cache/download progress of an object.

License: MIT
Signed-off-by: Sivachandran <sivachandran.p@gmail.com>

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99eb21625b6ac4714c1d5c249b48724aac7d7036
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99eb21625b6ac4714c1d5c249b48724aac7d7036
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

 * Commit: 8f9db3017f20e98c0e61353aa8571565399e9156
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99eb21625b6ac4714c1d5c249b48724aac7d7036
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

 * Commit: 8f9db3017f20e98c0e61353aa8571565399e9156
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99eb21625b6ac4714c1d5c249b48724aac7d7036
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

 * Commit: 8f9db3017f20e98c0e61353aa8571565399e9156
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by RichardLitt** [comment]
Wow, that is atrocious. @sivachandran, I am so sorry. 

@chriscool what happened here?

**Comment by sivachandran** [comment]
@RichardLitt Those are my attempts to make GitCop happy but I couldn't. Finally I closed the PR and created a new one https://github.com/ipfs/go-ipfs/pull/2446.

**Comment by chriscool** [comment]
It looks like there should be a blank line before the "License:..." and "Signed-off-by: ..." lines.
I will see if I can improve error messages...

**Pull request closed without merging**
