### PR TITLE
Fix indent in sharness tests

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/ipfs/go-ipfs/issues/4002, using tabs as it's easiest to check/change to something else.

No more stuff like this

### CODE REVIEW

**Comment by kevina** [comment]
This was never really discussed.  Can we hold off on merging it?  See my comments on #4002.

**Comment by magik6k** [comment]
Using 2 space indent now, should be redy to review.

**Comment by magik6k** [comment]
fixed

**Comment by chriscool** [comment]
Sorry to be late about this but see also my comment on #4002 about Sharness, Git and other projects.

**Pull request merged**
