### PR TITLE
make: fix `make install` not using ldflags for git hash

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves https://github.com/ipfs/go-ipfs/issues/3837

License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu could we perhaps have a test for this?

**Comment by Kubuxu** [comment]
Not sure how to test it, it uses buildsystem and at the same time it installs into GOPATH, it would be hard.

**Comment by whyrusleeping** [comment]
A sharness test should be able to just check `ipfs version --commit` no?

**Comment by Kubuxu** [comment]
This affects `make install` not `make build`. We test for commit in docker tests, not sure if they run.

I will add test for commit, but it will find regression with `build` not `install` and I can already tell that it won't pass with coverage collection (as coverage doesn't insert this variable either).

**Comment by whyrusleeping** [comment]
@Kubuxu how about we default the variable to something that indicates its not an 'official' build?

**Comment by Kubuxu** [comment]
So do we want to confront Semver?

Then I suggest:
Official `0.4.8-rc1`
Unofficial if not git var available `0.4.8-rc1+sometag` IDK what to place there there.
With git: `0.4.8-rc1+git.a8b56d3ad`

**Comment by whyrusleeping** [comment]
those SGTM. The 'sometag' is generally 'dirty'

**Comment by Kubuxu** [comment]
We can also add `+dirty` if there is git hash but there are local (not committed changes)

**Comment by whyrusleeping** [comment]
@Kubuxu is this ready to go?

**Comment by Kubuxu** [comment]
If tests are to be separate, yes.

**Pull request merged**
