### PR TITLE
handle sym links in when calculating repo size

### PR DESCRIPTION
**Pull request by leerspace**
repo/fsrepo: follow symbolic links when calculating RepoSize

Now if the IPFS path is a symbolic it will be followed before
calculating the repo size.

License: MIT
Signed-off-by: John Reed <john@re2d.xyz>

### CODE REVIEW

**Comment by leerspace** [comment]
Fixes #4056

**Comment by leerspace** [comment]
I'm confused by the GitCop failures since the commit already has the license and signed-off-by trailers.

**Comment by whyrusleeping** [comment]
@leerspace sometimes it gets upset because it doesnt perfectly match its regex. If you have the right content, then just ignore it.

**Comment by Kubuxu** [comment]
If it isn't too much to ask for, a sharness test for it would be great.

**Comment by leerspace** [comment]
I started working on the sharness test, but now I'm trying to figure out why every time I run `ipfs repo stat` the RepoSize gets larger by about ~1kB. This is even with no daemon running.

**Comment by Kubuxu** [comment]
@leerspace this is the behaviour of those DBs, every time they are opened they create new logfile and if there are X of them (or other condition) they compact. I would suggest adding few hundreds of KiB to ipfs in sharness and checking if size is larger than X.

**Comment by Kubuxu** [comment]
Also according to `go fmt` this code is not formatted correctly.

**Comment by whyrusleeping** [comment]
@leerspace starting from a fresh repo (as in a test) should yield the same size every run (we have tests that test this). I would just pick a number, run the test, see what it actually was in the test failure output and then adjust the value in your test assertion.

**Comment by whyrusleeping** [comment]
Though I definitely agree that running `ipfs repo stat` with no daemon running should not affect the size of the repo.

**Comment by leerspace** [comment]
I just committed the gofmt fix and a sharness test for this.

**Comment by whyrusleeping** [comment]
@leerspace looks like you might not have set the executable bit on that test file. the test runners arent very happy trying to run it

**Comment by leerspace** [comment]
@whyrusleeping sorry about that. I think it should be fixed now. I did this on Windows, but fortunately there's [a way to set this on Windows](https://stackoverflow.com/a/21694391/1388019).

**Pull request merged**
