### PR TITLE
adder: add support for specifying the hash function

### LINKED ISSUE #3917: Add flag to ipfs add to select hash function to use
I see this as step 1 towards enabling blake2b support. This flag could even default to blake2b-256

### PR DESCRIPTION
**Pull request by kevina**
Closes #3917 

License: MIT
Signed-off-by: Kevin Atkinson <k@kevina.org>

### CODE REVIEW

**Comment by kevina** [comment]
@whyrusleeping this p.r. will unconfitially set the Cid version to 1 if the `--hash` option is used, even if the value is `sha2-256`.

**Comment by whyrusleeping** [comment]
Great! I would just like to see a test that adds some directory stuff recursively too

**Comment by kevina** [comment]
I'm working on it.  Raw leaves are a bit of a problem.  They need proper support for specifying a hash function.

**Comment by kevina** [comment]
@whyrusleeping okay this should be good to go, the first commit  "Rename NewBlock to NewBlockV0" is not necessary, I did it as a debugging aid and it might be useful to keep.  If not it can be cleanly dropped.

**Comment by whyrusleeping** [comment]
Then theres a code climate issue, documenting the NewNodeWithPrefix would be very helpful

**Comment by kevina** [comment]
@whyrusleeping both issues should be addressed now

**Pull request merged**
