### PR TITLE
change Dockerfile order to create VOLUME under user ipfs

### PR DESCRIPTION
**Pull request by ChristianKniep**
License: MIT
Signed-off-by: Christian Kniep <christian@qnib.org>

Changed the commit message...

### CODE REVIEW

**Comment by whyrusleeping** [comment]
this seems correct to me, @jbenet @Luzifer ?

**Comment by Luzifer** [comment]
Hadn't time to test yet but either it makes things better or it doesn't change things. So no negative results expected. LGTM

**Comment by jbenet** [comment]
would be good to have a sharness test that tests the Dockerfile
>
>

**Comment by whyrusleeping** [comment]
test it by running a docker image with the file?

**Comment by jbenet** [comment]
yep!

**Comment by whyrusleeping** [comment]
are we saying that a test on the dockerfile is a hard requirement for this PR?

**Comment by jbenet** [comment]
Well We should confirm it works, and that it be broken again. If not now, when?



—

**Comment by whyrusleeping** [comment]
just clarifying so we know what tasks need to be done before this PR can merge.

**Comment by jbenet** [comment]
@ChristianKniep are you familiar with our sharness testing and would you have time to do this? 

else, is anyone else able to?

**Comment by lgierth** [comment]
continued in #2064

**Pull request closed without merging**
