### PR TITLE
bump go requirement to 1.7

### PR DESCRIPTION
**Pull request by whyrusleeping**
CI is gonna be fun with this one...

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@diasdavid the js-ipfs-api test failures look like an issue on your end. Could you confirm and let me know when there is a fix?

**Comment by whyrusleeping** [comment]
the docker thing needs fixing too, fun.

**Comment by diasdavid** [comment]
@whyrusleeping the error is:

```
[19:55:21][Step 3/3]   1) .config callback API .get retrieve a value through a key:
[19:55:21][Step 3/3]      Uncaught AssertionError: expected [Error: cannot show or change private key through API] to not exist
[19:55:21][Step 3/3]       at node_modules/interface-ipfs-core/lib/config.js:39:31
[19:55:21][Step 3/3]       at send (src/api/config.js:28:18)
[19:55:21][Step 3/3]       at Wreck.read (src/request-api.js:46:9)
[19:55:21][Step 3/3]       at finish (node_modules/wreck/lib/index.js:360:16)
[19:55:21][Step 3/3]       at wrapped (node_modules/hoek/lib/index.js:871:20)
[19:55:21][Step 3/3]       at onReaderFinish (node_modules/wreck/lib/index.js:406:16)
[19:55:21][Step 3/3]       at finishMaybe (_stream_writable.js:488:14)
[19:55:21][Step 3/3]       at endWritable (_stream_writable.js:498:3)
[19:55:21][Step 3/3]       at Writable.end (_stream_writable.js:463:5)
[19:55:21][Step 3/3]       at IncomingMessage.onend (_stream_readable.js:512:10)
[19:55:21][Step 3/3]       at endReadableNT (_stream_readable.js:975:12)
[19:55:21][Step 3/3]       at _combinedTickCallback (internal/process/next_tick.js:74:11)
[19:55:21][Step 3/3]       at process._tickCallback (internal/process/next_tick.js:98:9)
```

Because the key we selected to `get` on tests was Identity, see:

```
https://github.com/ipfs/interface-ipfs-core/blob/master/src/config.js#L37-L43
```

I can update the tests to use some other key, is this decision final with regards to not being able to access Identity from the API? How does the go CLI do it then? Some special whitelisting for go-ipfs cli?

**Comment by whyrusleeping** [comment]
@diasdavid yeah, you can't access anything containing the private key via the api in any way (including the CLI). You could use identity.peerID if you wanted

**Pull request merged**
