### PR TITLE
Added env var info to init, dameon help

### PR DESCRIPTION
**Pull request by RichardLitt**
See #1296

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by lgierth** [comment]
This one is used by all commands though, not just init

**Comment by RichardLitt** [comment]
Agreed. Still, it should be in more than just main, maybe? 

@jbenet:
> This is documented in ipfs main help now. Should likely also be documented
in ipfs daemon and ipfs init.

**Comment by lgierth** [comment]
Oh got it :+1:

**Comment by jbenet** [comment]
LGTM.

**Pull request merged**
