### PR TITLE
Gateway composite file add

### LINKED ISSUE #1819: gateway: file upload functionality?
Would it make sense to enable adding a file to node via HTTP POST/PUT request to gateway? This would enable IPFS to be used in lots of web applications that just need GET/PUT functionality. This option should not probably be default and could be enabled via a command line switch (similarly how unrestricted-api is enabled).

### PR DESCRIPTION
**Pull request by rht**
- [x] Depends on https://github.com/ipfs/go-ipfs/pull/1778 to be merged
- [ ] tests (curl can only upload multiple files with PUT, but not structured files with dir)
- [x] pin parameter
- [x] obsoletes #1543
- [ ] fixes #1819

### CODE REVIEW

**Comment by whyrusleeping** [comment]
hmm... two panics in the failed test, neither appear to be related to this PR. but the second one seems like an actual problem.

**Comment by rht** [comment]
@cryptix this should have been in `putHandler`?

**Comment by rht** [comment]
@whyrusleeping panic test (the stalled build one) once again.

**Comment by cryptix** [comment]
The original put handler took json similar too "ipfs object put"

**Comment by prusnak** [comment]
What is the state of this?

**Comment by rht** [comment]
this needs test

**Comment by prusnak** [comment]
What do you mean by test? Should I grab your branch and test if it works? Or should we rebase on top of ipfs:dev0.4.0 and test this?

**Comment by rht** [comment]
Test as in sharness test to make sure the POST multipart work. Currently making it.

The current master is already 0.4.0.

**Comment by prusnak** [comment]
Cool! Let me know if I can help somehow. Would love to see this feature
merged in soon.

--
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>
 
 
On Fri, Jan 15, 2016, at 03:17 PM, rht wrote:
> Test as in sharness test to make sure the POST multipart work. Currently making it.


> The current master is already 0.4.0.


> 


> —
> Reply to this email directly or view it on GitHub[1]. 
> 


>  
 


Links:

  1. https://github.com/ipfs/go-ipfs/pull/1845#issuecomment-171971734

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c242660da50fca838f9fa937822a2c337e637f3f
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: 38a600b3c83d72ca5cebef07890b197a3d9b3a06
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by rht** [comment]
@prusnak figuring out how to use curl POST that is also specified in rfc1867 and updating the api documentation in https://github.com/ipfs/js-ipfs-api/blob/master/README.md (this has the multipart/form-data example, but only for a single file).

I have fixed the merge conflicts in #2205.

**Comment by rht** [comment]
I'm using this for multiple files POST: https://github.com/ipfs/go-ipfs/pull/2205/files#diff-cbe32203deec9b995950e3110e5db668R69. But there should be a tool that auto-convert file arguments / directory into a multipart form for curl?

**Comment by prusnak** [comment]
Does master already support single file upload using `curl -X POST --data-binary @infile "$URL"`?

**Comment by rht** [comment]
Yes it does, it is used in one of the test https://github.com/ipfs/go-ipfs/blob/c1847e9f693e716a54e0223e44729c76ef64308b/test/sharness/t0111-gateway-writeable.sh#L30

**Comment by prusnak** [comment]
Great, I just tested it at it works. Wohooo!

**Pull request closed without merging**
