### PR TITLE
Refactor iptb tests

### PR DESCRIPTION
**Pull request by chriscool**
This removes some code duplication in tests using iptb.

### CODE REVIEW

**Comment by chriscool** [comment]
The errors are both:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by chriscool** [comment]
There is this strange but unrelated failure on OSX:

```
expecting success: 

		test_kill_repeat_10_sec $IPFS_PID

ok 71 - 'ipfs daemon' can be killed

expecting success: 

    	echo "Hello Worlds!" >mountdir/hello.txt &&
        ipfs add mountdir/hello.txt >actual

Error: api not running

not ok 72 - ipfs add succeeds
```

**Comment by rht** [comment]
LGTM

**Comment by whyrusleeping** [comment]
LGTM

**Pull request merged**
