### PR TITLE
Add a --no-pin option to 'ipfs add'

### PR DESCRIPTION
**Pull request by eminence**
My first PR in go, so please review carefully.  Minor nits and style concerns welcome

See #1908 for details on the use-case this tries to solve

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bbc2b1f7bfea1fffd1be5febcb21d8affc2c3503
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by lgierth** [comment]
Maybe this should be `--pin` and default to `true`

**Comment by eminence** [comment]
Soon this PR will be closed, and re-opened against the `dev0.4.0` branch once #1778 is merged.

**Comment by lgierth** [comment]
No need to open a new PR, you can `git push -f` to the same branch and it'll update

**Comment by whyrusleeping** [comment]
@lgierth github doesnt let you change what branch your PR is based off of, this PR needs to be made on dev0.4.0 after the other PR gets merged into it.

**Comment by lgierth** [comment]
Oh I see. I was thinking they wanted to wait until dev0.4.0 is merged into master.

**Comment by eminence** [comment]
Please see #1931 instead

**Pull request closed without merging**
