### PR TITLE
Fix config option

### PR DESCRIPTION
**Pull request by chriscool**
The first patch in this PR makes "ipfs -c=dir/.go-ipfs init" work.
The second patch adds some tests to catch any regression.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@chriscool is this PR still something that could be merged? or should we just close it?

**Comment by whyrusleeping** [comment]
closing due to inactivity, if needed, reopen

**Comment by chriscool** [comment]
Yeah, sorry for not responding. I think it was too old and could not be merged anymore.

**Comment by whyrusleeping** [comment]
no worries, just working on cleaning up our stale PRs.

**Pull request closed without merging**
