### PR TITLE
gx: update go-libp2p-peer

### PR DESCRIPTION
**Pull request by Stebalien**
Switch _back_ to the 0.4.18 style of peer IDs while we figure things out. See https://github.com/libp2p/specs/issues/138.

### CODE REVIEW

**Comment by Stebalien** [comment]
This *also* pulls the new provider query subsystem for bitswap.

**Comment by Stebalien** [comment]
And the DHT query queue fixes, and probably a bunch of others.

**Comment by Kubuxu** [comment]
Wait, how is Circle passing and everything else failing?

**Comment by Kubuxu** [comment]
Circle has separate status for gotest.

**Pull request merged**
