### PR TITLE
add option to only hash input

### PR DESCRIPTION
**Pull request by whyrusleeping**
I'm not married to the placement of this command, but it works, and does what we expect it to! (its also realllly fast)

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
Clever way to do it :)

Sharness tests! With both deamon and without (see the bootstrap config tests)

**Comment by whyrusleeping** [comment]
@jbenet added sharness tests

**Comment by jbenet** [comment]
@whyrusleeping what about naming it `--dry-run` ?

**Comment by jbenet** [comment]
@whyrusleeping had suggested `--dry` and @cryptix said:

> \<cryptix> whyrusleeping: oh okay. i'd be more in favor of 'ipfs checksum <file>' though. add is already quite complex and --dry from other tools implies to me that it could change/break something without it
> https://botbot.me/freenode/ipfs/2015-06-22/?msg=42593522&page=4

I'm fine with either. i'll merge this for now.

**Comment by jbenet** [comment]
@whyrusleeping maybe we should test that objects returned by `--only-hash` are not retrievable. basically:

```sh
hash=$(ipfs add -q file | tail -n1) 
test_must_fail ipfs cat $hash
```

**Comment by whyrusleeping** [comment]
i could have sworn i wrote that test... but it appears that i didnt. I'll do that!

**Pull request merged**
