### PR TITLE
Add support for hidden files and .ipfsignore file

### PR DESCRIPTION
**Pull request by gatesvp**
Should resolve issue #653.

Should incorporate all of the feedback from the previous PR that was closed.

Manually tested / built on Linux and Windows with a set of folders of my own design.

### CODE REVIEW

**Comment by jbenet** [comment]
@gatesvp thanks! btw-- you can just `git push -f <remote> <branch>` to overwrite the old branch-- that way dont need to open a second PR.

**Comment by gatesvp** [comment]
Thank you, that makes sense. 

Still a git newbie, so I'm always a little hesitant to do anything that involves a `-f` :)

**Comment by jbenet** [comment]
Testing all the commits

**Comment by jbenet** [comment]
Tests don't pass before the last commit -- i'm just going to squash everything.

**Comment by jbenet** [comment]
Squashed over at https://github.com/ipfs/go-ipfs/commit/gatesvp-squashed

**Comment by jbenet** [comment]
Ok, @gatesvp this is looking good. 

This doesn't have any tests though. I can't merge this without tests because this is a very important change of functionality. It will likely break right away without tests. We need at least some sharness tests for it so that we both (a) make sure it does what we expect it to, and (b) catches any problems.

It may be worth taking a look at git's `.gitignore` tests: https://github.com/git/git/blob/master/t/t0008-ignores.sh

**Comment by jbenet** [comment]
maybe can see if others who want this can help write tests.

**Comment by gatesvp** [comment]
So I actually support your desire for tests 100%. Honestly would have been easier to write with test file to work off of :) I basically built this convoluted folder of hidden files and `.ipfsignore` files and kept building and running against that.

However, it doesn't look like the CLI commands have any `_test.go` files, so I'm not really clear where to start on this.. of course, as I type this, I realize that's probably what the `sharness` is for.

I'll fire up my Linux Box and try building some extra tests in `sharness` based on my crazy folder.

**Comment by gatesvp** [comment]
Update on this item. I have some basic tests working on my local dev box.

However, I am trapped on one set of tests. I am trying to test that `.ipfsignore` files from parent directories are respected. This works on my personal tests but fails in the `sharness` temp folder.

On Ubuntu it looks like the test creates this `\trash ` folder with a space in the name.

My code tries to walk the parent folders by splitting out the components and then gluing them back together one at a time with `path.join()`. However, this whole process fails inside of this weird `\trash` folder. Effectively doing a `split` then a `join` results in a bad directory :(
https://github.com/gatesvp/go-ipfs/blob/iss653/core/commands/add.go#L389

I will keep tinkering with it, but if we have a known workaround here, it would be appreciated.

**Comment by whyrusleeping** [comment]
@gatesvp i dont know how sold i am on respecting ipfsignores from parent directories in the first place... @jbenet thoughts?

**Comment by whyrusleeping** [comment]
So, a little bit more thought on this:

I think we should respect 1) the global `.ipfsignore`, 2) the one in our current working directory, and 3) any we encounter going downwards recursively (if its a recursive add).

An example of 3:

```
top/
  a/
    .ipfsignore // says to ignore '*.blah'
    testfile.txt
    testfile.blah
  b/
    testfile.txt
    testfile.blah
```

The `testfile.blah` under `b/` would be added while the one under `a/` would be skipped.

let me know what you think, and also lets gets @jbenet's input.

**Comment by jbenet** [comment]
> My code tries to walk the parent folders by splitting out the components and then gluing them back together one at a time with path.join(). However, this whole process fails inside of this weird \trash folder. Effectively doing a split then a join results in a bad directory :(
> https://github.com/gatesvp/go-ipfs/blob/iss653/core/commands/add.go#L389

sounds like it's not dealing with spaces correctly. to catch errors like this is _precisely_ why the trash folders have a space. (thanks git and @chriscool)

>  i dont know how sold i am on respecting ipfsignores from parent directories in the first place... @jbenet thoughts?

i think the way @gatesvp has it -- which is 1-3 + parent dirs -- is the right way. the way git does it, too.

"doing parent dirs" should go along with "doing child dirs". it's a symmetric relationship. otherwise tool will behave differently depending on what dir in hierarchy you run it. 


to give an example,
```
ipfs add -r foo
cd foo && ipfs add -r .
cd foo/bar && ipfs add -r ../foo
cd foo/bar/baz && ipfs add -r ../../foo
```
should all ignore the same files, not be dependent on where you started the call.. that'd be super confusing.

**Comment by whyrusleeping** [comment]
Oh, i agree with that. I thought that (using your example) it would look at 'foo's parent for an ipfsignore file.

**Comment by gatesvp** [comment]
So to clarify, what I have right now is actually recursive _"to the root"_. There's no check of current working directory (CWD)

So with respect to @whyrusleeping 's notation, I have 1 & 3, but not really 2 (CWD).

If you have `/root/foo/bar/baz` and you run `ipfs add -r /root/foo/bar` or `ipfs add -r /root/foo` my code is actually looking for the following files:

 1. `/root/.ipfsignore`
 2. `/root/foo/.ipfsignore` => for everything under `foo`
 3. `/root/foo/bar/.ipfsignore` => for everything in & under `bar`
 4. `/root/foo/bar/baz/.ipfsignore` => for everything in & under `baz`

It doesn't sound like _"to the root"_ is really desired behaviour... but it feels like all of the options are kind of awkward.

 - "Current Working Directory" would break @jbenet 5 line example (_hence not implemented_)
 - Travelling _"to the root"_ means that `ipfs add -r /root/code/project` and `ipfs add -r /root/code/project/subtask` both ignore the sames files. But it may also result in unexpected changes if someone modifies `/root/.ipfsignore`
 - Key difference here is that `git` has a known "root" which is the top-most directory under source control. `ipfs` does not have such a "root" hence this difference.

**Comment by whyrusleeping** [comment]
yeah, kill my current working directory idea, that was bad. i'm quite skeptical about traveling to the root... youre right about unexpected behaviour if `/root/.ipfsignore` gets modified

**Comment by jbenet** [comment]
@gatesvp would love to have this in, any update on tests here?

**Comment by gatesvp** [comment]
Yes, I am still alive and think I have it figured out :)

Testing it on my windows box right now, will test some more tonight. And
give an update.

On Tue, Jun 30, 2015 at 11:20 AM, Juan Batiz-Benet <notifications@github.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ddaa9a67353312a01c585a3067d718b2187e203f
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 9517911f1b5c28621329302fad265d4eac84f97c
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 88077f778e36908adfd9bbf5f40b4f5cf47616d6
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 50e3b151813bcc254b897993338eeaebdf67999d
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 99f15e6d17ab254f1c8d5512e232e76b4c1a2b6a
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: efae6b1fc70f41ae04115d7d6770192a504b3425
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

 * Commit: 3923aa8f389c3e6f14abb1ed67abbd329f879b69
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 1e66056f81748296f8f77599f61580deb1a13556
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 66a5f1f1f87a25b7036a35d9e758914213f415f1
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**
  * Your subject line is longer than 80 characters

 * Commit: f04ac6f274950a9a86a9957fd899a7f06a50aea6
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 7f818e223b8a2077b51167eb936e87f82ef1745c
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 032cd3cf9b31d997b1752600c3f0b604638640f2
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 70dc7d977e011511d983ce42a2e417ecdac8031b
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 8e9a4778ceb1aca19dd43d556eba32d3628d1ba8
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: bd7c8f5b81edae2be0a697695006d5cbfe72e705
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 9e5dfe2fc99c3c256b21887eb74fbc7a9b687055
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 1914a2690fb656b94d8d52cb378cc66d07a1e7aa
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 153886ea4244daae578ae24fc8e6b856aec8e040
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 500e75669e780a3f1b7ed3e4d80437e9f280ceb5
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 5cb34ee55c668f6842eaaceb38504d60cdaa6baa
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 441740a3b15d5ef0e626368fa2bba4f44a86ee0e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: e8d8642f8503234ee6d4d5a9145fc57ac7642c4e
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: ff0d236980e7d7cbb8cb3b4f2779ba439be17ff5
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 954c0db503537dc56f67d1d0f256a7b65a8ec630
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 53fc454db37308043306833123870114f5255610
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 372862bbd13986d2beca5ff9b4a064f25d770bdf
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 314bb95b6ff1024e3e8a34646653d4fc896f7a73
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: b86d5d463e4a631722307b23807d1c84aaf1ed33
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by gatesvp** [comment]
So that last changeset adds the required tests and also fixes an issue I found while building out the tests. Namely that `filepath.Join` was ignoring "blank" strings in a key location.

As it stands, that last check-in is a little wild because I am pulling in two months of work and trying to rebase over top.

@jbenet this may need some manual intervention. The only key files changed in that last set were `t0040-...` and `core/commands/add.go`. Their end state is correct

**Pull request closed without merging**
