### PR TITLE
namesys: fix case where there is no cache

### PR DESCRIPTION
**Pull request by Kubuxu**
License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu Tests? i'm not sure what scenario this actually resolves

**Comment by Kubuxu** [comment]
See https://github.com/ipfs/go-ipfs/blob/master/namesys/routing.go#L98

**Comment by whyrusleeping** [comment]
For some weird alignment of the stars type reason all the osx tests seem to have failed... for different reasons. Rerunning them to try for better

**Comment by Kubuxu** [comment]
OSX passed on Travis

**Pull request merged**
