### PR TITLE
add utp listeners to default config

### PR DESCRIPTION
**Pull request by whyrusleeping**
Been meaning to do this for a while, hopefully now it will make it into the official 0.4.0 release :D

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by yangwao** [comment]
yes! :D

**Comment by lgierth** [comment]
Gonna make it 4001 instead of 4002? Not sure -- we'll have other transports too, and we've been preaching 4002 for a while already.

**Comment by Kubuxu** [comment]
Most routers will give user default option of forwarding both TCP and UDP of same port number at the same time.

**Comment by lgierth** [comment]
> Most routers will give user default option of forwarding both TCP and UDP of same port number at the same time.

OpenWrt doesn't. What I meant to say was, if we change from 4002 to 4001, a few more todos arise.

**Comment by Kubuxu** [comment]
This is only default, it won't change already generated configs.

**Comment by whyrusleeping** [comment]
@lgierth what is the issue with using 4001?

**Comment by lgierth** [comment]
> @lgierth what is the issue with using 4001?

Nothing really, I'm just wondering why and if I should update the bootstrappers, docker image, v03x/v04x blog post, etc. to match :)

**Comment by whyrusleeping** [comment]
holding off on this until some issues with utp are fixed (primarily memory consumption)

**Comment by whyrusleeping** [comment]
closing for now, will reopen later

**Pull request closed without merging**
