### PR TITLE
commands diagnostics

### PR DESCRIPTION
**Pull request by whyrusleeping**
This lets us see running commands and some basic info about them.

The next PR on this front will allow us to cancel requests by killing their contexts.

### CODE REVIEW

**Comment by lgierth** [comment]
LGTM! :+1: 

Two nice-to-haves:

- also log api calls through `:8080/api` - on first look at `core/corehttp/commands.go` it should just work, no idea why it doesn
- ordering the options column
  - i got e.g. `[v=true,encoding=json,stream-channels=true,]` and `[encoding=json,stream-channels=true,v=true,]` for the same calls

**Comment by whyrusleeping** [comment]
@lgierth hrm... calls through `:8080/api` have a different commands context, which is why they don't show up. we would need to add this command to the readonly api for us to see those requests (which might not be a bad idea)

**Comment by lgierth** [comment]
Oh I understand -- it would be useful because we're exposing https://ipfs.io/io for public use, and I could even imagine legitimate use cases for `echo /dns/ipfs.io/ip4/tcp/80 > $IPFS_PATH/api`

**Comment by lgierth** [comment]
That links should have been https://ipfs.io/api of course

**Comment by lgierth** [comment]
> I could even imagine legitimate use cases for `echo /dns/ipfs.io/ip4/tcp/80 > $IPFS_PATH/api`

In fact I just came up with one: in order for gx in a container to use an ipfs daemon running on the host, I'm doing `echo /ip4/172.17.0.1/tcp/8080 > $IPFS_PATH/api` in the container.

:')

**Comment by whyrusleeping** [comment]
cool, i'll get @lgierth's other 'nice to have' in another PR

**Pull request merged**
