### PR TITLE
extract binaries with .exe name on windows

### PR DESCRIPTION
**Pull request by whyrusleeping**
Should address #3019 
We really need to work on some sort of CI for windows.

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Verified this works on an AWS box

**Comment by Kubuxu** [comment]
If it runs LGTM.

**Comment by jbenet** [comment]
I think this should have a test case

**Comment by jbenet** [comment]
we want to test all this install/migrations stuff. it doesnt have to be tested on every commit to go-ipfs, so maybe it could all be in another package, like `go-ipfs-migrations` or something

**Pull request merged**
