### PR TITLE
vendor commands/files outside of ipfs

### PR DESCRIPTION
**Pull request by whyrusleeping**
I'm using this code in `ipfs-shell`, extracted so it doesnt have to import all of go-ipfs. I think it will be easier to have it separated here, so I dont have to make changes in two different places.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by rht** [comment]
Currently `ipfs get` uses tar as transport format, while `ipfs add` uses multipart and the files abstraction.
Will the former become multipart as well, or the other way around?

**Comment by whyrusleeping** [comment]
@rht good point. I think TAR might be a little nicer format to deal with overall. we could probably switch to that, but keeping in mind that it will break compatibility with all of the api bindings people are making

**Comment by rht** [comment]
What would be the "llvm" of the file format to convert one format to another?

**Comment by rht** [comment]
For api bindings, yes it breaks compatibility with the existing ones, but will also make future api writing in more systems easier. The multipart will be further complicated with the fileinfo mimetype (which tar already supports).

**Comment by whyrusleeping** [comment]
> For api bindings, yes it breaks compatibility with the existing ones, but will also make future api writing in more systems easier.

Not disagreeing in the slightest. Just saying that we need to inform (or maybe even PR to help out if its simple enough) those people who are writing api bindings.

**Comment by rht** [comment]
(Caveat: any file type that is not in tar specs must be specified in a regular file like git symlink?)

**Comment by rht** [comment]
It doesn't have to break compatibility. Simply add a mimetype `application/tarToBeExtracted` that will surely be extracted.

**Comment by whyrusleeping** [comment]
@rht tar can handle symlinks and the like: http://golang.org/pkg/archive/tar/#pkg-constants

**Comment by jbenet** [comment]
> - TAR or Multipart

Both. web interfaces that let you do things with multiple formats are very nice to use as sometimes users have constraints.

But really, `car + unixfs` would be sweet.

> PR

yeah sure, +1 on vendoring. actually, @whyrusleeping why dont we rip out the entire cmds lib? would be good to finally vendor that whole thing. need to hack around the Context thing, but may be a nice way to do it with just giving it an `interface{}` to hang on to / pass.

**Comment by whyrusleeping** [comment]
> why dont we rip out the entire cmds lib?

I looked into doing that, the issue is that it needs to import core. which makes it hard to extract easily. i was able to pull the files stuff out nicely because its pretty self contained.

**Comment by whyrusleeping** [comment]
I'll need to update this with the recent chanegs @rht made to the files lib

**Comment by jbenet** [comment]
> needs to import core

I think the imports from core are minimal. AFAIK it's just the node + config in the Context thing. need to hack around the Context thing, but may be a nice way to do it with just giving it an `interface{}` to hang on to / pass.

**Comment by whyrusleeping** [comment]
closing, will use gx at a later date

**Comment by rht** [comment]
Can gx be used now?

Here is a heuristic `git blame` stat on `commands/files`
```shell
$ ls commands/files/* | xargs -n1 git blame --line-porcelain | grep "^author " | sort | uniq -c | sort -nr
    427 author Matt Bell
    182 author Jeromy
     48 author gatesvp
     38 author rht
     35 author Juan Batiz-Benet
      4 author Dominic Della Valle
```

**Comment by whyrusleeping** [comment]
very soon! (working on it this week)

**Comment by rht** [comment]
While `ipld` hasn't shipped yet, it'd be useful to add mime type method into the interface. That it is more seamless for any web tools that use the [file api](https://www.w3.org/TR/FileAPI/).

ref: #2203 for where the mimetype/encoding detection should be put in the file transformation chain (at least should be earlier than gateway serve).

**Pull request closed without merging**
