### PR TITLE
makes 'ipfs files write' usage docs clearer

### PR DESCRIPTION
**Pull request by noffle**
addresses https://github.com/ipfs/go-ipfs/issues/2380 and https://github.com/ipfs/go-ipfs/issues/2380#issuecomment-188443493

### CODE REVIEW

**Comment by RichardLitt** [comment]
Doesn't truncate start where offset starts if offset is there, though?

**Comment by noffle** [comment]
@RichardLitt I'm not sure what the *intended* behaviour is, but what I see is the file being wiped first:

```
stephen // ~ $ ipfs files read /myfs/file
!!!?
hello world
stephen // ~ $ echo '&' | ipfs files write /myfs/file --offset 4 --truncate
stephen // ~ $ ipfs files read /myfs/file
&
```

---

cc @whyrusleeping

**Comment by whyrusleeping** [comment]
`ipfs files write /myfs/file --offset 4 --truncate` equates to opening a file with `O_TRUNC` and calling `seek()` to set the position of the file descriptor to 4. Doing so will sparsely expand the file (with zeros) up to the point where you start writing.

**Comment by whyrusleeping** [comment]
these doc changes LGTM

**Pull request merged**
