### PR TITLE
Fixes #4003

### LINKED ISSUE #4003: Out of bounds access kills daemon
#### Version information:
The latest version of the release branch, currently 0.4.8. I've digged a bit into the code and it seems this is still the case on master.

#### Type:
Bug

#### Severity:
application panic, but probably not that critical

#### Description:
I've tried to write an api client for ipfs, while doing that I noticed my client is crashing the ipfs daemon. I was able to fix this issue and my client is now working correctly, but I spent some more time to reproduce the issue with a one-liner to verify the issue without compiling my application:

```
echo -ne "POST /api/v0/add?pin=true HTTP/1.1\r\nHost: 127.0.0.1:5001\r\nContent-Type: multipart/form-data; boundary=Pyw9xQLtiLPE6XcI\r\nContent-Length: 22\r\n\r\n\r\n--Pyw9xQLtiLPE6XcI\r\n" | nc -v 127.0.0.1 5001
```

This causes an out-of-bounds access on an empty list:
```
docker[18425]: panic: runtime error: index out of range
docker[18425]: goroutine 255211 [running]:
docker[18425]: github.com/ipfs/go-ipfs/core/coreunix.(*Adder).Finalize(0xc427bf26c0, 0xc420062020, 0x562d1ba4c7a0, 0xc420062020, 0xc420062001)
docker[18425]:         /go/src/github.com/ipfs/go-ipfs/core/coreunix/add.go:204 +0x315
docker[18425]: github.com/ipfs/go-ipfs/core/commands.glob..func6.1(0x562d1ba5c720, 0xc42c4ff350, 0xc42c4ff350, 0xc420287fd8)
docker[18425]:         /go/src/github.com/ipfs/go-ipfs/core/commands/add.go:254 +0x138
docker[18425]: github.com/ipfs/go-ipfs/core/commands.glob..func6.2(0xc42cd20420, 0xc4287dd040, 0x562d1ba610c0, 0xc42c1012c0, 0x562d1ba604a0, 0xc42941e380)
docker[18425]:         /go/src/github.com/ipfs/go-ipfs/core/commands/add.go:268 +0x7e
docker[18425]: created by github.com/ipfs/go-ipfs/core/commands.glob..func6
docker[18425]:         /go/src/github.com/ipfs/go-ipfs/core/commands/add.go:273 +0xa11
systemd[1]: go-ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

https://github.com/ipfs/go-ipfs/blob/b04cd7a68d55861850357c33a7c8fdaa4762f5ef/core/coreunix/add.go#L204

I hope this helps to resolve the underlying issue. :)

### PR DESCRIPTION
**Pull request by Quantomicus**
Includes a general sanity check to skip further checks if user provided fewer arguments than minimum required and a specific check for corrupted data passed as file.

License: MIT
Signed-off-by: Mateja Milosevic <minima38123@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
This broke quite many things in tests, see for yourself: https://ci.ipfs.team/blue/organizations/jenkins/go-ipfs/detail/PR-4053/1/pipeline/

**Comment by Quantomicus** [comment]
Yep, pretty sure I know what it is.

**Comment by Quantomicus** [comment]
From the looks of it, the only thing that makes the test fail is the fact that now some commands which should output an error output a different error higher up the stack. I apologize, but I haven't had contact with such a developed repository before; should I have modified the tests to reflect the fact I changed the position in the stack the error happens? If so, how?

**Comment by Kubuxu** [comment]
Right, the refactor of commands lib is being worked on at https://github.com/ipfs/go-ipfs-cmds

The early exit on too little arguments is interesting. We are able to provide more info to the user if he misses some arguments, but we are more susceptible to possible bug without it.

cc @whyrusleeping

**Comment by Quantomicus** [comment]
After a little discussion on the irc, it's better to leave just the regular, bug-specific check in.

**Comment by Quantomicus** [comment]
It was decided that for now, a bandaid fix for this edgecase was enough. It is not certain if this kind of problems will happen again, if they do, a new issue can be created and further solutions can be discussed.

**Comment by Kubuxu** [comment]
Could you add a test case in sharness that demonstrates what was the problem before.

**Comment by Quantomicus** [comment]
Done.

**Pull request merged**
