### PR TITLE
gateway: embed directory-listing styles

### PR DESCRIPTION
**Pull request by lgierth**
This embeds bootstrap.css and icons.css into the index page, so that the styles are **always available**, even when we're on a static page hosted off IPFS, where `/ipfs` and `/ipns` aren't exposed.

Travis failure is from mock_notif_test.

### CODE REVIEW

**Comment by jbenet** [comment]
May want to work on https://github.com/ipfs/dir-index-html

**Comment by rht** [comment]
https://github.com/ipfs/go-ipfs/pull/1487 now works. Forgot to trim the trailing newline: https://github.com/ipfs/go-ipfs/pull/1487/files#diff-d68d022661f02d0093d7693d0a76b010R32

**Comment by jbenet** [comment]
@rht let's rebase + land that PR. then we can make @lgierth's changes on top. we should also fix some of the stuff here: https://github.com/ipfs/dir-index-html/issues

**Comment by rht** [comment]
@lgierth how to generate the 'minified' index page here?

**Comment by rht** [comment]
gulp-inject / gulp-usemin / gulp-useref? However can't vendor npm packages in dir-index-html repo because package.json is used for gx.

**Comment by rht** [comment]
@lgierth if you can concat the css and html file in dir-index-html (optionally vendor the concat build script later), I will then update the gx package here in go-ipfs.

**Comment by jbenet** [comment]
> can't vendor npm packages in dir-index-html repo because package.json is used for gx.

AFAIK, gx and npm can be used in same package/repo. they shouldn't conflict? if they do, we should change that. other PMs make a point not to conflict because invariably people end up having to use multiple systems. cc @whyrusleeping

**Comment by lgierth** [comment]
@rht it's from here https://gateway.ipfs.io/ipfs/QmWxrgcm6nTNbRB7S2ugq7Wfw3pD1FVBTN6WMtkHiD396u/bundle.css (courtesy of @krl)

**Comment by whyrusleeping** [comment]
@rht @jbenet yeah, i would hope npm and gx can coexist, any issues between the two should be reported (granted, i havent tried that yet)

**Comment by rht** [comment]
@whyrusleeping https://github.com/whyrusleeping/gx/blob/master/gxutil/pkgfile.go#L11 if this is `gxDependencies`?

**Comment by rht** [comment]
What about collision with godep in go 1.5?

**Comment by whyrusleeping** [comment]
@rht which collision? i'm going to move from putting packages in `vendor/src` to just putting them in `vendor` to comply with the go1.5 vendoring spec.

**Comment by rht** [comment]
Since gx now is compatible with go1.5 vendor/, the question has been obsolete.

This PR can be closed, https://github.com/ipfs/go-ipfs/commit/8ec121239e3241071ddebe8e3574623e1fda3a06

**Comment by rht** [comment]
(here goes)

**Comment by lgierth** [comment]
cool :cake:

**Pull request closed without merging**
