### PR TITLE
protobuf: compile proto files using protoeasy

### PR DESCRIPTION
**Pull request by peter-edge**
This uses https://go.pedge.io/protoeasy to compile protos, making the whole process much simpler and consistent. This does not update the protos as godep is not being fun.

Small discussion at https://groups.google.com/forum/?fromgroups#!topic/grpc-io/PDnNrp8bSL4.

I don't think this PR will be immediately merged, and needs some discussion. Ask me questions if you want, or I can explain further. I wanted to see if this was something the maintainers would like.

License: MIT
Signed-off-by: Peter Edge <peter.edge@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
thanks @peter-edge -- first, congrats, it's a very cool tool.

i don't know though. this has rarely been a problem for us.  this also seems to have problems:
- AFAIU, compilation _requires_ user to be online. instant dealbreaker.
- AFAIU, compilation _requires_ your service to be online. instant dealbreaker.
- AFAIU, compilation _requires_ your service to survive as long as the code.
- we also have very unconventional (by rest of go community) standards around vendoring, [even having our own vendoring/packaging tool](https://github.com/whyrusleeping/gx).
- apparently we use gogoprotobuf... sometimes, but not always. (ok switching to always)

we take a very negative view on _requiring services_. we minimize our dependence on other people. so if we were to use it, this would be an _option_ and not the requirement.

**Comment by peter-edge** [comment]
Fast reply, I like this repository already!

So:

- `protoeasy` works both as a local tool, AND as a client/server application. The environment variable `PROTOEASY_ADDRESS` controls the mode that `protoeasy` attempts to operate in. In fact, if you were to use it right now with `make proto`, it would not connect at all to anything, and would use locally-installed tools (including you locally installed `protoc-gen-gogo` if it is an older version).
- If you switch between go and gogo, this tools actually is even nicer for you :)

Does this help? Happy to give more information.

**Comment by jbenet** [comment]
@peter-edge do you have an example written up of how this would work, in the case where we explicitly do not want to use the service?

**Comment by peter-edge** [comment]
`make proto`

I'm assuming you don't have `PROTOEASY_ADDRESS` set in your environment, so this will run locally, not connecting to any service.

**Comment by whyrusleeping** [comment]
This actually looks pretty nifty. I hate messing with protobufs, I'll try this out tomorrow when i get a chance

**Comment by whyrusleeping** [comment]
closing, we're going to be dealing with protobufs less and less after ipld

**Pull request closed without merging**
