### PR TITLE
docs: Require go 1.8

### LINKED ISSUE #4043: make install error in mac
go install -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=0b481a3"  ./cmd/ipfs
# gx/ipfs/QmVSase1JP7cq9QkPT46oNwdp9pT6kBkG3oqS14y3QcZjG/go-datastore/syncmount
../../../gx/ipfs/QmVSase1JP7cq9QkPT46oNwdp9pT6kBkG3oqS14y3QcZjG/go-datastore/syncmount/mount.go:31: undefined: sort.Slice

### PR DESCRIPTION
**Pull request by magik6k**
Closes #4043

### CODE REVIEW

**Comment by whyrusleeping** [comment]
I'll need to push another release of gx and gx-go for this. (gx-go asserts that it was compiled with the sufficient version of go due to changes in the stdlib ast parsing changing between versions)

**Comment by Kubuxu** [comment]
You also have to fix build systems.
I will fix Jenkins as it is a bit more complex.

**Comment by Kubuxu** [comment]
Jenkins runs Go 1.8 already so the failure is unrelated.

**Comment by whyrusleeping** [comment]
i released new version of gx (0.12.0) and gx-go (1.5.0), update bin/Rules.mk to use these new versions

**Pull request merged**
