### PR TITLE
"repo stat": Don't crash when Datastore.StorageMax is not defined

### LINKED ISSUE #4241: `ipfs stats repo` fails if `Datastore.StorageMax` is empty
It tries to parse it as a float and fails, causing the whole command to fail out. Ipfs in general seems to run fine without this option set, so the command should either omit that field in this case or have some default.

### PR DESCRIPTION
**Pull request by kevina**
Closes #4241

License: MIT
Signed-off-by: Kevin Atkinson <k@kevina.org>

### CODE REVIEW

**Comment by kevina** [comment]
@whyrusleeping note I use `math.MaxUint64` as the default value in the stat structure to avoid an API change and then simply don't report it in the `repo stat` command if the value is `math.MaxUint64`

**Comment by whyrusleeping** [comment]
@kevina I think '0' works as a default value too, might be a little easier to reason about

**Comment by kevina** [comment]
@whyrusleeping A very large value makes more logical sense.  0 could theoretically have a meaning as in no-storage.  If the the of 0 is used for something bad things could happen.  If a very large value is used, then it will effectively main the same as no limit.  That is why I think `math.MaxUint64` makes more sence.  If it was a floating point number I would use positive Infinity.

**Comment by kevina** [comment]
I can also make `math.MaxUint64` a constant, say `NoLimit`, to make the code easier to read.

**Pull request merged**
