### PR TITLE
make files stat --with-local return immediately when no data is present

### PR DESCRIPTION
**Pull request by MichaelMure**
Currently when the daemon is running, asking for `ipfs files stat QmDoesntExistLocally` will hang instead of returning immediately. This PR fix that by using the offline DAGService earlier. I guess I got confused in the test I was doing when implementing that the third time :-|

License: MIT
Signed-off-by: Michael Muré <batolettre@gmail.com>

### CODE REVIEW

**Comment by MichaelMure** [comment]
test failure is unrelated

**Comment by Stebalien** [comment]
Test failure is https://github.com/ipfs/go-ipfs/issues/4726 (confirmed unrelated).

**Comment by MichaelMure** [comment]
Can we merge ?

**Comment by whyrusleeping** [comment]
Thanks @MichaelMure, getting this one into 0.4.14 since the feature was introduced in this release.

**Pull request merged**
