### PR TITLE
Filestore: more verbose error when adding a file from outside of the root

### PR DESCRIPTION
**Pull request by MichaelMure**
I got very confused by what 'ipfs root' is. Hopefully this will help the next person.

License: MIT
Signed-off-by: Michael Muré <batolettre@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Test failures appear to be unrelated.

**Comment by Mikaela** [comment]
Hi, I don't know if I am the next person, but my confusion is why I cannot `ipfs add` a file from a directory where everyone and everything has rw access.

> Error: cannot add filestore references outside ipfs root (/home/mikaela)

**Comment by aratic** [comment]
@Mikaela  same glitches, i've even create soft links, complete duplicate files in specific formats potentially waste space, and not sure if there are methods to change ipfs root, some IPFS_PATH variable ?

**Comment by hsanjuan** [comment]
@whyrusleeping @Stebalien actually I'm curious, do you know why there is this restriction?

**Comment by Stebalien** [comment]
https://discuss.ipfs.io/t/ipfs-update-1-5-3/7175

**Pull request merged**
