### PR TITLE
Use 'dag' forall namespace import prefixes of merkledag

### PR DESCRIPTION
**Pull request by rht**
Oldest code uses 'merkledag'. Slightly older code uses 'mdag'. Most recent code uses 'dag'.

### CODE REVIEW

**Comment by rht** [comment]
Also a small issue (since naming is one out of two hard problems in cs?), 'n','nd','node' are used interchangeably for core.IpfsNode and dag.Node (not to mention that both use of  "node"). Would it be more grep-able if the former's shorthand is changed to 'in'/'inode'?

**Comment by whyrusleeping** [comment]
i don't like the connotation of calling the core.IpfsNode an inode, i agree we should be consistent though. maybe `dag.Node` -> `nd`, and `core.IpfsNode` -> node?

**Comment by whyrusleeping** [comment]
this PR LGTM, mind rebasing on top of latest 0.4.0?

**Comment by rht** [comment]
Rebased.

Both 'in' and 'inode' already have connotation that may confuse things, it definitely should be something else, it's just that I haven't come up a shorthand yet.

**Comment by whyrusleeping** [comment]
@rht i'm 99% certain the circle sharness test failures have nothing to do with this PR. but do you have any idea what might be causing them?

**Comment by lgierth** [comment]
Travis looks similar, doesn't it? Some of these look hairy. I'm also seeing the same errors in #1987.

**Comment by lgierth** [comment]
ctrl+f "not ok"

**Comment by rht** [comment]
The stalled os x build (errs not being output-ed?) might have an explanation in the circle-ci errs.

**Comment by jbenet** [comment]
could it be something in master?

**Comment by jbenet** [comment]
@rht was it the watermark repo gc? i recall some pr recently being the first. i dont think it's travis-ci here.

**Comment by jbenet** [comment]
certainly in this run it was: https://travis-ci.org/ipfs/go-ipfs/jobs/92377814#L5059-L5060

**Comment by rht** [comment]
> could it be something in master?

Yes but there is less merge conflict in 0.4.0.

Also, here is another naming clash that might cause confusion [commands.Context and context.Context](https://github.com/ipfs/go-ipfs/blob/master/commands/http/handler.go#L147).

**Comment by jbenet** [comment]
In general, this PR LGTM.

i think we should still solve the random failures on master + rebase dev0.4.0 on top of that, and this on top of dev0.4.0.

at some point we let through something that randomly breaks and now we're paying the price. :(  maybe someone could try bisecting it?

**Comment by rht** [comment]
Rebased. In this case, test fails are orthogonal to the possible errs caused by import errs.

**Comment by whyrusleeping** [comment]
@rht mind redoing this on latest master? would be good to have a bit of consistency there

**Comment by rht** [comment]
This could have been merged before dev0.4.0 was merged into master.

**Comment by Kubuxu** [comment]
@rht you have to just create new PR to master instead of dev0.4.0

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c242660da50fca838f9fa937822a2c337e637f3f
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: 38a600b3c83d72ca5cebef07890b197a3d9b3a06
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
