### PR TITLE
update libp2p for stream closure refactor

### PR DESCRIPTION
**Pull request by Stebalien**
Depends on:
* https://github.com/libp2p/go-libp2p/pull/1001
* https://github.com/multiformats/go-multistream/pull/52
* https://github.com/libp2p/go-libp2p-pubsub/pull/385
* https://github.com/ipfs/go-bitswap/pull/445
* https://github.com/libp2p/go-libp2p-kad-dht/pull/693
* https://github.com/libp2p/go-libp2p-gostream/pull/60
* https://github.com/ipfs/go-graphsync/pull/116
* https://github.com/libp2p/go-libp2p-pubsub-router/pull/81

### CODE REVIEW

**Review by aschmahmann — COMMENTED** [review]
Are any changes to the `/p2p` folder required? e.g. In `ipfs p2p close` calling Close instead of Reset?

**Comment by Stebalien** [comment]
Hm. Yes, we need to call CloseWrite and CloseRead in some cases.

**Comment by Stebalien** [comment]
Ah, now I remember. I wrote some patches a while ago to fix this.

**Comment by Stebalien** [comment]
Actually, the p2p code _was_ wrong (I think?) because it didn't wait for an EOF. Now it's more correct because "close" actually closes the stream in both directions.

Ideally, we'd support half-open streams instead of closing the streams in both directions, but that's very tricky to get right and probably not worth it for now.

**Comment by Stebalien** [comment]
This should be ready to merge.

**Review by aschmahmann — APPROVED** [review]

**Comment by moul** [comment]
LGTM, tested here: https://github.com/berty/berty/pull/2718

**Comment by Stebalien** [comment]
Ok, it was a but in bitswap. All fixed.

**Pull request merged**
