### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drathir**
Update the usage output to present one.
License: MIT
Signed-off-by: drathir <drathir@users.noreply.github.com>

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a283db232836577b36ecf881af5c6137f308cc81
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by drathir** [comment]
updated

**Comment by jbenet** [comment]
Thanks!

**Comment by jbenet** [comment]
@drathir in the future, when contributing code, please add the appropriate license to the commit. Read the message from GitCop above, and see https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh

**Pull request merged**
