### PR TITLE
object put: Allow empty objects

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/ipfs/go-ipfs/issues/1331

### CODE REVIEW

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipfs/commit/443073142635d9703a8ff254c09aea543a0f14c7. I ran into trouble detecting mis-encoded XML objects.

**Comment by magik6k** [comment]
If we really want to be correct on how we parse xml, we'd probably want to use `xml.Decoder` directly, but I'm not sure if it's worth the time in this case

**Comment by Stebalien** [comment]
> If we really want to be correct on how we parse xml, we'd probably want to use xml.Decoder directly, but I'm not sure if it's worth the time in this case

Probably not. Want to just drop that test? However, I would backport my JSON error checking into this patch.

**Comment by magik6k** [comment]
(done)

**Pull request merged**
