### PR TITLE
correct the blocksize calculation for link blocks

### PR DESCRIPTION
**Pull request by whyrusleeping**
This has been wrong for a while, and ive known about it for a while, but i finally decided to fix it.

### CODE REVIEW

**Comment by jbenet** [comment]
Oh it's in bytes! 

and the tests need fixing (chunking changed)

**Comment by whyrusleeping** [comment]
thats weird... the hash for the 5MB random file changed... which doesnt make sense.

**Comment by jbenet** [comment]
why not? maybe it was chunked to multiple indirect blocks and not to less.

**Comment by whyrusleeping** [comment]
5MB/256k = 20

8K/(258+3 + 5) = 30

**Comment by whyrusleeping** [comment]
Ah, okay, its the 100MB test thats failing. makes a lot more sense

**Comment by jbenet** [comment]
Aw man, i just found the perfect gif: 


i guess it still works.

**Comment by whyrusleeping** [comment]
the day when your gifs are hosted in ipfs will be a good one

**Pull request merged**
