### PR TITLE
Improve t0240

### PR DESCRIPTION
**Pull request by chriscool**
This is a small series of small cleanups.

### CODE REVIEW

**Comment by chriscool** [comment]
It looks like the tests that failed sometimes fail according to comments above them.

**Comment by jbenet** [comment]
@whyrusleeping the "cannot resolve entry stuff" is that the new resolve tests?

**Comment by whyrusleeping** [comment]
@jbenet yeah, it looks like some operation that occurs before we do the 'expect resolve to fail' checks is taking such a long time that the republish triggers. We can do one of two things, leave this as a reminder to ourselves to fix the dht code so it doesnt do that (this is nothing new), or we can add explicit timeouts to all of those operations so this cant happen (hides the problem)

**Comment by jbenet** [comment]
i dont think we should have intermittent failures. expected failures can be tagged as such and fixed. if we have a reliable way to repro the error, then have that as an expected failure and then add explicit timeouts here?

**Comment by whyrusleeping** [comment]
i think its random based on the layout of the keys generated by the nodes.

**Pull request merged**
