### PR TITLE
use forked lumberjack (buffers writes)

### PR DESCRIPTION
**Pull request by cryptix**
Played a little with the pprof tools added in #1163 and saw that lumberjack writes directly to an `*os.File` which is unbuffered, which explains profiles with the 20-30% of time beeing spent in eventlog stuff.

Also opened natefinch/lumberjack#10 so we can switch back upstream someday.

### CODE REVIEW

**Comment by jbenet** [comment]
@cryptix i'd like to kill writing logs to disk in general. the goal is to expose them at an HTTP route in the api, that behaves like tailing logs. (so if there's no http request consuming them, the logs are never written). (should support multiple requests too)

**Comment by jbenet** [comment]
this PR is fine with me as a stop gap-- but ideally we would do the http route thing

**Comment by natefinch** [comment]
I commented on the issue in lumberjack, but I'll repost here:

You don't actually need to add this code to lumberjack, you can do it external to lumberjack, by just wrapping the lumberjack.Logger in a bufio.Writer:

```go
log := bufio.NewWriter(&lumberjack.Logger{ /* config here */})
```

Yay interfaces :)

**Comment by cryptix** [comment]
Oh right, that's much cleaner. Thanks @natefinch!

**Pull request merged**
