### PR TITLE
Do not install gx if user explicitly didn't ask for it

### PR DESCRIPTION
**Pull request by Kubuxu**
License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@gmail.com>

### CODE REVIEW

**Comment by noffle** [comment]
I'd really prefer to see a specific version tied to the `go-ipfs` repo. If we always grab the latest we love reproducible builds. However, if we use whatever's already on the user's system, it could be out of date or have security holes.

cc @whyrusleeping

**Comment by Kubuxu** [comment]
It PRed it because we talked with @whyrusleeping on IRC about packaging gx and repackaging go-ipfs on AUR.

If user has tool on disk we shouldn't touch it. If it is outdated, it is his problem. Same reason Chrome doesn't have auto updater in Linux.

**Comment by whyrusleeping** [comment]
this moves more towards reproducible builds than what we currently have

**Comment by Kubuxu** [comment]
Also build time is about half of what it was because we are no longer syncing and building two go projects.

**Comment by noffle** [comment]
> this moves more towards reproducible builds than what we currently have

This is a lateral step: we have no idea what version of `gx` users will have installed, so this isn't fundamentally any better/different than always fetching the latest.

One small shim that could be made to this PR that slightly would improve reproducibility would be to run `gx -v` and `go get` it if it's below some value. This would at least let us control the lower version bound.

> If user has tool on disk we shouldn't touch it. If it is outdated, it is his problem.

This is a really dangerous user-hostile stance to take: it's **our** job to make builds reproducible, not the user's. This sort of thinking is what makes so many userland software so fragile.

**Comment by Kubuxu** [comment]
Do you upgrade gcc or go on user's system, no. The moment you want to use gx for something more than only IPFS (and it is happening right now) the same rules apply to gx.

Builds should be reproducible using the same set of tools, I am sure that not everybody compiling IPFS has same version of go.

**Comment by Kubuxu** [comment]
Rebased

**Comment by chriscool** [comment]
Yeah, I agree that it's nicer and more efficient to just define the minimum version of gx we need and error out with a "nice error message" if gx is not installed or if its version is below the minimum.

The nice error message in case of a version below the minimum could say something like:

```
Sorry, it appears that you have an old gx version (vX.Y.Z) and we need at least vX'.Y'.Z'.
Please upgrade gx! This can be done automatically by running `make upgrade_gx`.
```

For Travis CI and Circle CI we might create a special make target called for example "upgrade_gx_and_install" that would just depend on the "upgrade_gx" and the "install" targets.

**Comment by Kubuxu** [comment]
Ok, will do that.

**Comment by Kubuxu** [comment]
The check is implemented.

**Comment by Kubuxu** [comment]
@chriscool thank you very much for the script.

It should be good to go now.

**Comment by Kubuxu** [comment]
Ok, this time it should be good to go, Windows works, Travis works.

**Comment by chriscool** [comment]
Yeah, there is this Circle CI failure:

```
expecting success: 
	grep "log/tail" cmd_out2 | grep "true" > /dev/null

not ok 12 - output looks good
#	
#		grep "log/tail" cmd_out2 | grep "true" > /dev/null
```

but it is not related.

**Comment by Kubuxu** [comment]
Works as in: code affected in this PR worked and build continued.

**Comment by chriscool** [comment]
LGTM!

**Comment by whyrusleeping** [comment]
Cool, LGTM too

**Comment by whyrusleeping** [comment]
mmmm... @Kubuxu i just realized that we should probably add a bit to the readme mentioning this:
"If you don't already have gx and gx-go installed you will need to do X"

**Comment by whyrusleeping** [comment]
Do you think you could add something like that and PR it soon? I would but i'm about to get some sleep

**Comment by Kubuxu** [comment]
No problem.

**Comment by RichardLitt** [comment]
@Kubuxu could you reference this from the PR?

**Comment by Kubuxu** [comment]
In process:  #2342

**Pull request merged**
