### PR TITLE
Revert "godeps: update everything to master"

### PR DESCRIPTION
**Pull request by whyrusleeping**
This reverts commit dc758b1c819cc9dd638e54e81df62e8f8c52a393, it introduced a bug in bitswap (somehow). The test i was using to repro was a simple iptb two node setup, add a 1GB file on one node, and cat it to /dev/null on the other. The bug would cause the cat to hang between 150 and 250 MB.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
https://github.com/ipfs/go-ipfs/pull/1302#issuecomment-106872235

**Comment by jbenet** [comment]
Ooooooof!! 

We need some serious business integration tests before merging things like this (as you mentioned).

**Comment by jbenet** [comment]
@whyrusleeping before i merge this, are you sure you "can repro with", and "cannot repro without" ?

if so, maybe make a test case (that, yes, generates a 300GB random file and then adds it) for it and commit it? we dont have to run it, can just have it a benchmark we can run manually in cases like these.

**Comment by whyrusleeping** [comment]
@jbenet i have an iptb sharness test locally, but you disabled all the other sharness tests so i didnt add it

**Comment by whyrusleeping** [comment]
Also, i am very sure about the issue being here, i tested it back and forth for around an hour.

**Comment by jbenet** [comment]
@whyrusleeping can you add it _disabled_ ? (like `x11....` whatever). we can manually run tests that are disabled.

**Comment by chriscool** [comment]
The problem with https://github.com/ipfs/go-ipfs/commit/dc758b1c819cc9dd638e54e81df62e8f8c52a393 is that it updates many dependencies in the same commit.

If we could just update dependencies one by one, we could see exactly which dependency update introduces a regression, and it would be easier to find out where the regression comes from.
We could also revert only one dependency update.

**Comment by whyrusleeping** [comment]
sorry, meant that it hung around 300MB not around 300GB.  (i realized this as i filled up my disk generating a 300GB file)

**Comment by jbenet** [comment]
@chriscool  said:
> If we could just update dependencies one by one, we could see exactly which dependency update introduces a regression

Yes, let's do this from now on when updating large swaths of deps. (small tightly coupled deps, like say go-peerstream and a stream muxer, are probably ok). cc  @cryptix

**Comment by cryptix** [comment]
I agree with updating one-by-one but it's a lot more legwork. I don't know when I can do this. We should increase the frequency of updating to keep the sets smaller.

**Comment by chriscool** [comment]
Isn't it possible to script updating one dependency to make it easier and faster?

**Comment by cryptix** [comment]
yes it's all possible but needs to be welded together.

You can run `godeps update $importPath` to update just one dependency but you still need to check the changes in with git (also currently - Don't forget to rewrite import paths..!) and then hope that regressions are caught by out tests...

To get the list of which deps aren't up to date, you need to reclone all the deps (recommendation `godeps restore` in a clean `$gopath` with just go-ipfs in it). Then you can use [gostatus](https://github.com/shurcooL/gostatus) to see which ones have more commits at the remote.

This only tooling though. If the updates depend on each other to work you need to know about their relationship, a scripted one-by-one update won't work then. All of this is why I already advised to do this more often back in [april](https://github.com/ipfs/go-ipfs/pull/1156#issuecomment-97458636) to keep the sets smaller.

**Comment by chriscool** [comment]
I think it's `godep update $importPath`. And yeah it is not easy to script.

**Pull request merged**
