### PR TITLE
Put all Taglines & most Option descriptions in active, present tense

### PR DESCRIPTION
**Pull request by JesseWeinstein**
For consistency. This should probably be documented somewhere, too.

### CODE REVIEW

**Comment by thomas-gardner** [comment]
Hi, I think the imperative mood is the default for this subset of
technical writing. Some non-IPFS examples include, 

	`git`, `go`, `gcc --help`.

**Comment by JesseWeinstein** [comment]
Sigh. I was afraid that might be the case. Well, if we settle on imperative, I'll make them all consistent with *THAT*, instead.

**Comment by RichardLitt** [comment]
This should be documented here: https://github.com/ipfs/community/blob/master/docs-styleguide.md. Might be good to open an issue about it in ipfs/community before doing all of the changes again, in case we want to weigh in on it not only for go-ipfs but also for other repos.

**Comment by whyrusleeping** [comment]
blocked on resolution of https://github.com/ipfs/community/issues/150

**Comment by jbenet** [comment]
Please keep using imperative. It's a decades old convention for unix
tooling.

And I think it's much better, too. Think of it like a button. Buttons in an
airplane don't say "[this button] turns the engine on". They say "Turn the
engine on". These descriptions are putting in writing what "the user will
do" by executing that command (pushing the button) instead of doing it
manually.

**Comment by JesseWeinstein** [comment]
OK, I've closed this PR, and will make another (much smaller) one to fix the few taglines & options descriptions that weren't in imperative mood.

**Pull request closed without merging**
