### PR TITLE
typo

### PR DESCRIPTION
**Pull request by wasserfuhr**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9fd8fa26f5893f614fba2d9cc9134bf93cc8410
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
LGTM, could you add a license signoff to your commit?

just `git commit --amend`, and add:
```
License: MIT
Signed-off-by: Your Name <your email>
```

at the bottom,
Then go ahead and do a force push to your branch and i'll merge this.

**Comment by jbenet** [comment]
ping again after the signoff, so we get notified. thanks @wasserfuhr !

**Comment by whyrusleeping** [comment]
closing due to inactivity

**Pull request closed without merging**
