### PR TITLE
sharness/Makefile: clean all BINS when cleaning

### PR DESCRIPTION
**Pull request by chriscool**
I think it is better to clean all the binaries.

### CODE REVIEW

**Comment by chriscool** [comment]
The Travis errors are:

```
[4 / 6] fetched dep: go-net

  - fetch finished in 11.431411965s

  - fetch QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV complete!

[5 / 6] fetched dep: gogo-protobuf

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by chriscool** [comment]
The CircleCI failure has an error in iptb that is fixed with https://github.com/whyrusleeping/iptb/pull/19.

**Comment by chriscool** [comment]
The teamcity failure is:

```
[21:48:12][Step 2/3] TestAllKeysRespectsContext
[21:48:12][TestAllKeysRespectsContext] 	blockstore_test.go:186: should not be closed
[21:48:12][TestAllKeysRespectsContext] TestValueTypeMismatch
[21:48:12][TestAllKeysRespectsContext] TestReturnsErrorWhenSizeNegative
[21:48:12][TestAllKeysRespectsContext] TestRemoveCacheEntryOnDelete
[21:48:12][TestAllKeysRespectsContext] TestElideDuplicateWrite
[21:48:12][TestAllKeysRespectsContext] FAIL
[21:48:12][TestAllKeysRespectsContext] exit status 1
[21:48:12][TestAllKeysRespectsContext] FAIL	github.com/ipfs/go-ipfs/blocks/blockstore	0.008s
[21:48:12][TestAllKeysRespectsContext] Process exited with code 1
[21:48:12][TestAllKeysRespectsContext] Step go tests (Command Line) failed
```

**Comment by whyrusleeping** [comment]
LGTM, thanks!

**Pull request merged**
