### PR TITLE
Added note about error codes

### PR DESCRIPTION
**Pull request by RichardLitt**
How does this look? See #2293

License: MIT
Signed-off-by: Richard Littauer richard.littauer@gmail.com

### CODE REVIEW

**Comment by RichardLitt** [comment]
@Kubuxu What do you think about this?

**Comment by Kubuxu** [comment]
First thing it fails to build as you used backticks as quotes.
Other thing is that error codes from CLI are general knowledge to most users, it would make sense if our error codes had special meanings (type of crash, system that failed), but they don't. This would better fit http-api docs as the purpose of of the `Code` over there is unclear.

The `Code` in case of error on http corresponds to https://github.com/ipfs/go-ipfs/blob/master/commands/response.go#L17-L22 where first is 0 and last 2.

**Comment by RichardLitt** [comment]
> Other thing is that error codes from CLI are general knowledge to most users...

I disagree with this - or, rather, I disagree with assuming that this is OK. Offloading knowledge building is important for some things, but I think having a place that says this may be useful to newcomers. I think the code in this PR is easy to put in, and helpful. 

I would like there to be more special meanings, too. I know where the codes come from - found that part of the code (thanks for linking it! Makes me feel pretty confident in my CR ability) - and there's a comment there saying this, too. Is there any plan to add more codes?

**Comment by whyrusleeping** [comment]
I think that we should instead do something like manpages do for exit status. See `man grep` or `man man` and look for `EXIT STATUS`

**Comment by RichardLitt** [comment]
How does that look?

**Comment by whyrusleeping** [comment]
LGTM

**Comment by Kubuxu** [comment]
LGTM

**Pull request merged**
