### PR TITLE
mk: add tarball support

### PR DESCRIPTION
**Pull request by Kubuxu**
You can create tarball by running: go-ipfs-source.tar.gz

License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by Kubuxu** [comment]
Still making small improvements.

**Comment by Kubuxu** [comment]
I should be finished.
Building out of the GOPATH is quite hard so I gave up on it for time being.

**Comment by Stebalien** [comment]
@Kubuxu where?

**Comment by Kubuxu** [comment]
`--local` puts gx deps under `vendor`: https://github.com/ipfs/go-ipfs/pull/4920/files#diff-ed297a84ee3216a4c453668f358a4895R17

**Pull request merged**
