### PR TITLE
Maint/fuse

### PR DESCRIPTION
**Pull request by cryptix**
Update `bazilion.org/fuse` to use latest `Node.Attr` function signature. (Context and errors, yey!)

### CODE REVIEW

**Comment by cryptix** [comment]
@whyrusleeping found some unmount issue in the sharness tests, I think.

**Comment by whyrusleeping** [comment]
yeah, i'm really not sure whats going on here: https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0030-mount.sh#L30

**Comment by whyrusleeping** [comment]
although it is unrelated (i beleive) to this PR

**Comment by cryptix** [comment]
I also don't see any changes to exit/unmount behaviour in the shortlog:

```
~GOPATH/src/bazil.org/fuse:master$ git shortlog 48c34fb7780b88aca1696bf865508f6703aa47f1..e4fcc9a2c7567d1c42861deebeb483315d222262
Tommi Virtanen (8):
      Remove dead code
      Make saveLookup take Context, return error
      Make serveNode.attr take Context, return error
      Make nodeAttr take Context, return error
      API change: Move attribute validity time inside Attr
      Set attribute validity default time in one place
      API change: Attr method takes Context, returns error
      Set LookupResponse validity times up front, instead of after the handler

```

**Comment by jbenet** [comment]
@cryptix these are in two different commits, will surely will not pass. squash? 

_every commit must pass_.

**Comment by cryptix** [comment]
I pushed the first one before I knew of the 2nd API change, they should both pass. I can squash as well and update the commit msg with the upstream changes.

**Comment by jbenet** [comment]
@cryptix +1 to squash

**Pull request merged**
