### PR TITLE
The conquest of El Cid, Pt. 2

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
weird... for some reason the gx install is getting skipped on the osx sharness builds... uhhh

**Comment by whyrusleeping** [comment]
Was a weird CI fluke. moving on.

**Comment by kevina** [comment]
@whyrusleeping I just know that once this is merged it going to create another round of not so nice conflicts for me to resolve in #2634 :slightly_frowning_face:

**Comment by whyrusleeping** [comment]
@kevina it shouldnt be too bad. I can handle them if you like. The biggest thing to keep in mind is that you won't be able to compare keys/cids with `==` anymore. (theres a `.Equals` method).

**Comment by RichardLitt** [comment]
@whyrusleeping I'm curious what this is, besides a ridiculously long epic poem about a Spaniard. What does Cid stand for, and why is it replacing multihash everywhere?

**Comment by whyrusleeping** [comment]
@RichardLitt https://github.com/ipld/cid

**Pull request merged**
