### PR TITLE
Merge release v0.6.0

### PR DESCRIPTION
**Pull request by aschmahmann**

### CODE REVIEW

**Comment by Stebalien** [comment]
Ok, so rebase and merge doesn't work because it will actually _rebase_ on master (which will destroy the merges). There is no "fast forward merge" on github. I just reset the master branch to this branch and pushed.

**Comment by RubenKelevra** [comment]
> Ok, so rebase and merge doesn't work because it will actually _rebase_ on master (which will destroy the merges). There is no "fast forward merge" on github. I just reset the master branch to this branch and pushed.

Well, you can always rebase/merge via console and push it to github :)

**Comment by RubenKelevra** [comment]
@Stebalien wrote:

> Ok, so rebase and merge doesn't work because it will actually _rebase_ on master (which will destroy the merges). There is no "fast forward merge" on github. I just reset the master branch to this branch and pushed.

Well, you can always rebase/merge via console and push it to github :)

**Comment by Stebalien** [comment]
I needed to preserve the merge already present on this branch, making it look like a fast-forward merge to master.

**Pull request merged**
