### PR TITLE
feat(cmd/ls): link name removes invisible char

### PR DESCRIPTION
**Pull request by chenminjian**
refs: #5887 

License: MIT
Signed-off-by: chenminjian <727180553@qq.com>

### CODE REVIEW

**Comment by schomatis** [comment]
> we might use `strconv.QuoteToASCII` for strings that need escaping

Agreed.

Do we allow this kind of names in the first place? Is there any character whitelist for UnixFS names? (From what I've seen in the code I think not; is the new UnixFSv2 spec considering it?)

**Comment by magik6k** [comment]
cc @mikeal @warpfork

**Comment by Stebalien** [comment]
Take a look at https://github.com/ipld/specs/issues/84 and https://github.com/ipfs/unixfs-v2/issues/3. As far as I know, there isn't a complete proposal. However, UnixFSv2 will have restrictions.

I really don't know the best way to handle existing files (escaping sounds promising but we have to be careful). `ls` uses a weird bash-like escaping.

**Comment by chenminjian** [comment]
Ok, I will look at those discussions first.

**Comment by schomatis** [comment]
> Ok, I will look at those discussions first.

Those references were mostly for my question, you needn't care about those design decisions that escape the scope of this PR, you can definitely check them out if you're interested but I think we (i.e., `go-ipfs` team) should settle for a temporary solution while UnixFSv2 is in the oven.

**Comment by Stebalien** [comment]
(closing as we'll have to rethink this a bit)

**Pull request closed without merging**
