### PR TITLE
gx: update go-multihash

### PR DESCRIPTION
**Pull request by Stebalien**
Blocked on:

* [x] https://github.com/ipfs/go-ipfs/pull/4455 (broken)
* [x] A gx update of go-ipfs-cmdkit in go-ipfs-cmds.
* [x] https://github.com/ipfs/go-ipfs/pull/4398 (go 1.9)
* [x] https://github.com/ipfs/go-ipfs-cmds/pull/46
* [x] https://github.com/ipfs/go-ipfs-cmds/pull/44

**Shiny ✨**:

* Fewer allocations when parsing multiaddrs (and when dialing). This should significantly reduce CPU usage when using the DHT.
* Default identity hash length to -1 (auto). Was 32 bits.
* Fixes websocket goroutine leak: https://github.com/libp2p/go-ws-transport/issues/21
* CID prefix constructor (🎉). You can now make CIDs by calling `cid.NewPrefixV1(cid.DagCBOR, mh.SHA_256).Sum(data)`. (TODO: Make go-ipfs actually use this, it's a lot nicer than constructing these manually).
* cmds fixes: #4360, #4436, https://github.com/ipfs/go-ipfs-cmds/pull/46, https://github.com/ipfs/go-ipfs-cmds/pull/44

### CODE REVIEW

**Comment by Stebalien** [comment]
Depends on go 1.9.

**Comment by Stebalien** [comment]
There's a deadlock somewhere in the commands library now. Reproducible by running `t0110-gateway.sh`. Test 31 fails ("refs IPFS directory file through readonly API succeeds").

**Comment by Stebalien** [comment]
Possibly relevant error:

```
expecting success: 
    test_must_fail ipfs repo gc --stream-errors 2>&1 | tee repo_gc_out &&
    grep -q "Error: could not retrieve links for $LEAF1" repo_gc_out &&
    grep -q "Error: could not retrieve links for $LEAF2" repo_gc_out &&
    grep -q "Error: garbage collection aborted" repo_gc_out
  
Error: could not retrieve links for QmSijovevteoY63Uj1uC5b8pkpDU5Jgyk2dYBqz3sMJUPc: merkledag: not found
Error: could not retrieve links for QmTbPEyrA1JyGUHFvmtx1FNZVzdBreMv8Hc8jV9sBRWhNA: The block referred to by 'QmTbPEyrA1JyGUHFvmtx1FNZVzdBreMv8Hc8jV9sBRWhNA' was not a valid merkledag node
Error: json: cannot unmarshal number into Go value of type commands.GcResult

not ok 48 - 'ipfs repo gc --stream-errors' should abort and report each error separately

#	
#	    test_must_fail ipfs repo gc --stream-errors 2>&1 | tee repo_gc_out &&
#	    grep -q "Error: could not retrieve links for $LEAF1" repo_gc_out &&
#	    grep -q "Error: could not retrieve links for $LEAF2" repo_gc_out &&
#	    grep -q "Error: garbage collection aborted" repo_gc_out
```

**Comment by Stebalien** [comment]
> Possibly relevant error

I couldn't reproduce this error after running these tests for several (4?) hours on repeat. If I had to hazard a guess, I'd say that this was caused by a bug in the HTTP streaming implementation. I'm guessing it returned the final 0 instead of treating it as a length.

---

I believe this is ready to merge.

**Comment by whyrusleeping** [comment]
Wooo! thanks @Stebalien !

**Pull request merged**
