### PR TITLE
Test repeat in 10 sec: increase check frequency tenfold

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by jbenet** [comment]
@rht thanks!

**Comment by rht** [comment]
Ok will at least replace with ```test_seq```.

The tests in sharness are meant to be passed by the node & python implementation, right? 
The granular check didn't cut the test time that much, so now I am in favor for integer sleep (and so no boilerplate dependency for other implementation). Unless absolutely necessary.

**Comment by rht** [comment]
I wonder if there is a checker for sh for POSIX compliance.

**Comment by chriscool** [comment]
In Git test_seq uses Perl but we don't want to depend on Perl I think.

**Comment by rht** [comment]
e.g. debian posh

**Comment by chriscool** [comment]
Unfortunately it looks like http://www.shellcheck.net/ doesn't check for POSIX compliance.

**Comment by rht** [comment]
Also shellcheck is less portable than perl (no binary build in https://github.com/koalaman/shellcheck).

I think any of posh, dash, bsh is sufficient to check for POSIX compliance.
With dash being the most available everywhere (I can't find posh in yum/rpm/homebrew. I didn't check for bsh though).

**Comment by jbenet** [comment]
> The best way if we really want to sleep for less than a second might be to write or find a go program that sleeps for the specified amount of time. It might use: http://golang.org/pkg/time/#Sleep

Let's do this. The fractional seconds add up. I'd like to have our tests wait as little time as we can make them.

**Comment by rht** [comment]
What about ```perl -MTime::HiRes -e 'sleep(0.1)'``` + ```test_seq```?
Since sharness already assumes that perl exists.
And 0.1s is an order of magnitude longer than the load time concern in http://stackoverflow.com/questions/7757814/how-to-sleep-a-random-fraction-of-a-second-in-posix-shell.

And what about reusing the test for other lang implementation?

**Comment by chriscool** [comment]
Where does sharness assumes that perl exists?

Greping for perl, I found only:
```
test/3nodetest/bin/save_logs.sh:STRIP="perl -pe 's/\e\[?.*?[\@-~]//g'"
```
which is not part of sharness.

**Comment by rht** [comment]
Ah right, it is git test that uses perl, while sharness is pure shell.

Hence any util that is not fully portable is to be written in go?
Including seq (and curl)?

**Comment by chriscool** [comment]
@rht yeah we often write some small utils in go, when we need them and there is no easy way to have them in POSIX shell.
About seq we can implement test_seq in POSIX shell using expr.
About curl, for now we accept that we depend on it, but the long term goal is to replace it with a go binary.

**Comment by chriscool** [comment]
See PR #1329 for test_seq  in POSIX shell using expr.

**Comment by chriscool** [comment]
About sleeping for some milliseconds there is now, shamelessly stolen from go-random:

https://github.com/chriscool/go-sleep

**Comment by jbenet** [comment]
@chriscool :+1:

**Comment by chriscool** [comment]
By the way after sleeping a bit on it myself :-) I think I will rename it soon like "go-millisleep".

**Comment by jbenet** [comment]
haha, i like it. (maybe can use seconds but allow fractions. (i.e. parse it as a time.Duration))

**Comment by rht** [comment]
Which one is usually preferable: ```sleep 0.1```, ```gosleep 0.1``` (like golint), or ```go sleep 0.1```?

**Comment by jbenet** [comment]
I'd say:




sleep 0.1




But this may clash with other tools so another name is ok. Don't use "go sleep" as that should only be a tool part of the go distribution 



—

**Comment by cryptix** [comment]
Like this a lot.

I opened PR chriscool/go-sleep#1 to use `time.ParseDuration()` instead. `go-sleep 2s` is much easier to approach for new people IMHO.

**Comment by rht** [comment]
```go sleep 0.1```!# This is all for the want of the machines to sleep less and less. For the same reason we want an ever faster in-time compiler.

**Comment by chriscool** [comment]
I merged @cryptix's PR so now it is `sleep 100ms`, but I think I will rename the command to `go-sleep`.

**Comment by chriscool** [comment]
I renamed it `go-sleep` as it is the most logical given the name of the repo.

**Pull request merged**
