### PR TITLE
Switched to amd64 version of ipfs

### LINKED ISSUE #2149: Docker out of memory crash (32 bit binary used)
It seems like the Docker image uses a [32 bit ipfs binary](https://github.com/ipfs/go-ipfs/blob/master/Dockerfile#L18).

This causes out-of-memory crashes when I import many files at once, for instance: [crash.txt](https://github.com/ipfs/go-ipfs/files/76231/crash.txt).

Is there any reason for not using a 64 bit binary?

### PR DESCRIPTION
**Pull request by Luzifer**
- Also cleaned the Dockerfile a bit and made it more easy to read.
- Also moved the VOLUME statement (refs #1804)
- Includes #2169
- fixes #2149

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This looks good to me, but i'm not any good at docker stuff. @lgierth CR here?

**Comment by lgierth** [comment]
LGTM!

**Comment by rht** [comment]
Reminder to rebase.

**Comment by Luzifer** [comment]
As we are now (#2212) building ipfs inside the container it should be amd64… Needs verification, afterwards this can be closed… Well… This can be closed anyway…

**Pull request closed without merging**
