### PR TITLE
make: be smarter about downloading running gx install

### PR DESCRIPTION
**Pull request by Kubuxu**
this might have unwanted side effect but I can't see any

//cc @chriscool 

License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by lgierth** [comment]
I'm not generally opposed to this, but I'm wondering what the "why" is. Is it that gx is too noisy? Then it should get a quiet mode instead, which only prints stuff if actual work is being done.

I can see an unwanted side effect of this PR which is that gx won't have a chance to verify the dependency files on disk -- they might have been legitimately deleted, some bit might have flipped, etc.

I'm not sure it's doing that currently, but it's something worth considering.

**Comment by Kubuxu** [comment]
Noise is one of the reasons, other is that other is that in 99% of cases it is unneded and it inflates rebuild time by 10% in my case.

Checking the dependencies is good point.

**Comment by chriscool** [comment]
I think there is no good reason to skip the go_check and the path_check targets. They are not related to package.json at all and they depend on things like the go version and environment variable that could change and that are important to check every time we build.

**Comment by Kubuxu** [comment]
Closing it for time being, I will rethink it.

**Pull request closed without merging**
