### PR TITLE
Fix whitespace discrepency in security-notes

### PR DESCRIPTION
**Pull request by lytedev**
Just remove an extra space that found its way into one of the default text files. It bothered me, but I know it's a very minor thing - if it matters at all, even.

### CODE REVIEW

**Comment by lgierth** [comment]
Thanks! This is blocked by #2997

**Comment by whyrusleeping** [comment]
@lgierth assigning you here just to make sure we don't lose track of things

**Comment by whyrusleeping** [comment]
@lgierth could you take care of this?

**Comment by lgierth** [comment]
Hey @lytedev, I have another PR coming which also covers the security-notes, and I took care of the whitespace there. Thank you! :+1:

**Pull request closed without merging**
