### PR TITLE
Replace #3990: blocks: move block format to it's own repo

### PR DESCRIPTION
**Pull request by magik6k**
This continues #3990

### CODE REVIEW

**Comment by Stebalien** [comment]
Did I miss something? This PR is identical to #3990...

**Comment by whyrusleeping** [comment]
@Stebalien yeah, #3990 was on your repo (and not the main go-ipfs one) so we couldnt rebase it on our own. This is just your commits rebased on latest master, we didnt want to bother you asking for a rebase :)

**Comment by Stebalien** [comment]
Ah. Got it. Thanks :).

**Comment by Stebalien** [comment]
Waiting on https://github.com/ipfs/go-ipld-cbor/issues/16

**Comment by Stebalien** [comment]
The current test failure looks unrelated:

**test/sharness/t0130-multinode.sh:**

```
expecting success: 
			check_has_connection "$i" ||
			test_fsh cat "swarm_peers_$i"
		(B
> cat swarm_peers_3

not ok 7 - node 3 is connected(B
#	
#				check_has_connection "$i" ||
#				test_fsh cat "swarm_peers_$i"
#			
```

**Comment by Kubuxu** [comment]
Yes it is one of unrelated failures we are chasing for a long time.

**Comment by whyrusleeping** [comment]
LGTM!

**Pull request merged**
