### PR TITLE
docker: take -dev version suffix into account

### PR DESCRIPTION
**Pull request by lgierth**
The other commit makes sharness tests work with my symlinked-into-gopath setup.

### CODE REVIEW

**Comment by lgierth** [comment]
This fix is pretty important because it's making master green again!!11

**Comment by Kubuxu** [comment]
Could we just grep the version string with expected hash instead? This way if we choose other suffix (rc for example) it won't break again.

**Comment by lgierth** [comment]
Something like `sed -e s/(-\w)?//`?

**Comment by Kubuxu** [comment]
You could use `ipfs version --enc json` and parse it using sed:
`{"Version":"0.4.3-dev","Commit":"4fa85cc","Repo":"4","System":"amd64/linux","Golang":"go1.6.2"}`

**Comment by lgierth** [comment]
Updated it to parse from `ipfs version --enc json`, the quotes got waay complicated so heredoc we go :)

**Comment by whyrusleeping** [comment]
bashy bashy bashy bash. LGTM

**Pull request merged**
