### PR TITLE
Add boolean value to type assertion, for skipping assertion panic

### PR DESCRIPTION
**Pull request by ridewindx**
License: MIT
Signed-off-by: Jason Chang ridewindx@163.com

### CODE REVIEW

**Comment by Stebalien** [comment]
Where did you run across this issue? The parent should *always* be a pointer to a directory, as far as I know.

**Comment by ridewindx** [comment]
@Stebalien the parent field of Directory may be the *Root:
`rval, err := NewDirectory(parent, node.String(), node, root, ds)`
[https://github.com/ipfs/go-ipfs/blob/5622cc5bb34ddccd2eee7116700bbaf81940d8d4/mfs/system.go#L93](url)
But *Root is obviously not a *Directory. Uh, is that right?

**Comment by Stebalien** [comment]
Oh. I see. Um, yeah... that can't currently do anything *but* panic (it's currently dead code). Thanks for catching this!

I'd rather use a type switch and *panic* if the parent is neither a directory nor root:

```go
switch parent := cur.parent.(type) {
case *Directory:
	cur = parent
	// ...
case *Root:
	return path
default:
	panic("directory parent neither a directory nor a root")
}
```

**Comment by Kubuxu** [comment]
Could you also add simple unit test for it?

**Pull request closed without merging**
