### PR TITLE
fix pinning

### PR DESCRIPTION
**Pull request by whyrusleeping**
Addresses #1008

### CODE REVIEW

**Comment by jbenet** [comment]
LGTM. @whyrusleeping could you add a test case for this? it's a serious problem, if it re-emerges. would be good to protect against it.

**Comment by whyrusleeping** [comment]
@jbenet I think trying to write a test case where a pin fails halfway through is going to be more trouble than its worth. We have no easy (or even 'somewhat easy') way of reliably killing a daemon halfway through a 'pin' operation. Its another timing nightmare test waiting to happen

**Comment by jbenet** [comment]
@whyrusleeping can't we:

- create an object that links to one object that exists locally and one that doesn't
- run the pin
- either kill it 1s later (yes, timing problem), or wait until it times out (we maybe could lower the timeout with an env var or something) 
- check the pinning result

this is probably useful to test what happens when on a pin failure case

**Comment by jbenet** [comment]
@whyrusleeping added tests that surface the problems

**Comment by whyrusleeping** [comment]
@jbenet after reading through the add command, it looks like we pin each file of a recursive add recursively, so:
```
dir/   <- pinned -r
    a  <- pinned -r
    b  <- pinned -r
```

But running `ipfs pin rm -r dir-hash` only runs Unpin-recursive(dirhash). leaving the children still pinned recursively. what is the expected behaviour here?

**Comment by jbenet** [comment]
- [x] fixed `pin lists look good`
- [ ] `some objects are still there` exits with `Error: context deadline exceeded` ?? looks like `gc` is resolving objects instead of just checking pins? oh i guess it needs to resolve objects?

**Comment by jbenet** [comment]
@whyrusleeping pushed more to the test case. i'm pretty sure this found problems with pinning.

**Comment by whyrusleeping** [comment]
@jbenet this is RFM

**Pull request merged**
