### PR TITLE
In blockstore tests treat Close and Closing the same way

### LINKED ISSUE #2762: TestAllKeysRespectsContext fails randomly
http://ci.ipfs.team:8111/viewLog.html?buildId=2160&buildTypeId=GoIpfs_CiTests&tab=buildLog#_

```
[19:06:48][Step 3/4] TestAllKeysRespectsContext
[19:06:48][TestAllKeysRespectsContext] 	blockstore_test.go:194: should not be closed
[19:06:48][TestAllKeysRespectsContext] TestValueTypeMismatch
[19:06:48][TestAllKeysRespectsContext] TestReturnsErrorWhenSizeNegative
[19:06:48][TestAllKeysRespectsContext] TestRemoveCacheEntryOnDelete
[19:06:48][TestAllKeysRespectsContext] TestElideDuplicateWrite
[19:06:48][TestAllKeysRespectsContext] FAIL
[19:06:48][TestAllKeysRespectsContext] exit status 1
[19:06:48][TestAllKeysRespectsContext] FAIL	github.com/ipfs/go-ipfs/blocks/blockstore	0.010s
[19:06:48][TestAllKeysRespectsContext] Process exited with code 1
[19:06:49][TestAllKeysRespectsContext] Step go tests (Command Line) failed
```

### PR DESCRIPTION
**Pull request by Kubuxu**
This should prevent race condition that caused https://github.com/ipfs/go-ipfs/issues/2762

Resolves #2762 

License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
I'm not sure i follow how this solves the issue, could you elaborate?

**Comment by Kubuxu** [comment]
If the cancel is run in the same goroutine then it will send signal to the already waiting goroutine which will cause the goprocess to close. By running it in separate goroutine we should give ourselves enough time to reach the `select` statement before the `cancel` causes the goprocess to close.

**Comment by Kubuxu** [comment]
This fix doesn't work as I thought it would.
As I am able to replicate the issue I might be able to fix it now.

**Comment by Kubuxu** [comment]
I've changed the approach as that one was not working and I was able to replicate the issue by repeatability running tests.

**Comment by Kubuxu** [comment]
Ok, it looks like it isn't test inconsistency after all. I am getting failures at https://github.com/ipfs/go-ipfs/pull/2832/files#diff-89a41509a8389c8bc3dbf7594aa13416R192 now.

**Pull request closed without merging**
