### PR TITLE
Updated Bash complete script

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
Some minor bug still exist but not breaking.
Everything is marked with "TODO" inline the script.

License: MIT
Signed-off-by: Elias Gabrielsson <elias@benefactory.se>

### CODE REVIEW

**Comment by EliasGabrielsson** [comment]
Replacing old pull request. @Kubuxu

**Comment by Kubuxu** [comment]
Hmm, zsh has bash completion compat, which means that I can give it actual use test. I will use it for 1-2 days and get back to you.

Thanks again.

**Comment by Kubuxu** [comment]
Looks like it doesn't work well for complex completions so I will just run it in bash and test out.

**Comment by Kubuxu** [comment]
LGTM, only thing that I observed is that it doesn't support short options `-r` vs `--recursive` and so on but either way it is much much better than current completion.

Thank you very much.

@whyrusleeping good for merge.

**Comment by EliasGabrielsson** [comment]
I have intentionally not implemented short option. It's not a big deal to implement if its needed.

**Comment by Kubuxu** [comment]
Nah, I think in the bash's completion method it might cause more confusion than good.

**Comment by whyrusleeping** [comment]
Alright cool, will be good to finally have this in.

**Comment by EliasGabrielsson** [comment]
Under the development of the complete-script I have wonder how the script could be installed in an easy fashion way. 

`ipfs autocomplete install` - or similar,
a) Search for current shell, eg. `bash` / `zsh`. 
b) Search if there is a script available _somewhere_. How does `ipfs update` work, does it fetch things from github or by ipfs itself? Is version mapped to github versions?
c) Install script on default location based on OS and profilesettings. This can be tricky but I think its do able. An option could be to specify install location.

The `ipfs-install` could also keep track if the script have been installed and autoupdate it when ipfs gets updated by `ipfs-install`

What do you think?

**Comment by Kubuxu** [comment]
Usually it is package mangers that do this and I think it is good enough.

**Pull request merged**
