### PR TITLE
[WIP] doc: Files API

### PR DESCRIPTION
**Pull request by schomatis**
This is a work in progress, I don't have a clear idea of the final form of this document, for now it is placeholder for any information I want to provide to the user while studying the Files API. Much of that information may not ultimately belong here but for the ease of the development process I'm centralizing it all (to avoid raising many PRs scattered through different repos).

### CODE REVIEW

**Comment by nitishm** [comment]
@schomatis This is something I definitely feel comfortable doing. I have been using `dlv` with my IDE to follow the flow of `ipfs add`. (I should've really written it down yesterday. God dang!)
Where exactly do you want me to capture the flow ?

> Here is some (really incomplete) documentation about how we organize files in IPFS (any questions/clarifications you ask while reading that would be invaluable): https://github.com/ipfs/go-mfs#documentation.

I will add my thoughts and questions as I go through the code once again.

**Comment by schomatis** [comment]
Great!

> Where exactly do you want me to capture the flow ?

For now, open a separate PR (or issue, whatever feels best to write a simple document) tagging this milestone since I'm not sure I can give you permissions to push to this one.

**Comment by nitishm** [comment]
@schomatis How can I tag my issue #5858 with the milestone ?

**Comment by schomatis** [comment]
Closing in favor of https://github.com/ipfs/go-ipfs/pull/5864.

**Pull request closed without merging**
