### PR TITLE
Add Stackdriver export

### PR DESCRIPTION
**Pull request by anacrolix**
I'm using this to export traces to Stackdriver. I'd like some feedback. Perhaps the exporter Location and default sample rate can be taken from the environment, and the export only attempted if particular environment variables are set.

### CODE REVIEW

**Comment by magik6k** [comment]
Are there any discussions / issues linked to this?

**Comment by anacrolix** [comment]
@magik6k What sort are you referring to? There's efforts in filecoin to do tracing, and libp2p to tracing and metrics via OpenCensus.

**Comment by raulk** [comment]
@anacrolix – I believe @magik6k is referring to the attempt to introduce Stackdriver specifically. It's not clear to me the kind of feedback you are seeking.

**Comment by anacrolix** [comment]
I'd like to know if OC exporters could be supported, via environment flags, similar to as is done in this PR for Stackdriver.

**Comment by anacrolix** [comment]
I'll update this PR to be more general, to reflect how I've done this in other projects.

**Comment by magik6k** [comment]
Using env vars feels better.

What is the difference in binary size with this patch applied? Can this be made into a plugin?

**Comment by anacrolix** [comment]
@magik6k 
```
master              37757316
stackdriver-tracing 43943460
```

**Comment by anacrolix** [comment]
As a plugin, I wonder if having upstream projects in libp2p directly reference opencensus tracing will defeat the purpose (the dependencies will be pulled in anyway). In particular, while there is no OC tracing in libp2p yet, I think there will be soon, and the cost will already be paid to add that there. It may be possible to avoid that cost, by tapping into OC's `runtime/trace` support, but then we lose a lot of extra features there, and there'll need to be a lot of fiddly OC injection outside libp2p to regain the extra OC tracing features by consumers. I.e. everything that wants OC tracing enabled, will need to call out to the plugin before calling into anything related to libp2p.

**Comment by magik6k** [comment]
6MB is a lot, especially given that it isn't going to be used by 99.99% of users. Can we hide this behind a build tag, say `tracing`?

**Comment by Stebalien** [comment]
It looks like a almost all of the weight comes from the stackdriver exporter, not opencensus. Putting the stackdriver code in a plugin should help quite a bit.

**Comment by anacrolix** [comment]
Thanks @Stebalien that seems like the best solution.

**Comment by Stebalien** [comment]
(we'll reopen this when we pick this work back up)

**Pull request closed without merging**
