### PR TITLE
Revert da4a4ac and add more longDesc

### PR DESCRIPTION
**Pull request by RichardLitt**
This reverts most of the changes in da4a4ac, which were later found to be errorful. See https://github.com/ipfs/go-ipfs/pull/2657 for details.

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
Can you use revert commit for the da4a4ac changes and thus separate new changes?

**Comment by RichardLitt** [comment]
@Kubuxu I went through manually and looked at the diffs for the new ones. Would `revert` have done that automatically? I still think this should work.

**Comment by Kubuxu** [comment]
`git revert da4a4ac` would create commit that reverts the da4a4ac commit in full.

**Comment by RichardLitt** [comment]
This was more subtle, as I added some stuff.

**Comment by Kubuxu** [comment]
Yeah, but in that case you can create revert commit and commit that adds the changes.

**Comment by RichardLitt** [comment]
@Kubuxu Should I close this and reopen that?

**Comment by Kubuxu** [comment]
It is @jbenet call, as the PR is in response for his CR.

**Comment by jbenet** [comment]
@RichardLitt it will make it easier to understand the change if you do a revert commit and then your changes on top. pls thanks.

no need to close and reopen, you can `git push origin feat/undo-a4a4ac -f`

**Comment by jbenet** [comment]
Ask for git help if you get stuck rebasing

**Comment by RichardLitt** [comment]
I might need some git help, then. 

```
15:24 ~/src/ipfs/go-ipfs (feat/revert-da4a4ac) 🐕  git revert da4a4ac0bc26b80457f537b950c5e43130bce242
error: Commit da4a4ac0bc26b80457f537b950c5e43130bce242 is a merge but no -m option was given.
fatal: revert failed
15:25 ~/src/ipfs/go-ipfs (feat/revert-da4a4ac) 🐕  git revert da4a4ac0bc26b80457f537b950c5e43130bce242 -m 2
On branch feat/revert-da4a4ac
nothing to commit, working directory clean
```

Using git revert doesn't seem to do anything. I could manually try and revert the two parent commits?

**Comment by Kubuxu** [comment]
The mainline `-m` is 1 in this case. 
You have to also remove existing changes from the branch, you can use `git reset --hard origin/master` for that, warning it will remove the changes you made.

Also it looks like `revert` in this cases gives quite an ugly looking revert conflict but it isn't that bad really.

**Comment by RichardLitt** [comment]
Interesting! How do you know that it `-m` is 1? The PR has two commits:

screen shot 2016-09-11 at 9 33 44 am

**Comment by lgierth** [comment]
> Interesting! How do you know that it -m is 1? The PR has two commits:

**Comment by lgierth** [comment]
> Interesting! How do you know that it -m is 1? The PR has two commits:

Numbering starts at 1, ordering is mainline -> merged commit, and mainline is the commit on top of which the merge was made :)

**Comment by Kubuxu** [comment]
The commit you are reverting was created when the PR was merged, it wasn't the part of original PR. When it was merged two commits were joined into one chain, commit being HEAD of the `master` and commit being HEAD of your PR.

As you are reverting merge commit git asks you which commit chain that was merged in this merge commit is the "main" one, so it knows which commits chains from that merge to revert.

**Comment by RichardLitt** [comment]
Closing in favor o #3239. Will use as reference for that.

**Pull request closed without merging**
