### PR TITLE
update go-msgio dependency

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@jbenet one of your msgio commits that never merged into ipfs broke ipfs tests: https://github.com/jbenet/go-msgio/commit/d5bbf59d3c4240266b1d2e5df9dc993454c42011

**Comment by whyrusleeping** [comment]
fix in: https://github.com/jbenet/go-msgio/pull/11

**Comment by jbenet** [comment]
merged that, maybe rebase?

**Comment by whyrusleeping** [comment]
deps updated, RFM

**Pull request merged**
