### PR TITLE
Update link to ipfs installation guide

### PR DESCRIPTION
**Pull request by makevoid**
in Readme.md

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: da9d5ecd238ea17136ec6c9609a0a95fdd42cc74
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by jbenet** [comment]
Hey @makevoid thanks for the doc fix! 

Would you please update your commit message with the proper license trailers?

if you run this script from within the repo: https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh

and then:

```
git rebase -i origin/master  # this will rebase and should add the trailers
git push origin patch-1 -f  # force push to fix the commit
```
it should take <30sec, though understood there is much more cognitive complexity to this than there ought to be for a one-line fix. if you prefer, i'll do it manually.

**Comment by makevoid** [comment]
done, I hope to do a code PR in the future :D

**Comment by jbenet** [comment]
thanks @makevoid!

**Pull request merged**
