### PR TITLE
vendor notifier outside of go-ipfs

### PR DESCRIPTION
**Pull request by whyrusleeping**
was tired of seeing this test fail in CI.

We also use this only in one place, maybe we should find a better way? (that doesnt randomly fail under load?)
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping other stuff uses the notifier. i think it doesnt import it because it just matches the interface? (or something like that).

> maybe we should find a better way? (that doesnt randomly fail under load?)

i think we just need to fix that test to not be time based. better mocking. i'm at fault for all the time-based tests.

**Comment by jbenet** [comment]
it all has to do with the first part: https://travis-ci.org/ipfs/go-ipfs/jobs/71693808#L202 -- that's the problem.

**Comment by whyrusleeping** [comment]
@jbenet so do you think we need to try and fix the tests? and not vendor them externally?

**Comment by jbenet** [comment]
- i'm +1 on external vendoring.
- but i'm also +1 on fixing the test.

**Comment by jbenet** [comment]
update here? in light of other PR?

**Comment by whyrusleeping** [comment]
@jbenet sorry, been distracted from this one. can take a look at fixing these tests.

**Comment by rht** [comment]
Or make it less frequent.

On a spare server, run:
```shell
cd $GOPATH/src/github.com/ipfs/go-ipfs/p2p/net/swarm
while true; do go test; sleep .5; done  
``

And characterize the mean of the fail frequency, then adjust https://github.com/ipfs/go-ipfs/blob/master/p2p/net/swarm/swarm_dial.go#L50 so that it will happen less frequently.

**Comment by whyrusleeping** [comment]
closing, old PR cleanup time.

**Pull request closed without merging**
