### PR TITLE
Reorged from jbenet/go-ipfs to ipfs/go-ipfs

### PR DESCRIPTION
**Pull request by hosh**
Fixes: https://github.com/ipfs/go-ipfs/issues/990

WIP, do not merge

1 test failing. See comment below.

### CODE REVIEW

**Comment by hosh** [comment]
All tests passes except for one test.

When initializing a new `ipfs`, the init docs gets loaded in there. For some reason, the `contact` file is not included when you run `ipfs refs local`. However, it is there when you run `ipfs refs $HASH_WELCOME_DOCS` (which is currently `Qmc8ZcdAUduQfC32oSXnLsUyDb7GNZ9rX4VjrtB4s212v4`

This is a a blocker 🚫

**Comment by jbenet** [comment]
```
i think hosh encountered a bug.
- make sure to move your local directory from jbenet/go-ipfs to ipfs/go-ipfs or go will hate you.
- make sure to "go install -a ./..." or old files may linger
- `cd test/sharness && make bin/ipfs && ./t0080-repo.sh`
- it should fail on `'ipfs refs local' no longer shows file`
- go into the trash dir and:

```sh
IPFS_PATH=.go-ipfs ipfs refs -r Qmc8ZcdAUduQfC32oSXnLsUyDb7GNZ9rX4VjrtB4s212v4
# shows QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y

IPFS_PATH=.go-ipfs ipfs cat QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y
# works

IPFS_PATH=.go-ipfs ipfs refs local
# doesn't show QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y -- wat1?
```

wat.

**Comment by whyrusleeping** [comment]
well... this test failure is block all my development. Can we just merge it and file a bug?

**Comment by jbenet** [comment]
Closing in favor of #993

**Pull request closed without merging**
