### PR TITLE
update go-peerstream to newest version

### PR DESCRIPTION
**Pull request by whyrusleeping**
I was trying to rebase dev0.4.0 on master, but it was difficult to do without first doing this. So i'm making this PR separate.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
i'd actually prefer to merge https://github.com/jbenet/go-stream-muxer/pull/3 so i can update this PR before merging.

**Comment by whyrusleeping** [comment]
Not sure why godeps sucks so hard and cant figure out how to vendor yamux...

**Comment by jbenet** [comment]
@whyrusleeping does this break compatibility? i guess not because it's still using yamux directly, right?

**Comment by whyrusleeping** [comment]
nope! still compatible

**Pull request merged**
