### PR TITLE
cmds/add: use dagutils.Editor, like patch

### PR DESCRIPTION
**Pull request by jbenet**
This changes the pin behavior. It uses the filenames given through
the api, and allows files to be streamed faltly (not a hierarchy),
which is easier for other things (like vinyl in node-ipfs-api land).
Files can also be entirely out of order, and the garbage intermediate
directories will not be pinned (gc-ed later).

License: MIT
Signed-off-by: Juan Batiz-Benet <juan@benet.ai>

---

WAAAY easier to do the vinyl fs stuff. no multipart madness.

thanks @whyrusleeping for making good things (dagutils.Editor).

cc @diasdavid @mappum

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Can we do this on top of dev0.4.0? there are a lot of changes in there to this part of the code, would make my life a lot easier.

**Comment by jbenet** [comment]
@whyrusleeping we need this asap for electron-app -- for CCC.

we could just rebase 0.4.0 on top of a revert of this commit, and implement the change on top of 0.4.0 separately (it's a nice hack). the danger is this very quickly gets out of sync.

**Comment by whyrusleeping** [comment]
> @whyrusleeping we need this asap for electron-app -- for CCC.

okay... i guess we can merge it. What is it needed for for the electron app?

also, the tests dont seem to pass.

**Comment by diasdavid** [comment]
:+1: 😀

**Comment by jbenet** [comment]
@whyrusleeping:

```
This changes the pin behavior. It uses the filenames given through
the api, and allows files to be streamed faltly (not a hierarchy),
which is easier for other things (like vinyl in node-ipfs-api land).
Files can also be entirely out of order, and the garbage intermediate
directories will not be pinned (gc-ed later).

The changes also mean the output of add has changed slightly-- it
no longer shows the local path added, but rather the dag path
relative to the added roots. This is a small difference, but changes
tests.

The dagutils.Editor creates a lot of chaff (intermediate objects)
along the way. Wonder how we might minimize the writes to the
datastore...

This commit also removes the "NilRepo()" part of the --only-hash
mode. We need to store at least in an in-mem repo/datastore because
otherwise the dagutils.Editor breaks.
```

One bad part about this is that the intermediate, temporary objects get (a) written to disk, and (b) added to bitswap (and thus advertised).

@whyrusleeping could you make a version of dagutils.Editor that doesn't write to the DagService until the very end? (with a "Finalize" or something)

**Comment by jbenet** [comment]
that's kind of hard because then the dag needs to be kept in memory... :/

**Comment by whyrusleeping** [comment]
> @whyrusleeping could you make a version of dagutils.Editor that doesn't write to the DagService until the very end? (with a "Finalize" or something)

Sure, can do. I want this for my dag diffing stuff too.

**Pull request merged**
