### PR TITLE
allow cid format selection in block put command

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu what do you mean?

**Comment by Kubuxu** [comment]
You had to change the hashes in the tests, which means that hashes outputted by `ipfs block` API have changed.

**Comment by whyrusleeping** [comment]
Ah, yeah. Youre referring to setting the default format value to be "v0". That makes sense to me.

**Comment by whyrusleeping** [comment]
@Kubuxu there, now the default behaviour doesnt change. Good catch

**Pull request merged**
