### PR TITLE
Linted object diff help text

### PR DESCRIPTION
**Pull request by RichardLitt**
Also used `>` instead of `$`, per the guidelines.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90aef288b306e092bca60664e0833233437bf9e3
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by RichardLitt** [comment]
Actually, I can't figure this out. How do you get from `ls foo` to the output? 

```
   > ls foo
   bar baz/ giraffe
```

**Comment by whyrusleeping** [comment]
generally in examples such as this, `ls` is used in examples to show the user that we are going to be working with a directory containing some prexisting files.

**Comment by RichardLitt** [comment]
Ahaha, wow. Didn't think to make multiple files. My bad. Wow.

**Comment by RichardLitt** [comment]
Well, still should be good to merge.

**Comment by whyrusleeping** [comment]
@RichardLitt you broke the tests, see the CI output

**Pull request merged**
