### PR TITLE
Add "privkey" parameter to ipfs name publish

### PR DESCRIPTION
**Pull request by gamemanj**
This allows publishing to an arbitrary IPNS private key.
This is mostly meant for use by blockchain-like applications, but it's possible (if a bit inconvenient) for users to use it to.
The IPNS key QmdeadvG5GdPWiea2h7jAsZdVyxawY714KDWSDBAaRgkAD is used in documentation, and the private key included for it is valid.
The test of the publish w/privkey can't try resolving, because someone may deliberately change what it resolves to to break tests.
The test does perform an ipfs add in order to make sure there's something to publish, I'm not sure if this is a major problem. It's probably better that it be a hash, but I tried that, and it didn't work.
Also, I wasn't sure where to put the keypair, so I put it in the hashes test lib, since that seemed better than any other place I could've put it.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: da466e4cf27275b04b0a4abdb3970d4a30742672
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: 846848c786b38da443b9612ea780854887934c74
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
@gamemanj this sort of functionality is going to be implemented later, after dev0.4.0, in the form of the keystore. https://github.com/ipfs/specs/tree/master/keystore

**Comment by gamemanj** [comment]
Which is good! But what if the key isn't in the keystore (say, if it's a key used by an application?)

**Comment by jbenet** [comment]
the keystore should implement delegation to other systems. and yeah the CLI could provide an interface to pass in a key, or an agent to call to sign. (not sure how this is done in a bunch of other systems yet, havent surveyed, but we should be doing something good and standard here)

**Comment by jbenet** [comment]
@gamemanj thanks for the PR, maybe rebase on top of 0.4.0 ?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3d55feb3b1f2fae240323ce60d8bcf387116e458
  * Your subject line is longer than 80 characters

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by gamemanj** [comment]
The syntax here doesn't match with the syntax dev0.4.0...
Either this should be closed, or an alternate syntax suggested.
Oh well.

**Comment by jbenet** [comment]
@gamemanj why not? which syntax? not understanding

**Comment by gamemanj** [comment]
@jbenet See: https://github.com/ipfs/go-ipfs/blob/dev0.4.0/core/commands/publish.go
It would have to try parsing it as either a privkey or an IPFS name, so we'd end up with the arg acting as both a privkey parameter and an IPNS key parameter, depending on what it successfully parsed as... IDK if that's the way stuff "should" be done - which error takes priority if neither parses, for example?

**Comment by jbenet** [comment]
cc @whyrusleeping for feedback on the last points

**Comment by whyrusleeping** [comment]
this is primarily a UX issue. I'm not sure how best to do this interface. My first thought it to have a flag that specifies a file name containing the key. I dont like having it as an argument because of how 'in the open' that is. I dont want to encourage people to do things that might leave their private keys in various .shell_history files all over the place.

**Comment by jbenet** [comment]
could be identifiers used to retrieve the key from somewhere. a filename should be valid. but also other things like key agents. any standard protocols that are good there?

**Comment by whyrusleeping** [comment]
could use ssh-agent in some way. thats what i use for key management on my system.

**Comment by gamemanj** [comment]
As it is, until the syntax and details can be worked out, adding this is a bit of a difficulty.
In actual practical terms, once you've worked out the syntax, it should be a few lines.
Just keep in mind: From an API-user perspective, there needs to be a way to put in a private key, without any keystore abstraction or such. From a CLI/GUI-user perspective, the keystore should be used.
Until some syntax, entry method, or something is worked out that fulfills both of these requirements, may as well close PR.

**Pull request closed without merging**
