### PR TITLE
Gpe ccd06e5b66621568f7b66d9867779eaef843a75f

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by jbenet** [comment]
@rht no need to make PRs? it should be enough to push using `git-push-each` directly to this repo? https://github.com/jbenet/git-push-each/ 

i use it like:

```
git checkout mybranch
git cherry origin/master | git push-each
```

**Comment by jbenet** [comment]
the thing is that a PR notifies everyone watching this repo. pushing a branch does not

**Comment by rht** [comment]
ic

**Comment by jbenet** [comment]
@rht sorry about that, i should've been more clear. `git-push-each` is a weird workaround a github bug with its own bugginess.

**Pull request closed without merging**
