### PR TITLE
add circleci support

### PR DESCRIPTION
**Pull request by jbenet**

### CODE REVIEW

**Comment by jbenet** [comment]
Fixed IPv6 suppor on Circle-CI. needed:

```yml
dependencies:
  pre:
    # setup ipv6
    - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0 net.ipv6.conf.all.disable_ipv6=0
```

**Comment by jbenet** [comment]
Interesting failure: https://circleci.com/gh/ipfs/go-ipfs/18 

```
> diff -u expected_daemon actual_daemon
--- expected_daemon	2015-05-30 05:19:38.485674000 +0000
+++ actual_daemon	2015-05-30 05:19:37.753674000 +0000
@@ -1,5 +1,5 @@
 Initializing daemon...
-initializing ipfs node at /home/ubuntu/go-ipfs/test/sharness/trash directory.t0060-daemon.sh/.ipfs
+initializing ipfs node at /home/ubuntu/.go_project/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0060-daemon.sh/.ipfs
 generating 2048-bit RSA keypair...done
 peer identity: QmRwRKHMhXdBabdc7tv9TvDbznQggkTrW5a4GXGzmxGXmG
 to get started, enter:
```

Looks like `$(pwd)` isn't cutting it. weird links? cc @chriscool @cryptix

**Comment by whyrusleeping** [comment]
circleCI needs to run tests with the nofuse tags set

**Comment by jbenet** [comment]
> circleCI needs to run tests with the nofuse tags set

i think that's a different problem, no?

i set the `TRAVIS` env var. maybe also need another.

**Comment by jbenet** [comment]
> circleCI needs to run tests with the nofuse tags set

is that the bug here though? seems different

**Comment by chriscool** [comment]
Yeah it look like a path or Iink related bug. I will have a look on Saturday or Sunday.

**Comment by jbenet** [comment]
@chriscool any leads? 

maybe a symlink issue? `ipfs` thinks it is in a different path than the sharness tests. odd because `ipfs init` is called by the same shell.

```diff
> diff -u expected_daemon actual_daemon
--- expected_daemon	2015-05-30 05:19:38.485674000 +0000
+++ actual_daemon	2015-05-30 05:19:37.753674000 +0000
@@ -1,5 +1,5 @@
 Initializing daemon...
-initializing ipfs node at /home/ubuntu/go-ipfs/test/sharness/trash directory.t0060-daemon.sh/.ipfs
+initializing ipfs node at /home/ubuntu/.go_project/src/github.com/ipfs/go-ipfs/test/sharness/trash directory.t0060-daemon.sh/.ipfs
 generating 2048-bit RSA keypair...done
 peer identity: QmRwRKHMhXdBabdc7tv9TvDbznQggkTrW5a4GXGzmxGXmG
 to get started, enter:
```

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c3f6369b2fc39b8edc7c5da4440f5f1222cde50b
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by chriscool** [comment]
Exporting IPFS_PATH is enough to make the CircleCI sharness tests pass.

**Comment by jbenet** [comment]
@chriscool great stuff!

**Comment by chriscool** [comment]
@jbenet is there anything else I can do about this?
Your commit is missing a License and a Signed-off-by trailer but I think it's better if you add them yourself.

**Comment by chriscool** [comment]
One Travis test failed with "Error: context deadline exceeded":

```
expecting success: 
	export IPFS_PATH="$IPTB_ROOT/3" &&
	NODE2_ID=`iptb get id 2` &&
	ipfs cat /ipns/$NODE2_ID > output
Error: context deadline exceeded
not ok 5 - cat that entry on a third node
#	
#		export IPFS_PATH="$IPTB_ROOT/3" &&
#		NODE2_ID=`iptb get id 2` &&
#		ipfs cat /ipns/$NODE2_ID > output
#	
```

**Comment by jbenet** [comment]
@chriscool this is great, thanks. Will fix, force-push and merge

**Comment by jbenet** [comment]
circleci support merged! thanks very much @chriscool  \o/

**Pull request merged**
