### PR TITLE
smart bitswap requesting

### PR DESCRIPTION
**Pull request by whyrusleeping**
This PR allows bitswap to watch for popular keys on the network and request them in hopes of rehosting later. this is still somewhat WIP, but im looking for some feedback.

### CODE REVIEW

**Comment by briantigerchow** [comment]
Good idea. Try to design it as an extension, rather than a built-in.

**Comment by whyrusleeping** [comment]
@briantigerchow thats a good idea, make it something passed into the bitswap constructor like an `Option`

**Comment by briantigerchow** [comment]
Even better would be to avoid the constructor entirely and create something that can be enabled after the core has be instantiated. The IPFSNode constructor is tangled up as it is, so the less branching that has to occur in there, the better.

**Comment by briantigerchow** [comment]
(Using PubSub...)

```Go
// in ReceivedMessage...
bs.notifications.PeerWants(k)
```

```Go
keys := bs.notifications.SubscribeToPeerWants()
// or let client provide channel
bs.notifications.SubscribeToPeerWants(keys)

// allow clients to stop listening
bs.notifications.UnsubscribeFromPeerWants(keys)
```

**Comment by whyrusleeping** [comment]
closing for now. Ill come back to this later.

**Pull request closed without merging**
