### PR TITLE
update dists path with 1.2.2 migrations

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
We might have one more dist fix as it seems that files aren't closed properly in time in the migration code in go-ds-flatfs.

**Comment by whyrusleeping** [comment]
@Kubuxu link to issue?

**Comment by whyrusleeping** [comment]
Got a confirmation from @lgierth that these migrations binaries work for upgrading the docker node gateways.

**Comment by whyrusleeping** [comment]
@Kubuxu :+1:  ?

**Pull request merged**
