### PR TITLE
delete useless  command `ipfs help`

### PR DESCRIPTION
**Pull request by kjzz**
fix issue #5557 

License: MIT
Signed-off-by: Kejie Zhang <601172892@qq.com>

### CODE REVIEW

**Comment by Stebalien** [comment]
I'd like to do this but our documentation literally says to use `ipfs help`. I think we're just going to have to improve it a bit.

**Comment by Stebalien** [comment]
https://docs.ipfs.io/introduction/install/

**Comment by Mr0grog** [comment]
So… should we update those docs to use `--help` if that’s the preferred form? Can someone file an issue on the docs repo if so?

**Comment by Stebalien** [comment]
I don't think either is really preferred. It's more that our current CLI library doesn't support `help` very well. However, this has now been *properly* fixed in #5573.

**Pull request closed without merging**
