### PR TITLE
t0080 improvements

### PR DESCRIPTION
**Pull request by chriscool**
This may not fix https://github.com/ipfs/go-ipfs/issues/2028.
But it might help us get more information when it fails.

### CODE REVIEW

**Comment by chriscool** [comment]
Here is the (unrelated) Travis-CI failure in t0230:

```
expecting success: 

		mkdir -p testdir &&

		echo "hello test" >testdir/test.txt &&

		ipfs add -r testdir &&

        curl -i "http://localhost:$PORT_API/api/v0/refs?arg=QmTcJAn3JP8ZMAKS6WS75q8sbTyojWKbxcUHgLYGWur4Ym&stream-channels=true&encoding=text" >actual_output

	

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by chriscool** [comment]
Circleci build also timed out but in t0040!

**Comment by rht** [comment]
@chriscool t0080, t0043, t0081, t0160 all contain the `tail -n1` race condition.

**Comment by jbenet** [comment]
> Perhaps "ipfs add x then get the last hash" can be wrapped in a function.

yes, sounds like a good idea. we could also make this into another output mode for `ipfs add`, which only outputs the root hash. (it's a common enough occurrence that forcing `| tail -n1` always is annoying). We could make `-q` do this, or use `-qq`*

* @whyrusleeping another reason why `-qq` is not great for `--silent`. there may be degrees of quiet before silent

**Comment by jbenet** [comment]
I'm sick of these osx travis failures. we need to find the problem and fix it.

**Comment by jbenet** [comment]
@rht, wait

> all contain the `tail -n1` race condition.

whats the race condition?

**Comment by chriscool** [comment]
@jbenet 

> we could also make this into another output mode for ipfs add, which only outputs the root hash. (it's a common enough occurrence that forcing | tail -n1 always is annoying).

Yeah, I think it's a good idea!

@rht I don't like `ipfs cmd ... | something` because it doesn't detect when `ipfs cmd ...` fails as by default the exit code of the whole expression is the exit code of `something`, the part after the pipe (`|`). (You can try `false | true; echo $?` in a shell to see that.)

**Comment by rht** [comment]
@chriscool / @jbenet  I see, I thought the cause of the fluctuating `ipfs refs -r` in https://github.com/ipfs/go-ipfs/pull/2041/files#diff-3300d84a935a8de682f5e1225c53b384L220 was due to `tail -n1

**Comment by chriscool** [comment]
Is there something that should be done on this?
The build failure are not related.

**Comment by jbenet** [comment]
thanks @chriscool

**Comment by rht** [comment]
Found several errs of this type while stress testing in https://github.com/ipfs/go-ipfs/pull/2101, e.g. t0045 https://travis-ci.org/ipfs/go-ipfs/jobs/97678447 and one more on t0043. At least in the t0045 case it is shown that some of the files don't get added.

**Comment by chriscool** [comment]
Yeah, my commits in this PR haven't fixed the problem described in #2028. It really looks like a bug in ipfs add.

**Pull request merged**
