### PR TITLE
test: query test might work sometimes, mark it as 'might fail' 

### PR DESCRIPTION
**Pull request by Kubuxu**
License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu doesnt appear related, but the GC sharness test failure here is odd

**Comment by Kubuxu** [comment]
This is weird failure.

**Comment by Kubuxu** [comment]
Reported it as: https://github.com/ipfs/go-ipfs/issues/4176

**Comment by whyrusleeping** [comment]
Though maybe we should be looking into figuring out whats wrong?

**Comment by Kubuxu** [comment]
I was, but I couldn't figure it out right away and as I am changing GC it might fix it.

**Pull request merged**
