### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://github.com/ipfs/go-ipfs/issues | https://github.com/ipfs/go-ipfs/issues 
http://golang.org/doc/install | https://golang.org/doc/install 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://hub.docker.com/r/jbenet/go-ipfs | https://hub.docker.com/r/jbenet/go-ipfs/ 
http://ipfs.io/docs/install | http://ipfs.io/docs/install/ 
https://code.google.com/p/protobuf/downloads/list | https://github.com/google/protobuf

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: db894da7bc71eb7fc9b32096f2407355f2d65a62
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by ReadmeCritic** [comment]
@jbenet hey let me know if I need to make any changes

**Comment by whyrusleeping** [comment]
@ReadmeCritic could you signoff on your commits?

**Comment by ReadmeCritic** [comment]
hm let me see how to do this..

**Comment by whyrusleeping** [comment]
you can just do a `git commit --amend`and add the following at the end:
```
License: MIT
Signed-off-by: YOUR NAME <YOUR@EMAIL.COM>
```

**Comment by ReadmeCritic** [comment]
Will try this again

**Pull request closed without merging**
