### PR TITLE
[WIP] Unixfs: enforce refs on files when using nocopy

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/ipfs/go-ipfs/issues/4558

Depends on:
* https://github.com/ipfs/go-unixfs/pull/56
* https://github.com/ipfs/go-mfs/pull/55

### CODE REVIEW

**Comment by magik6k** [comment]
Looks like due to https://github.com/ipfs/go-mfs/issues/38, running mfs related commands locally is racy:

```sh
$ alias tipfs='IPFS_PATH=/tmp/ipfs ipfs'
$ tipfs init --profile=test -b=1024
$ tipfs files mkdir /cats
$ tipfs files ls
$ # no cats :( (about 70% of the time, if there are, rm /tmp/ipfs and start over)
```

(This PR works fine without https://github.com/ipfs/go-mfs/issues/38)

@Stebalien @schomatis ^

**Comment by schomatis** [comment]
Sorry for that, small typo, we really need to add tests for the republisher. Pushed it as a hotfix in v0.1.31 (https://github.com/ipfs/go-mfs/commit/2e0c3bc16e67617135127f7436343cff4a33b1dd).

**Comment by Stebalien** [comment]
Thanks for catching that!

(yeah, we need better tests)

**Comment by magik6k** [comment]
There are still some errors in `t0250-files-api`, found this in `daemon_err`:

```
[0;37m15:14:18.505 [31mERROR [0;34m  cmd/ipfs: [0merror from node construction:  error loading filesroot from DAG: merkledag: not found [0;37mdaemon.go:330[0m
Error: error loading filesroot from DAG: merkledag: not found
```

**Comment by magik6k** [comment]
I'm fairly confident that it's not related to these changes, the missing CID is `zDMZof1kvpZj7Lxs5KKpabLZy2VNuQZMsoDJ6ShLAA812gJEAejp`, which is a [dag-pb blake2b cid](https://ipfs.io/ipfs/QmQaPJNzwroguXVU4uPkq5LdHFrp9L3Cb9Ff7m11hQ65fC/#zDMZof1kvpZj7Lxs5KKpabLZy2VNuQZMsoDJ6ShLAA812gJEAejp)

**Comment by Stebalien** [comment]
Yeah, it looks like there's a regression in go-mfs due to that WaitPub PR. And https://github.com/ipfs/go-blockservice/pull/15 dosn't fix it.

**Comment by Stebalien** [comment]
Dammit github! Replaced by https://github.com/ipfs/go-ipfs/pull/5937 (github wouldn't let me reopen this after I rebased).

**Pull request closed without merging**
