### PR TITLE
use os.Interrupt for cross platform happiness

### PR DESCRIPTION
**Pull request by whyrusleeping**
the intention here is to address #1897 but i still need to test this.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
@MichaelMure can you test this?

**Comment by whyrusleeping** [comment]
@jbenet this one isnt ready, 'in progress' tag

**Comment by whyrusleeping** [comment]
the issue is that windows signals like `WM_CLOSE` are handled differently than actual signals, even though windows does support os.Interrupt and os.Kill... its very confusing

**Comment by MichaelMure** [comment]
Already did, it didn't work in my case (https://github.com/ipfs/go-ipfs/issues/1897#issuecomment-150980848)

I'll try again to see if I can find out what's going on.

**Pull request closed without merging**
