### PR TITLE
Reverse label numbers

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/ipfs/go-ipfs/pull/2883#issuecomment-227528997. Will need to change current issues.

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM

**Comment by RichardLitt** [comment]
How do we want to change all of the current instances where people use the old system? Go through and edit them manually?

**Comment by whyrusleeping** [comment]
@RichardLitt eh, i'm not super worried about it. It will sort itself out in time.

**Comment by RichardLitt** [comment]
OK. What are we waiting for to merge this?

**Comment by RichardLitt** [comment]
RFM.

**Pull request merged**
