### PR TITLE
Gxify fuse lib, update it, might fix OSX with new fuzz and move lots of stuff to gx

### PR DESCRIPTION
**Pull request by Kubuxu**
I've tested it on my Arch Linux 4.7.6 machine.
It might solve more issues we are seeing with FUSE.

Resolves https://github.com/ipfs/go-ipfs/issues/3471

License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
i wonder why the js-ipfs-api tests are still failing...

**Comment by whyrusleeping** [comment]
This resolves #3410 right?

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs/pull/3413 resolves #3410 directly but Victor tested it out it turns out that on OSX fuse 3 doesn't work so I hope that this fixes it.

**Comment by VictorBjelkholm** [comment]
Ok, I've tested this as well, on OSX 10.11.4 and osx-fuse 3.5.3 and it's working fine now!

**Comment by whyrusleeping** [comment]
@Kubuxu can you rebase this one?

**Comment by Kubuxu** [comment]
Rebased

**Comment by whyrusleeping** [comment]
@Kubuxu This is such a large diff that it makes me nervous to put it in 0.4.5. Thoughts?

**Comment by Kubuxu** [comment]
I think I will fixup the messages with FUSE on OSX and let's leave it for next release. I feel like it could delay this one too much.

**Comment by whyrusleeping** [comment]
@Kubuxu update here? Since we want to release 0.4.6 very soon, how about we get this in 0.4.7 in the next week or so?

**Comment by Kubuxu** [comment]
I think right now it might be easier to do it from grounds up...

Rebasing is hell

**Comment by Kubuxu** [comment]
Closing this, I'll do it part by part.

**Pull request closed without merging**
