### PR TITLE
Make `ipfs commands --flags` option

### PR DESCRIPTION
**Pull request by rht**
cc: @chriscool

### CODE REVIEW

**Comment by jbenet** [comment]
is this listing out all combinations? i dont think it will be feasible to test _all_ flag combinations... thoughts @chriscool

**Comment by jbenet** [comment]
or, maybe it is. not sure.

**Comment by rht** [comment]
It lists all the flags available for a command. It is definitely not feasible to test all combinations (any n-gram combination). The point is each flag *should* get tested.

**Comment by jbenet** [comment]
ok what's some example output then?

**Comment by rht** [comment]
e.g.
```
ipfs
ipfs add
ipfs add --chunker / ipfs add -s
ipfs add --hidden / ipfs add -H
ipfs add --only-hash / ipfs add -n
ipfs add --progress / ipfs add -p
ipfs add --quiet / ipfs add -q
ipfs add --trickle / ipfs add -t
ipfs add --wrap-with-directory / ipfs add -w
ipfs add -r / ipfs add --recursive
ipfs bitswap
ipfs bitswap stat
ipfs bitswap unwant
ipfs bitswap wantlist
ipfs bitswap wantlist --peer / ipfs bitswap wantlist -p
ipfs block
ipfs block get
ipfs block put
ipfs block stat
ipfs bootstrap
ipfs bootstrap add
ipfs bootstrap add --default
ipfs bootstrap list
ipfs bootstrap rm
ipfs bootstrap rm --all
ipfs cat
ipfs commands
ipfs commands --flags / ipfs commands -f
ipfs config
ipfs config --bool
ipfs config --json
ipfs config edit
ipfs config replace
ipfs config show
ipfs daemon
ipfs daemon --disable-transport-encryption
ipfs daemon --init
ipfs daemon --mount
ipfs daemon --mount-ipfs
ipfs daemon --mount-ipns
ipfs daemon --routing
ipfs daemon --unrestricted-api
ipfs daemon --writable
ipfs dht
ipfs dht findpeer
ipfs dht findprovs
ipfs dht findprovs --verbose / ipfs dht findprovs -v
ipfs dht get
ipfs dht get --verbose / ipfs dht get -v
ipfs dht put
ipfs dht put --verbose / ipfs dht put -v
ipfs dht query
ipfs dht query --verbose / ipfs dht query -v
ipfs diag
ipfs diag net
ipfs diag net --vis
ipfs dns
ipfs dns --recursive / ipfs dns -r
ipfs file
ipfs file ls
ipfs get
ipfs get --archive / ipfs get -a
ipfs get --compress / ipfs get -C
ipfs get --compression-level / ipfs get -l
ipfs get --output / ipfs get -o
ipfs id
ipfs id -f / ipfs id --format
ipfs init
ipfs init --bits / ipfs init -b
ipfs init --empty-repo / ipfs init -e
ipfs init --force / ipfs init -f
ipfs log
ipfs log level
ipfs log tail
ipfs ls
ipfs ls --headers / ipfs ls --
ipfs mount
ipfs mount --ipfs-path / ipfs mount -f
ipfs mount --ipns-path / ipfs mount -n
ipfs name
ipfs name publish
ipfs name publish --lifetime / ipfs name publish -t
ipfs name publish --resolve
ipfs name resolve
ipfs name resolve --recursive / ipfs name resolve -r
ipfs object
ipfs object data
ipfs object get
ipfs object links
ipfs object new
ipfs object patch
ipfs object patch --create / ipfs object patch -p
ipfs object put
ipfs object put --inputenc
ipfs object stat
ipfs pin
ipfs pin add
ipfs pin add --recursive / ipfs pin add -r
ipfs pin ls
ipfs pin ls --count / ipfs pin ls -n
ipfs pin ls --quiet / ipfs pin ls -q
ipfs pin ls --type / ipfs pin ls -t
ipfs pin rm
ipfs pin rm --recursive / ipfs pin rm -r
ipfs ping
ipfs ping --count / ipfs ping -n
ipfs refs
ipfs refs --edges / ipfs refs -e
ipfs refs --format
ipfs refs --recursive / ipfs refs -r
ipfs refs --unique / ipfs refs -u
ipfs refs local
ipfs repo
ipfs repo gc
ipfs repo gc --quiet / ipfs repo gc -q
ipfs resolve
ipfs resolve --recursive / ipfs resolve -r
ipfs stats
ipfs stats bw
ipfs stats bw --interval / ipfs stats bw -i
ipfs stats bw --peer / ipfs stats bw -p
ipfs stats bw --poll
ipfs stats bw --proto / ipfs stats bw -t
ipfs swarm
ipfs swarm addrs
ipfs swarm addrs local
ipfs swarm addrs local --id
ipfs swarm connect
ipfs swarm disconnect
ipfs swarm filters
ipfs swarm filters add
ipfs swarm filters rm
ipfs swarm peers
ipfs tar
ipfs tar add
ipfs tar cat
ipfs tour
ipfs tour list
ipfs tour next
ipfs tour restart
ipfs update
ipfs version
ipfs version --number / ipfs version -n
```

**Comment by jbenet** [comment]
ok, LGTM.

**Comment by chriscool** [comment]
There is something strange in the output for `ipfs add -r`. It looks like for this command the short option name `-r` is output first while for other command the short option name is output last.

(It looks like `ipfs id -f` has this problem too.)

**Comment by chriscool** [comment]
The above tempts me to make changes to:

https://github.com/ipfs/go-ipfs/blob/master/commands/option.go

Maybe we should say that the first name should be a long name and the second a short one.

**Comment by whyrusleeping** [comment]
@chriscool i think enforcing that Options take three arguments and requiring that the second one be a single character might be a good idea

**Comment by chriscool** [comment]
@whyrusleeping ok I will do that.

**Pull request merged**
