### PR TITLE
improve the documentation for the p2p feature

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
> One thing to note is that when you p2p stream dial, the listening endpoint is one-shoot (unlike ssh's -L).

Are you sure? It looks like listen dials the listener for every inbound stream (although it looks like there are many obvious bugs...).

**Comment by magik6k** [comment]
I meant the listening endpoint on the dialer side (the one on client side) - https://github.com/ipfs/go-ipfs/blob/master/p2p/p2p.go#L87.

The code is messy/weird there, I'll revisit it eventually to fix some of this stuff (likely when I'll get to creating coreapi for it).

**Comment by Stebalien** [comment]
> I meant the listening endpoint on the dialer side (the one on client side) - https://github.com/ipfs/go-ipfs/blob/master/p2p/p2p.go#L87.

Ah... I see. Really, we should support an HTTP upgrade from a command (although supporting both makes sense).

**Comment by Stebalien** [comment]
We should make it work like `ssh -L` (that's what users likely expect)`. Blocked on #4895.

**Comment by whyrusleeping** [comment]
@Stebalien is this unblocked yet?

cc @magik6k

**Comment by magik6k** [comment]
I've cherry-picked this in https://github.com/ipfs/go-ipfs/pull/4929 and adjusted to changes there, so if the refactor pr is going to be merged soon I'd say this can be closed.

**Pull request closed without merging**
