### PR TITLE
Migrate go-datastore to gx

### PR DESCRIPTION
**Pull request by Kubuxu**
https://github.com/ipfs/go-datastore/pull/5 should be reviewed and merged first.

### CODE REVIEW

**Comment by Kubuxu** [comment]
Yey, it is green.

**Comment by whyrusleeping** [comment]
the docker tests were failing on travis for some reason. Rerunning to see if it was a fluke

**Comment by whyrusleeping** [comment]
@Kubuxu hrm... travis tests still failing..

**Comment by Kubuxu** [comment]
@whyrusleeping: I have no idea what is going on but it is weird: go here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/136932611/log.txt

and search for: `QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD` from the bottom, this is cause of the failure.

**Comment by kevina** [comment]
@whyrusleeping, @Kubuxu could you look at my pull requests I put on go-datastore and possible get those in before moving to gx.  This way, I can avoid having to use my own version of go-datastore.

**Comment by Kubuxu** [comment]
@kevina from what I can see your changes are only very small, if it is possible just extract those changes atop https://github.com/ipfs/go-datastore and give me commites/branch.

**Comment by kevina** [comment]
As a clarification I am talking merging ipfs/go-datastore#2 and ipfs/go-datastore#3.

**Comment by Kubuxu** [comment]
@whyrusleeping it is green, the problem was that the `package.json` was including same package multiple times (I've messed up some rebases).

**Comment by whyrusleeping** [comment]
@Kubuxu sorry, i merged a different PR first with package.json changes. gonna need a rebase :(

**Comment by Kubuxu** [comment]
Resolved the conflict.

**Pull request merged**
