### PR TITLE
rename and fix sharness issue in ptp test

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@magik6k the ptp tests appear to fail on OSX. Any ideas on a quick fix?

**Comment by whyrusleeping** [comment]
Ah, i think as someone else mentioned, its like the use of 'wait' having different semantics between platforms

**Comment by magik6k** [comment]
What /might/ happen is that the $server_pid process finishes before the `wait` even starts, it (`wait`) then gets the $server_pid and locks up the test. It sounds really, really unlikely, though it's the only logical thing that would affect `wait`.

Simplest thing I can think of now is to use pid files for ma-pipe-.., like in https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0180-ptp.sh#L119-L126, this way the tests wouldn't lockup at least(assuming it's not a wait issue). Should I do that?

**Comment by whyrusleeping** [comment]
@magik6k i'm pretty sure wait doesnt behave the same on OSX as it does on linux. I think i remember something about this happening before. cc @Kubuxu @chriscool

**Comment by Kubuxu** [comment]
I am not sure, I recall issues with netcat not exiting but not that.

**Comment by whyrusleeping** [comment]
@magik6k i think we can use a loop that calls `kill -0 $PID` until it fails as a cheap 'wait'

**Comment by magik6k** [comment]
I rebased on current master and fixed the wait issue.

**Pull request merged**
