### PR TITLE
Update README URLs based on HTTP redirects 

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://github.com/ipfs/go-ipfs/issues | https://github.com/ipfs/go-ipfs/issues 
http://golang.org/doc/install | https://golang.org/doc/install 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://hub.docker.com/r/jbenet/go-ipfs | https://hub.docker.com/r/jbenet/go-ipfs/ 
http://ipfs.io/docs/install | http://ipfs.io/docs/install/ 
https://code.google.com/p/protobuf/downloads/list | https://github.com/google/protobuf 

Previously #2123

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8457e08e68eda3a33c11567a3a2749ff83376f8a
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by ReadmeCritic** [comment]
@whyrusleeping hmm what went wrong :confused:

**Comment by whyrusleeping** [comment]
@ReadmeCritic huh, idk. Your commit message looks fine to me so i'll just delete gitcops comment.

In the future though, you don't need to start a new pull request, you can just `git commit --amend` and `git push -f REMOTE BRANCH`

**Comment by ReadmeCritic** [comment]
ok :sweat_smile:

**Comment by whyrusleeping** [comment]
welp, this looks good to me.

**Pull request merged**
