### PR TITLE
feat: export rcmgr metrics to prometheus

### PR DESCRIPTION
**Pull request by marten-seemann**
Part of #8761 

Adds basic metrics under `libp2p_rcmgr_*`

## Demo sample

````
# HELP libp2p_rcmgr_conns_allowed_total allowed connections
# TYPE libp2p_rcmgr_conns_allowed_total counter
libp2p_rcmgr_conns_allowed_total{direction="inbound",usesFD="false"} 682
libp2p_rcmgr_conns_allowed_total{direction="inbound",usesFD="true"} 614
libp2p_rcmgr_conns_allowed_total{direction="outbound",usesFD="false"} 7647
libp2p_rcmgr_conns_allowed_total{direction="outbound",usesFD="true"} 9107
# HELP libp2p_rcmgr_conns_blocked_total blocked connections
# TYPE libp2p_rcmgr_conns_blocked_total counter
libp2p_rcmgr_conns_blocked_total{direction="inbound",usesFD="false"} 2274
libp2p_rcmgr_conns_blocked_total{direction="inbound",usesFD="true"} 1938
libp2p_rcmgr_conns_blocked_total{direction="outbound",usesFD="false"} 15206
libp2p_rcmgr_conns_blocked_total{direction="outbound",usesFD="true"} 16344
# HELP libp2p_rcmgr_memory_allocations_allowed_total allowed memory allocations
# TYPE libp2p_rcmgr_memory_allocations_allowed_total counter
libp2p_rcmgr_memory_allocations_allowed_total 9808
# HELP libp2p_rcmgr_memory_allocations_blocked_total blocked memory allocations
# TYPE libp2p_rcmgr_memory_allocations_blocked_total counter
libp2p_rcmgr_memory_allocations_blocked_total 0
# HELP libp2p_rcmgr_peer_blocked_total blocked peers
# TYPE libp2p_rcmgr_peer_blocked_total counter
libp2p_rcmgr_peer_blocked_total 0
# HELP libp2p_rcmgr_peers_allowed_total allowed peers
# TYPE libp2p_rcmgr_peers_allowed_total counter
libp2p_rcmgr_peers_allowed_total 17416
# HELP libp2p_rcmgr_protocols_allowed_total allowed streams attached to a protocol
# TYPE libp2p_rcmgr_protocols_allowed_total counter
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/bitswap/1.1.0"} 23
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/bitswap/1.2.0"} 5065
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/id/1.0.0"} 6213
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/id/push/1.0.0"} 859
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/kad/1.0.0"} 4920
libp2p_rcmgr_protocols_allowed_total{protocol="/ipfs/ping/1.0.0"} 936
libp2p_rcmgr_protocols_allowed_total{protocol="/libp2p/autonat/1.0.0"} 11
libp2p_rcmgr_protocols_allowed_total{protocol="/libp2p/circuit/relay/0.1.0"} 29
libp2p_rcmgr_protocols_allowed_total{protocol="/p2p/id/delta/1.0.0"} 18
# HELP libp2p_rcmgr_services_allowed_total allowed streams attached to a service
# TYPE libp2p_rcmgr_services_allowed_total counter
libp2p_rcmgr_services_allowed_total{service="libp2p.autonat"} 11
libp2p_rcmgr_services_allowed_total{service="libp2p.identify"} 6247
libp2p_rcmgr_services_allowed_total{service="libp2p.ping"} 827
# HELP libp2p_rcmgr_services_blocked_total blocked streams attached to a service
# TYPE libp2p_rcmgr_services_blocked_total counter
libp2p_rcmgr_services_blocked_total{service="libp2p.ping"} 109
# HELP libp2p_rcmgr_streams_allowed_total allowed streams
# TYPE libp2p_rcmgr_streams_allowed_total counter
libp2p_rcmgr_streams_allowed_total{direction="inbound"} 9199
libp2p_rcmgr_streams_allowed_total{direction="outbound"} 9743
```

### CODE REVIEW

**Review by vyzo — APPROVED** [review]
looks fine to me, but I don't know how this prometheus business works in ipfs.

**Comment by marten-seemann** [comment]
Yes, that test checks all exported metrics against a list, and fails if any is missing / not expected. I was planning to fix this later.

Note: once libp2p gets a coherent metrics story (see https://github.com/libp2p/go-libp2p/issues/1356), this test should probably be modified to exclude libp2p metrics. I'll leave that decision to the IPFS stewards though.

**Comment by BigLep** [comment]
@marten-seemann : please comment/ping when the test is updated/passing.  Also, I assume we need to update so that this PR only shows the incremental diff on top of https://github.com/ipfs/go-ipfs/pull/8680 ?  I'll make sure we then get reviewer eyes to land this.

**Review by lidel — APPROVED** [review]
LGTM, thank you!

- Rebased this on top of https://github.com/ipfs/go-ipfs/pull/8680
- Refactored a bit to ensure these metrics are created and exposed only when `Swarm.ResourceMgr.Enabled`

**Pull request merged**
