### PR TITLE
go: bump minimal dependency to 1.14.4

### PR DESCRIPTION
**Pull request by RubenKelevra**
due to major bugfixes in the .4 release

### CODE REVIEW

**Comment by ribasushi** [comment]
> major bugfixes in the .4 release

@RubenKelevra out of curiosity: which bugfix are you referring to?

**Comment by Stebalien** [comment]
https://github.com/golang/go/issues/38933? Probably not critical, but anyone on 1.14.2 can upgrade to 1.14.4.

**Comment by RubenKelevra** [comment]
@Stebalien no, this one: https://github.com/golang/go/issues/37833 

I hit it multiple times and was about to create a ticket with some stack traces... but it's gone since the update.

I just wanted to make sure people build IPFS with the latest bugfixes, to avoid trying to track issues already fixed in Go down.

**Comment by RubenKelevra** [comment]
Yes, had some hangs on startup lately. Thought it was a different fix (but mixed up the ticket numbers).

I was about to create a ticket with some stack traces... but it's gone since the go update.

I just wanted to make sure people build IPFS with the latest bugfixes, to avoid trying to track issues already fixed in Go down.

**Comment by Stebalien** [comment]
Fair enough.

> I just wanted to make sure people build IPFS with the latest bugfixes, to avoid trying to track issues already fixed in Go down.

In general, we try to stick to the _lowest_ supported release unless there's a know nissue as most distros don't update immediately.

**Pull request merged**
