### PR TITLE
fuse travis-ci

### PR DESCRIPTION
**Pull request by thelinuxkid**
Waiting for master to be green again to test changes.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@thelinuxkid Master should be green now if you want to test

**Comment by whyrusleeping** [comment]
looks like theres an actual issue on the osx travis tests, it cant find fusermount

**Comment by thelinuxkid** [comment]
It looks like it's missing `gx` https://travis-ci.org/thelinuxkid/go-ipfs/jobs/109452862#L1339, https://travis-ci.org/thelinuxkid/go-ipfs/jobs/109452865#L3651. Since `gx`is a a package tool I don't know how it interfaces with Godeps.

**Comment by Kubuxu** [comment]
You would have to rebase is on to of master again and see how [.travis.yml](https://github.com/ipfs/go-ipfs/blob/master/.travis.yml#L17) works now.

**Comment by thelinuxkid** [comment]
Hmm. I have already rebased and that line is there: https://github.com/thelinuxkid/go-ipfs/blob/master/.travis.yml#L23.

**Comment by thelinuxkid** [comment]
I see. I think the hash changed: https://travis-ci.org/thelinuxkid/go-ipfs/jobs/109452862#L182.

**Comment by whyrusleeping** [comment]
@thelinuxkid i see whats going wrong here, mind if i push a commit?

**Comment by thelinuxkid** [comment]
Sure. I found a couple of things though. I had to do a `go clean` in order for both gx and gx-go to work correctly. Also, it looks like `gx --verbose install --global` is not taking into account that `GOPATH` can have several paths.

**Comment by thelinuxkid** [comment]
I already made the changes to the `fuse` module though.I can push those.

**Comment by whyrusleeping** [comment]
ooooh, the multiple components thing is definitely not considered by gx... I'll fix that

**Comment by thelinuxkid** [comment]
I am not 100% sure using `go clean` is the best way to do that. But it did work.

**Comment by thelinuxkid** [comment]
I am going to leave the `go clean` out. It breaks everything if the packages don't already exist. @whyrusleeping let me know when the GOPATH change has been made.

**Comment by thelinuxkid** [comment]
@whyrusleeping I am seeing the fusermount error on osx now https://travis-ci.org/thelinuxkid/go-ipfs/jobs/109495802#L3695. It's the only thing failing at the moment. I will look further into it.

**Comment by whyrusleeping** [comment]
@thelinuxkid yeah, i pushed the multiple GOPATH fix last night

**Comment by thelinuxkid** [comment]
@whyrusleeping Cool. Just tested it. Works for me. Also rebased. Let me know how this change looks https://github.com/thelinuxkid/go-ipfs/commit/85b9ef3eb49617e3d9fa467de1fe08e12bc617df. I couldn't get the upgrade to work without the `go clean`.

**Comment by thelinuxkid** [comment]
re: osx fusermount https://github.com/osxfuse/osxfuse/wiki/FAQ#48-how-should-i-unmount-my-fuse-for-os-x-file-system-i-cannot-find-the-fusermount-program-anywhere

**Comment by whyrusleeping** [comment]
@thelinuxkid what was the failure case fixed by adding that `go clean` there?

**Comment by thelinuxkid** [comment]
@whyrusleeping `make toolkit_upgrade` didn't fix things until I ran `go clean`.

**Comment by thelinuxkid** [comment]
Tests passing. Please merge.

**Comment by thelinuxkid** [comment]
There was a stall error (unrelated to this). But it the test passed at first retry: https://travis-ci.org/ipfs/go-ipfs/builds/113009295

**Comment by whyrusleeping** [comment]
@chriscool wanna take a look at this one?

**Comment by whyrusleeping** [comment]
pending chris' feedback, this LGTM

**Comment by whyrusleeping** [comment]
Both of the travis failures are fuse issues...  We've spent a lot of time lately making sure our CI is green. I need to think about what we want to do here, i'd prefer not to merge in things that make our CI less green, but I also don't want to delay this code merging any longer.

**Comment by chriscool** [comment]
Except the points about unmounting this LGTM!

**Comment by chriscool** [comment]
Also is a fix for https://github.com/ipfs/go-ipfs/issues/2214 needed?

**Comment by whyrusleeping** [comment]
Maybe  we could enable the fuse testing under travis CIs 'allowed failures' target for now: https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail

**Comment by thelinuxkid** [comment]
@whyrusleeping what failures are you referring to?

@chriscool you can close https://github.com/ipfs/go-ipfs/issues/2214

**Comment by thelinuxkid** [comment]
@whyrusleeping OK. I was looking at my own travis tests which are passing. I see the `context canceled` error which shows up intermittently in the  go tests.  I had not seen it in a while. That might be an easy fix. I don't see an error for the sharness job that failed though.

**Comment by thelinuxkid** [comment]
@whyrusleeping @chriscool can the `context canceled` error be ignored in this instance?

**Comment by whyrusleeping** [comment]
Closing as inactive, reopen as necessary

**Pull request closed without merging**
