### PR TITLE
Improve the install.sh script

### PR DESCRIPTION
**Pull request by mkg20001**
This script now looks for all available locations in $PATH and chooses the best

License: MIT
Signed-off-by: mkg20001 mkg20001@gmail.com

### CODE REVIEW

**Comment by lgierth** [comment]
Could you elaborate a bit more what it does?

**Comment by mkg20001** [comment]
I have no idea what the word "elaborate" means.
(I´m from Germany)

**Comment by lgierth** [comment]
It means to explain :)

**Comment by mkg20001** [comment]
Ok
And how?
Should I add comments everywhere or...

**Comment by Kubuxu** [comment]
There is already PR improving installation process: https://github.com/ipfs/go-ipfs/pull/2504

It is waiting for review by @jbenet

**Comment by mkg20001** [comment]
Oh

**Comment by whyrusleeping** [comment]
closing in favor of #3194

**Pull request closed without merging**
