### PR TITLE
Make Makefile patch to use global gateway actually work

### PR DESCRIPTION
**Pull request by Kubuxu**
Now it was doing whole nothing

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cee002940df6f3f2cc8d85e98eff3f4bee3dc14a
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by Kubuxu** [comment]
Fixed the gitcop issue. Forgot to install the hook here.

**Comment by lgierth** [comment]
Oh wow... :S

**Comment by Kubuxu** [comment]
I found that while improving PKGBUILD for AUR.

**Comment by noffle** [comment]
Nice catch!

**Comment by whyrusleeping** [comment]
wow, i guess i have no idea how makefiles work... thanks!

**Pull request merged**
