### PR TITLE
Make the #foo references absolute instead of relative.

### PR DESCRIPTION
**Pull request by spikebike**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5ae70a738324bdb00d04f44126195a2abf21bbbc
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by jbenet** [comment]
@spikebike thanks but we probably should just run a post-processing script in https://github.com/ipfs/website/ -- not here.

**Comment by jbenet** [comment]
@RichardLitt saw you PRed something similar. we can just run a sed replace over the output, over at the website repo.

**Comment by RichardLitt** [comment]
@jbenet Actually, I think that the gencmdref script should be moved to the website repo. I'm working on a branch for that in [ipfs/website branch cmdref-make](https://github.com/ipfs/website/tree/feature/cmdref-make), but I am waiting on a solution to https://github.com/ipfs/go-ipfs/issues/1735 to figure that out.

**Comment by jbenet** [comment]
Ok sounds good, though this is useful to make api docs independent of the website. Maybe this should be in an api repo, once we make it



—

**Comment by RichardLitt** [comment]
Agreed, but the script as it is now is entirely website specific. Any later API scripts can be dealt with when we cross that bridge.

**Comment by jbenet** [comment]
Ok sgtm

**Pull request closed without merging**
