### PR TITLE
gx update deps

### PR DESCRIPTION
**Pull request by Stebalien**
Updates:

* go-net
* go-text
* dns
* prometheus
* protobuf

Dedups:

* protobuf

Unblocks:

* https://github.com/libp2p/go-libp2p/pull/285

Part of:

* https://github.com/ipfs/go-ipfs/issues/4485

### CODE REVIEW

**Comment by Stebalien** [comment]
I had to play some games to get prometheus working (especially with our version of protobuf). It would be nice to test this on a gateway before merging.

**Comment by Stebalien** [comment]
@lgierth this patch updates prometheus. Can we test it on a gateway?

Also, is https://github.com/ipfs/go-ipfs/issues/4132 still valid?

**Comment by Stebalien** [comment]
Alternative to #5269. We can also do both but this patch *also* deduplicates the protobuf packages.

**Comment by whyrusleeping** [comment]
yolo

**Pull request merged**
