### PR TITLE
Config null

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by jbenet** [comment]
Oh should i revert the previous ones?

**Comment by rht** [comment]
rewrite the history with this one where the order is changed?

**Comment by jbenet** [comment]
i'm ok with rewriting history, but i think many systems out there aren't. since it's been some time and many people may have pulled down the changes (particularly automated systems) let's keep it this way and deal with a small bisect hit.

**Comment by jbenet** [comment]
thanks for preparing this though, @rht

**Pull request closed without merging**
