### PR TITLE
Binary data and json test

### PR DESCRIPTION
**Pull request by chriscool**
This is a test for issue #1582 (JSON encoding corrupts non-UTF-8 binary data).

~~But please don't merge this until the issue of the license of UTF-8-test.txt is fixed.~~

The first patch adds a file that is CC BY 4.0 licensed, but after discussing with the author I think it is ok.

### CODE REVIEW

**Comment by chriscool** [comment]
Go tests are failing which is not related.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 241309cc85b22dc287349366449f050b7094c8dd
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4a0a3bfcbdb79efcfd0ad3f506f486fb5b2b925
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4a0a3bfcbdb79efcfd0ad3f506f486fb5b2b925
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by chriscool** [comment]
Ok, I think it should be ok to merge this now.

**Comment by jbenet** [comment]
@chriscool so it's not broken? 

cc @davidar

**Comment by chriscool** [comment]
Yes its broken. The last test uses `test_expect_failure`:

```
+	test_expect_failure "'ipfs object put --inputenc=json' output looks good" '
+		echo "added $HASH" >expected &&
+		test_cmp expected actual
+	'
```

You can also wait for someone to fix the problem, but I think it will be valuable to add some tests for this anyway.

**Comment by jbenet** [comment]
@chriscool ok sounds good.

**Pull request merged**
