### PR TITLE
Pinning interop: Pin ls returns appropriate zero value

### PR DESCRIPTION
**Pull request by aschmahmann**

### CODE REVIEW

**Comment by aschmahmann** [comment]
We don't have any streaming interop tests so I'm not sure if we should remove the `json:",omitempty"` from `PinLsObject` as well.

**Comment by Stebalien** [comment]
Ugh. We _want_ to omit `PinLsList.Keys` if we're streaming.

What if we set `Keys` to a non-nil empty map? That will cause us to send the correct `{}`.

**Comment by Stebalien** [comment]
When _not_ streaming, that is.

**Comment by Stebalien** [comment]
Wait, that's what we're doing.

**Comment by Stebalien** [comment]
Ah. I didn't test this the right way. omitempty doesn't care about nil versus non-nil empty.

**Pull request merged**
