### PR TITLE
Fix: Using the `dnslink` feature led to infinite redirects

### PR DESCRIPTION
**Pull request by Luzifer**
For details see comment thread at #1233

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This looks good to me! @wking did you write a test for this?

**Comment by wking** [comment]
On Mon, May 18, 2015 at 09:03:37PM -0700, Jeromy Johnson wrote:
> This looks good to me! @wking did you write a test for this?

I didn't add ipns_hostname to #1208.  Maybe just merge this and I'll
rebase #1208 on top?  I'm still not sure about the best way to handle
host-resolution [1], but I think we all agree that having a
doubled-backslash isn't useful to anyone.  As an alternative to the
trim+append approach, we could use path.Join [2].

[1]: https://github.com/ipfs/go-ipfs/pull/1208/files#r30462883
     and following comments
[1]: http://golang.org/pkg/path/#Join

**Comment by jbenet** [comment]
+1 to `path.Join` -- @Luzifer ?

**Comment by jbenet** [comment]
@Luzifer mind rebasing, also? thanks

**Comment by Luzifer** [comment]
`path.Join` works for me. http://play.golang.org/p/9l7EkkF_kY

**Comment by Luzifer** [comment]
@jbenet rebased onto `ipfs/master`, changed to `path.Join`

**Comment by wking** [comment]
On Wed, May 20, 2015 at 10:43:04AM -0700, Knut Ahlers wrote:
> rebased onto `ipfs/master`, changed to `path.Join`

Looks good to me :).

**Comment by Luzifer** [comment]
argh…

**Comment by jbenet** [comment]
LGTM!, thanks very much @Luzifer

**Comment by jbenet** [comment]
(sorry it took so long!)

**Pull request merged**
