### PR TITLE
Get travis to test all commits

### PR DESCRIPTION
**Pull request by jbenet**
This PR:
- config set: allow arbitrary json input
- sharness: randomize swarm address too.
- travis: use the KVM setup
- travis-ci: make test_all_commits

Ideally, after this, our travis runs:

- will randomize Swarm addr (and stop clashing \o/)
- will run faster (kvm setup)
- will test all commits.

Note: after this PR users can set arbitrary json input to config:

  ipfs config --json Addresses.Swarm '["/ip4/0.0.0.0/tcp/4002"]'

A future commit should introduce "-" as a value param (or --stdin)
to allow users to give the value in stdin.

### CODE REVIEW

**Comment by jbenet** [comment]
@chriscool looks like travis is running a tty, or the tty check in `test/bin/continueyn` didn't work.

**Comment by jbenet** [comment]
Hmmm, travis doesn't seem to be testing our branches the same way we do. They seem to be rsyncing stuff manually on top of master. https://travis-ci.org/ipfs/go-ipfs/jobs/61965693#L352

@chriscool any ideas?

**Comment by chriscool** [comment]
It looks like "master" isn't know by travis:

```
$ LANG=C GIT_EDITOR=true git rebase -i --exec "make test" stuff
fatal: Needed a single revision
invalid upstream stuff
```

**Comment by chriscool** [comment]
Probably because --branch is used when cloning:

```
christian@ubuntu:~/src/testb$ LANG=C git clone --depth=50 --branch=travis-test-all-commits git://github.com/ipfs/go-ipfs.git 
Cloning into 'go-ipfs'...
remote: Counting objects: 5065, done.
remote: Compressing objects: 100% (3246/3246), done.
remote: Total 5065 (delta 2208), reused 3786 (delta 1511), pack-reused 0
Receiving objects: 100% (5065/5065), 5.19 MiB | 315.00 KiB/s, done.
Resolving deltas: 100% (2208/2208), done.
Checking connectivity... done.
christian@ubuntu:~/src/testb$ cd go-ipfs/
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$ LANG=C GIT_EDITOR=true git rebase -i --exec "make test" master
fatal: Needed a single revision
invalid upstream master
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$ 
```

**Comment by chriscool** [comment]
You might want to use `origin/master` instead of `master` in the rebase command:

`GIT_EDITOR=true git rebase -i --exec "make test" origin/master`

**Comment by jbenet** [comment]
I tried origin/master first and that failed. Maybe we can fetch the origin first.



—

**Comment by chriscool** [comment]
Yeah, it looks like when you use clone with `--branch=...` it fetches only the branch you passed with the option.

**Comment by chriscool** [comment]
```
christian@ubuntu:~/src/testb$ LANG=C git clone --depth=50 --branch=travis-test-all-commits git://github.com/ipfs/go-ipfs.git 
Cloning into 'go-ipfs'...
remote: Counting objects: 5065, done.
remote: Compressing objects: 100% (3246/3246), done.
remote: Total 5065 (delta 2208), reused 3785 (delta 1511), pack-reused 0
Receiving objects: 100% (5065/5065), 5.19 MiB | 303.00 KiB/s, done.
Resolving deltas: 100% (2208/2208), done.
Checking connectivity... done.
christian@ubuntu:~/src/testb$ cd go-ipfs/
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$ git branch -a
* travis-test-all-commits
  remotes/origin/travis-test-all-commits
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$
```

**Comment by jbenet** [comment]
@chriscool what about this error: https://travis-ci.org/ipfs/go-ipfs/jobs/61977410#L355-L356

```
git config --global user.email "nemo@ipfs.io"
git config --global user.name "IPFS BOT"
git fetch origin master
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 38 (delta 28), reused 27 (delta 17), pack-reused 0
Unpacking objects: 100% (38/38), done.
From git://github.com/ipfs/go-ipfs
 * branch            master     -> FETCH_HEAD
GIT_EDITOR=true git rebase -i --exec "make test" origin/master
fatal: Needed a single revision
invalid upstream origin/master
make: *** [test_all_commits_travis] Error 1
```

**Comment by chriscool** [comment]
@jbenet this is the same error. It means that git doesn't know about `origin/master` because it has not been created by `git fetch origin master`.

The following log message:

```
From git://github.com/ipfs/go-ipfs
 * branch            master     -> FETCH_HEAD
```

means that only the FETCH_HEAD ref has been created (or updated) locally (using the master branch from the remote).

The reason is that the `git clone --branch=...` created the following in .git/config:

```
[remote "origin"]
        url = git://github.com/ipfs/go-ipfs.git
        fetch = +refs/heads/travis-test-all-commits:refs/remotes/origin/travis-test-all-commits
```

The `fetch=...` refspec means that by default only the travis-test-all-commits will be fetched. 
And `git fetch origin master` is not enough to override the refspec.

Something like `git fetch origin master:master` will create the "master" branch locally, so that `GIT_EDITOR=true git rebase -i --exec "make test" master` will work:

```
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$ LANG=C git fetch origin master:master
From git://github.com/ipfs/go-ipfs
 * [new branch]      master     -> master
christian@ubuntu:~/src/testb/go-ipfs (travis-test-all-commits u=)$ LANG=C GIT_EDITOR=true git rebase -i --exec "make test" master
Executing: make test
...
```

**Comment by chriscool** [comment]
It looks like Travis failed because some go tests take too long on Linux...

**Comment by jbenet** [comment]
@chriscool ahh thank you. that fixed it.

**Comment by jbenet** [comment]
@chriscool and yeah looks like it. wonder if we should ask for a bump or try to speed them up.

**Comment by whyrusleeping** [comment]
file bugs for tests that take too long, they should either be made faster, or marked 'expensive'

**Comment by chriscool** [comment]
@jbenet @whyrusleeping the test that is taking too long is github.com/ipfs/go-ipfs/exchange/bitswap.
And at the top of exchange/bitswap/bitswap_test.go there is:

```
// FIXME the tests are really sensitive to the network delay. fix them to work
// well under varying conditions
```

Perhaps there is already an issue about this.

**Comment by whyrusleeping** [comment]
Ah, i make these tests cheaper in my latest PR, hopefully after that theyre a bit nicer

**Comment by jbenet** [comment]
This is our CI. It runs expensive tests. Cheap tests are for local dev.



—

**Comment by jbenet** [comment]
> I don't think it is a good solution. Unless I am missing something, it looks like it will not be simple to check that all the branches have passed the tests.

we can see the commit status on all commits:



And inspect them individually.

Though agreed-- the final PR indicator will look green even if there are commits that fail.

Any other ideas to work around this? our tests right now take a long time, but even if we got them to be fast, stress tests do take time. a PR with, say > 10 commits will likely be slow.

It's possible this may get easier if we break apart go-ipfs into submodules and test those independently. (e.g. `p2p/` could be it's own repo, etc)

**Comment by whyrusleeping** [comment]
easy solution: require all PRs be a single commit

**Comment by chriscool** [comment]
@jbenet if we can easily see the commit status of each commit, yeah we can probably live with that.

Is there a place where we document all the CI tools like Travis, Jenkins, and so on with all the pro and cons?

@whyrusleeping requiring all PRs be a single commit is not a good solution either. If we do that then people will squash everything together and then when bisecting it will be difficult to have a good idea of where a problem can come from.

**Comment by wking** [comment]
What's the problem with test_all_commits_travis running a rebase-exec?
Just that it could take longer to complete than Travis' time limit?
There were comments about “otherwise travis may cancel its run if it
detects that the branch is no longer there”, and I don't understand
the concern there.

**Comment by jbenet** [comment]
> What's the problem with test_all_commits_travis running a rebase-exec? Just that it could take longer to complete than Travis' time limit?

Yes, by a long shot. And it's not only the time limit-- testing independently (serially) will also prevent any machine-level parallelism travis might do on its own.

> There were comments about “otherwise travis may cancel its run if it detects that the branch is no longer there”, and I don't understand the concern there.

If you push branch `branchname` at `ref1`, it will trigger a webhook to travis, kicking off a build. if you push `branchname` at `ref2` shortly after, it will trigger another webhook, kicking off another build. It seems that sometimes travis is smart enough to detect that `branchname` now points to something new, and (rightly) cancels the older build.

**Comment by wking** [comment]
On Wed, May 13, 2015 at 10:15:47AM -0700, Juan Batiz-Benet wrote:
> > What's the problem with test_all_commits_travis running a
> > rebase-exec? Just that it could take longer to complete than
> > Travis' time limit?
>
> Yes, by a long shot.

So maybe “run the cheap tests on every commit and the expensive tests
on the tip”?  That's not as nice as running the expensive tests on
every commit, but it might give us something that works fairly well.
If that's not good enough, running an alternative CI tester might be
the best bet (which sounds like where @chriscool was headed with [1]).

> And it's not only the time limit-- testing independently (serially)
> will also prevent any machine-level parallelism travis might do on
> its own.

Are there docs for this parallelization?  Or is this just “we don't
know how Travis works, but want to allow it to optimize like this”?

> > There were comments about “otherwise travis may cancel its run if
> > it detects that the branch is no longer there”, and I don't
> > understand the concern there.
> 
> If you push branch `branchname` at `ref1`, it will trigger a webhook
> to travis, kicking off a build. if you push `branchname` at `ref2`
> shortly after…

Is this just “why pushing each commit sequentially to the same branch
doesn't work”?  It doesn't seem to apply to the rebase-exec approach.

[1]: https://github.com/ipfs/go-ipfs/pull/1220#issuecomment-101639464

**Comment by jbenet** [comment]
@chriscool 
> Is there a place where we document all the CI tools like Travis, Jenkins, and so on with all the pro and cons? 

Nothing very big. I collected some of it here: https://github.com/ipfs/infrastructure/issues/20

I don't have time to own this-- anybody want to step up for this -- (@chriscool maybe when you have more time)? 

---

> Are there docs for this parallelization?  Or is this just “we don't know how Travis works, but want to allow it to optimize like this”?

yeah, their docs. each build they do is independent, and sets up its own vm or container (kvm)

**Comment by chriscool** [comment]
@jbenet ok when I have more time I can have a look at improving the documentation about the infrastructure.

**Pull request merged**
