### PR TITLE
ulimit: handle freebsd ulimit code separately from the rest of the un…

### PR DESCRIPTION
**Pull request by whyrusleeping**
…ixes

Resolves https://github.com/ipfs/go-ipfs/issues/3423

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
gonna wait for at least one OSX build to go through since this is a 'cross platform' change

**Comment by deltab** [comment]
Is this necessary? Could the hardcoded number just use a smaller type? (I don't know Go's type coercion rules.)

**Comment by Kubuxu** [comment]
Yes it is required.

**Comment by djdv** [comment]
Build seems to work on 32-bit as well now. Yay!
ipfs-bsd

**Pull request merged**
