### PR TITLE
update go-ipfs-cmds to 0.4.12

### LINKED ISSUE #4436: Panic on Ctrl-D on ipfs add
To reproduce:

```sh
> ipfs add
^D
```

Result:

```
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.
panic: interface conversion: interface {} is map[string]interface {}, not *coreunix.AddedObject

goroutine 42 [running]:
github.com/ipfs/go-ipfs/core/commands.glob..func7.1(0xc420076960)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/commands/add.go:390 +0x9fc
created by github.com/ipfs/go-ipfs/core/commands.glob..func7.2
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/commands/add.go:449 +0x181
```

### PR DESCRIPTION
**Pull request by keks**
Closes #4436.

### CODE REVIEW

**Comment by Stebalien** [comment]
Those look like actual failures:


```
ok 46 - outputs look correct

expecting success: 
    ipfs dag get $IPLDHASH/hello > sub1 &&
    ipfs dag get $IPLDHASH/sub > sub2 &&
    ipfs dag get $IPLDHASH/sub/beep > sub3 &&
    ipfs dag get $IPLDHASH/sub/beep/0 > sub4 &&
    ipfs dag get $IPLDHASH/sub/beep/1 > sub5
  
Error: reflect: call of reflect.Value.Type on zero Value
not ok 47 - resolving sub-objects works
#	
#	    ipfs dag get $IPLDHASH/hello > sub1 &&
#	    ipfs dag get $IPLDHASH/sub > sub2 &&
#	    ipfs dag get $IPLDHASH/sub/beep > sub3 &&
#	    ipfs dag get $IPLDHASH/sub/beep/0 > sub4 &&
#	    ipfs dag get $IPLDHASH/sub/beep/1 > sub5
#	  

expecting success: 
    echo "\"world\"" > sub1_exp &&
    test_cmp sub1_exp sub1 &&
    echo "{\"beep\":[0,\"bop\"],\"dict\":\"ionary\"}" > sub2_exp &&
    test_cmp sub2_exp sub2 &&
    echo "[0,\"bop\"]" > sub3_exp &&
    test_cmp sub3_exp sub3 &&
    echo "0" > sub4_exp &&
    test_cmp sub4_exp sub4 &&
    echo "\"bop\"" > sub5_exp &&
    test_cmp sub5_exp sub5
  
> diff -u sub1_exp sub1
--- sub1_exp	2017-12-04 18:37:24.337737375 +0000
+++ sub1	2017-12-04 18:37:24.125745130 +0000
@@ -1 +0,0 @@
-"world"

not ok 48 - sub-objects look right
#	
#	    echo "\"world\"" > sub1_exp &&
#	    test_cmp sub1_exp sub1 &&
#	    echo "{\"beep\":[0,\"bop\"],\"dict\":\"ionary\"}" > sub2_exp &&
#	    test_cmp sub2_exp sub2 &&
#	    echo "[0,\"bop\"]" > sub3_exp &&
#	    test_cmp sub3_exp sub3 &&
#	    echo "0" > sub4_exp &&
#	    test_cmp sub4_exp sub4 &&
#	    echo "\"bop\"" > sub5_exp &&
#	    test_cmp sub5_exp sub5
#	  
```

**Comment by Stebalien** [comment]
IPLD objects can be anything so I think the right fix is just `interface{}`.

**Comment by Stebalien** [comment]
I just modified that commit to use `new(interface{})` tell me if it looks right to you.

**Comment by Stebalien** [comment]
Same error for a different command:

```
expecting success: 
  ma-pipe-unidir --listen --pidFile=listener.pid send /ip4/127.0.0.1/tcp/10101 < test0.bin &

  test_wait_for_file 30 100ms listener.pid &&
  kill -0 $(cat listener.pid) &&

  ipfsi 1 p2p stream dial $PEERID_0 p2p-test /ip4/127.0.0.1/tcp/10102 2>&1 > dialer-stdouterr.log &&
  ma-pipe-unidir recv /ip4/127.0.0.1/tcp/10102 > client.out &&
  test ! -f listener.pid

Error: reflect: call of reflect.Value.Type on zero Value
not ok 12 - Test server to client communications
#	
#	  ma-pipe-unidir --listen --pidFile=listener.pid send /ip4/127.0.0.1/tcp/10101 < test0.bin &
#	
#	  test_wait_for_file 30 100ms listener.pid &&
#	  kill -0 $(cat listener.pid) &&
#	
#	  ipfsi 1 p2p stream dial $PEERID_0 p2p-test /ip4/127.0.0.1/tcp/10102 2>&1 > dialer-stdouterr.log &&
#	  ma-pipe-unidir recv /ip4/127.0.0.1/tcp/10102 > client.out &&
#	  test ! -f listener.pid
#	
```

**Comment by keks** [comment]
@Stebalien actually the MaybeError for untyped parsing should have fixed this without having to change the commands. I'll make a new PR for upgrading to 0.4.13, it that one passes we can close this one unmerged.

**Comment by Stebalien** [comment]
Replaced by https://github.com/ipfs/go-ipfs/pull/4463

**Pull request closed without merging**
