### PR TITLE
WIP Fix DagModifier for raw-leaves nodes

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
We shouldnt need to make different types of dagreaders, The single dagreader should be able to handle all 'unixfs' nodes (including rawnodes)

**Comment by whyrusleeping** [comment]
@Kubuxu I had some WIP work on this from last night, pushed it here: https://github.com/ipfs/go-ipfs/tree/feat/dagmod-raw

**Comment by Kubuxu** [comment]
I thought it would be just easier as there is a clear upgrade spot when the simple handling of raw-leaves becomes just being like any other node that DagModifier handles.

I don't think there is much reason to complicate the DagModifier code with 1. logic of handling just one solo raw-node 2. logic of upgrade from solo raw-node to multiple raw-nodes linked.

**Comment by kevina** [comment]
@Kubuxu @whyrusleeping do you want me to take this over?

**Comment by whyrusleeping** [comment]
@kevina sure, but i do prefer the approach in the branch i linked above. I think its much simpler than creating a new type of dagmodifier for the case where we have to deal with a different type.

**Comment by kevina** [comment]
@whyrusleeping Okay I will cherry pick your changes in.  I was starting to do something similar.

**Comment by whyrusleeping** [comment]
@kevina sounds good! thanks!

**Comment by kevina** [comment]
@Kubuxu can we close this is favor of https://github.com/ipfs/go-ipfs/pull/4026?

**Comment by whyrusleeping** [comment]
Yeah, i think #4026 closes this. If i'm wrong, please go ahead and reopen it

**Pull request closed without merging**
