### PR TITLE
update go multiplex dep with half closed streams support

### PR DESCRIPTION
**Pull request by whyrusleeping**
for @diasdavid  :)

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by Kubuxu** [comment]
Everything is red.

**Comment by whyrusleeping** [comment]
bumping to 0.4.7 as @dignifiedquire is still working on finalizing interop, may require more changes on the go side of things.

**Comment by dignifiedquire** [comment]
@whyrusleeping I expect to be able to tell you if this is good to go tonight

**Comment by dignifiedquire** [comment]
@whyrusleeping just finished testing, this is good to go from the js side 👍

**Pull request merged**
