### PR TITLE
Add the packaging metadata to build the ipfs snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

If we upload the snap to the ubuntu store we will get a great way to deliver the software, and transactional automatic updates. I've been testing the snap [1] and it seems to me good enough to publish in the edge channel, which will make it really easy to do crowd-testing before the stable release.

If you have any doubts or comments, please let me know :)

[1] https://gist.github.com/elopio/7492a28bd1aef6c4a86b5dcf5d5cb65b

**Comment by elopio** [comment]
Hello. Anybody around to review this?

**Comment by Kubuxu** [comment]
I have never used it, I would love to have some other snapcraft user confirm that everything works.

**Comment by whyrusleeping** [comment]
@elopio Yeah, i've never used snapcraft (rather happy pacman user over here) and am uncertain where to begin for reviewing this. My general opinion on package build systems is that the build scripts should be separate from the source, and the source should be linked in.

If any other users of snapcraft want to voice their opinions here, that would be appreciated, but merging this would set a precedent of then having to support *every* packaging system that wants to merge their build infos into the codebase. So this is something we need to think about carefully

**Comment by elopio** [comment]
I'm sorry for all the travis noise. I was using this to try to find a nice travis script that would work upstream, so I could use it as an example for the other projects asking about it. I'm happy because now it's green :)

@whyrusleeping I understand your position, of course. For me as an ipfs user, it's the same if the snap comes from the master branch or from somewhere else. This will just work from a separate repo or a separate branch after changing the source value in snapcraft.yaml. However, I have no permissions to create that branch in ipfs, it will have to come from you.

I'm glad to help in whatever you decide. Just let me know.

**Comment by elopio** [comment]
Hey. I'm not a happy pacman user, but today I had to install arch to test snapd there. After a couple of hours, I came out victorious ^_^.

I took a moment to update the gist, in case you have a few minutes to give it a try: https://gist.github.com/elopio/7492a28bd1aef6c4a86b5dcf5d5cb65b#file-ipfs-build-arch-md

**Comment by whyrusleeping** [comment]
@elopio i think maintaining this in a separate repo will be the best path forward.

**Comment by elopio** [comment]
Works for me: https://github.com/elopio/ipfs-snap
I'm going to close this PR. But I still would like to get an official snap, with automatic updates for every new release. Are you interested in that?
If so, take my branch an push it to your github organization. That actually solves your concerns about the version because I we can add the travis scripts with the magic to publish new versions to the edge channel for every change in the master repo, and new versions to the stable channel every time a tag is added. The version is just sed'ed by the deployment script.

Here's a proposal: take [this snap](http://people.ubuntu.com/~elopio/snaps/ipfs_v0.4.4_amd64.snap) I've just build and [publish it to the store](https://myapps.developer.ubuntu.com/dev/click-apps/register-name/). See if people like it, take a look at the stats, and then decide if it makes sense to keep the travis hooks that will keep it fresh.

Thanks for reviewing @whyrusleeping!

**Comment by elopio** [comment]
I'm sad I didn't here back from you. I need the snap to start my peronsal project during the holidays, so I went ahead and configured the push in my repo.
https://github.com/elopio/ipfs-snap/blob/master/.travis.yml#L17

I hooked it to travis cron. That means that there will be a new ifps snap in the edge repo every day, with the most recent contents from your master.

If you would like to take ownership of it, just let me know and I'll make the transfer and help you in any way I can.

pura vida.

**Comment by whyrusleeping** [comment]
Hey @elopio, sorry, I've got a lot on my plate. I'm fine having you manage the releases for that, thanks!

**Comment by elopio** [comment]
That's alright, I understand. I'll keep you posted about stats and feedback.

**Comment by whyrusleeping** [comment]
Thank you! is there somewhere we can easily see usage stats and such?

**Comment by elopio** [comment]
Yes, I can add you as a collaborator to this snap in the store. I just need your email address.

**Comment by elopio** [comment]
@whyrusleeping we just got 100 tests :D 

Do you think we can put the instructions to install the snap in the docs, to get more people trying it?

ekrankopio de 2017-02-06 10-32-29

**Comment by whyrusleeping** [comment]
@elopio Thats great! Let's get that info into the readme :) Wanna PR in instructions  before "Install From Source" but after "Install Prebuilt Packages", Something like "From your linux package manager" And have a section in that about snaps?

**Comment by whyrusleeping** [comment]
Also, if you wanted to add me as a collaborator in the snap store, you can use why () ipfs.io as my email

**Comment by elopio** [comment]
Thanks @whyrusleeping. You should have an invitation in your mailbox. And I've made #3663.

**Pull request closed without merging**
