### PR TITLE
add systemd support

### PR DESCRIPTION
**Pull request by Stebalien**
This change:

1. adds socket activation support for the API and the gateway
2. notifies systemd when go-ipfs is ready
3. notifies systemd when go-ipfs is shutting down

Unlike my previous attempt (https://github.com/ipfs/go-ipfs/pull/5514), this change _merges_ the sockets passed by systemd with those configured in `ipfs config`. This is likely what the user wants.

Motivation:

1. Change 1 makes it possible to start go-ipfs on demand.
2. Change 2 makes it possible to _wait_ for go-ipfs to finish starting. This makes it possible to use systemd's automount feature along with https://github.com/ipfs/go-ipfs/pull/6612 to auto-start IPFS and auto-mount /ipfs on demand.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Would you consider putting the sockets part as a separate, re-usable module out of the ipfs codebase? Seems quite useful.

**Comment by Stebalien** [comment]
@hsanjuan done.

**Comment by olizilla** [comment]
@Stebalien could you merge these systemd improvements into the stabalize-dht branch so we can try them on a gateway node pls?

**Comment by Stebalien** [comment]
@olizilla I've rebased the stabilize branch. However, that branch now requires 2048 bit keys so we'll want to wait until we've updated the bootstrappers (or add a patch to that branch to revert it).

**Pull request merged**
