### PR TITLE
Add CID Codecs to block put

### PR DESCRIPTION
**Pull request by hermanjunge**
Adding codecs found in https://github.com/ipfs/go-cid/blob/b42583c8bfdafac9965f450294b371d1b734c6f6/cid.go#L67-L79

### CODE REVIEW

**Comment by hermanjunge** [comment]
Force pushed an updated with a more decent commit message 😬

**Comment by kevina** [comment]
@whyrusleeping should we hard code every cid type into go-ipfs?  It seams to me we should use a lookup table from an external library.  Was this discussed somewhere else?

**Comment by hermanjunge** [comment]
Good point @kevina @whyrusleeping, as `mhtype` does have a lookup table (https://github.com/hermanjunge/go-ipfs/blob/c19f1bca895cbab264a6025f5d792616bb0ecb86/core/commands/block.go#L195)

**Comment by whyrusleeping** [comment]
Yeah, we should add a lookup table. Someone want to PR that into go-cid?

**Comment by hermanjunge** [comment]
@whyrusleeping will do. Let's close this meanwhile.

**Comment by hermanjunge** [comment]
@whyrusleeping https://github.com/ipfs/go-cid/pull/26

Once merged, I rebase this PR.

**Comment by whyrusleeping** [comment]
@hsanjuan you should be unblocked now, the go-cid package has been updated in master

**Comment by hsanjuan** [comment]
@whyrusleeping you meant to mention @hermanjunge right ?

**Comment by whyrusleeping** [comment]
Heh, yes i did. I guess my brain saw "oh, theres a j in the middle of that username that starts with an h, thats the right one"

**Pull request merged**
