### PR TITLE
assets: fix gc example

### PR DESCRIPTION
**Pull request by lgierth**
Same as #1850 but with Signed-off-by

### CODE REVIEW

**Comment by jbenet** [comment]
and travis hates it :]  -- did we break master?

**Comment by jbenet** [comment]
https://travis-ci.org/ipfs/go-ipfs/jobs/94537138#L129 ?

**Comment by cryptix** [comment]
`go generate` in `assets/` to update `bindata.go`.

**Comment by lgierth** [comment]
Damn lol that was me: `assets_test.go:52: asset init-doc/quick-start: vcs and embedded data isnt equal`

**Comment by lgierth** [comment]
Ok here we go, updated bindata and test-lib-hashes.sh -- the remaining failure is a variation of #2027/#2028

**Comment by jbenet** [comment]
thanks @lgierth

**Pull request merged**
