### PR TITLE
return a better error if the ref is not an object

### LINKED ISSUE #2807: ipfs get $hashofblock gives confusing error message
When the hash referred is a block, one cannot use `ipfs get` (as it expects a file object) - but instead have to use `ipfs block get`. This is fine, but the error message when attempting is not very helpful in understanding this:
```
$ ipfs get QmSnWHYwDUE1gdcUb6ZYgU2khZ5FkxuWsTvXbw3zGsKc3x
Error: Failed to decode Protocol Buffers: incorrectly formatted merkledag node: Unmarshal failed. proto: illegal wireType 6

$ ipfs block get QmSnWHYwDUE1gdcUb6ZYgU2khZ5FkxuWsTvXbw3zGsKc3x
�ripld-image-versionhtilesize�axayetiles�axayflevel0��fformatcpngdsize�axayddata�
......
````
Expected would be something like "Requested hash $hash refers to a block, not an object. Use ipfs block get instead". Possibly with the detailed error message above following it.

Ping @Kubuxu

### PR DESCRIPTION
**Pull request by whyrusleeping**
closes #2807 

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by Kubuxu** [comment]
LGTM

**Comment by Kubuxu** [comment]
Looks even better to me.

**Comment by RichardLitt** [comment]
What API messages should this change? Only `block`?

**Comment by Kubuxu** [comment]
This changes error messages in many cases, but I don't think you have to include it in API changes.

**Pull request merged**
