### PR TITLE
Fix dist_get script: prevents get_go_vars() returns same %s-%s values twice

### PR DESCRIPTION
**Pull request by MrSparc**
This PR fix `bin/dist_get_script` script used to download dependencies.
  License: MIT
  Signed-off-by: MrSparc <sparciie@yahoo.com>

`make install` fails when tries to use `dist_get` script to download `gx` because` get_go_vars()` method returns the same var values  `GOOS` and `GOARCH` twice, ie:

`gx_v0.8.0_linux-amd64linux-amd64.tar.gz`
instead of:
`gx_v0.8.0_linux-amd64.tar.gz`

This is my first PR on this project, so be friendly please  and excuse me  if breaking any procedure or mistake :)
Greetings from Portugal!

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This Looks good to me, thank you! 

If you could sign off on your commit by doing `git commit --amend` and putting:

```
License: MIT
Signed-off-by: MrSparc sparciie@yahoo.com
```

At the bottom, that will let us get this merged in.

**Comment by MrSparc** [comment]
Sorry for all this mess with git :(, I promise be more careful and read community docs about it the next time.

**Comment by whyrusleeping** [comment]
No worries! It happens all the time :)

**Comment by Kubuxu** [comment]
You can clean it up with `git reset --soft HEAD~3 && git commit`, and inputting correct commit message.

**Comment by MrSparc** [comment]
I don't know why or how to solve but looks GitCop doesn't like my signature when push a merge required after amend comments :/ 
If needed, you can close this PR and merge this fix by manual, I give you all my credits and rights! :)

**Comment by chriscool** [comment]
@MrSparc when I look at your branch using `git log --oneline --decorate --graph` I see:

```
*   6c27f5f (mrsparc/master) Merge branch 'master' of https://github.com/MrSparc/go-ipfs
|\  
| *   ccbaffc Merge branch 'master' of https://github.com/MrSparc/go-ipfs
| |\  
| | *   e40eb5a Merge branch 'master' of https://github.com/MrSparc/go-ipfs
| | |\  
| * | \   4fc0591 Merge branch 'master' of https://github.com/MrSparc/go-ipfs
| |\ \ \  
| | |/ /  
| |/| /   
| | |/    
| | * 0e5c2ef Fix dist_get script: prevents get_go_vars() returns same %s-%s values twice
| * | c5e0927 Fix dist_get script: prevents get_go_vars() returns same %s-%s values twice
| |/  
* | 80d036e Fixes dist_get script: prevents get_go_vars() returns same %s-%s values twice
|/  
* 685cd28 (HEAD -> master, tag: v0.4.3-rc3, origin/master, origin/HEAD) ipfs version 0.4.3-rc3
```

I think you might want to clean that up and that may fix the GitCop problems too.

**Comment by Kubuxu** [comment]
@chriscool I just reapplied the patch over here for him: https://github.com/ipfs/go-ipfs/pull/3079

**Comment by chriscool** [comment]
(Also 0e5c2ef, which is part of your branch, still has no "License" and "Signed-off-by" trailers.)

@Kubuxu thanks! I am just explaining why GitCop is not happy.

**Comment by MrSparc** [comment]
Thanks @chriscool for your explanation and sorry again for all this mess wit git... 
I tried to fix the sign-off comment and the multiple merges but the rebase on my repository went wrong...  
The original patch will be handled at #3079 thankfully by @Kubuxu so this PR can be closed.

**Pull request closed without merging**
