### PR TITLE
Edited following @chriscool feedback

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/ipfs/go-ipfs/commit/dec4a72da1342eb750c581fb5072fccbdd79281f

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by RichardLitt** [comment]
cc @chriscool

**Comment by chriscool** [comment]
Yeah, LGTM.

**Comment by whyrusleeping** [comment]
@RichardLitt looks like some tests are failing, could you go ahead and fix those before we merge this?

**Comment by whyrusleeping** [comment]
I don't know if I like this phrasing, its unclear to me what it means

**Comment by Ape** [comment]
I think the previous version is better. We want to say that you can use SIGTERM or SIGINT to shutdown the daemon, for example with Ctrl-C. And that another signal will kill it forcibly.

**Comment by chriscool** [comment]
This is nice as it teaches the user things, but then why not:

>To shutdown the daemon, send ```SIGTERM``` or ```SIGINT``` signal to it. This can be done using respectively ```kill``` or ```Ctrl-C```. It may take a while for the daemon to shutdown gracefully, but it can be killed forcibly by sending the signal again.

Also it doesn't address people on Windows who may not use the command line at all.

**Comment by Ape** [comment]
We don't have to say that ```Ctrl-C``` sends a ```SIGINT```. On the other hand, we should specify ```SIGTERM``` since it can be sent with any external program.

>To shutdown the daemon, press ```Ctrl-C``` or send ```SIGTERM``` signal to it (e.g. with ```kill```). It may take a while for the daemon to shutdown gracefully, but it can be killed forcibly by pressing ```Ctrl-C``` again.

**Comment by RichardLitt** [comment]
I've edited it, again. Thoughts?

**Comment by Ape** [comment]
I would prefer the version on my previous comment, because we don't really need to say that ```Ctrl-C``` emits a ```SIGINT```, but instead try to keep it simple and short. This isn't very important issue, though.

Also, I think you duplicated the paragraph there.

**Comment by RichardLitt** [comment]
Changed. Ctrl+C only works on unix, but it is useful for some users. I think this one is fine.

**Comment by rht** [comment]
It'd be useful / more discoverable to add a brief line such as "hit C-c again to force-shutdown the daemon" at https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/daemon.go#L153.

**Comment by rht** [comment]
Other than the small UX comment, this LGTM.

**Comment by jbenet** [comment]
LGTM. 

> It'd be useful / more discoverable to add a brief line such as "hit C-c again to force-shutdown the daemon" at https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/daemon.go#L153.

Yes, specifically at https://github.com/ipfs/go-ipfs/blob/master/cmd/ipfs/daemon.go#L163

**Pull request merged**
