### PR TITLE
use net/url to escape paths in web-ui

### PR DESCRIPTION
**Pull request by noffle**
This is @adrian-bl's work on https://github.com/ipfs/go-ipfs/pull/2092 with his test patch added and rebased against master.

Addresses https://github.com/ipfs/go-ipfs/issues/2061.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
theres something weird here with git submodules...

**Comment by noffle** [comment]
You're right: I forgot to remove the inner `.git` directory.

**Comment by whyrusleeping** [comment]
@noffle circleCI isnt super happy about that

**Comment by noffle** [comment]
Should be good now. I had revendored by hand and didn't re-apply the unescaping change.

**Comment by whyrusleeping** [comment]
Cool, LGTM. thanks @noffle and @adrian-bl !

**Pull request merged**
