### PR TITLE
metrics: rework prometheus integration

### PR DESCRIPTION
**Pull request by lgierth**
The peers_total metric used to live deep down in libp2p,
it is now nicely separated, and there's space for even
more metrics. Tests are a good thing too.

The Prometheus library is now gx'ed too. I pinned it on biham.

License: MIT
Signed-off-by: Lars Gierth <larsg@systemli.org>

### CODE REVIEW

**Comment by lgierth** [comment]
Build red -- need to gx the dependencies as well, mh.

**Comment by whyrusleeping** [comment]
@lgierth check out `gx-go import`

**Comment by whyrusleeping** [comment]
that import command has a flag to take a json map of packages to existing hashes, so if you want to reuse a package thats already vendored, you should add it there

**Comment by lgierth** [comment]
Heeere we go -- with gxified prometheus dependencies and all.

**Comment by whyrusleeping** [comment]
LGTM, nice work :)

**Pull request merged**
