### PR TITLE
Add --empty-repo option for init (#1559)

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: efa7231467a2a9cba8170180e33fd1e33fcfc357
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by prusnak** [comment]
Seems that one Travis test exited with a weird error, most probably unrelated to the pull request:

https://travis-ci.org/ipfs/go-ipfs/jobs/76375495

The other three seem fine.

**Comment by jbenet** [comment]
@prusnak LGTM. i think needs a test to make sure we dont add regressions. (see the sharness tests. just make a new file, probably based on the `repo` one, or init or daemon. and test the initial state after initing with the option.

**Comment by chriscool** [comment]
Here is a test I wrote for this:

https://github.com/chriscool/go-ipfs/commit/872daf8357ced1dbb4f019619dec25deef06a6b9

**Comment by chriscool** [comment]
@prusnak and @jbenet what do you want to do on this?
@prusnak feel free to cherry pick the commit that contains the test and push it into this branch.
Otherwise I can also create a PR from the empty-repo branch on my fork (https://github.com/chriscool/go-ipfs/commits/empty-repo).

**Comment by jbenet** [comment]
the PR LGTM. +1 to having tests before merging it. whoever does it first, wins a :star:

**Comment by prusnak** [comment]
Pulled chriscool/empty-repo into this PR.

**Comment by jbenet** [comment]
ok thanks @prusnak

**Pull request merged**
