### PR TITLE
update go-ipfs-cmds to 0.4.13

### LINKED ISSUE #4360: sending SIGINT to `ipfs repo verify` incorrectly reports verify complete when daemon isn't running
#### Version information:
go-ipfs version: 0.4.12-rc1-
Repo version: 6
System version: amd64/windows
Golang version: go1.9

#### Type:
Bug

#### Severity:
Medium

#### Description:
Sending a SIGINT using CTRL+C to `ipfs repo verify` without the daemon running causes the command to report

```
verify complete, all blocks validated.
```

even though the command did not get a chance to complete. Before it reports this message, it appears to keep processing blocks for a few seconds until it finally stops.

When the daemon is running, canceling the `ipfs repo verify` command instead spits out an error. I'm not sure if this is desirable, but at least it doesn't report that the verify is complete.

```
21:09:37.028 ERROR commands/h: net/http: request canceled client.go:247
Error: net/http: request canceled
```

Perhaps the output in both cases (daemon running and stopped) should report something like

```
verify interrupted, not all blocks were validated
```

### PR DESCRIPTION
**Pull request by keks**
Hopefully fixes #4360 and #4436.

### CODE REVIEW

**Comment by keks** [comment]
So *sometimes* this one happens:
```
*** test/sharness/t0065-active-requests.sh ***

[snip]

ok 4 - api file shows up

[snip]

expecting success: 
  kill $LOGPID
  go-sleep 0.5s
  kill $LOGPID
  wait $LOGPID || true
Error: request canceled
./t0065-active-requests.sh: 4: kill: No such process
ok 13 - kill log cmd
expecting success: 
  ipfs diag cmds > cmd_out3
Error: api not running
not ok 14 - long running command inactive
#	
#	  ipfs diag cmds > cmd_out3
#	
expecting success: 
  grep "log/tail" cmd_out3 | grep "false"
not ok 15 - command shows up as inactive
#	
#	  grep "log/tail" cmd_out3 | grep "false"
#	
expecting success: 
    kill -0 $IPFS_PID
  
./t0065-active-requests.sh: 2: kill: No such process
not ok 16 - 'ipfs daemon' is still running
#	
#	    kill -0 $IPFS_PID
#	  
expecting success: 
    test_kill_repeat_10_sec $IPFS_PID
  
./t0065-active-requests.sh: 263: kill: No such process
ok 17 - 'ipfs daemon' can be killed
# failed 3 among 17 test(s)
1..17
```
The reason is a data race in the http ResponseEmitter, working on it...

**Comment by whyrusleeping** [comment]
@keks does this supercede #4455 ?

**Comment by Stebalien** [comment]
@whyrusleeping yes. Waiting on https://github.com/ipfs/go-ipfs-cmds/pull/38

**Comment by Stebalien** [comment]
Bundled in https://github.com/ipfs/go-ipfs/pull/4453

**Pull request closed without merging**
