### PR TITLE
dag/get: accept paths and not just cids

### LINKED ISSUE #3500: Shouldn't dag api take paths, not just CIDs?
#### Version information:

```
> ipfs version --all
go-ipfs version: 0.4.5-dev-4cb236c
Repo version: 4
System version: amd64/darwin
Golang version: go1.7
```

#### Type:

This should work
```
http://127.0.0.1:5001/api/v0/dag/get?arg=/ipfs/QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
```
I get

```
{"Message":"selected encoding not supported","Code":0}
```

and
```
http://127.0.0.1:5001/api/v0/dag/get?arg=QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
```
works fine :/

### PR DESCRIPTION
**Pull request by whyrusleeping**
resolves #3500 

License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by lgierth** [comment]
LGTM :+1: 

It should also get support for proper paths once we've figured out which namespace to use.

**Comment by lgierth** [comment]
Actually this doesn't resolve #3500 since it only supports `Qmfoobar/a/b/c` and not `/ipfs/Qmfoobar/a/b/c`

**Comment by whyrusleeping** [comment]
@lgierth does `path.Parse` really not handle `/ipfs/QmFooBar` paths?

**Comment by whyrusleeping** [comment]
@lgierth No, this totally works: https://github.com/ipfs/go-ipfs/blob/master/path/path.go#L95

**Comment by lgierth** [comment]
Uggh sorry, I must have used the wrong binary again...

```sh
> ipfs dag get /ipfs/$(echo foo | ipfs add -q)
{"data":"CAISBGZvbwoYBA==","links":[]}

> ipfs dag get /ipns/ipfs.io/theme
Error: selected encoding not supported
```

I was pretty sure I got the same error with /ipfs too -- all good now! :+1:

**Pull request merged**
