### PR TITLE
Fix text contrast for dark mode

### LINKED ISSUE #8024: README in github dark mode
no biggie - just noticed it - since github has a dark mode now the contrast here can be a problem:

Selection_075

a simple color change can fix this

### PR DESCRIPTION
**Pull request by RubenKelevra**
fixes #8024

### CODE REVIEW

**Comment by RubenKelevra** [comment]
Todo: Add CID to the IPFS-Websites cluster

**Comment by ligi** [comment]
Thanks for the fast PR - but I think the contrast should be even stronger

**Comment by RubenKelevra** [comment]
ok

**Comment by RubenKelevra** [comment]
@ligi not super beautiful but the contrast is there :D

https://github.com/ipfs/go-ipfs/blob/550195129908b2e8f502bd7fd3e1ea46a0cf38d0/README.md

**Comment by ligi** [comment]
I think it's nice now!

**Comment by RubenKelevra** [comment]
I think this one is much better:

https://github.com/ipfs/go-ipfs/blob/db58dbc6257a5319564fd80b50770ce012e5af5f/README.md

**Comment by RubenKelevra** [comment]
@ligi your opinion?

**Review by Stebalien — APPROVED** [review]
The current version LGTM. I'm going to merge this as "it works" and we can always make followup PR to increase the contrast.

**Comment by Stebalien** [comment]
@RubenKelevra I'm having trouble finding the xcf version on the network.

**Comment by RubenKelevra** [comment]
> @RubenKelevra I'm having trouble finding the xcf version on the network.

Strange, I actually pinned it on two nodes and pinata to be sure it's available. 🤔

Via the pinata gateway I'm able to download it:

https://gateway.pinata.cloud/ipfs/bafykbzacecaesuqmivkauix25v6i6xxxsvsrtxknhgb5zak3xxsg2nb4dhs2u

**Comment by Stebalien** [comment]
Ah, and our gateways are peered with pinata which makes everything "just work" (unless I want to pin it from my machine...).

This appears to fall into the category of "pinata has too many things to announce to the network".

**Pull request merged**
