### PR TITLE
add http://{127.0.0.1,localhost}[:5001] as allowed default CORS referer

### LINKED ISSUE #1883: webui broken?
can't use the webui in 0.3.8 -- looks like some permission errors-- others seeing this?

### PR DESCRIPTION
**Pull request by MichaelMure**
Fix #1883 and #1839 for me.

License: MIT
Signed-off-by: Michael Muré <mure.michael@gmail.com>

### CODE REVIEW

**Comment by rht** [comment]
And https://github.com/ipfs/webui/pull/82

**Comment by lgierth** [comment]
I like!

Maybe we should do the same for the gateway? And also add :8080 to the API headers, to make the API-via-Gateway work?

**Comment by jbenet** [comment]
@MichaelMure yeah-- there is something very odd going on. this is supposed to happen naturally: https://github.com/ipfs/go-ipfs/blob/27eece3e81f4e946db4294702c9ac39bd86ccce6/core/corehttp/commands.go#L70

**Comment by jbenet** [comment]
im not sure adding this to config is the right way-- i think we should fix the bug in the code.

**Comment by lgierth** [comment]
Oh @jbenet is right, we should fix the code

**Comment by MichaelMure** [comment]
Soooo, what happen is that the default origins are stored as string with a placeholder for the port (for instance "http://127.0.0.1:<port>"). The `patchCORSVars` is here to replace `<port>` with the correct port. This function use a sample net.Listener to find the right port. There is a race condition somewhere, and the port selected end up being `8080` instead of `5001`.

**Comment by rht** [comment]
`patchCORSVars` is called for each http api and gateway that there should be a race condition?

I tried `fmt.Println`-ing the port after this [line](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/commands.go#L85), I got both 5001 and 8080.

**Comment by jbenet** [comment]
ah interesting. that's likely the problem!

**Comment by jbenet** [comment]
this is a priority fix as this is screwing up uses of the API. anybody have a bugfix?

@whyrusleeping if we find a bugfix in the next couple of days can we fit this into 0.3.10 along with the other api fix?

cc @dignifiedquire and @diasdavid as they're probably interested

**Comment by diasdavid** [comment]
SGTM! :)

**Comment by Dignifiedquire** [comment]
Would love to have a fix for this yes, can't comment on race conditions in go code I'm afraid ;)

**Comment by rht** [comment]
I noticed the `defaultLocalhostOrigins` slice was mutated in https://github.com/ipfs/go-ipfs/blob/792da9d87587e28d65b98a28fa4cc2d20388ccca/core/corehttp/commands.go#L95 regardless of the rwmutex protection from (https://github.com/ipfs/go-ipfs/commit/45550858449935c831c037e5061912c7fb28175f).

A possible fix: https://github.com/rht/go-ipfs/tree/fix/corsconfig (https://github.com/rht/go-ipfs/commit/e7dee98457f1696221de05c315458fa7c9d7240e). I checked the `c.AllowedOrigins()`, with this fix they show 5001 for 8080 for each api and gateway. Previously it depends on which one mutates the slice first (the race condition described by @MichaelMure). The rwmutex thing is probably unnecessary.

**Comment by parkan** [comment]
+1 for this, webui is broken for me

**Pull request closed without merging**
