### PR TITLE
README.md: Add MacPorts to install section

### PR DESCRIPTION
**Pull request by ShadSterling**

### CODE REVIEW

**Review by Stebalien — COMMENTED** [review]
Thanks!

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Hm. This might need another line in the release checklist to make a PR against https://github.com/macports/macports-ports/blob/master/net/ipfs/Portfile.

**Comment by Stebalien** [comment]
cc @sirn 

If you're still maintaining this, the build script should probably download from https://dist.ipfs.io/go-ipfs/v0.9.0/go-ipfs-source.tar.gz (a vendored source tarball).

**Comment by aschmahmann** [comment]
@Stebalien is this ready to merge?

**Comment by Stebalien** [comment]
Upstream isn't being kept up to date and I'm not able to do that. I'll ask to see if anyone on the team wants to maintain it.

**Comment by sirn** [comment]
Oops sorry I'll take a look.

**Comment by sirn** [comment]
@Stebalien MacPorts maintainer @herbygillot worked on this in https://github.com/macports/macports-ports/pull/11814 (sorry and huge thanks!) I think this PR should be ready as soon as MacPorts one is merged.

**Comment by Stebalien** [comment]
Thank you so much!

**Pull request merged**
