### PR TITLE
Add err check to coremock node init

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by jbenet** [comment]
Do this over 0.4.0. remember we dont want to rebase all the things

**Comment by rht** [comment]
At this point anything that touches logging will cause merge conflict.

In fact, most of the conflicts with 0.4.0 are logging.
Tried a rebase https://github.com/rht/go-ipfs/tree/dev0.4.0-rebase with the changelog:
1. https://github.com/wking/go-ipfs/commit/1d404a7b0ce4576adf3ec2e1275b1b00280c7392
2. https://github.com/ipfs/go-ipfs/commit/7eaebfadd95f91a6e7668df9d23278f5bf7844d3 (because shellquote was added)
3. https://github.com/ipfs/go-ipfs/commit/9974f56bc3425e31ecc1b28783e4c78c515c3df6
4. https://github.com/ipfs/go-ipfs/commit/2f3f58263783a27abffdbbcf4d524cfd5007dda0 (There was a WriteLen refactor)
5. https://github.com/ipfs/go-ipfs/commit/1cb0ee2cf27d3ad00d314d6b5f331961c3526f67 (because go-log was added)
6. https://github.com/ipfs/go-ipfs/commit/4f2a22616313b0115ce64160aad71f8abce008f1 (because go-log was added)
7. https://github.com/ipfs/go-ipfs/commit/9d2bd0528d67e18b8c030954e0ba42962f0b487c (because go-log was added, leveldbDS no longer a field of FSRepo, ds.Close method, redo https://github.com/ipfs/go-ipfs/commit/35a5ca0ef5776573e4b161dde315e602d663e5af)
8. https://github.com/ipfs/go-ipfs/commit/681c5d903939f246ca05f459972ef63140c2dec0 (because go-log was added)
9. https://github.com/ipfs/go-ipfs/commit/6e49de018cb701502afa04a7a24307b2c2da6c5a (comment rename ThreadSafeDatastore -> Datastore, and uses the go-datastore in 0.3.8-dev branch because it is most likely more up to date, I can't find go-datastore@47af23f2ad09237ccc09c586c118048e2b39b358)
10. https://github.com/ipfs/go-ipfs/commit/45d3d5bef9cffe76512ebc4a9c47118f6367a9ea (go-datastore in 0.3.8-dev is newer)
11. https://github.com/ipfs/go-ipfs/commit/72c0282346fb7b54f2b9b26e30787f32a0919410 (redo https://github.com/ipfs/go-ipfs/commit/192ee643380d4a7a20b08405806c8eb91ddb55c7)
12. https://github.com/ipfs/go-ipfs/commit/de41a9feaec5555e7d6467ae322029bc2bbc7c58 (module conflict unixfs)
13. https://github.com/ipfs/go-ipfs/commit/d69891f98177fee9185dc3eb94db9aaf57d677dc (unixfs -> uio)

The trickiest part is in the datastore conflicts, but can't be sure unless @whyrusleeping is doing it.

**Comment by whyrusleeping** [comment]
if you do this on master, it will conflict with every single commit on 0.4.0 that touches any of the same code you touched here.

**Comment by rht** [comment]
Will redo the PR after 0.4.0 is merged. Also it's not performance critical, and doesn't fix any bugs.

**Comment by jbenet** [comment]
sounds good

**Comment by whyrusleeping** [comment]
was this always just  a three line change? I'm totally fine merging just this.

**Comment by rht** [comment]
Because the commits with conflicts were removed.

**Pull request merged**
