### PR TITLE
refactor(mfs): use mfs type helper

### PR DESCRIPTION
**Pull request by overbool**
Fixes: https://github.com/ipfs/go-mfs/issues/22

License: MIT
Signed-off-by: Overbool <overbool.xu@gmail.com>

### CODE REVIEW

**Comment by Stebalien** [comment]
go-mfs is up-to-date. It's just that we need the `pdir` variable.

**Comment by schomatis** [comment]
Oh, I missed that, I now see that those were commited directly to `master`, (pending the final tests) RFM then.

**Comment by Stebalien** [comment]
> Oh, I missed that, I now see that those were commited directly

Yeah, I generally just push gx-workspace updates to master. I guess I could make PRs and then merge them locally but when I have to change 50+ repository, I stop caring.

**Comment by Stebalien** [comment]
So, I agree that those helpers are useful but I'm not sure *this* change actually improves the code. Instead of having clearly safe type switches, we're now just asserting the type.

**Comment by schomatis** [comment]
> Instead of having clearly safe type switches, we're now just asserting the type.

Agreed. Those assertions are pretty safe because we are checking the type but still, this is not adding much code clarity, we're still type casting the `FSNode` interface to do pretty much anything. We should first extend that interface (e.g., add access to name, parent and other information common to both file and directory) for these helper functions to be useful.

Closing this for now while I work on the MFS side (thanks anyway @overbool!).

**Pull request closed without merging**
