### PR TITLE
take a pin lock while performing ipfs files operations

### PR DESCRIPTION
**Pull request by whyrusleeping**
This should make running a gc not harm programs using the ipfs files api.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
cc @RichardLitt

**Comment by jbenet** [comment]
@whyrusleeping this needs a rebase?

**Comment by jbenet** [comment]
@whyrusleeping does this mean current master is unsafe regarding this?

**Comment by RichardLitt** [comment]
@whyrusleeping why the cc?

**Comment by whyrusleeping** [comment]
closed, we don't actually want this

**Pull request closed without merging**
