### PR TITLE
Feat/0.4.5 changelog

### PR DESCRIPTION
**Pull request by whyrusleeping**
First pass at cleaning up the PR list into a changelog. cc @lgierth @Kubuxu

### CODE REVIEW

**Comment by Kubuxu** [comment]
I am not a fan of those empty check mark boxes.

**Comment by whyrusleeping** [comment]
oh, yeah. didnt look at it in non-text mode. Lemme remove those

**Comment by whyrusleeping** [comment]
Removed the checkboxes

**Comment by Kubuxu** [comment]
Your sed eat up some letters from the middle of the words.

**Comment by lgierth** [comment]
The IPLD and deps sections should be reworded before release, but this LGTM :+1:

**Pull request merged**
