### PR TITLE
[WIP] Strict Cids

### PR DESCRIPTION
**Pull request by kevina**
Uses https://github.com/ipfs/go-cid/pull/50 and partly reverts #4751.

### CODE REVIEW

**Comment by kevina** [comment]
And before anyone points it out, I will fix my commits. :)

**Comment by Stebalien** [comment]
@kevina what's the status of this?

**Comment by kevina** [comment]
Stalled.  Mainly because I wasn't sure how to test the migration.  I get back to it after the base32 migration (and likely the switch to using a string representation for Cid's and Multihashes) is done.

**Comment by Stebalien** [comment]
Closing for now as this will need a rebase. DO NOT DELETE

**Pull request closed without merging**
