### PR TITLE
Clarify error message on merkeldag not found

### PR DESCRIPTION
**Pull request by timthelion**
Fixes https://github.com/ipfs/website/issues/85

License: MIT
Signed-off-by: Timothy Hobbs <timothyhobbs@seznam.cz>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This is a tough one, because `ErrNotFound` could potentially be returned when an online search fails too.

**Comment by kevina** [comment]
I would be inclined to leave the error message alone and maybe add more helpful information upstream.

One thing I would do is make ErrNotFound a class so it can include the Cid of the object not found.  That would break a lot of code though as we would need to either add a IsNotFound helper function or (less preferably) try and cast to the ErrNotFound class.

**Comment by whyrusleeping** [comment]
@kevina I like that idea, it mirrors closely the standard libs `os.IsNotFound(err)` paradigm.

**Comment by kevina** [comment]
@whyrusleeping that was the idea (mirror the `os.IsNotFound(err)` paradigm)

**Comment by timthelion** [comment]
Hm, I'm not familiar with golang error classes and am not sure that it 
is worth my time to learn them. Should I close this?

**Comment by kevina** [comment]
> Hm, I'm not familiar with golang error classes and am not sure that it
> is worth my time to learn them.

Go lang does not really have error classes.  What is needed is something like this:
```
type ErrNotFound struct {
  Cid *cid.Cid
}
func (e ErrNotFound) Error() string {return fmt.Sprintf("merkledag: not found: %s", e.Cid)}
func IsNotFound (e error) bool {_, ok := e.(ErrNotFound); return ok}
```

> Should I close this?

It is up to you.  I will be happy to implement the above if you don't have the time.

**Comment by kevina** [comment]
Also note that the ErrNotFound to `go-ipld-format` which means fixing this error message no requires a change to that package.

**Comment by hsanjuan** [comment]
Thanks @timthelion. I think we can close this one as the approach was not the best, but I'll follow up other other approaches that were tried and see if the issue can be picked up again.

**Pull request closed without merging**
