### PR TITLE
Swap all 'crypto/rand' rng in tests with 'math/rand'

### PR DESCRIPTION
**Pull request by rht**
#143

### CODE REVIEW

**Comment by rht** [comment]
I wonder if ```NewTimeSeededRand``` should be renamed to explicitly show that it outputs bytes? Other than this, there are ```SeededRand``` and default ```math.rand``` for integers, and finally ```crypto/rand```.

All ```math.rand``` should be replaced with ```SeededRand```.

Should the list be: ```RandomBytes``` (```NewTimeSeededRand```), ```RandomIntegers``` (```SeededRand```), and ```crypto/rand```?

**Comment by rht** [comment]
(adding one more commit to see if the go test fails again)

**Comment by rht** [comment]
Test is still not faster than expected standard deviation.

**Comment by jbenet** [comment]
hm. i think it makes the most difference in any keygen things -- there may also be other hardware based differences (diffs between systems where the os is serious about entropy collection or not)

**Pull request merged**
