### PR TITLE
Dignifiedquire fix/access controll headers

### PR DESCRIPTION
**Pull request by whyrusleeping**
this is #1979 I just hardcoded the values.

@Dignifiedquire, give this a shot

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping tests fail.

**Comment by whyrusleeping** [comment]
@jbenet 
image

**Comment by Dignifiedquire** [comment]
Looks good. @diasdavid Any good ideas on how to run the js-ipfs-api tests on this branch?

**Comment by diasdavid** [comment]
@Dignifiedquire you can do it by:

1. pull the branch
2. go install ./cmd/ipfs
3. cp $GOPATH/bin/ipfs js-ipfs-api/node_modules/go-ipfs/bin/ipfs
4. npm test on js-ipfs-api

This way the binary used by ipfsd-ctl is the one you just copied

**Comment by Dignifiedquire** [comment]
@diasdavid I just remembered there is a much easier way now: 

```bash
$ IPFS_EXEC=$GO_PATH/bin/ipfs gulp test
```

**Comment by Dignifiedquire** [comment]
@whyrusleeping all good from my side, just tested it with js-ipfs-api tests.

Also tests are still failing ;)

**Comment by jbenet** [comment]
check that out-- appveyor tests! 

wish they didnt run without the appveyor.yml ... those will fail until #1982 is fixed.

**Comment by whyrusleeping** [comment]
@jbenet rfm?

**Comment by jbenet** [comment]
Before we merge this, i saw on IRC that people couldn't find where these headers are used-- are these actually even necessary? or are they vestigial? thoughts @Dignifiedquire ?

**Comment by diasdavid** [comment]
@jbenet @whyrusleeping this `allow-headers` will enable ipfs-api in the browser to access `x-stream` and `x-chuncked` to make this assertion https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L29-L30

**Comment by jbenet** [comment]
@diasdavid 

> that people couldn't find where these headers are used

I mean in go-ipfs -- why are we using them? why can't we remove them altogether?

**Comment by diasdavid** [comment]
The `Allow-` headers will be only useful from a browser environment, yes. The `x-chunked` and `x-stream` are used by everyone that talks with the API. Would you prefer that the `ipfs-api` do the call to set these headers when it is instantiated?

**Comment by jbenet** [comment]
@diasdavid 

> The x-chunked and x-stream are used by everyone that talks with the API.

But _why_ -- _why_ do they need to be there?

**Comment by whyrusleeping** [comment]
@jbenet @Dignifiedquire update here? do we have a decision?

**Comment by jbenet** [comment]
Yeah LGTM

**Comment by Dignifiedquire** [comment]
whoooo :tada:

**Pull request merged**
