### PR TITLE
core/commands/pubsub.go: flush output before iterating over received messages

### PR DESCRIPTION
**Pull request by keks**
Fixes go-ipfs-api hanging on pubsub tests (currently all tests fail over there because of this)

### CODE REVIEW

**Comment by keks** [comment]
This should fix https://github.com/ipfs/go-ipfs-api/issues/62

**Comment by lgierth** [comment]
LGTM 👍 -- could you squash the commits?

**Comment by whyrusleeping** [comment]
@keks can we run the js-ipfs-api tests too?

**Comment by keks** [comment]
@whyrusleeping js-ipfs-api tests pass for me 🎉

**Comment by whyrusleeping** [comment]
@Stebalien @keks whats with the strange syscall/unix related changes here?

**Comment by keks** [comment]
That is stebalien's commit. After squashing it also showed up interested pretty, but it's already in. Not entirely sure why it's here though. 

Am 21. November 2017 18:33:30 MEZ schrieb Whyrusleeping <notifications@github.com>:

**Comment by Stebalien** [comment]
This is the second time this week I've seen something like this happen on github...

**Comment by Stebalien** [comment]
Interesting, rebasing on master seemed to fix it.

**Comment by keks** [comment]
> Interesting, rebasing on master seemed to fix it.

Okay, I'll try to remember to do this after squashing.

**Pull request merged**
