### PR TITLE
Fix/namesys validation

### PR DESCRIPTION
**Pull request by dirkmc**
Update go-ipfs to use new validation function format in libp2p/go-libp2p-record#9

### CODE REVIEW

**Comment by vyzo** [comment]
Just a heads up -- @Stebalien (rightfully) does like the accessor functions in the new record:
https://github.com/libp2p/go-libp2p-record/pull/11

**Comment by dirkmc** [comment]
Ok I will fix :)

**Comment by vyzo** [comment]
He is also keen on splitting off the namespace: https://github.com/libp2p/go-libp2p-record/pull/12

**Comment by dirkmc** [comment]
This PR is getting messy, moving to https://github.com/ipfs/go-ipfs/pull/4597

**Pull request closed without merging**
