### PR TITLE
Integrate go-dag-jose plugin

### PR DESCRIPTION
**Pull request by smrz2001**
# Integrate `go-dag-jose` plugin

## Description

This PR integrates the `go-dag-jose` plugin into IPFS.

## How Has This Been Tested?

- [x] `ipfs dag put --store-codec dag-jose` and `ipfs dag get` work correctly
- [x] All IPLD `dag-jose` [fixtures](https://github.com/ipld/ipld/tree/dag-jose-fixtures) work correctly

## Definition of Done

- [x] My code follows conventions, is well commented, and easy to understand
- [x] My code builds and tests pass without any errors or warnings
- [x] I have tagged the relevant reviewers
- [x] The changes have been communicated to interested parties
- [x] Use the released version of `go-dag-jose`

## References:

- https://github.com/ceramicnetwork/go-dag-jose/pull/23

### CODE REVIEW

**Comment by warpfork** [comment]
@aschmahmann suggests that we should also add a smoke tests that all the wiring works, by using a sharness test: https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0280-plugin-git.sh is an example for git.  Can we quickly add something similar for this?

**Comment by smrz2001** [comment]
> @aschmahmann suggests that we should also add a smoke tests that all the wiring works, by using a sharness test: https://github.com/ipfs/go-ipfs/blob/master/test/sharness/t0280-plugin-git.sh is an example for git. Can we quickly add something similar for this?

Had to wrangle bash into submission so took a little longer than I expected. Please take a look @aschmahmann and @warpfork.

Also, I do see the failing CI tests so will work on fixing them ASAP.

**Comment by BigLep** [comment]
@smrz2001: @aschmahmann is going to rebase first since it's quite possible the CI failures aren't your fault.  It looks like you may have forked at an inopportune time while we were getting interoperability tests to pass.

**Comment by aschmahmann** [comment]
@smrz2001 I don't have permissions to push to your branch can you give me permissions (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) or do the rebase yourself?

**Comment by smrz2001** [comment]
Thanks, @BigLep.

Hey @aschmahmann, just looking at this. I can't find that checkbox for some reason 😕 Give me a couple min to figure this out, otherwise I'll try the rebase myself.

**Comment by smrz2001** [comment]
omfg, I _hate_ WSL (Windows Subsystem for Linux) sometimes. One of the submodules keeps messing up my attempts to do anything because it shows up as a diff when there is none.

I just added you to my fork, @aschmahmann.

**Review by aschmahmann — APPROVED** [review]

**Comment by stbrody** [comment]
🥳 🎉 

Thanks @aschmahmann for the quick turnaround!

**Pull request merged**
