### PR TITLE
Godeps maintenance

### PR DESCRIPTION
**Pull request by cryptix**
Main motivation was to have everything at latest master and to move away from `code.google.com/p`

- [x] moved (go)goprotobuf to github location
- [x] added iptb to the `sadhack` package - 'make vendor' can't see it otherwise
- [x] Followed up #1098 so that all its code is dropped

 I also experimented with the [eg](https://github.com/golang/tools/blob/master/refactor/eg/eg.go#L18) tool [some time ago](https://github.com/ipfs/go-ipfs/compare/errRampage). Want to do that again.

- [x] updated all dependencies to latest master
- [ ] `hashicorp/mdns` uses a fork of `go.net` which isn't up to date - [issue](https://github.com/hashicorp/mdns/pull/37)
- [ ] we still use `go-uuid` from `code.google.com` in `Godeps/.../github.com/jbenet/go-datastore/key.go` and `./thirdparty/eventlog/metadata.go`. There are [dozens](http://go-search.org/search?q=RFC%204122) of forks and other versions. Maybe we can find one with an identical interface and drop that in.

I think we can merge this now and wait for hashicorp/mdns#37 to proceed with the rest.

### CODE REVIEW

**Comment by jbenet** [comment]
This LGTM. sounds good about merging now.

**Comment by jbenet** [comment]
Dont really care what we do about `uuid` -- whatever works.

in general I'm all for staying up to date (cause bugs get fixed) though sometimes, newer isn't always better -- sometimes newer releases are actually more broken. We should always verify that the changelogs show improvement. (thoughts on these @cryptix ?)

**Comment by wking** [comment]
On Tue, Apr 28, 2015 at 10:41:37AM -0700, Juan Batiz-Benet wrote:
> We should always verify that the changelogs show improvement.

I don't know anything about our dependencies here, but if they are
cutting versioned releases it would be nice to bump our vendored
version to their latest point release, instead of their latest master.
That might also make finding changelogs/release-notes easier to figure
out what has changed.

**Comment by jbenet** [comment]
yeah, point releases may be a safer strategy.

**Comment by jbenet** [comment]
@dylanPowers it may be useful to compile a lot of these workflow preferences/workflows (like how to vendor, what to vendor, [requirement that all commits pass](https://github.com/ipfs/go-ipfs/pull/1138#issuecomment-97151404), etc) into some doc in community repo.

**Comment by cryptix** [comment]
> in general I'm all for staying up to date (cause bugs get fixed) though sometimes, newer isn't always better -- sometimes newer releases are actually more broken. We should always verify that the changelogs show improvement. (thoughts on these @cryptix ?)

re things can get worse: Agreed, but tracking the changelog of every package down our import tree is a lot of work. IMHO we should classify our dependencies and act accordingly - at least by direct and indirect imports.

For instance, currently our most fragile dependencies are `bazil.org/fuse`, `github.com/syndtr/goleveldb/leveldb` and `github.com/hashicorp/yamux`, I would say. Breaking changes to these are dangerous, afaict the rest is mostly utility and imports by other imports.

Personally, I would like to do this: Move everything to latest (maybe bi-)weekly, dog food our tests to catch regressions (we should also deploy benchcmp on our next gen ci) and deploy a 'staging beta' test network of maybe 10 nodes with the newest version of the deps, running profiling for a week. If it's green push the updates into the next release.

For updating to latest master I'd use these rules:

1) indirect imports stay at the version that the 'parent' wanted.
2) direct import with a version system should just bump minor and patch versions and have good reasons for a major upgrade.
3) direct imports without a version just get bumped to master.

All of these defiently exceeds my current `Go-Package-Store && godep update...` workflow which is a bit foolish but to be honest, but I think it's very important to keep an eye on the dependencies and not loose track of them, especially in alpha stage where I feel that 'We finished these 5 features over the last x month but in the meantime 2 critical layers of dependency started melting and converging and now we have a lot of adoption and replacement :hankey: on our hands'.

That beeing said, I think the writing is on the [wall](https://github.com/constabulary/gb) for a proper godeps replacement. And I feel like we should [build the tools](https://botbot.me/freenode/ipfs/2015-04-29/?msg=37870021&page=4) we need for it. Maybe also look at shurcool's [gostatus](https://github.com/shurcooL/gostatus) to automate upstream change monitoring.

**Comment by jbenet** [comment]
I'm down to start making the tools we need. 

```
import (
   pkgname "ipfs.io/ipfs/<hash>"
)
```

**Comment by jbenet** [comment]
on the rest-- i think in general the deps tend to either be stable or fail horribly (compiler errors). subtle bugs are way rarer. dont want to add a ton of workflow barriers to updating deps (e.g. pushing to some nodes and waiting for a week). this probably is what we want to do down the road for safety, but right now would slow us down.

i'll merge this

**Pull request merged**
