### PR TITLE
Add tests for recursively pinning a dag (i.e. large file).

### LINKED ISSUE #3688: Ipfs pin add does not fetch raw leaves and thus pins incomplete dag
#### Description:

In local or offline mode:
```
$ random 1048576 56 > afile
$ ipfs add --pin=false --raw-leaves afile
added Qmcd9X534wgpJEojZ1Tukngsrt7ySo1sZ2bBNXuyfBiWcb afile
$ ipfs ls Qmcd9X534wgpJEojZ1Tukngsrt7ySo1sZ2bBNXuyfBiWcb
zb2rhZWKCMcHCfCym41ocwE5BhNQsEVLrwBkLEQaxJzRHHZch 262144 
zb2rhdUpCuyoQPRtvBW8JhAEfPaNd9dBb3QQCMMWYS1V8hjBR 262144 
zb2rhnwyvreekPqEMAbKqs35KYHxkNi7pXED7L2TfJKveTTva 262144 
zb2rhnvAVvfDDnndcfQkwqNgUm94ba3zBSXyJKCfVXwU4FXx2 262144 
$ ipfs block rm zb2rhZWKCMcHCfCym41ocwE5BhNQsEVLrwBkLEQaxJzRHHZch
$ ipfs pin add Qmcd9X534wgpJEojZ1Tukngsrt7ySo1sZ2bBNXuyfBiWcb
pinned Qmcd9X534wgpJEojZ1Tukngsrt7ySo1sZ2bBNXuyfBiWcb recursively
$ ipfs cat Qmcd9X534wgpJEojZ1Tukngsrt7ySo1sZ2bBNXuyfBiWcb
Error: failed to fetch all nodes
```

### PR DESCRIPTION
**Pull request by kevina**
Test for already fixed #3688 

License: MIT
Signed-off-by: Kevin Atkinson <k@kevina.org>

### CODE REVIEW

**Comment by kevina** [comment]
@Kubuxu there is no way this could decrease coverage.  It only adds test!

**Comment by whyrusleeping** [comment]
Codecov sensed a disturbance in the cov, as if hundreds of lines were suddenly untested.

**Comment by Kubuxu** [comment]
For some reason pubsub was suddenly not tested.

**Comment by kevina** [comment]
@Kubuxu, note #3693.  I did accidentally remove a test. :(

**Pull request merged**
