### PR TITLE
pin update fixes

### PR DESCRIPTION
**Pull request by Stebalien**
* flush pins
* correctly print output
* add a sharness test

### CODE REVIEW

**Comment by schomatis** [comment]
@Stebalien What issue/PR/doc would you recommend to learn about the pinning system architecture to better understand the `Flush` call?

**Comment by Stebalien** [comment]
Don't know. Looking at the code, it looks like pins are cached in-memory until the user calls `Flush`. At that point, they're packed into a single protonode and stored in the datastore. `corerepo.Pin` and `corerepo.Unpin` automatically flush (and have a bunch of other interesting logic) but `pinner.{Pin,Unpin,Update}` don't.

**Comment by schomatis** [comment]
There's some interesting logic down there..

**Comment by schomatis** [comment]
> corerepo.Pin and corerepo.Unpin automatically flush (and have a bunch of other interesting logic) but pinner.{Pin,Unpin,Update} don't.

Sounds reasonable.

I can confirm this fixes some weird `unwrapOutput` error.

LGTM, minus the rebase, probably because I took to long to review this, sorry.

**Comment by whyrusleeping** [comment]
will merge in 0.4.18

**Pull request merged**
