### PR TITLE
Close errnotifier chan on err

### PR DESCRIPTION
**Pull request by whyrusleeping**
rebased #2279 on master

### CODE REVIEW

**Comment by rht** [comment]
LGTM sorry didn't rebase #2279.

**Comment by whyrusleeping** [comment]
I'm not sure why the sharness tests keep failing

**Comment by Kubuxu** [comment]
@whyrusleeping I've rebased it and it looks good. RFM?

**Comment by whyrusleeping** [comment]
it looks good minus the part where all the tests fail... hrm..

**Comment by Kubuxu** [comment]
The teamcity passed: http://ci.ipfs.team:8111/viewLog.html?buildId=2262&buildTypeId=GoIpfs_CiTests&guest=1

**Comment by whyrusleeping** [comment]
rebased again, lets see if the tests are more happy

**Comment by Kubuxu** [comment]
Now tests passed. RFM?

**Comment by rht** [comment]
Relevant fact: the errs in circleci/travis-ci-push are orthogonal to the issue supposedly fixed in this pr.

**Comment by whyrusleeping** [comment]
I do think those failures are related. I keep seeing those same failures here (even after multiple rebases), and I don't see them elsewhere.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/134215099/log.txt

**Comment by whyrusleeping** [comment]
closing, this doesnt appear to be an issue anymore

**Pull request closed without merging**
