### PR TITLE
Updated bash auto complete

### PR DESCRIPTION
**Pull request by EliasGabrielsson**
**Review pull request** 

Updated the bash auto complete when I was learning out how ipfs works.
This autocomplete script is rather ambitious integrated to IPFS.

* Added support for Files API with relevant completion.
* Local filesystem completion (eg. ipfs add /users/fileA.txt)
* Dynamic completion for `ipfs update install`
* Merkeldag completion (Partly broken for white spaces, need a little more escaping love on right spots)
* Multiaddr (Need a dirty hack for IP ranges)
* Correct all options and added auto complete.

### Blocker list to get all working:
All bugs are marked with TODO:s inline as well.
* `ipfs diag cmds set-time <time>` - Which format?
* `ipfs files ls -F´ is needed to get correct auto complete to the files api. See: `ls -F`
* The same goes for `ipfs file ls -F´
* Alternatives to `ipfs add --chunker`, just replace placeholder options.

### General CLI feedback:
* Add `ipfs diag sys --pretty` - Printing JSON readable?
* Typo in `ipfs swarm disconnect --help`, change "connect" -> "disconnect"
* `ipfs object patch` Help have different sayings on the order, eg. `hash command` and `command hash`
* There is different sorting of the commands between, -h, --help, ipfs commands
* Add `ipfs update autocomplete` which tries to detect system and shell and give proposal where to install:

```
user $: ipfs update autocomplete
Detected shells: bash, Detected os: Ubuntu
Installing completion file to: /etc/bash_completion.d/ipfs
(Y/n)
```
I guess the completion is stored on ipfs with some sort of reference to each version so only right command is exposed.

### IPLD thoughts
As I have understood bash: `complete -o filenames` autocomplete option it works much  better with single forward-slash. Eg. `/@link/` could work better then `//`. I guess you know that @link is in parity with `ls -F` symlinks? I don't say that the protocol shall be adapted to bash but a lot of computer is running bash and have a working autocomplete is a good thing for adoption. Just one more perspective.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d2e4c1b84d87d01459c1b5c00bfa64f580de90c8
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by EliasGabrielsson** [comment]
@thomas-gardner Looks like we have been doing similar improvements to go-ipfs on the same time.
I guess we need to get the best out of our pull request.

**Comment by Kubuxu** [comment]
Hello, it will be great to improve bash completion.

Current problem with this PR is that it isn't following Contribution Guidelines, more precisely lack of sign-off and license. See the gitcop message to fix this current issue.

Thank you.

**Comment by EliasGabrielsson** [comment]
Recreated this pull request:
https://github.com/ipfs/go-ipfs/pull/3109

**Pull request closed without merging**
