### PR TITLE
Changed 'ipfs gc' to 'ipfs repo gc'

### PR DESCRIPTION
**Pull request by matshenricson**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 35d91af52309e8fe0e16ed7cdc78cf3441e5c6f6
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
@matshenricson You're going to have to sign off your commit to make gitcop happy. Then you will need to re-generate the assets files (check assets/README.md). Once thats done, the last step is to re-run ipfs init to get the new welcome docs hash and update that in `tests/sharness/lib/test-lib-hashes.sh`.

**Comment by jbenet** [comment]
@matshenricson see https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh -- can just run it from `go-ipfs` root dir, amend the commit, and push again. something like:

```sh
cd $GOPATH/src/github.com/ipfs/go-ipfs

# setup the commit hook
wget https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh
chmod +x setup_commit_msg_hook.sh
./setup_commit_msg_hook.sh

# checkout your branch
git checkout quick-start-tiny-fix

# amend the commit
git commit --amend

# force push
git push origin quick-start-tiny-fix -f
```

**Comment by matshenricson** [comment]
Sorry for late reply. I understand that you need these license signoffs,
but it makes the process way way way too complex for me. Sorry guys, maybe
if I ever get interested in this again, but then I'll probably send emails
to you instead.

Good luck!

Mats

**Comment by jbenet** [comment]
@matshenricson it _literally_ takes < 30s to setup the hook + amend commits. and this is standard for many large projects, like Git, the Linux Kernel, Docker, ...

**Comment by matshenricson** [comment]
I like to know what I'm doing, and "hook + amend" are two words I've never
ever heard of before. Probably because I'm way behind the 1337 crowd, but
none the less.

Mats

**Comment by whyrusleeping** [comment]
alright, i'll pick this one up

**Comment by rht** [comment]
< 30s to just write the sign-off by hand.

**Comment by lgierth** [comment]
#2029

**Pull request closed without merging**
