### PR TITLE
pin: fix concurrent map access race

### LINKED ISSUE #6418: fatal error: concurrent map iteration and map write
#### Version information:
```
go-ipfs version: 0.4.21-
Repo version: 7
System version: amd64/linux
Golang version: go1.12.5
```

#### Description:
Regular operation of an IPFS node crashed due to what would appear to be a data race?

Output from the logs can be viewed on IPFS via [Qmb39D6U7YWx49kNSTVFb8iXpZ5zAT8qfdiF2bRraEo9eC](https://ipfs.io/ipfs/Qmb39D6U7YWx49kNSTVFb8iXpZ5zAT8qfdiF2bRraEo9eC)

### PR DESCRIPTION
**Pull request by Stebalien**
Not sure why this didn't show up sooner.

fixes #6418

### CODE REVIEW

**Comment by Stebalien** [comment]
cc @postables for review.

**Comment by zhjgit** [comment]
#6418 After which version, please fix the bug. @Stebalien @postables

**Comment by Stebalien** [comment]
We need to cut a release for this.

**Comment by zhjgit** [comment]
@Stebalien When will go-ipfs 0.18 be released to fix the bug? I need to use it urgently.

**Comment by Stebalien** [comment]
Please build the latest master.  We're planning on cutting an RC for the next release ASAP (days) but I can't give an exact date.

**Comment by zhjgit** [comment]
I can't use the latest version. I only need version 0.4.18

**Comment by Stebalien** [comment]
We will not backport to 0.4.18. What's your issue with the latest version?

**Comment by zhjgit** [comment]
That's the problem. #6418

**Pull request merged**
