### PR TITLE
[WIP] Parallelize dht provide commmand

### PR DESCRIPTION
**Pull request by michaelavila**
https://github.com/ipfs/go-ipfs/issues/4863

### CODE REVIEW

**Comment by michaelavila** [comment]
@Stebalien yeah, makes sense. Sorry, I just wanted to get a PR up to see if this caused problems with the slew of tests as is on CI (because I'm having some trouble with the tests locally). I'll be sure to add some guardrails before this work is merge-ready.

**Comment by Stebalien** [comment]
SGTM. Thanks for tackling this!

**Comment by michaelavila** [comment]
Upon thinking about this further, I wonder if we should deprecate the `ipfs dht provide` command? I think we can offer `ipfs provider provide` for providing larger sets of cids. Doing that kind of coordination is really the job of the provider at that layer anyway.

One nice thing about the `ipfs dht provide` command is that it is synchronous, reporting error or success at the end. Maybe we can preserve this behavior through an option of some kind, e.g. `ipfs provider provide -s` which will work in some reasonable way that's yet to be defined.

cc @Stebalien

**Comment by Stebalien** [comment]
I'd say:

1. Leave `dht provide` for now. It's a low-level plumbing command that's useful for debugging. We could still add a recursive option, but this command shouldn't touch the provider subsystem itself.
2. Add a `provider provide` command that adds a provider record to the provider subsystem. Or maybe even `provider add`, `provider rm`, etc? Or `provider provide` provider unprovide`. Naming is annoying...

**Comment by michaelavila** [comment]
@Stebalien right, makes sense. I'm going to leave this `ipfs dht provide` command as is, for debugging purposes, and point people to `ipfs provider provide` (or whatever we come up with) for regular use. Closing this PR.

**Pull request closed without merging**
