### PR TITLE
Add appveyor conf

### PR DESCRIPTION
**Pull request by rht**
- [ ] add test_go_expensive
- [x] add appveyor pr webhook http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests @ipfs/go-ipfs-team (can only be done by someone with admin access -- not me)

### CODE REVIEW

**Comment by jbenet** [comment]
Oh this is great! sorry for delay-- hadn't seen it. will make an account + enable with @ipfsbot (has admin)

**Comment by jbenet** [comment]
sigh: 



> Repository webhooks and services
> Admin access
> This application will have full access to repository webhooks and services (no direct code access).

**Comment by jbenet** [comment]
Ok i added the webhook with Push and PR perms as advertised. will try re-pushing this branch

**Comment by jbenet** [comment]
Hook is firing the builds: https://ci.appveyor.com/project/ipfsbot/go-ipfs/history but they say master (probably because it will test the PR on top of master? ie apply the PR on top? not sure). This causes them to fail-- we may have to merge this first if so. wish it could build the branch directly, too (shoudnt the push build this branch, not master??)

Commit indicator still does not show. asked in https://github.com/appveyor/ci/issues/527

**Comment by jbenet** [comment]
So webhook triggered. See https://ci.appveyor.com/project/ipfsbot/test/history Still missing:

- this didnt build right. build error (`make`)
- commit indicator. ongoing with https://github.com/appveyor/ci/issues/527

(it's called "test" historically. doesn't look changeable)

**Comment by jbenet** [comment]
commit indicator shows up now. build needs to be fixed. @rht want to look into it? or someone with lots of windows experience? @mithgol @gatesvp ?

**Comment by Mithgol** [comment]
It seems that [`make`](https://en.wikipedia.org/wiki/Make_%28software%29) is not available at all and thus `make install` fails.

(Also your `Makefile` contains commands in the form `env1=val1 env2=val2 someCommand` and I am not sure if Windows supports such form of environment settings.)

**Comment by rht** [comment]
To set env var in windows shell: http://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt.

**Pull request closed without merging**
