### PR TITLE
Fuse and docker tests together 

### PR DESCRIPTION
**Pull request by chriscool**
This is trying to have both fuse and docker tests together.
Not sure it is possible though. Let's see how the tests look like.

### CODE REVIEW

**Comment by chriscool** [comment]
There is the following go test failure:

```
ok  	github.com/ipfs/go-ipfs/exchange/reprovide	0.021s

--- FAIL: TestFilePersistence (0.18s)

	ipns_test.go:189: Closed, opening new fs

	ipns_test.go:195: open /tmp/fusetest870241229/local/atestfile: no such file or directory

--- FAIL: TestMultipleDirs (0.15s)

	ipns_test.go:206: make a top level dir

	ipns_test.go:212: write a file in it

	ipns_test.go:217: sub directory

	ipns_test.go:222: file in that subdirectory

	ipns_test.go:228: closing mount, then restarting

	ipns_test.go:88: stat /tmp/fusetest901302151/local/test1: no such file or directory

FAIL

FAIL	github.com/ipfs/go-ipfs/fuse/ipns	7.131s
```

But it doesn't look related and the sharness tests all passed...

**Comment by chriscool** [comment]
On OSX there is the following error on one of the two go tests:

```
?   	github.com/ipfs/go-ipfs/p2p/net/filter	[no test files]

12:32:58.791 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.791 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.791 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.813 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.813 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.813 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.882 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.883 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.883 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.918 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.918 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.918 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.922 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.922 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.922 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.987 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.988 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:58.988 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.072 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.072 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.072 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.073 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.073 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.081 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.139 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.139 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.139 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.366 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.366 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.366 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.398 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.399 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.399 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.403 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.403 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.403 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.419 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.419 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

12:32:59.419 ERROR    mocknet: mock_streamio: read/write on closed pipe mock_stream.go:126

--- FAIL: TestLimitedStreams (2.39s)

	mock_test.go:579: Expected 2ish seconds but got  2.388548056s

FAIL

FAIL	github.com/ipfs/go-ipfs/p2p/net/mock	5.311s
```

**Comment by chriscool** [comment]
cc @thelinuxkid @whyrusleeping @jbenet

**Comment by whyrusleeping** [comment]
the test limited streams one just looks like its caused by a timing issue. That one should get disabled on CI

**Comment by whyrusleeping** [comment]
the fuse test failures look like the changes arent being correctly propogated... thats unfun and something i'll need to look at soon

**Comment by chriscool** [comment]
@whyrusleeping issue #2214 is about the first test failure I comment about above.
Also this PR should be closed because @thelinuxkid implemented what I test here in PR #2120.

**Comment by thelinuxkid** [comment]
@whyrusleeping the fuse failures have been debugged. All that's left is for the changes described in #2214 to be implemented.

**Pull request closed without merging**
