### PR TITLE
swap transport over to spdystream

### PR DESCRIPTION
**Pull request by whyrusleeping**
Don't merge this. I'm pushing this up for @diasdavid to take a peek at, and for @jbenet to see if he knows why the p2p/test/reconnect tests are failing.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
something is wrong in the spdystream 'IsClosed' implementation. Right now, its only ever counted closed when we call Close on it, but the other muxers have an 'IsClosed' impl that will notice if the other side closes the stream.

**Comment by whyrusleeping** [comment]
fixed here: https://github.com/jbenet/go-peerstream/pull/10

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21b45df3bb857e03c55c5650e906844341fdc4dd
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 2925713aa98f655897366a7e363361c38a4717df
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 21b45df3bb857e03c55c5650e906844341fdc4dd
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 2925713aa98f655897366a7e363361c38a4717df
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

 * Commit: 741a897cae89b60e01f51e2db7dd90ef05a0851d
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
@jbenet i screwed up godeps...

**Pull request closed without merging**
