### PR TITLE
daemon help docs for CORS

### PR DESCRIPTION
**Pull request by carver**
Convey the basic idea, plus an example.  Don't encourage using `*`.

This would have saved me some code spelunking.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c4fb36b8c8ee23fc75d56f229253bca316020ee3
  * Invalid signoff. Commit message must end with **License: MIT
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23)

---
This message was auto-generated by https://gitcop.com

**Comment by carver** [comment]
License: MIT is fine. Do I need to rewrite the commit and force-push?

**Comment by jbenet** [comment]
> License: MIT is fine. Do I need to rewrite the commit and force-push?

yes please, see [Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages)

**Comment by whyrusleeping** [comment]
this is a feature i did not know we had. :+1:

**Comment by jbenet** [comment]
LGTM :+1: 

@carver bonus points if you make an example for https://github.com/ipfs/examples

**Comment by carver** [comment]
unfortunately, although exporting this variable did stop the CORS errors, i am still getting a `403 Forbidden` from the API server when trying to post some text.

i'm happy to add one to ipfs/examples, but i'll wait until i have the browserified version of ipfs-api working end to end.

i'm also working on node-ipfs-api, adding the CORS info to the readme, and maybe fixing a Buffer bug: `Uncaught Error: File.contents can only be a Buffer, a Stream, or null.`

**Pull request merged**
