### PR TITLE
routing: use extracted dht and routing code

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Thanks @geoah for doing 99% of the work here :+1: :100: :+1: :hand:

**Comment by whyrusleeping** [comment]
of course the tests are failing... why?

**Comment by geoah** [comment]
There were two notification packages, ipfs was subscribing for query results to one, dht was announcing to the other one. #3227 should fix it.

**Comment by whyrusleeping** [comment]
cc @lgierth @Kubuxu for review. I cant wait to have this in!

**Comment by geoah** [comment]
Two minor notes, the following files and directories can be safely removed. They are leftovers the last couple extractions and should not be in use any more.

* `/blocks/key`
* `/notifications`

**Pull request merged**
