### PR TITLE
p2p: report-peer-id option for listen

### PR DESCRIPTION
**Pull request by magik6k**
Was suggested on IRC, when set it basically passes `QmPeerid\n` of connecting peer into listener stream.

(works but needs tests)

### CODE REVIEW

**Comment by Stebalien** [comment]
We should also consider sending a binary peer ID (maybe length-prefixed?, although peer IDs are already prefix-free codes). This may be easier to parse than having to read to a newline and then potentially base58 decode. It also means we can change encoding without breaking things.

However, I haven't thought though this thuroughly.

**Comment by magik6k** [comment]
Technically they carry the multihash prefix which has length. I can see binary form being useful, but I can't think of any nice way to do this other than 2 separate flags

**Comment by Stebalien** [comment]
Meh. The current version *is* quite user friendly.

Any objections @ipfs/go-team?

**Comment by whyrusleeping** [comment]
Eh, I think that practically, the base58 encoded version will be the most useful. If we make it binary, writing a parser becomes just that much more difficult.

**Pull request merged**
