### PR TITLE
Assorted 'ipfs object patch' cleanups

### PR DESCRIPTION
**Pull request by wking**
Lots of detail and motivation in the commit messages themselves.
Major changes:

* New replace-link action.
* Both add-link and replace-link auto-create nodes for any missing
  intermediate paths (more on this below).
* rm-link now removes all links matching a name (not just the first).
* Docs and tests for all the actions :).

I expect most of this to be fairly non-controversial (although I've
been wrong about that sort of thing before ;).  The main UI thing we
need to work out is auto-creating intermediate nodes.  Talking about
this on IRC, @whyrusleeping expressed concern about auto-creation as
part of the object-patch command (see [1] through [2]).  Options I
see:

a. Keep the auto-creation as it's currently implemented in this PR
   (i.e. just do it).  Folks who typo paths may end up accidentally
   creating a few DAG entries, but that's not a big deal (we don't
   even pin the stuff made by `object patch` as far as I can tell).
   Folks who want a different intermediate node can either patch the
   auto-created node, or build their indentded intermediate node first
   and then run the bubbling patch through that node (or any of its
   ancestors).

b. Add a flag enabling auto-creation (like `mkdir`'s `-p` /
   `--parents`).  This lets folks like me (who don't want them)
   opt-out of typo'ed path checks, but keeps the checks in place for
   users who haven't thought about what they want (and who may
   therefore expect errors in the missing-intermediate case).  This
   approach almost ties with (a) for me, since `-p` isn't that hard to
   type (and I could always alias it), with the main drawback being an
   extra knob that I don't really think we need.  This option still
   doesn't give the control @whyrusleeping apparently desires over the
   auto-created objects themselves.

c. Add a flag (`-t` / `--template`?) that accepts all the strings
   understood by `ipfs object new`.  Then we use the same logic
   internally when auto-creating intermediates.  This gives some
   control over the auto-created objects, which may satisfy
   @whyrusleeping.  On the other hand, the only template there is
   currently unixfs-new, and for creating intermediates that are
   Unix-FS directories I think we should really be looking at an `ipfs
   file patch …` command that auto-creates directories by default.  It
   would also handle things like transparent sharding, chunking, and
   shard/chunk-transparent Path resolution (e.g. an `a/b/c` path would
   work even if the Merkle representation was:

        {a-shard-root}→{a-shard}→{b-shard-root}→{b-shard}→{c-chunk-root}→[{c-chunks}…]

d. Create some new command that handles the auto-creation in a
   separate step.  But then folks like me that can (with this PR) run:

        $ ipfs object patch $ROOT replace-link a/b/c $CONTENT

   would need to run something like:

        $ if ipfs object ls $ROOT/a/b >/dev/null 2>&1
        > then  # parent already exists
        >   ipfs object patch $ROOT replace-link a/b/c $CONTENT
        > else
        >   ipfs object mkdir -p $ROOT/a/b &&
        >   ipfs object patch $ROOT add-link a/b/c $CONTENT
        > fi

   and that seems like useless hoop-jumping.

[1]: https://botbot.me/freenode/ipfs/2015-06-20/?msg=42439389&page=4
[2]: https://botbot.me/freenode/ipfs/2015-06-20/?msg=42445602&page=5

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping more thoughts on this? im not entirely sure what the implications of creating intermediate nodes is-- ware you worried about types?

**Comment by whyrusleeping** [comment]
I'm worried about a few different things that @wking mentions above, first, i dont want to accidentally mistype a long path under a node, and have it create a bunch of un-asked-for nodes (although, the only cost there is having to run a GC). The other worry i had was what should those intermediate nodes be? blank nodes? or unixfs dirs? You can pass that as an option, but then the command invocations start to get really messy, and it brings the UX down a bit in my opinion.

**Comment by jbenet** [comment]
> first, i dont want to accidentally mistype a long path under a node, and have it create a bunch of un-asked-for nodes (although, the only cost there is having to run a GC). 

i think accidentally creating additional objects is likely ok.

> The other worry i had was what should those intermediate nodes be? blank nodes? or unixfs dirs? You can pass that as an option, but then the command invocations start to get really messy, and it brings the UX down a bit in my opinion.

yeah this is a harder question. not sure, could pass a template as an option and default to a blank node? not sure.

**Comment by wking** [comment]
On Thu, Jun 25, 2015 at 02:20:59PM -0700, Juan Batiz-Benet wrote:
> > The other worry i had was what should those intermediate nodes be?
> > blank nodes? or unixfs dirs? You can pass that as an option, but
> > then the command invocations start to get really messy, and it
> > brings the UX down a bit in my opinion.
> 
> yeah this is a harder question. not sure, could pass a template as
> an option and default to a blank node? not sure.

I still think (see the tail end of (c) in my initial comment) that the
best choice here is to create blank nodes in ‘ipfs object patch …’
(like this PR does now), and then add additional commands for other
situations (e.g. ‘ipfs file patch …’ that hides sharding/fanout in
path handling and auto-creates Unix-FS directories).

**Comment by jbenet** [comment]
> New replace-link action.

what are the semantics of replace when many links with the same name exist? remove all and add just one?

> rm-link now removes all links matching a name (not just the first).

maybe should be named `rm-links`. another option is to use a flag `rm-link --all`. this brings up something else, links without names need to be able to be removed, maybe with their int offset.

(in general i would like to be able to address links by their number, but this is currently not kosher with names without introducing a special prefix)

> Docs and tests for all the actions :).

:+1: :+1: 

> auto-creation

i gave it some thought and i think i would want auto-creation, but definitely _optionally_, and being able to specify a template. So i think we want _both_ `-p` and `-t` (with -t defaulting to a blank node (no data))

**Comment by jbenet** [comment]
is this still needed?

**Comment by whyrusleeping** [comment]
closing, old PR cleanup time.

**Pull request closed without merging**
