### PR TITLE
Release 0.4.19

### PR DESCRIPTION
**Pull request by Stebalien**
I don't anticipate any other changes. I'll merge this and cut the release
tomorrow if nothing happens between now and then.

### CODE REVIEW

**Comment by magik6k** [comment]
https://github.com/ipfs/go-ipfs/pull/6019 will introduce API breaking change, but I don't think it's worth blocking release on that. (And there is still this comment https://github.com/ipfs/interface-go-ipfs-core/blob/master/unixfs.go#L39)

**Comment by Stebalien** [comment]
Meh, I consider the CoreAPI to be unstable/internal for now.

**Comment by Kubuxu** [comment]
What about other blockers https://github.com/ipfs/go-ipfs/issues/5867#issuecomment-467676213

**Comment by Stebalien** [comment]
@Kubuxu I'll rebase this once we've merged fixes for those (and possibly cut another RC).

**Pull request merged**
