### PR TITLE
Update go-datastore to 1.2.2, go-cid to 0.7.16

### PR DESCRIPTION
**Pull request by magik6k**

### CODE REVIEW

**Comment by magik6k** [comment]
CI needs bump do Go 1.8, caused by using sort.Slice in https://github.com/ipfs/go-datastore/pull/66#discussion_r124595855

**Comment by magik6k** [comment]
Tests are broken on more things here, new mountds.Query appears to have problems.

**Comment by magik6k** [comment]
Bubling PRs to merge:
- [ ] failstore https://github.com/whyrusleeping/failstore/pull/4
- [ ] retry-datastore https://github.com/whyrusleeping/retry-datastore/pull/3
- [ ] go-ds-flatfs https://github.com/ipfs/go-ds-flatfs/pull/21
- [ ] go-ds-measure https://github.com/ipfs/go-ds-measure/pull/9
- [ ] go-ds-leveldb https://github.com/ipfs/go-ds-leveldb/pull/7
- [ ] autobatch https://github.com/whyrusleeping/autobatch/pull/4
- [ ] go-libp2p-routing https://github.com/libp2p/go-libp2p-routing/pull/12
- [ ] go-libp2p-kad-dht https://github.com/libp2p/go-libp2p-kad-dht/pull/63
- [ ] go-block-format https://github.com/ipfs/go-block-format/pull/2
- [ ] go-ipld-format https://github.com/ipfs/go-ipld-format/pull/16
- [ ] go-ipld-cbor https://github.com/ipfs/go-ipld-cbor/pull/19

**Comment by whyrusleeping** [comment]
@magik6k remove the second 'go-libp2p-routing' reference from the package.json, it should fix the issue here

**Pull request merged**
