### PR TITLE
Migrations to gx

### PR DESCRIPTION
**Pull request by Kubuxu**
Part of https://github.com/ipfs/go-ipfs/issues/2722

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM

**Comment by whyrusleeping** [comment]
Let me know when you want to merge

**Comment by Kubuxu** [comment]
@whyrusleeping it is good for merge now

**Comment by hoffmabc** [comment]
Hey this merge I think broke some stuff. Either that or I'm ignorant to how this works. Quite possible btw.

```
../go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/errors/errors.go:14:2: cannot find package "github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage" in any of:
	/usr/local/opt/go/libexec/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage (from $GOROOT)
	/Users/brianhoffman/golang/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage (from $GOPATH)
../go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/errors/errors.go:15:2: cannot find package "github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util" in any of:
	/usr/local/opt/go/libexec/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util (from $GOROOT)
	/Users/brianhoffman/golang/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util (from $GOPATH)
```

The only way I was able to remedy this was to install the goleveldb repo independently and remove those _workspace references in the imports.

**Comment by Kubuxu** [comment]
As you can see there is no goleveldb at all: https://github.com/ipfs/go-ipfs/tree/master/Godeps/_workspace/src/github.com/syndtr/

Make sure that you did good pull, no unchecked files and run `make build` or `gx install`,

**Comment by hoffmabc** [comment]
This is coming from https://github.com/OpenBazaar/openbazaar-go

**Comment by whyrusleeping** [comment]
@hoffmabc do you have some repro steps? I can definitely take a look at it.

We're in the middle of transitioning all the rest of our deps from godeps into gx so that we can avoid problems like this in the future.

**Comment by Kubuxu** [comment]
Looks like openbazaar vendors go-ipfs in https://github.com/OpenBazaar/openbazaar-go/tree/master/vendor/github.com/ipfs/go-ipfs it is possible that something got stale or not removed or something.

**Comment by hoffmabc** [comment]
@cpacia could answer this better probably but there is a possibility of something lingering, but I completely cleaned my $GOPATH and started from scratch just doing 
```
go get https://github.com/OpenBazaar/openbazaar-go
```
and this is what I got. I then proceeded to install go-ipfs and gx separately and still didn't improve.

**Comment by Kubuxu** [comment]
Ok, everything is explained now I think: https://github.com/OpenBazaar/openbazaar-go/blob/f62cbb590cb60bcce4f4dbe540f643c355385707/core/core.go

OpenBazaar uses vendored deps of go-ipfs directly, that dep was removed from place where OB uses it.

**Comment by hoffmabc** [comment]
Ok gotcha thanks

**Comment by cpacia** [comment]
That was my ide autochaning the import on me :p

Also @hoffmabc we aren't working out of master. Just last releases.

**Pull request merged**
