### PR TITLE
Fix formatting in merkledag.go

### PR DESCRIPTION
**Pull request by Kubuxu**
License: MIT
Signed-off-by: Jakub Sztandera <kubuxu@protonmail.ch>

### CODE REVIEW

**Comment by Kubuxu** [comment]
It is quite important as it is one of tests on Jenkins.

**Comment by kevina** [comment]
Note.  I have two p.r. that touch `merkledag.go` #3671 and #3700.  They both fix the formatting problems.  If either of them are to go in within the next couple of days It would save me some trouble if this P.R. is closed without merging.

**Comment by whyrusleeping** [comment]
@Kubuxu how did this get through in the first place? I thought gofmt was part of our normal test suite?

**Comment by Kubuxu** [comment]
It was on teamcity, and is on Jenkins. Jenkins is almost working.

**Pull request merged**
