### PR TITLE
humanize for ipfs bitswap stat

### PR DESCRIPTION
**Pull request by myself659**
License: MIT
Signed-off-by: Eric Wu <myself659@163.com>

### CODE REVIEW

**Comment by Stebalien** [comment]
To match our other commands, we should:

1. Add a --humanize flag.
2. _Replace_ the sizes with the humanized sizes when humanizing.

**Comment by myself659** [comment]
my little suggest: 
bitswap-stat
as shown in the above picture， I think this way is better with adding --humanize flag.   and it has a better user experience.

**Comment by myself659** [comment]
and I think more users will like this type of cmd.

You can discuss it internally. Thx!

**Comment by Stebalien** [comment]
So, I'm just trying to be consistent with the rest of go-ipfs. Other commands (`ls`, `du`, etc.) provide humanize flags so `ifconfig` is really the outlier here. Actually, the replacement for `ifconfig`, `ip`, also uses a `-human` flag (`ip -s -human addr`).

**Comment by Stebalien** [comment]
Thanks!

**Comment by Stebalien** [comment]
cc @ipfs/wg-js-core

**Pull request merged**
