### PR TITLE
coreapi: extract interface

### PR DESCRIPTION
**Pull request by magik6k**
Now lives in https://github.com/ipfs/interface-go-ipfs-core

### CODE REVIEW

**Comment by Kubuxu** [comment]
That will be annoyingly long import name, we didn't think about it while deciding on naming scheme.

**Comment by Stebalien** [comment]
My only comment is that the repo name doesn't match the go naming convention (would otherwise be go-ipfs-interface-core). But don't really mind either way.

**Comment by magik6k** [comment]
The naming is to match https://github.com/ipfs/interface-js-ipfs-core/issues/423#issuecomment-457305646

**Comment by Stebalien** [comment]
I'm not going to bikeshed this too much but I've pinged david to try to get his rational. I *do* like being able to run shell commands over `go-*`.

**Comment by Stebalien** [comment]
We can quibble over naming later.

**Pull request merged**
