### PR TITLE
Fix data race in commands/http/handler/ServerConfig

### PR DESCRIPTION
**Pull request by miolini**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1f69105dddacd3801dea33861105eb14a53f7960
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: b64e456020bfef3daa4fefa14595fff8dd9b56f7
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1f69105dddacd3801dea33861105eb14a53f7960
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: b64e456020bfef3daa4fefa14595fff8dd9b56f7
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: f41e3211b2c96743026fbdd9ee5178392a0afc1b
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1f69105dddacd3801dea33861105eb14a53f7960
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: b64e456020bfef3daa4fefa14595fff8dd9b56f7
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

 * Commit: f41e3211b2c96743026fbdd9ee5178392a0afc1b
  * Invalid signoff. Commit message must end with  
    **License: MIT  
Signed-off-by: .* <.*>**

[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help. Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).

---
This message was auto-generated by https://gitcop.com

**Comment by whyrusleeping** [comment]
@miolini grab the script that gitcops links and run it in your go-ipfs git repo. The do a git rebase master and ammend the commit message

**Comment by jbenet** [comment]
@miolini i saw that you closed the PR and deleted the repo, is this because of gitcop?

i want to explain that this is a critical important step to ensure this codebase is patent and copyright safe. contributing to other major projects like the linux kernel, git, docker, ... all require signing your work. (the DCO is better than a CLA as you keep your copyright)

**Comment by miolini** [comment]
Yes, I'll create a new PR today.

**Pull request closed without merging**
