### PR TITLE
command to clear inactive requests from request log

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by lgierth** [comment]
Will we have to run the clear command regularly, e.g. to prevent the log from eating up memory?

**Comment by whyrusleeping** [comment]
no, it automatically clears entries older than half an hour. This is just to clear it up while analyzing things, I found it really helpful while working on registry mirror stuff

**Comment by lgierth** [comment]
Cool LGTM then :+1:

**Comment by whyrusleeping** [comment]
sweet, thanks!

**Pull request merged**
