### PR TITLE
fix race condition in notifications test

### PR DESCRIPTION
**Pull request by whyrusleeping**
We were assuming that the notifications would be received in the same order that they were sent, which is false. If multiple goroutines are trying to send on a channel, the scheduler randomly selects one.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping mmm i think this is not right
- https://travis-ci.org/ipfs/go-ipfs/jobs/71860593#L140
- https://travis-ci.org/ipfs/go-ipfs/jobs/71860581#L195

**Comment by whyrusleeping** [comment]
@jbenet hrm.. we expect more than one connection between a given pair of peers?

**Comment by jbenet** [comment]
yep, it can and does happen.

**Comment by whyrusleeping** [comment]
i've rerun the tests a few times now, no notifications failures! :smile:

**Comment by jbenet** [comment]
:+1:

**Pull request merged**
