### PR TITLE
Fix SetAllowedOrigins

### PR DESCRIPTION
**Pull request by rht**
Fix #1966

### CODE REVIEW

**Comment by rht** [comment]
I tested this by simulating the race condition when the ro gateway overtakes the api:
1. On current master, deliberately launch the API 10s after the gateway. Get 403 resp code when uploading files
2. On this branch, deliberately launch the API 10s after the gateway. Uploading file works.

**Comment by jbenet** [comment]
@rht can we do that in less than 10s? make a sharness test?

**Comment by jbenet** [comment]
thanks for picking this up @rht

**Comment by rht** [comment]
The launch order change & time delay to ensure the order are *hardcoded*. It is not sensible to expose this to cli if the reason is only for sharness testing.

To reproduce the race test, move https://github.com/ipfs/go-ipfs/blob/c8e48456308cc68556f0804e8ecff9ef4ea21e32/cmd/ipfs/daemon.go#L253-L257 to after https://github.com/ipfs/go-ipfs/blob/c8e48456308cc68556f0804e8ecff9ef4ea21e32/cmd/ipfs/daemon.go#L268, and put `<-time.After(time.Second*10) in between.

**Comment by jbenet** [comment]
@rht could a test case run it a few times to attempt to trigger a race condition? or could do a golang test with a mock-- i want to make sure this does not become a problem in the future. we have many less tests than i would like as it is.

**Comment by whyrusleeping** [comment]
couldnt we test for this by just building the binary we use for sharness tests with `-race`?

**Comment by rht** [comment]
Just fixed this test.
ci errs are orthogonal to the part this pr fixes.

To explain how the test checks for race condition, currently, if the api (5001) starts before the gateway (8080), the curl command that works has to be `curl -X GET -H "Origin:http://localhost:5001" -I http://localhost:5001/api/v0/version` (api) and `curl -X GET -H "Origin:http://localhost:5001" -I http://localhost:8080/api/v0/version` (gateway).

**Comment by rht** [comment]
RFCR, for this has issue count of 3: #1883, #1839, https://github.com/ipfs/go-ipfs/issues/1839.

**Comment by jbenet** [comment]
this makes sense, thanks

**Comment by chrber** [comment]
Hi,
I had this problem with my installation. I have been able to fix this in the meantime, as the description here helped. However, I have installed ipfs on a Debian wheezy. 

Agentenversion go-ipfs/0.4.10/
Protokollversion ipfs/0.1.0

Am I wrong in thinking that this should be actually already default in 0.4.10? Is this maybe a regression?

**Pull request merged**
