### PR TITLE
gx update sync to bring in go-ipfs-config changes

### PR DESCRIPTION
**Pull request by lgierth**
This simple go-ipfs-config update spiraled completely out of control.

- The first commit is from #5401, which the go-ipfs-config update depends on
- The second commit executes this update manifest: https://ipfs.io/ipfs/QmbGifBgNZCfvxK5Rg6XS57dASgSREuoULMkKyYNf4gRaY/gx-workspace-update.json
- The third commit has #5401-related fixes to go-ipfs-config and iptb

There's even more changes needed though, which I'm not sure I'll be able to do at the moment.

```
go build -i -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=1ba275c2c" -o "cmd/ipfs/ipfs" "github.com/ipfs/go-ipfs/cmd/ipfs"
# github.com/ipfs/go-ipfs/core
../../../go/src/github.com/ipfs/go-ipfs/core/core.go:527:21: cannot use routinghelpers.Compose literal (type *routinghelpers.Compose) as type []routing.IpfsRouting in field value
../../../go/src/github.com/ipfs/go-ipfs/core/core.go:533:5: cannot use n.Routing (type routing.IpfsRouting) as type record.Validator in field value:
	routing.IpfsRouting does not implement record.Validator (missing Select method)
cmd/ipfs/Rules.mk:22: recipe for target 'cmd/ipfs/ipfs' failed
```

### CODE REVIEW

**Comment by lgierth** [comment]
@magik6k are the needed routing changes something up your alley?

**Comment by kevina** [comment]
@lgierth I might be able to handle this.  What needs to be done?

**Comment by lgierth** [comment]
>  What needs to be done?

go-ipfs successfully building would be a start :):)

This cascade of package updates stems from go-datastore

**Comment by kevina** [comment]
@lgierth I can have a look later today if no one else does.  I will likely do a forced update if I do take it over.

**Comment by kevina** [comment]
@lgierth okay fixed the build problem, although I am not sure if I did it correctly as I am not familiar with that part of the code.

**Comment by kevina** [comment]
One of the deps. doesn't compile on 32-bit platforms.
```
[go-ipfs] Running shell script
+ go build -i -ldflags=-X github.com/ipfs/go-ipfs/repo/config.CurrentCommit=pr-5553-5 -o cmd/ipfs/ipfs github.com/ipfs/go-ipfs/cmd/ipfs
# gx/ipfs/QmUQy76yspPa3fRyY3GzXFTg9n8JVwFru6ue3KFRt4MeTw/go-buffer-pool
../../../gx/ipfs/QmUQy76yspPa3fRyY3GzXFTg9n8JVwFru6ue3KFRt4MeTw/go-buffer-pool/pool.go:55:12: constant 4294967296 overflows int
../../../gx/ipfs/QmUQy76yspPa3fRyY3GzXFTg9n8JVwFru6ue3KFRt4MeTw/go-buffer-pool/pool.go:68:31: constant 4294967296 overflows int
script returned exit code 2
```
I filed a bug report https://github.com/libp2p/go-buffer-pool/issues/1

This needs to be fixed and then the gx-update redone.  I can do that tomorrow if required.

**Comment by lgierth** [comment]
Thanks a lot @kevina :):)

At least the swarm/circuit/ipfs-config parts of the update are correct then, since t0182-circuit-relay.sh finally passes again without modifications and `gx-go link`s :)

**Comment by Stebalien** [comment]
That bug's rather odd... That constant has existed (elsewhere) for *ages*).

**Comment by Stebalien** [comment]
@kevina I've cut a new release of go-buffer-pool. Bubble when ready.

**Comment by lgierth** [comment]
@kevina feel free to just do an additional update for go-buffer-pool instead of throwing the existing update out. Updating iptb was a bit annoying since its master has advanced a lot from the version that go-ipfs is using: ipfs/iptb#93

**Comment by kevina** [comment]
> That bug's rather odd... That constant has existed (elsewhere) for ages).

It could be that it is only recently being detected by go.

**Comment by kevina** [comment]
@lgierth will do, as the `iptb` is not involved in the update.  Bubble list:
```
go-libp2p-secio
go-libp2p-swarm
go-libp2p-circuit
go-libp2p
go-libp2p-kad-dht
go-libp2p-floodsub
go-libp2p-pubsub-router
go-bitswap
go-blockservice
go-merkledag
go-path
go-unixfs
go-mfs
go-ipfs
```

**Comment by Stebalien** [comment]
> It could be that it is only recently being detected by go.

Probably.

**Comment by kevina** [comment]
I started to do the update and ran into duplicate deps.  I am now first updating go-libp2p-peerstore with this bubble list:
```
go-ipns
go-libp2p-kbucket
go-libp2p-net
go-libp2p-netutil
go-libp2p-routing
go-conn-security
go-libp2p-interface-connmgr
go-libp2p-transport
go-libp2p-routing-helpers
go-conn-security-multistream
go-libp2p-secio
go-libp2p-connmgr
go-libp2p-host
go-libp2p-quic-transport
go-libp2p-transport-upgrader
go-ipfs-routing
go-libp2p-blankhost
go-tcp-transport
go-ws-transport
go-libp2p-swarm
go-libp2p-circuit
go-libp2p-floodsub
go-libp2p
go-libp2p-pubsub-router
go-bitswap
go-libp2p-kad-dht
go-blockservice
go-merkledag
go-path
go-unixfs
go-mfs
go-ipfs
```

**Comment by kevina** [comment]
@Stebalien okay this should be good to go, can we get this is before any other gx updates so I don't have to redo this.

**Pull request merged**
