### PR TITLE
replace imports with absolute path instead of using symlink

### PR DESCRIPTION
**Pull request by whyrusleeping**
I dont like this. Not one bit. but it *should* fix windows builds. Im restraining myself from ranting about windows here.

License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by jbenet** [comment]
could @gatesvp @Mithgol or someone else with windows verify?

**Comment by gatesvp** [comment]
```
> git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
> go build -tags nofuse
c:\go_code\src\github.com\ipfs\go-ipfs\blocks\blockstore\blockstore.go:15:2: cannot find package "github.com/ipfs/go-ipfs/vendor/go-log-v1.0.0" in any of:
        C:\Go\src\github.com\ipfs\go-ipfs\vendor\go-log-v1.0.0 (from $GOROOT)
        c:\go_code\src\github.com\ipfs\go-ipfs\vendor\go-log-v1.0.0 (from $GOPATH)
>  git checkout feat/no-symlink
Branch feat/no-symlink set up to track remote branch feat/no-symlink from origin.
Switched to a new branch 'feat/no-symlink'
>  go build -tags nofuse
> .\ipfs.exe version
ipfs version 0.3.8-dev
```

That's a success from my end!

**Comment by jbenet** [comment]
thanks @gatesvp !

@whyrusleeping needs rebase i think

**Comment by whyrusleeping** [comment]
image

**Comment by whyrusleeping** [comment]
im downloading a windows vm, going to set up a local jenkins thing so i can test on various different systems.

**Comment by whyrusleeping** [comment]
windows vm installed and setup. This PR lets us build (`-tags=nofuse` still required).

Once this lands lets see about rebasing #1705 to make things even easier.

**Pull request merged**
