### PR TITLE
Add way to check if node is online or offline

### PR DESCRIPTION
**Pull request by Kubuxu**
As requested by @lgierth.

@RichardLitt this changes API.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM

**Comment by jbenet** [comment]
@Kubuxu changed the API in what way? this type of thing is important to put directly into the commit messages, not just the PR, and to be very explicit about what, to be super clear with everyone. cc @whyrusleeping too about this.

**Comment by jbenet** [comment]
(i think it just _added_ a feature, but just checking)

**Comment by Kubuxu** [comment]
Yes, it is just an added feature, we are pining Richard like that to notify him that this PR includes something that requires update in http-api-spec.

**Comment by jbenet** [comment]
- We should codify API changes directly into commits.
- Makes it easy to include in changelog
- remember many people wont have the full github PR comment history to understand from.

**Pull request merged**
