### PR TITLE
Checks TEST_OS in a more POSIX-y manner.

### PR DESCRIPTION
**Pull request by noffle**
Addresses https://github.com/ipfs/go-ipfs/issues/2347.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
what was the cause of the failure? weird shell inconsistencies?

**Comment by noffle** [comment]
> what was the cause of the failure? weird shell inconsistencies?

I suspect. Bash wouldn't evaluate what was there, no matter how much massaging I tried.

@chriscool: is the intent to **not** set `POSIX` when running on Cygwin? I thought Cygwin was POSIX-compliant.

**Comment by chriscool** [comment]
@noffle yeah, the prereq name 'POSIX' is probably not the best. I added this prereq because the error messages are different on Cygwin. So maybe it should be named 'STD_ERR_MSG' or something like that.

**Comment by noffle** [comment]
Closing in favour of @chriscool's PR.

**Pull request closed without merging**
