### PR TITLE
update deps to introduce yamux hang fix

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <why@ipfs.io>

### CODE REVIEW

**Comment by Kubuxu** [comment]
LGTM

**Comment by whyrusleeping** [comment]
@Kubuxu the main changes from libp2p here are:

- this yamux PR, fixing the hang bug: https://github.com/hashicorp/yamux/pull/28
- this go-stream-muxer refactor: https://github.com/jbenet/go-stream-muxer/pull/9

the muxer refactor makes it much easier for us to update the code for each individual muxer without having to update the go-stream-muxer and go-peerstream packages every time

**Comment by Kubuxu** [comment]
Yup, LGTM

**Comment by whyrusleeping** [comment]
it would be cool if we had a github bot to add the RFM label once a certain set of people comment "LGTM"

**Comment by RichardLitt** [comment]
@whyrusleeping Who would be the best person to set that up? @lgierth?

**Pull request merged**
