### PR TITLE
core: get cmd outPath removes trailing slash from args - fixes #3729

### LINKED ISSUE #3729: ipfs get /ipns/example.com fails with unexpected error
Version: 0.4.6-rc1

Reproduction:
```
ipfs get /ipns/multiformats.io/                                 
Saving file(s) to .
 1024 B / 412.86 KB [>-----------------------------------------------------------------]   0.24% 0s
Error: open .: is a directory
```

### PR DESCRIPTION
**Pull request by adamliesko**
Commit a09d97465270ef441791b65bca98d37c25eb0564 was a poor fix, which only
modified the path printed to the StdOut. The arguments of command are
passed to the request's reader, which is turned into a tar Extractor.
The headers of that the tar Extractor were incorrectly populating the
write path, missing the root directory, causing files nested in root
folder to be written into the root output path.

fix visible at: https://asciinema.org/a/mDili4YFnOacgt3dbjHuXTzcT

We are making the assumption, that get Command will have always only 1 argument and it's safe to remove the trailing fix of all the paths. Happy to hear feedback on this from maintainers.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Hey @adamliesko thanks for the fix :)

Mind addressing the issues that codeclimate is complaining about?

**Comment by adamliesko** [comment]
@whyrusleeping I refactored and split the tests, but fully adhering to those warnings, it would mean that table driven tests are dead :) - artificial cuts in the size of functions would result in less readability. The other code duplication/similarity is not a real duplication. Do we have some option to ignore it?

Are these coming from CircleCI ok or is it a regression ```Error: verify complete, some blocks were corrupt``` ?

**Comment by whyrusleeping** [comment]
@adamliesko oh weird, i've never seen those sorts of complaints from codeclimate before. cc @Kubuxu

**Comment by whyrusleeping** [comment]
@adamliesko re: the test failures, that looks like a regression. Things have been pretty green on master lately.

**Comment by Stebalien** [comment]
> We are making the assumption, that get Command will have always only 1 argument and it's safe to remove the trailing fix of all the paths. Happy to hear feedback on this from maintainers.

It *should* accept multiple arguments (according to the help, at least). However, that's a different issue that can be addressed separately.

**Comment by adamliesko** [comment]
@whyrusleeping @Stebalien - I see this is a bit too hacky and it probably shows up with the test failures. Maybe making a change on the level of tar extractor or when constructing the Reader inside the request is a better place. I will try to look into it further next week.

**Comment by Kubuxu** [comment]
@whyrusleeping when codeclimate is complaining like that you can go to their page end either mark issues as "won't fix" or approve whole change set.

**Comment by lidel** [comment]
Original issue seems to be fixed in latest release: https://github.com/ipfs/go-ipfs/issues/3729#issuecomment-589229387

**Pull request closed without merging**
