### PR TITLE
Ipfs release 0.4.9

### PR DESCRIPTION
**Pull request by whyrusleeping**
License: MIT
Signed-off-by: Jeromy <jeromyj@gmail.com>

### CODE REVIEW

**Comment by lgierth** [comment]
Also needs `gx publish`.

Confused about CIDs in `ipfs add`, is the change only a command flag, or has the default changed?

**Comment by kevina** [comment]
@lgierth 

> Confused about CIDs in ipfs add, is the change only a command flag, or has the default changed?

It is only a command flag.

**Comment by whyrusleeping** [comment]
@lgierth gx published!

**Comment by lgierth** [comment]
LGTM -- Put it on a boat Jeromy!!

**Pull request merged**
