### PR TITLE
namesys: set the correct cache TTL on publish

### PR DESCRIPTION
**Pull request by Stebalien**
fixes https://github.com/ipfs/go-ipfs/issues/6656#issuecomment-534252128

### CODE REVIEW

**Comment by Stebalien** [comment]
cc @postables.

**Comment by dirkmc** [comment]
Conceptually it LGTM 👍 

Is this still considered experimental?
https://github.com/ipfs/go-ipfs/blob/1a32379c998f706c1bc7751fc8326f4f4a63f778/namesys/publisher.go#L200-L211

**Comment by Stebalien** [comment]
> Is this still considered experimental?

No but I started going down the rabbit hole of fixing the interfaces and stopped myself.

**Comment by dirkmc** [comment]
A wise choice :)

**Comment by kpp** [comment]
How do I test the fix?

**Comment by Stebalien** [comment]
@kpp:

1. Build the latest master.
2. Run `ipfs name publish --ttl=10m YYY`.
3. Try running `ipfs name resolve YYY`. That should continue to work for 10 minutes.

However, this _doesn't_ resolve #6656. It only resolves https://github.com/ipfs/go-ipfs/issues/6656#issuecomment-534252128.

**Pull request merged**
